"""Close this immutable development cycle; no follow-on fit, tuning or trading."""
from common import *
def main():
 a=json.loads((OUT/'INDEPENDENT_AUDIT.json').read_text());b=json.loads((OUT/'INDEPENDENT_SUPPLEMENT.json').read_text());o=json.loads((OUT/'INDEPENDENT_ORACLE_AUDIT.json').read_text());c=json.loads((OUT/'CAUSAL_CANARY_RESULTS.json').read_text());d=json.loads((OUT/'DETERMINISTIC_RERUN.json').read_text());p=json.loads((OUT/'APPEND_ONLY_PRESERVATION_AUDIT.json').read_text());s=json.loads((OUT/'SUCCESS_CRITERIA.json').read_text());remote=json.loads((WORK/'remote_state.json').read_text())
 assert a['mismatch_N']==b['mismatch_N']==o['mismatch_N']==0 and c['FAIL_N']==0 and d['PASS'] and all(p['checks'].values())
 cfg=json.loads((OUT/'POLICY_PRECOMMIT.json').read_text())
 assert all(sha(CODE/name)==h for name,h in cfg['runtime_code_hashes'].items())
 source=json.loads((OUT/'SOURCE_HASHES.json').read_text());assert all(sha(SOURCE/name)==h for name,h in source.items())
 x={'JST':now(),'status':'CLOSED_STOP','repo':remote['repo'],'branch':remote['branch'],'instruction_basis_HEAD':BASIS,'last_observed_report_result_HEAD':remote['head'],'last_observed_report_result_tree':remote['tree'],'closure_result_HEAD_tree':'Actual postcommit GET receipt stored separately; not fabricated in advance.',
 'criteria':s,'Oracle_max_feasible_U5':104,'Control_U5_recovery':42/104,'v5_U5_recovery':50/104,'remaining_oracle_U5_gap':54,'core_and_supplement_checks':a['check_N']+b['check_N'],'audit_mismatch':0,'oracle_mismatch':0,'causal_canary_PASS':c['PASS_N'],'full_deterministic_identity':True,'source_identity_files':len(source),'Primary_replay_N':1,'Independent_replay_N':1,'deterministic_full_canary_rerun_N':1,'causal_synthetic_day_mini_replay_N':6,'Control_replay_N':0,'new_policy_N':1,'new_fit':0,'rank_changes':0,'retune':0,'new_provider':0,'Claude':0,'Movement':0,'HF1_HL0_use':0,'MAX4_MAX5':0,'position_replacement':0,'frozen_Entry_EXIT_changes':0,'Protected_Holdout_Fresh_Validation_OOS_Prospective_opened':0,'Exposure':'ITERATIVE_DEVELOPMENT_EVIDENCE','overfit_risk':'Same58 Development sessions repeatedly reused; OOF38 not fresh/OOS.','third_slot_quality':'MIXED; U5/U10 rate and loss amount improved but below2/loser rate worsened.','medium_N_change':-4,'North_Star':'NOT_REACHED','orders':0,'main_merge':0,'force_push':0,'Safety':SAFETY,
 'files':{'report_sha256':sha(OUT/'REPORT_FINAL-ja.md'),'config_sha256':sha(OUT/'POLICY_PRECOMMIT.json'),'arrival_sha256':sha(OUT/'ARRIVAL_TABLE.json'),'score_sha256':sha(FROZEN/'UPWARD_STAIRCASE_SCORE_STREAM.jsonl.gz'),'source_manifest_sha256':sha(OUT/'SOURCE_HASHES.json'),'model_hashes':json.loads((FROZEN/'MODEL_HASHES.json').read_text()),'code_hashes':{z.name:sha(z) for z in CODE.glob('*.py')}},'next':'STOP. Package actual GET receipts and deliver fixed evidence only. No same-cycle threshold/time/quantile/model/rank/MAX/Entry/EXIT rescue or retune.'}
 save(OUT/'CLOSURE.json',x);checkpoint('V10_CLOSURE','CLOSED_STOP',x,next_direction=x['next'])
 print(json.dumps({'status':x['status'],'mismatch':0,'Control_replay':0,'policy_count':1}))
if __name__=='__main__':main()
