"""Commit all finite teacher, metric, signal and Capital choices before new results."""
from control import *
import sklearn, numpy, scipy
def main():
    assert (OUT/'HF1_HL0_NEGATIVE_HISTORY_FREEZE.json').exists()
    model=read(MAIN/'inputs/movement/models/MOVE_P_BLOCK_01.json')
    prep=model['preprocessing'];manifest=read(MOV/'FEATURE_MANIFEST.json')
    numeric=prep['numeric_fields'];categorical=prep['categorical_fields']
    assert len(numeric)==46 and len(categorical)==7
    assert set(numeric)==set(manifest['core_numeric'])|{'movement/M'+str(i) for i in range(1,17)}|{'movement/I'+str(i) for i in range(1,4)}
    assert set(categorical)==set(manifest['categorical'])
    teacher={'name':'MONETIZATION_RESIDUAL_ABOVE_BUCKET_MEDIAN_V1','abbreviation':'MRET','bucket_return_boundaries':[.01,.02,.03,.04,.05,.10],'buckets':['B0_<1','B1_1-<2','B2_2-<3','B3_3-<4','B4_4-<5','B5_5-<10','B6_>=10'],'eligible':'finite realized, finite potential, capture_complete and strictly_after_entry_before_1520; train Entry minute<920 as exact Movement fitting universe; completed-past sessions only','realized_authority':'nested main inputs/evaluation/TEACHERS_EVALUATION.jsonl.gz','median':'ordinary empirical median, even support arithmetic mean of two central binary64 values','minimum_bucket_support':10,'support_failure':'MRET_TEACHER_SUPPORT_BLOCKED; STOP; no fit','backoff':False,'merge':False,'label':'int(realized_net_return > block completed-train bucket median)','exact_tie':0,'missing':'exclude; no zero imputation','test_labels_trainer_visible':False}
    metrics={'population':'frozen COMMON_EVAL_MASK included identities intersect realized/potential eligible current OOF; all 1039 causal OOF rows scored irrespective of evaluation support','controls':['pP','q2','q3','consensus'],'consensus':'exact v10 min(rp,r2,r3), each (1+count(completed train score<current))/(train_N+1)','best_existing':'maximum MRET target AUC among C0-C3; exact ties order pP,q2,q3,consensus','HF1_HL0_contextual_control':'not required; no new artifact acquisition/refit','ROC_AUC':'binary target rank AUC; ties half; invalid one-class null','PR_AUC':'average precision (step integral), not trapezoidal PR area','Brier':'mean squared raw Logistic ordering score minus MRET binary label; no probability-calibration claim','top':'ceil(.20*N),ceil(.30*N); stable score DESC then entry_id ASC','deciles':'stable score DESC then entry_id ASC, np.array_split ten equal-count groups; decile1 highest','conditional':'within potential bucket x block, unique unordered differing-realized pairs; credit1/0/.5, summed valid-pair weighted','same_session_conditional':'within potential bucket x session; secondary','realized_diagnostics':'AUC realized>0,>=.01,<=0 and Spearman; raw score orientation unchanged including loser AUC','subset_diagnostics':['common realized-supported OOF','I2 rank-native admission','saved I2 funded identities'],'bootstrap':{'seed':5701105,'resamples':1999,'unit':'38 OOF session clusters','generator':'numpy.random.default_rng PCG64; integer session indexes shape(1999,38), lexicographic session order; duplicate clusters repeat every observation','CI':'numpy.quantile .025,.975 method=linear; invalid resamples excluded separately','deltas':['MRET target AUC','MRET target average precision','bucket/block realized concordance','realized>0 AUC','Spearman realized'],'control':'single precommitted max-target-AUC existing control, held fixed across resamples','pair_weighting':'cluster multiplicities multiply each differing-outcome pair; original pair counts not independent samples'}}
    gate={'S1':'MRET target AUC > best existing target AUC','S2':'MRET target PR-AUC > same control PR-AUC','S3':'bucket/block realized concordance > same control concordance','S4':'bucket/block realized concordance > .5','S5':'realized>0 AUC > same control realized>0 AUC','S6':'MRET target block AUC improvement >=5/8 vs same best control','S7':'catastrophic blocks0; control>=.5,candidate<.5,delta<=-.10','S8':'session bootstrap MRET target AUC delta CI lower >0','S9':'integrity/leakage/independent signal mismatch0','STRONG':'S1..S9 all pass','PROMISING':'S1..S7/S9 pass and S8 CI includes zero','NO_GO':'otherwise','Capital_permission':'STRONG only; other status CapitalReplays0 and fixed STOP'}
    config={'penalty':'l2','C':1.0,'solver':'lbfgs','max_iter':2000,'class_weight':None,'random_state':57}
    o={'schema':'CAPITAL_V11_MRET_PRECOMMIT_V1','exact_jst':now(),'teacher':teacher,'features':{'numeric_fields':numeric,'categorical_fields':categorical,'Movement_manifest_sha256':sha(MOV/'FEATURE_MANIFEST.json'),'raw_pre_entry_only':True,'scores_buckets_outcomes_identities_policy_flags_in_X':False},'model':config,'preprocessing':'exact Movement algorithm: missing numeric0 plus indicators; train-only population mean/std applied to both numeric and indicators, zero scale1; train-only sorted vocabulary explicit __UNKNOWN__; one hot categorical unscaled','train_population':'MRET eligible completed training rows; same fixed split, source stream order; no test labels in fit','temporal':read(SPLIT),'metrics':metrics,'signal_gate':gate,'versions':{'sklearn':sklearn.__version__,'numpy':numpy.__version__,'scipy':scipy.__version__},'budgets':{'MRET_fits':8,'one_per_block':True,'within_block_refits':0,'optimizer_independent_refits':0,'other_fits':0,'control_replays':0},'Exposure':'ITERATIVE_DEVELOPMENT_EVIDENCE','Safety':SAFETY}
    save(OUT/'MRET_TEACHER_FEATURE_MODEL_PRECOMMIT.json',o)
    checkpoint('R2_MRET_TEACHER_FEATURE_MODEL_PRECOMMIT','MRET teacher/features/model/metrics/bootstrap/gate frozen','R3 M1/M2 precommit')
    capital={'schema':'CAPITAL_V11_MRET_CAPITAL_PRECOMMIT_V1','exact_jst':now(),'policies':{'M1':{'name':ARMS[0],'effective_cap':'frozen band equity cap * rM','waterfill':'only initially funded rows, effective cap respected','cap_can_increase':False},'M2':{'name':ARMS[1],'effective_cap':'rM>=.5 frozen band cap; rM<.5 min(frozen band cap,exact100share BUY debit)','exact_half':'HIGH side','note':'Frozen cap remains an upper bound even where one lot exceeds it; no cap increase','waterfill':'only initially funded rows, effective cap respected'}},'rM':'(1+count(MRET eligible completed train mP<current mP))/(train_N_score+1); frozen model resubstitution; binary64 unrounded; no labels/test cross-section','selectionPolicy':I2,'batch_order':['pP DESC','Entry timestamp ASC','symbol ASC','entry_id ASC'],'frozen':{'tenure':'B2 saved table exact','pressure':.5,'support':10,'tenure_bucket_minute':30,'MAX3':3,'candidate_band_caps':{'P_HIGH':.45,'P_MID':.35,'P_BASE':.25},'base_utilization':{'P_HIGH':.68,'P_MID':.56,'P_BASE':.44},'breadth_increment':.055,'maximum_target_utilization':.92,'desired_weight':'pP proportional','lot':100,'BUY':'1.0005','SELL':'.9995','commission':0,'cutoff':920,'long_cash_only':True,'replacement':False,'no_backfill':True,'no_later_topup':True,'Entry_EXIT_Selector':'permanent frozen','MTM_cash_release':'parent exact'},'quality_retention':{'U5_min':53,'U10_min':26,'Medium_min':32,'weak_rate_max':.36024845,'below3_rate_max':.47204969,'integrity_mismatch':0,'independent_mismatch':0},'secondary_v5_floor':{'U5_min':50,'U10_min':26,'Medium_min':27,'weak_rate_max':.38666667,'below3_rate_max':.48666667},'capital_gate_strict':{'rolling20_median':1.1991541915,'rolling20_mean':1.1906460126,'daily_geometric':.01032420041},'relative_progress_strict':{'median':.9283112455,'mean':.9542671531,'daily_geometric':-.00179924717,'v5_floor_required':True,'adoption':False},'winner':'STRONG AND retention AND v5 capital; 2xN DESC,median DESC,mean DESC,daily geometric DESC,Final38 DESC,MaxDD ASC,M1 tie','diagnostic':'retention PASS first, else v5 floor PASS, else saved I2; median DESC,mean DESC,daily geometric DESC,Final38 DESC,MaxDD ASC,M1 tie','bottleneck':{'not_STRONG':'REALIZED_MONETIZATION_INFORMATION_GAP; PROMISING means unconfirmed under fixed CI gate','STRONG_no_relative_progress':'MONETIZATION_POLICY_TRANSLATION','STRONG_relative_progress_v5_fail':'MONETIZATION_SIGNAL_STRENGTH_OR_CAPITAL_MAPPING','official_capital_pass_2x0':'NORTH_STAR_CAPITAL_GAP','official_2x_hit':'DEVELOPMENT_NORTH_STAR_REQUIRES_INDEPENDENT_NEXT_WORK'},'budget':{'M1':1,'M2':1,'total_if_STRONG':2,'total_else':0,'controls':0,'M3':0},'start_yen':1000000,'OOF_sessions':38,'rolling_windows':19,'window_independence_claim':False,'Final38_one_month_claim':False,'hindsight_policy_input':False,'result_change_allowed':False,'fresh_OOS_claim':False,'Safety':SAFETY}
    save(OUT/'M1_M2_CAPITAL_POLICY_PRECOMMIT.json',capital)
    checkpoint('R3_M1_M2_CAPITAL_POLICY_PRECOMMIT','Only M1/M2 and all success/winner/bottleneck rules frozen before teacher/score results','commit -> actual GET -> R4 teacher')
    print(json.dumps({'precommit':'COMPLETE','policies':ARMS,'new_diagnostic_computed':False}))
if __name__=='__main__':main()
