"""Apply frozen gate after independent audit; preserve every original result."""
from pathlib import Path
from datetime import datetime,timezone,timedelta
from collections import Counter
import json,hashlib,csv,shutil,sys
R=Path(__file__).resolve().parent;V=R.parent/'state_predictiveness_v5_r2_confirmation_20261002_v1';P=R/'PARENT_V4'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,x):
 p=R/n;assert not p.exists(),'ALREADY_FINAL:'+n;p.write_text(json.dumps(x,ensure_ascii=False,sort_keys=True,indent=2)+'\n')
def f(x,d=2):return 'NA' if x is None else f'{x:.{d}f}'
def pct(x):return 'NA' if x is None else f'{100*x:.2f}%'
def main():
 gitgets,gitwrites=map(int,sys.argv[1:3]);jst=datetime.now(timezone(timedelta(hours=9))).isoformat();g=json.loads((R/'V6_GATE_MEASUREMENTS.json').read_text());audit=json.loads((R/'INDEPENDENT_AUDIT_V6.json').read_text());inherit=json.loads((R/'V5_INHERITANCE_RECEIPT_V6.json').read_text());pre=json.loads((R/'PREDICTIVENESS_V6_PRECOMMIT.json').read_text());caps=json.loads((R/'BUDGET_START_V6.json').read_text())['finite_caps'];acq=json.loads((R/'ACQUISITION/RUNNER_FINAL_RECEIPT.json').read_text());manifest=json.loads((R/'FRESH_DATA_MANIFEST_V6.json').read_text());draw=json.loads((R/'BOOTSTRAP_GLOBAL_1000_RECEIPT_V6.json').read_text());ledger=[json.loads(s) for s in (R/'MODEL_EXECUTION_LEDGER_V5.jsonl').open()] if (R/'MODEL_EXECUTION_LEDGER_V5.jsonl').exists() else [];frozen=True
 for n,h in pre['hashes'].items():assert sha(R/n)==h,'PRECOMMIT_BREACH:'+n
 for n,h in json.loads((R/'EVALUATION_CODE_FREEZE_V6.json').read_text())['hashes'].items():assert sha(R/n)==h,'EVALUATION_CODE_BREACH:'+n
 for c in inherit['hash_checks']:assert sha(V/c['path'])==c['SHA256'],'PARENT_V5_CHANGED'
 compliant=len(ledger)<=caps['total_fits'] and acq['actual_provider_HTTP']<=caps['new_provider_HTTP'] and acq['new_steps']<=caps['frozen_current_slot_steps'] and draw['new_generated_vectors']<=2000 and gitgets<=caps['GitHub_GET'] and gitwrites<=caps['GitHub_writes'];direct=audit['status']=='PASS' and audit['mismatch_N']==0 and compliant and acq['protected_requests']==0
 if not direct:status='BLOCKED_V6_DIRECT_INTEGRITY'
 elif g['R2_TRUE_NULL']=='FAIL':status='BLOCKED_V6_R2_CONTROL'
 elif not g['sample_PASS']:status='STATE_R2_SUPPORT_STILL_LIMITED'
 elif not all(g[k] for k in ['pooled_dangerous_PASS','V6_only_direction_PASS','concentration_PASS']) or g['R2_TRUE_NULL']!='PASS':status='STATE_R2_SIGNAL_NOT_REPLICATED'
 elif g['calibration_PASS']:status='STATE_R2_REVERSAL_INTELLIGENCE_CONFIRMED_CALIBRATED'
 else:status='STATE_R2_REVERSAL_INTELLIGENCE_CONFIRMED_ENTRY_RESEARCH_ALLOWED'
 allowed=status in ['STATE_R2_REVERSAL_INTELLIGENCE_CONFIRMED_CALIBRATED','STATE_R2_REVERSAL_INTELLIGENCE_CONFIRMED_ENTRY_RESEARCH_ALLOWED'];prob=status=='STATE_R2_REVERSAL_INTELLIGENCE_CONFIRMED_CALIBRATED';s6=g['V6_only'];pool=g['pooled'];summ=g['R1_R2_summary'];d=g['dangerous_improvement_by_population'];source=json.loads((R/'ACQUISITION/SELECTED_METADATA_SCOPE_V6.json').read_text());acqlist=list(csv.DictReader((R/'DEVELOPMENT_COMPLETION_LEDGER_V6.csv').open()));counts=Counter(x['status'] for x in acqlist);A=[x for x in acqlist if x['lane']=='A_RETRY'];B=[x for x in acqlist if x['lane']=='B_NEW'];oof=list(map(json.loads,(R/'R1_R2_OOF_V6.jsonl').open()));rr=[r for r in oof if r['control']=='REAL' and r['model']=='R2' and not r['calibrated']];folds=sorted({r['fold'] for r in rr});dates=sorted({r['date'] for r in rr});acqdates=sorted({p['date'] for p in manifest['pairs']});parentdates=set(inherit['exact_evaluable_dates']);newcluster=sorted(set(dates)-parentdates)
 if ledger:shutil.copyfile(R/'MODEL_EXECUTION_LEDGER_V5.jsonl',R/'MODEL_EXECUTION_LEDGER_V6.jsonl')
 exposure={'JST':jst,'V6_new_Development_labels':manifest['endpoint_N'],'new_Development_security_sessions':[{'pair_id':p['pair_id'],'date':p['date'],'security_id':p['security_id'],'session_id':p['session_id']} for p in manifest['pairs']],'V5_result_changes':0,'V4_status_changes':0,'result_driven_scope_or_model_changes':0,'causal_full_State9_hard_signal_only':allowed,'rank_stability_checked':False,'rank_handoff_authorized':False,'past_V5_exposure_SHA256':sha(V/'EXPOSURE_APPEND_ONLY_DELTA_V5.json'),'past_unknown_nonzero_exposure_retained':True,**{k:0 for k in ['Holdout','Protected','Fresh_validation_reserve','OOS','Prospective','Entry','EXIT','profit','Capital','Portfolio','paper_live','orders','broker_write','external_AI','main_merge','force_push','State9_changes','Path_changes','target_changes','profile_changes','M0_changes','family_mapping_changes']}}
 save('EXPOSURE_APPEND_ONLY_DELTA_V6.json',exposure)
 budget={'JST':jst,'finite_caps_unchanged':caps,'delta_at_final_report':{'fresh_fits':len(ledger),'research_fits':0,'total_fits':len(ledger),'provider_HTTP':acq['actual_provider_HTTP'],'frozen_steps':acq['new_steps'],'Actions_runs':1,'bounded_acquisition_passes':1,'V6_only_bootstrap_vectors':draw['V6_ONLY']['vector_N'],'pooled_bootstrap_vectors':draw['V5_V6_POOLED']['vector_N'],'total_bootstrap_vectors':draw['new_generated_vectors'],'GitHub_GET':gitgets,'GitHub_writes':gitwrites},'independent_new_fit_draws':[0,0],'cumulative_known_provider_HTTP':inherit['past_known_provider_HTTP']+acq['actual_provider_HTTP'],'cumulative_known_kernel_steps':inherit['past_known_kernel_steps']+acq['new_steps'],'cumulative_known_bootstrap_vectors':inherit['past_known_bootstrap']+draw['new_generated_vectors'],'V1_3000_cap1000_breach_retained':True,'V2_four_fit_ledger_gap_retained':True,'old16FAIL_and_88workflow_incident_retained':True,'past_unknown_history_not_reset':True,'finite_budget_compliant':compliant,'GitHub_delivery_tail_recorded_separately':True,'start_GET_display_note':'BUDGET_START initial_GitHub_GET_N11 omitted one source-index read-only GET; full counter and final actual usage include it; no cap/contract/source/result mutation'}
 save('BUDGET_FINAL_V6.json',budget)
 frozenreceipt={'JST':jst,'status':status,'candidate_specification_frozen':bool(allowed),'primary_candidate':'R2','State9_semantic_SHA256':json.loads((R/'FROZEN_IDENTITY_RECEIPT_V6.json').read_text())['schema_SHA256'],'model_source_SHA256':sha(R/'MODEL_V5.py'),'target_source_SHA256':sha(R/'TARGET_KERNEL_V3_FROZEN.py'),'R2_final_all_data_refit':0,'deployment_authorized':False,'next_work':'HYBRID_ENTRY_INTELLIGENCE' if allowed else 'NEW_PRECOMMITTED_R2_CONFIRMATION_OR_DIRECT_FAILURE_REVIEW','representation_allowed':['Full State9 causal representation','R2 hard class'] if allowed else [],'probability_allowed_for_next_research':prob,'relative_rank_allowed':False,'semantic_target_changes':0}
 save('STATE_INTELLIGENCE_FREEZE_V6.json',frozenreceipt)
 final={'JST':jst,'status':status,'direct_integrity':'PASS' if direct else 'FAIL','independent_audit':audit['status'],'mismatch_N':audit['mismatch_N'],'R2_TRUE_NULL':g['R2_TRUE_NULL'],'sample_PASS':g['sample_PASS'],'pooled_dangerous_PASS':g['pooled_dangerous_PASS'],'V6_only_direction_PASS':g['V6_only_direction_PASS'],'concentration_PASS':g['concentration_PASS'],'calibration_PASS':g['calibration_PASS'],'Hybrid_Entry_research_allowed':allowed,'calibrated_probability_handoff_allowed':prob,'relative_rank_handoff_allowed':False,'promoted_representation':['Full State9 causal representation','R2 hard class'] if allowed else [],'V5_status_unchanged':'STATE_R2_CONFIRMATION_LIMITED_SAMPLE','V4_status_unchanged':'BLOCKED_V4_INTEGRITY','contract_SHA256':sha(R/'PREDICTIVENESS_V6_CONTRACT.md'),'precommit_SHA256':sha(R/'PREDICTIVENESS_V6_PRECOMMIT.json'),'scope_SHA256':sha(R/'FRESH_SCOPE_V6.json'),'OOF_SHA256':sha(R/'R1_R2_OOF_V6.jsonl'),'fresh_fits':len(ledger),'new_bootstrap_vectors':draw['new_generated_vectors'],'Entry_fit':0,'EXIT_rule':0,'result_driven_changes':0};save('FINAL_RECEIPT_V6.json',final)
 answers=[
 ('V5原本hash／HEAD',f"branch `{inherit['V5_branch']}`、実験C7 `{inherit['V5_final_experimental_HEAD']}`、納品HEAD `{inherit['V5_final_delivery_HEAD']}`。原本Contract／Precommit／scope／OOFのSHAは後表、全原本照合PASS。"),
 ('V6で追加できた日数',f"入力取得{len(acqdates)}日、evaluable V6-only OOF{s6['dates']}日。V5 OOFと重ならない新しい日clusterは{len(newcluster)}日。完全未exposed日数と呼ばず、未exposed security-sessionとして登録。"),
 ('V6 security-session追加',f"{manifest['fresh_pair_N']}件／{manifest['fresh_security_N']}security。OOF available targetのsecurity数{s6['securities']}。A回収{sum(x['status']=='ACQUIRED' for x in A)}/136件、B取得{sum(x['status']=='ACQUIRED' for x in B)}/{len(B)}件。"),
 ('V6-only DOWN support',str(s6.get('DOWN_REVERSAL_support',0))),('pooled DOWN support',str(pool.get('DOWN_REVERSAL_support',0))),('pooled UP support',str(pool.get('UP_CONTINUE_support',0))),
 ('V6-only R1 dangerous FP',f"{summ['V6_ONLY']['R1']['dangerous_numerator']}/{summ['V6_ONLY']['R1']['dangerous_denominator']} = {pct(summ['V6_ONLY']['R1']['dangerous_rate'])}"),
 ('V6-only R2 dangerous FP',f"{summ['V6_ONLY']['R2']['dangerous_numerator']}/{summ['V6_ONLY']['R2']['dangerous_denominator']} = {pct(summ['V6_ONLY']['R2']['dangerous_rate'])}"),
 ('pooled R1 dangerous FP',f"{summ['V5_V6_POOLED']['R1']['dangerous_numerator']}/{summ['V5_V6_POOLED']['R1']['dangerous_denominator']} = {pct(summ['V5_V6_POOLED']['R1']['dangerous_rate'])}"),
 ('pooled R2 dangerous FP',f"{pool['dangerous_numerator']}/{pool['dangerous_denominator']} = {pct(pool['dangerous_rate'])}"),
 ('pooled improvement pp',f(d['V5_V6_POOLED']['improvement_pp'],4)),('pooled95%CI',f"[{f(d['V5_V6_POOLED']['improvement_CI_low_pp'],4)}, {f(d['V5_V6_POOLED']['improvement_CI_high_pp'],4)}] pp。pooled日cluster1000 once、同日付を期間で分けない。"),
 ('V6-only改善方向',f"{'維持' if g['V6_only_direction_PASS'] else '逆転／未評価'}。R1−R2 {f(d['V6_ONLY']['improvement_pp'],4)} pp、95%CI [{f(d['V6_ONLY']['improvement_CI_low_pp'],4)}, {f(d['V6_ONLY']['improvement_CI_high_pp'],4)}] pp。"),
 ('R2 DOWN Precision／Recall／F1',f"V6-only {pct(s6.get('DOWN_REVERSAL_Precision'))}／{pct(s6.get('DOWN_REVERSAL_Recall'))}／{pct(s6.get('DOWN_REVERSAL_F1'))}。pooled {pct(pool.get('DOWN_REVERSAL_Precision'))}／{pct(pool.get('DOWN_REVERSAL_Recall'))}／{pct(pool.get('DOWN_REVERSAL_F1'))}。"),
 ('R2 UP Precision／Recall／F1',f"V6-only {pct(s6.get('UP_CONTINUE_Precision'))}／{pct(s6.get('UP_CONTINUE_Recall'))}／{pct(s6.get('UP_CONTINUE_F1'))}。pooled {pct(pool.get('UP_CONTINUE_Precision'))}／{pct(pool.get('UP_CONTINUE_Recall'))}／{pct(pool.get('UP_CONTINUE_F1'))}。"),
 ('TRUE_NULL PASSか',g['R2_TRUE_NULL']+'。raw/cal対称candidate-local、V6-only／pooled別表。R3過去failureによる自動BLOCKなし。'),
 ('concentration PASSか',str(g['concentration_PASS'])+'。V6-onlyとpooledのgross dangerous reduction／class correctness gainにmax日／security share<=0.5。State/foldは参考開示。'),
 ('independent mismatch0か',str(audit['mismatch_N'])+'、'+audit['status']+'。fit0／draw0、target／timestamps／purge／encoder／coefficients／alpha／T／予測／control／pooled／metric／CIを別logicで確認。'),
 ('calibration PASSか',str(g['calibration_PASS'])+'。V5固定rolling方式を変更0で適用。R2 date-equalLLとROW Brierのraw比5%gate、ECE／bucketも保存。'),
 ('hard signalだけでEntry researchへ進めるか','はい。固定gateを満たした範囲で次Workを許可。' if allowed else 'いいえ。V6固定gateを満たしていない。'),
 ('Entryへ渡してよい情報','causal Full State9 representationとR2 hard class。rankは未監査のため渡さない。'+('Protocol calibration gateもPASS、確率Evidenceは次研究で検証可能。' if prob else '確率は信頼できるprobabilityとして渡さない。') if allowed else 'promotionされたState representationなし。保存Evidenceのみ。'),
 ('禁止probability解釈','calibration未達なら「DOWN probability=8.3%」等の確率解釈、probability Entry threshold／position sizingを禁止。calibration PASSでもV6内のEntry rule／sizing／注文は0。'),
 ('State9／Path／target変更0か','各0。profile／M0／family mapping／R2 feature schema／base mathsも0。V5原本上書き0。'),
 ('Holdout／Protected exposure0か','V6 delta各0。Fresh reserve／OOS／Prospective／Entry／EXIT／profit／broker write等も0、過去unknown／nonzero履歴は保持。'),
 ('次はHybrid Entryへ進むか','はい。次Workの研究handoffのみ、V6ではEntry fit0／判断threshold0／EXIT rule0。' if allowed else '進まない。追加承認scopeまたは今回の固定failure理由を別Workで扱う。')]
 report=[f'# Ark Terminal State Predictiveness V6\n\nFinal status: `{status}`。JST {jst}。\n',f'V6-only DOWN {s6.get("DOWN_REVERSAL_support",0)}／UP {s6.get("UP_CONTINUE_support",0)}、pooled DOWN {pool.get("DOWN_REVERSAL_support",0)}／UP {pool.get("UP_CONTINUE_support",0)}。pooled危険率 {pct(summ["V5_V6_POOLED"]["R1"]["dangerous_rate"])} → {pct(pool["dangerous_rate"])}、改善 {f(d["V5_V6_POOLED"]["improvement_pp"],4)} pp。\n',f'Lane H integrity {final["direct_integrity"]}／TRUE_NULL {g["R2_TRUE_NULL"]}／independent {audit["status"]}（mismatch{audit["mismatch_N"]}）。Lane P calibration {"PASS" if g["calibration_PASS"] else "FAIL"}。V5はLIMITED_SAMPLEのまま、V4はBLOCKEDのまま。\n','## 必須25回答\n\n| # | 問い | 原本に基づく結果 |\n| ---: | --- | --- |']
 report.extend(f'| {k} | {question} | {answer} |' for k,(question,answer) in enumerate(answers,1));report+=['\n## R1／R2比較\n\n| population | model | N | DOWN | UP | dangerous numerator/denominator | rate | DOWN P/R/F1 | UP P/R/F1 | balanced accuracy | macro F1 |\n| --- | --- | ---: | ---: | ---: | --- | ---: | --- | --- | ---: | ---: |']
 for pop in ['V5_ONLY','V6_ONLY','V5_V6_POOLED']:
  for model in ['R1','R2']:
   s=summ[pop][model];report.append(f'| {pop} | {model} | {s["N"]} | {s.get("DOWN_REVERSAL_support",0)} | {s.get("UP_CONTINUE_support",0)} | {s["dangerous_numerator"]}/{s["dangerous_denominator"]} | {pct(s["dangerous_rate"])} | {pct(s.get("DOWN_REVERSAL_Precision"))}/{pct(s.get("DOWN_REVERSAL_Recall"))}/{pct(s.get("DOWN_REVERSAL_F1"))} | {pct(s.get("UP_CONTINUE_Precision"))}/{pct(s.get("UP_CONTINUE_Recall"))}/{pct(s.get("UP_CONTINUE_F1"))} | {pct(s.get("balanced_accuracy"))} | {pct(s.get("macro_F1"))} |')
 raw=g['V6_raw'];report+=['\n## Probability Lane P\n\n| V6 R2 | row LL | date-equal LL | row Brier | ECE |\n| --- | ---: | ---: | ---: | ---: |',f'| raw | {f(raw.get("row_LL"),6)} | {f(raw.get("date_equal_LL"),6)} | {f(raw.get("Brier"),6)} | {f(raw.get("ECE"),6)} |',f'| calibrated | {f(s6.get("row_LL"),6)} | {f(s6.get("date_equal_LL"),6)} | {f(s6.get("Brier"),6)} | {f(s6.get("ECE"),6)} |','\npositive temperatureはhard argmaxと同一row内class順序を変えない。異なるrow間のrelative rank stabilityは今回は評価していないのでhandoffしない。calibration PASSは固定relative悪化gateの合格であり、実運用確率の全面保証ではない。\n','## 固定scope・取得・split\n',f'136件の原順序、fresh retry許可60件、prior raw／label／protected76件は明示skip。Bはmetadata79日・最大4security/day、finite316上限。metadataで実選択{len(B)}件を全minute取得前に固定、結果によるrefill0。入力{len(acqdates)}日／{manifest["fresh_pair_N"]}security-session、OOF{len(dates)}日／{len(folds)}fold。calendar92日first5 warmup+3 blocks、空fold／空日も保持。status counts `{dict(counts)}`。\n',f'新provider{acq["actual_provider_HTTP"]}/2000HTTP、frozen kernel{acq["new_steps"]}/125000steps、fresh{len(ledger)}/160fits、research0、Actions1、V6-only1000+pooled1000 exactly once（actual {draw["new_generated_vectors"]}）。independent fit/draw0。V1 3000/cap1000 breach、V2 gap、old16FAIL/88workflow incident等は消さない。\n','## 観測の限界\n','V5+V6はユーザー指定のregistered cumulative support completion。V5をfreshに見せ直していない。V6は未exposed security-sessionで、同日other-security exposureや同じmarket regimeを含む。pooled union日clusterを利用し、V5/V6の同日を二重clusterにしない。OOFはpast-only trainでprequential、厳密な全期間未exposed OOSではない。V5絶対危険率とV6絶対危険率の上下をそのまま改善量と呼ばず、各populationのR1−R2を比較する。\n','historical known_atはUNKNOWN。bar-end因果availability仮定とprefix/timestamp監査を分離し、全State9 semantic kernel再auditはしていない。DOWN Recallとdangerous率は異なる分母。DOWNを見逃すriskとUP recall低下も表で開示。profit／cost／Entry／EXITルールの実測Evidenceにはしない。provider原ページは安全なrunner一時領域からpurge済み、原ページそのものの復元を保証しない。features／trace／source hash／M0照合を保持し、復元目的の新再取得はしない。\n','## V5原本identity\n\n| identity | SHA256 |\n| --- | --- |']
 report.extend(f'| {r["identity"]} | `{r["SHA256"]}` |' for r in inherit['hash_checks']);report+=['\n公開CSVはV5のp.read_text()公開処理によりCRLF→LF変換、原本ZIPのbyte/SHAが優先。V5 source indexはexperiment C7とdelivery snapshotを明示区分。これらは数値／label／予測の書換えではなく、原本hash照合PASS。\n','## Handoff\n',f'次Work: {"HYBRID ENTRY INTELLIGENCE" if allowed else "新しい事前固定確認またはfailureレビュー"}。自動実行0。HYBRID_ENTRY_INTELLIGENCE_HANDOFF.mdとSTATE_INTELLIGENCE_FREEZE_V6.jsonに受け渡し許可／禁止を固定。\n','## 納品\n\n2〜3個の通常ZIPを同じfolderに展開。V6報告／CSV／OOF／labels／fits／feature／trace／control／bootstrapvectors／audit／取得reasonを保持。V5 COMPLETE原本3 ZIPは変更せず同梱、元V4/V3 evidenceまで保持。Git-backed codeはSOURCE_CODE_LOCATION_INDEX_V6.jsonのexact commit/path/hash。再fit／再label／新draw／再取得は納品検証に不要。']
 (R/'REPORT-ja.md').write_text('\n'.join(report)+'\n')
 schema=json.loads((P/'FEATURE_SCHEMA_V4.json').read_text());handoff=f'''# Hybrid Entry Intelligence handoff from V6

Status `{status}`. Entry research allowed: {allowed}. V6 Entry fit0, threshold0, EXIT rule0, profit/capital/portfolio0, paper/live/orders0.

## Fixed State representation

R2 Full State9 is the sole candidate. Use the causal V5 State-only schema unchanged. Numeric `{schema['numeric_state']}`. Categorical `{schema['categorical_state']}`. Schema SHA256 `{sha(P/'FEATURE_SCHEMA_V4.json')}`. Exact base model source `{sha(R/'MODEL_V5.py')}`, target `{sha(R/'TARGET_KERNEL_V3_FROZEN.py')}`. The freeze is a candidate specification and saved OOF evidence, not a newly fitted deployable global model. Final all-data fit0.

## Permission boundary

{('Permit causal Full State9 and R2 hard class as baseline in the next independently precommitted Entry research.' if allowed else 'No promoted representation. Preserve evidence; do not start Entry from this result.')}
{('Protocol calibration gate PASS, probability evidence may be validated further in next research. This is not an Entry rule or probability sizing authorization.' if prob else 'Do not interpret raw or not-ready calibrated scores as reliable DOWN probabilities. No probability Entry threshold or position sizing.')}
Relative rank is not handed off: rank stability was not validated in V6. R3/R4 predictor promotion0. Path anatomy stays descriptive. State/Path/target/family meanings remain frozen.

## Next research sequence if authorized

For Selector-chosen Opportunity, enter while upside may remain rather than require an exact bottom. First baseline State9/reversal intelligence. Then evaluate one causal family at a time: Selector information, price structure, volume/liquidity, relative strength, market/sector context, volatility, time-of-day. Keep incremental value attributable. Freeze partitions, finite scope, timestamp availability, target/metrics/control, budget before new labels. Do not reuse exposed V1–V6 as fresh confirmation or downgrade reserves.

Separate UP continuation, DOWN risk, entry delay, available upside, winner capture, false entry, downside and transaction cost. A benign PULLBACK should not automatically prohibit Entry. No threshold optimizing or Entry fits have been done here. Remaining DOWN risk is not required to be0% at Entry.

## Future EXIT evidence, not EXIT rules

Shared causal State9 and CONTEXT_REVERSAL event-order evidence may later support UP_CONTINUE/HOLD research, benign-PULLBACK early-sale avoidance, true DOWN_REVERSAL/EXIT research and selling near highs rather than exact highs. V6 does not map classes to actionable HOLD/EXIT orders. Use a new independently fixed EXIT Work. Aim eventually to realize portions of Selector-following upward moves; current results contain no realized-profit evidence.

## Evidence caveats

Pooled support DOWN {pool.get('DOWN_REVERSAL_support',0)} /UP {pool.get('UP_CONTINUE_support',0)}, dangerous improvement {f(d['V5_V6_POOLED']['improvement_pp'],4)}pp, CI[{f(d['V5_V6_POOLED']['improvement_CI_low_pp'],4)},{f(d['V5_V6_POOLED']['improvement_CI_high_pp'],4)}]pp. V6-only direction PASS {g['V6_only_direction_PASS']}. DATE-cluster dependence retained; reused dates are not completely fresh market regimes. historical known_at UNKNOWN /causal bar-end assumption. No promise of safe Entry, profit or live performance.
'''
 (R/'HYBRID_ENTRY_INTELLIGENCE_HANDOFF.md').write_text(handoff)
 (R/'NEXT_STAGE_HANDOFF.md').write_text(f'# V6 next-stage handoff\n\nStatus `{status}`.\n\n'+('Next authorized research: HYBRID ENTRY INTELLIGENCE. Use causal Full State9 / R2 hard class only unless final calibrated permission=true. Relative rank not authorized. No automatic fits or orders.\n' if allowed else 'Do not start Hybrid Entry. Preserve V5/V6 evidence, finite unavailable ledger and failed gates. A new request and new precommit are required for further scope/research.\n')+'\nRead REPORT-ja.md / FINAL_RECEIPT_V6.json / HYBRID_ENTRY_INTELLIGENCE_HANDOFF.md / STATE_INTELLIGENCE_FREEZE_V6.json, then source index / scope / precommit / OOF / independent audit. V5 and V4 remain unchanged. Do not re-execute completed acquisition/fits/bootstrap.\n')
 (R/'00_README.txt').write_text(f'Ark Terminal State Predictiveness V6 COMPLETE\nStatus: {status}\nJST: {jst}\nRead REPORT-ja.md / REPORT-ja.html / FINAL_RECEIPT_V6.json / NEXT_STAGE_HANDOFF.md first.\nUnchanged parent V5 LIMITED_SAMPLE and V4 BLOCKED; exact original V5 ZIPs preserved.\nExtract every ordinary ZIP into the same directory. See DELIVERY_MANIFEST.json for byte/hash/placement, SOURCE_CODE_LOCATION_INDEX_V6.json for Git-backed code.\nR2 is the only candidate. Entry fits/rules/orders0. Probabilities and relative rank are not automatically authorized.\n')
 save('REPORT_25_ANSWERS_V6.json',{'status':status,'answers':[{'N':k,'question':q,'answer':a} for k,(q,a) in enumerate(answers,1)]})
 print(json.dumps({'status':status,'Entry_research_allowed':allowed,'calibrated_probability_allowed':prob,'V6_only_DOWN':s6.get('DOWN_REVERSAL_support',0),'pooled_DOWN':pool.get('DOWN_REVERSAL_support',0),'pooled_improvement':d['V5_V6_POOLED'],'audit':audit['status'],'mismatch':audit['mismatch_N'],'fits':len(ledger)}))
if __name__=='__main__':main()
