"""Finite metadata-only V6 support-completion scope. Outcome/risk driven choices0."""
from pathlib import Path
from datetime import datetime,timezone,timedelta
import json,hashlib,shutil
R=Path(__file__).resolve().parent;V=R.parent/'state_predictiveness_v5_r2_confirmation_20261002_v1';P=V/'PARENT_V4'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,x):
 p=R/n;assert not p.exists(),'ALREADY_FIXED:'+n;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,sort_keys=True,ensure_ascii=False,indent=2)+'\n')
def main():
 i=json.loads((R/'INVENTORY_PROVENANCE_V6.json').read_text());inherit=json.loads((R/'V5_INHERITANCE_RECEIPT_V6.json').read_text());jst=datetime.now(timezone(timedelta(hours=9))).isoformat();a=i['original_ordered_unavailable136'];dev=json.loads((V/'INVENTORY_METADATA/SESSION_ALLOCATION_METADATA_V3.json').read_text());dev={d for k,ds in dev['partitions'].items() if k.startswith('DEVELOPMENT_') for d in ds};parent=json.loads((P/'DATA_SCOPE_V4.json').read_text());approved=set(parent['authorized_Development_days'])|dev;blocked=set(i['blocked_days']);scopeA=[]
 for p in a:
  permitted=p['date'] in approved and p['previous'] in approved and p['date'] not in blocked and p['previous'] not in blocked
  scopeA.append({**p,'V6_minute_retry_authorized':bool(permitted and p['fresh_pair_eligible_before_retry']),'V6_pre_skip_reason':None if permitted and p['fresh_pair_eligible_before_retry'] else 'PROTECTED_OR_NONAPPROVED_DEPENDENCY' if not permitted else 'PRIOR_CURRENT_RAW_OR_LABEL_EXPOSURE_NO_FRESH_REUSE'})
 b=i['eligible_links'];calendar=sorted({p['date'] for p in scopeA if p['V6_minute_retry_authorized']}|{p['date'] for p in b});remaining=calendar[5:];q,n=divmod(len(remaining),3);blocks=[];cursor=0
 for k in range(3):size=q+int(k<n);blocks.append(remaining[cursor:cursor+size]);cursor+=size
 exclusion={(p['date'],p['code']) for p in i['historical_current_or_dependency_raw_exclusion_pairs']+i['previously_selected_pairs_no_replacement']}
 for p in json.loads((V/'extension_runner/config.json').read_text())['exclusion_pairs']:exclusion.add((p['date'],p['code']))
 caps={'total_fits':160,'fresh_fits':160,'research_fits':0,'new_provider_HTTP':2000,'frozen_current_slot_steps':125000,'Actions_runs':1,'fanout':1,'bounded_acquisition_passes':1,'fixed_retry_proposals':136,'max_new_metadata_proposals':len(b)*4,'global_V6_only_bootstrap_vectors':1000,'global_pooled_bootstrap_vectors':1000,'bootstrap_generations':2,'GitHub_GET':140,'GitHub_writes':50}
 budget={'JST':jst,'document':'WORK_STATE_PREDICTIVENESS_V6_HARD_SIGNAL_SUPPORT_COMPLETION_20261002_V1','finite_caps':caps,'fits_labels_draws_at_start':[0,0,0],'initial_GitHub_GET_N':11,'inherited_V5_budget_final_SHA256':sha(V/'BUDGET_FINAL_V5.json'),'past_known_provider_HTTP':inherit['past_known_provider_HTTP'],'past_known_kernel_steps':inherit['past_known_kernel_steps'],'past_known_bootstrap_vectors':inherit['past_known_bootstrap'],'past_history_not_reset':True,'V1_3000_cap1000_breach_retained':True,'V2_fit_ledger_gap_retained':True,'old16FAIL_and_88workflow_incident_retained':True,'independent_new_fit_draws':0,'R3_R4_fits':0,'calibration_method_research_fits':0,'cap_stop':'stop before next charge; no expansion or unrecorded retry'}
 save('BUDGET_START_V6.json',budget);save('BUDGET_START_V5.json',budget)
 scope={'JST':jst,'document':budget['document'],'parent_HEAD':inherit['V5_final_delivery_HEAD'],'unit':'unexposed exact Development security/session, not wholly new dates','priority':'A prior fixed unavailable original order; B metadata-only unexposed pairs, all fixed before minute/label','A_ordered136':scopeA,'A_retry_N':sum(p['V6_minute_retry_authorized'] for p in scopeA),'B_eligible_links':b,'B_eligible_dates':[p['date'] for p in b],'B_date_exclusions':i['date_exclusions'],'B_max_securities_per_day':4,'B_target_N_upper':len(b)*4,'B_selection':'paired dated master Code/Mkt/CoName/ProdCat continuity; exact inherited sorted-metadata SHA256 order; first4 factor-compatible unexposed codes; factor-only Daily projections; all selection before any current minute read','B_exclusion_pairs':[{'date':d,'code':c} for d,c in sorted(exclusion)],'B_current_and_previous_exclusion':True,'B_dynamic_dependency_exposure_rule':'before minute acquisition, freeze all B selections; if a selected current pair was returned as another selected earlier dependency, conservatively exclude that later test pair; do not refill','blocked_days':sorted(blocked),'approved_minute_days':sorted(approved-blocked),'fixed_calendar_dates':calendar,'outer_warmup_dates':calendar[:5],'outer_test_blocks':blocks,'chronological_scope_order':'A original136 first, B ascending eligible dates then exact metadata SHA order','provider_request_cap':caps['new_provider_HTTP'],'frozen_slot_step_cap':caps['frozen_current_slot_steps'],'maximum_possible_export_steps':327*(sum(p['V6_minute_retry_authorized'] for p in scopeA)+len(b)*4),'outcomes_or_labels_before_freeze':0,'no_support_driven_extension':True,'replacement_after_raw':0,'single_bounded_pass':True,'scope_provenance_SHA256':sha(R/'INVENTORY_PROVENANCE_V6.json')}
 assert scope['maximum_possible_export_steps']<=caps['frozen_current_slot_steps'],'SCOPE_STEP_CAP_DESIGN'
 save('FRESH_SCOPE_V6.json',scope);save('FRESH_SCOPE_PRECOMMIT_V6.json',{'JST':jst,'scope_SHA256':sha(R/'FRESH_SCOPE_V6.json'),'source_provenance_SHA256':sha(R/'INVENTORY_PROVENANCE_V6.json'),'budget_start_SHA256':sha(R/'BUDGET_START_V6.json'),'minute_requests':0,'fresh_labels':0,'fits':0,'fixed_order':True,'new_Protected_scope':0})
 for name in ['MODEL_V5.py','TARGET_KERNEL_V3_FROZEN.py','FORENSICS_V5.py','AUDIT_RESEARCH_V5.py']:
  shutil.copyfile(V/name,R/name)
 (R/'PARENT_V4').symlink_to(P,target_is_directory=True)
 save('FROZEN_IDENTITY_RECEIPT_V6.json',{'JST':jst,'status':'PASS','parent_HEAD':inherit['V5_final_delivery_HEAD'],'unchanged_core_sources':{n:sha(R/n) for n in ['MODEL_V5.py','TARGET_KERNEL_V3_FROZEN.py']},'schema_SHA256':sha(P/'FEATURE_SCHEMA_V4.json'),'parent_identity_receipt_SHA256':sha(V/'FROZEN_IDENTITY_RECEIPT_V5.json'),'semantic_changes':{'State9':0,'Path':0,'profile':0,'M0':0,'target':0,'family_mapping':0,'R2_input_schema_encoder_alpha_family_decision_split_purge_timestamp':0},'instrumentation_note':'immutable V5 model source retains V5 ledger/budget basenames in V6 private root; V6 ledger receipts explicitly reconcile them; no parent path is written','V5_result_changes':0})
 save('SPLIT_PLAN_V6.json',{'chronological':True,'fixed_calendar_dates':calendar,'warmup_dates':calendar[:5],'fixed_three_blocks':blocks,'training':'V4/V5 exposed only when strictly before outer test; earlier V6 train may be used; same-date and future labels never training','purge':'REAL and whole-label donor label_end strictly before test_start','minimum_initial_train_input_dates':5,'empty_date_retained':True,'availability_or_result_refolding':False})
 print(json.dumps({'A_ordered':136,'A_authorized_fresh_retries':scope['A_retry_N'],'B_dates':len(b),'B_max_new_pairs':scope['B_target_N_upper'],'calendar_dates':len(calendar),'maximum_steps':scope['maximum_possible_export_steps'],'HTTPcap':caps['new_provider_HTTP'],'new_labels':0,'new_fits':0,'scope_SHA256':sha(R/'FRESH_SCOPE_V6.json')}))
if __name__=='__main__':main()
