"""Terminal contract-failure evidence. Never runs solver, tables or replay."""
from control import *
def main():
 assert not (OUT/'PPRANK_DIAGNOSTIC_RESULT.json').exists()
 assert (PRIVATE/'PPRANK_CLAIRVOYANT_ADMISSION_DIAGNOSTIC_STARTED.json').exists()
 assert not any((PRIVATE/f'{a}_STARTED.json').exists() for a in ARMS)
 counts=COUNTS|{'primary_pP_diagnostic_solve':1};claim=read(OUT/'PPRANK_DIAGNOSTIC_PRECOMMIT.json');marker=PRIVATE/'PPRANK_CLAIRVOYANT_ADMISSION_DIAGNOSTIC_STARTED.json'
 failure={'exact_jst':now(),'status':'V8_CONTRACT_FAIL','failed_stage':'D5_PPRANK_DIAGNOSTIC_RESULT','execution_session_id':46293,'process_exit_code':1,'exception':'AssertionError: CASH_WITNESS_BLOCKED_NO_SECOND_SOLVE','location':'diagnostic.py solve() cash witness assertion, line 52','diagnostic_execution_started_receipt':read(marker),'diagnostic_execution_started_receipt_sha256':sha(marker),'precommit_sha256':sha(OUT/'PPRANK_DIAGNOSTIC_PRECOMMIT.json'),'precommitted_STOP_rule':claim['algorithm'],'claim_code_hash_exact':all(sha(CODE/n)==v for n,v in claim['code_sha256'].items()),'attempted_primary_diagnostic_solve_N':1,'certified_primary_diagnostic_solve_N':0,'second_solve':0,'B1_replay':0,'B2_replay':0,'independent_pP_solve':0,'runtime_policy_result':None,'cash_only_diagnostic_schedule_certified':False,'failure_not_rank_or_B1_B2_NO_GO':True,'cause':'The chosen interval-only min-cost-flow relaxation omitted cash while optimizing. Its minimum-lot witness failed cash>=0. A cash-relaxed optimum is not a valid cash-constrained diagnostic result.','scope_limit':'This does not show B1/B2 policy failure, cash sizing bottleneck, or lack of pP scheduling signal. Those are unevaluated.','recovery':'Known failed execution, not ambiguous; no rerun. STOP under committed rule. A corrected joint-cash evaluation solver requires a separate authorized cycle.','Safety':SAFETY}
 save(OUT/'FAILED_DIAGNOSTIC_EXECUTION_RECEIPT.json',failure)
 save(OUT/'APPEND_ONLY_STAGE_CORRECTION.json',{'exact_jst':now(),'D5_named_GitHub_publication':'Published new implementation source and earlier receipts only. No D5 checkpoint or successful diagnostic result exists. Its actual GET receipt proves publication, not solve success.','D6':'B1/B2 specification precommit exists; no tables/canaries/Main were executed. This spec publication occurred after failed diagnostic execution before STOP processing.','no_prior_record_rewritten':True,'first_incomplete_checkpoint':'D5_PPRANK_DIAGNOSTIC_RESULT','research_resume_forbidden_in_this_cycle':True,'next_policy':'D16 fixed contract-failure closure only'})
 save(OUT/'PRESERVATION_RESULT.json',{'exact_jst':now(),'status':'NOT_EVALUATED_CONTRACT_BLOCKED','profiles':{a:None for a in ARMS},'primary_N':1028,'U5_denominator':170,'U10_denominator':67,'admission_U5_denominator':124,'admission_U10_denominator':55,'gate_PASS_claim':False,'Main_replays':0})
 save(OUT/'CAPITAL_ROLLING20_RESULT.json',{'exact_jst':now(),'status':'NOT_EVALUATED_CONTRACT_BLOCKED','profiles':{a:None for a in ARMS},'38_session_chains':0,'20_session_windows_evaluated':0,'two_x_hit_N':None,'gate_PASS_claim':False})
 save(OUT/'INDEPENDENT_AUDIT.json',{'exact_jst':now(),'status':'NOT_RUN_CONTRACT_BLOCKED','required_full_independent_mismatch_N':None,'mismatch0_claim':False,'independent_policy_audit':False,'independent_pP_diagnostic_solve_N':0,'B1_B2_independent_recalculation_N':0,'reason':'Failed mandatory diagnostic contract and precommitted STOP before tables/canary/Main. No invented independent success.'})
 refs=read(OUT/'SAVED_REFERENCE_FREEZE.json');v5=refs['v5_benchmark'];saved=list(refs['v7_saved_profiles'].items());anatomy=read(OUT/'BLOCKED_WINNER_ANATOMY.json')['aggregate'];s=[]
 s+=['## A. North Star / rolling 20 sessions','','|Profile|20d min|20d mean|20d median|20d max|2x hit|','|---|---:|---:|---:|---:|---:|']
 for label,z in [('v5 saved',v5)]+[(f'v7 A{i+1} saved',z) for i,(k,z) in enumerate(saved)]:
  s.append(f"|{label}|{z['rolling20_minimum']:.10f}x|{z['rolling20_arithmetic_mean']:.10f}x|{z['rolling20_median']:.10f}x|{z['rolling20_maximum']:.10f}x|{z['north_star_hit_N']}/19|")
 s+=['|B1|未評価|未評価|未評価|未評価|未評価|','|B2|未評価|未評価|未評価|未評価|未評価|','','Status = **V8_CONTRACT_FAIL**。pP clairvoyant diagnosticのcash-only証明が失敗したため、事前commit済みSTOP ruleで停止。B1/B2 Main replayは0回。policyのNO_GOとは判定しない。','','## B. U5/U10 preservation','','|Profile|U5/170|U10/67|Admission recovery U5|Physical recovery U5|<2|Reserve U5|MAX3 U5|Rank reject U5|','|---|---:|---:|---:|---:|---:|---:|---:|---:|',f"|v5 saved|50/170|26/67|50/116|50/149|38.666667%|30|28|57|"]
 for i,(k,z) in enumerate(saved):
  p=refs['v7_saved_preservation'][k];q=p['funded_quality'];below=q.get('below2_rate',q.get('below2_N',0)/z['funded_N']);c=p['conservation']['U5']
  s.append(f"|v7 A{i+1} saved|{p['U5_funded']}/170|{p['U10_funded']}/67|{p['U5_funded']}/116|{p['U5_funded']}/149|{below*100:.6f}%|{c['LAST_SLOT_RESERVE_REJECT']}|{c['MAX3_FULL']}|{c['RANK_BASE_REJECT']}|")
 s+=['|B1|未評価|未評価|未評価|未評価|未評価|未評価|未評価|未評価|','|B2|未評価|未評価|未評価|未評価|未評価|未評価|未評価|未評価|','','v7 savedのみを表示。旧Oracleは再solveしていない。Admissionはruntime 490件、実行ソース完備488件。差の2 negative候補を削除せず、未来のexecution availabilityをruntime gateへ追加しなかった。','','## C. Preservation Gate','','B1/B2ともNOT_EVALUATED。U5>50、U10>=26、<2<=38.666667%、Admission recovery>50/116、integrity0、独立mismatch0のPASS claimは0。','','## D. Capital Gate','','B1/B2ともNOT_EVALUATED。rolling20 median/mean/daily geometricは生成していない。2x hit=0とは扱わず未評価とする。','','## E. Physical / Admission / Runtime waterfall','','|段階|U5|今回の扱い|','|---|---:|---|','|Primary|170|common supported OOF固定|','|Physical Oracle|149|v7 savedのみ|','|Admission Oracle|116|v7 savedのみ|','|B1/B2 runtime|未評価|Main 0回|','','Physical unavoidable=21、Admission ceiling loss=33は別のcounterfactual分解。新runtime gapは計算不可。','','## F. Blocked Winner Anatomy','','保存済みA1の51 higher-pP blocked U5を解析した。これはnew policy設計やthreshold変更には使っていない。','',f"最低pP blockerの<2 event={anatomy['minimum_blocker_below2_events']}/51、U5 event={anatomy['minimum_blocker_U5_events']}/51、U10 event={anatomy['minimum_blocker_U10_events']}/51。minimum blocker unique={anatomy['minimum_blocker_unique_N']}。age中央値={anatomy['blocker_age_wall_minutes']['median']} wall minutes、actual overlap中央値={anatomy['actual_overlap_wall_minutes']['median']} wall minutes。",'', '|Miss到着時台|09|10|11|12|13|14|','|---|---:|---:|---:|---:|---:|---:|','|N|'+ '|'.join(str(anatomy['arrival_hour'].get(str(h),0)) for h in range(9,15))+'|','','event数は重複holdingを含む診断。minimum blockerは一意の因果責任やreplacement利益を意味しない。JSON/CSVに全held position、pP/r/band、age、release、overlap、potential bucket、realized returnを保存。','','## G. False Reserve / Bad Fill','','B1/B2未評価。v7のsaved anatomy以外の新policy結果を生成していない。','','## H. pP Clairvoyant Scheduling Diagnostic','','1 solve invocationを開始し、区間/MAX3だけのrelaxed optimumを生成したが、100株minimum-lot cash witnessのcash>=0 assertionでexit code 1。cash-only制約を満たすdiagnostic scheduleとして認定できなかった。selected N / utility / U5 / U10 / <2は未保存・未認定であり、推測や再solveで穴埋めしない。','','今回の原因はevaluation solverのcash制約不足。これはB1/B2の失敗、cash sizing bottleneck、pP signal不在の証明ではない。U5/U10 labelはobjectiveに使っていない。未来scheduleはruntimeへ渡していない。','','主solve code/claim hashは一致。事前commit済み「cash witness失敗ならSTOP、second solveなし」を守り、cash-constrained solverへの変更やrerunを同cycleで行わなかった。','','## I. Slot1/2/3','','B1/B2未評価。slot qualityは生成なし。','','## J. pP decile / Entry hour','','B1/B2 funded/missed decile・hourは未評価。保存済み51件のanatomyだけをD3として保存。','','## K. Final38 / MaxDD / utilization Secondary','','|Profile|Final38|Minute MTM MaxDD|daily geometric|utilization mean|','|---|---:|---:|---:|---:|',f"|v5 saved|¥{v5['final_equity']:,.2f}|{v5['max_drawdown']*100:.6f}%|{v5['geometric_mean_daily_return']*100:.6f}%|既存authority参照|"]
 for i,(k,z) in enumerate(saved):s.append(f"|v7 A{i+1} saved|¥{z['final_equity']:,.2f}|{z['max_drawdown']*100:.6f}%|{z['geometric_mean_daily_return']*100:.6f}%|{z['utilization_mean']*100:.6f}%|")
 s+=['|B1/B2|未評価|未評価|未評価|未評価|','','Final38を1か月成績とは呼ばない。19 rolling windowsは独立19標本ではない。','','## L. Independent Audit / Safety','','Input/ZIP/GitHub contract byte mismatch=0。Required full independent auditはNOT_RUNでありmismatch0を主張しない。40 canary、training tables、pre-main independent policy auditは未実行、Mainを許可しなかった。','','|Count|N|','|---|---:|','|primary pP diagnostic attempted / certified|1 / 0|','|independent pP diagnostic solve|0|','|B1 / B2 primary replay|0 / 0|','|Rank / Slot ML fits|0 / 0|','|teacher regeneration / old Oracle rerun|0 / 0|','|v5 / v6 / v7 replay|0 / 0 / 0|','|provider / Claude / orders|0 / 0 / 0|','|main merge / force push / protected-fresh open|0 / 0 / 0|','','Selector / Entry / EXIT changes=0。Rank / Admission / Sizing / Liquidity changes=0。全Safety false。Exposure=ITERATIVE_DEVELOPMENT_EVIDENCE。','','D5-labelled GitHub publicationは実装source/旧receiptの保存であり、successful solve resultではない。D6には仕様precommitのみが存在する。append-only correctionで明示し、過去recordは書換えない。D7-D15は未完了のままterminal contract-failureとしてD16で固定STOP。','','## M. Next Bottleneck','','経済・preservationのNEXT_BOTTLENECKは未判定。B1/B2のobserved exclusive reasonが無いため、指定winner/diagnostic/bottleneck ruleを適用できない。solverのcash witness失敗からCASH_SIZINGを選ぶこともしない。','','次に必要なのは独立した新cycleでのcash制約付きevaluation diagnostic solverの設計・precommitであり、このcycleのsolve/replay再実行やpolicy rescueは認めない。v5 official Capital benchmarkとEXISTING_MOVE_P5 Rankを保持。','','selectedRankCandidate = EXISTING_MOVE_P5','selectedCapitalCandidate = null','diagnosticArm = null','NEXT_BOTTLENECK = null (CONTRACT_BLOCKED_NOT_EVALUATED)','fresh_OOS_claim = false','productionReady = false','CURRENT_STATE = CAPITAL_V8_D16_CLOSURE_FIXED_STOP','']
 with (OUT/'REPORT_FINAL-ja.md').open('x',encoding='utf-8') as f:f.write('\n'.join(s))
 completed=[p.stem for p in sorted((OUT/'checkpoints').glob('*.json'))]
 handoff={'exact_jst':now(),'status':'V8_CONTRACT_FAIL','selectedRankCandidate':'EXISTING_MOVE_P5','selectedCapitalCandidate':None,'diagnosticArm':None,'NEXT_BOTTLENECK':None,'NEXT_BOTTLENECK_status':'CONTRACT_BLOCKED_NOT_EVALUATED','retainedCapitalBenchmark':'V5_FROZEN_REFERENCE','reason':'Mandatory pP diagnostic exact cash feasibility not certified; precommitted STOP, no second solve or Main','permanentFreeze':['Selector','Entry','EXIT'],'Rank_Admission_Sizing_Liquidity_changes':0,'next_work_requires_independent_instruction':True,'same_cycle_resume':False,'do_not':['rerun diagnostic','run unclaimed Main','B3','threshold/support/bucket/median change','Rank/Admission change','Fresh open','replacement/MAX4/MAX5','orders/main merge/force push'],'Safety':SAFETY,'fresh_OOS_claim':False}
 save(OUT/'NEXT_WORK_HANDOFF.json',handoff)
 save(OUT/'CLOSURE.json',handoff|{'CURRENT_STATE':'CAPITAL_V8_D16_CLOSURE_FIXED_STOP','STOP':True,'exact_jst':now(),'completed_before_closure':completed,'first_incomplete_checkpoint':'D5_PPRANK_DIAGNOSTIC_RESULT','incomplete_not_claimed_PASS':['D5 result','D7 tables','D8 canary','D9 pre-main independent audit','D10 Main claim','D11 replay','D12 preservation','D13 Capital','D14 audit','D15 winner/bottleneck'],'counts':counts,'diagnostic_attempt_completed_with_known_failure':True,'required_independent_mismatch_N':None,'report_sha256':sha(OUT/'REPORT_FINAL-ja.md'),'failure_receipt_sha256':sha(OUT/'FAILED_DIAGNOSTIC_EXECUTION_RECEIPT.json'),'next_policy':'Fixed STOP. Only append publication/actual GET receipts and static scope verification; no research executions.'})
 checkpoint('D16_CLOSURE_FIXED_STOP','CAPITAL_V8_D16_CLOSURE_FIXED_STOP',['source/authority freeze','saved blocker anatomy','one failed diagnostic attempt documented','contract-failure report/handoff'],{'status':'V8_CONTRACT_FAIL','selectedCapitalCandidate':None,'diagnosticArm':None,'NEXT_BOTTLENECK':None,'Main_replay':0,'mandatory_independent_audit':'NOT_RUN'},'STOP. No second solve, Main, B3, retune, Admission/Rank/Fresh change. Terminal publication receipts only.',counts)
 print(json.dumps({'status':'V8_CONTRACT_FAIL','report_sha256':sha(OUT/'REPORT_FINAL-ja.md'),'B1':0,'B2':0,'STOP':True}))
if __name__=='__main__':main()
