"""Outcome joins and exposure reporting only; not in runtime dependency graph."""
from control import *
from decimal import Decimal as D
from collections import Counter
from statistics import mean,median
FINE=['<1','1-<2','2-<3','3-<4','4-<5','5-<10','>=10']
COARSE=['Weak','Low','Medium','Big','Mega']
def fine(x):return 'MISSING' if x is None else FINE[sum(x>=t for t in (.01,.02,.03,.04,.05,.10))]
def coarse(x):return 'MISSING' if x is None else COARSE[sum(x>=t for t in (.02,.03,.05,.10))]
def decile(r):return min(10,int(r*10)+1)
def group(rr,total=None):
    n=len(rr);c=Counter(coarse(r['potential_return']) for r in rr);supported=sum(c[k] for k in COARSE);real=[r['realized_net_return'] for r in rr if r['realized_net_return'] is not None];pos=sum(x>0 for x in real);ge1=sum(x>=.01 for x in real);lose=sum(x<=0 for x in real);buy=sum((D(r['buy_debit']) for r in rr),D(0));pnl=sum((D(r['actual_PnL']) for r in rr),D(0));unit=sum((D(r['unit_100share_PnL']) for r in rr if r['unit_100share_PnL'] is not None),D(0));lots=[r['lots'] for r in rr]
    return {'N':n,'supported_quality_N':supported,'Medium':c['Medium'],'U5':c['Big']+c['Mega'],'U10':c['Mega'],'Weak':c['Weak'],'Low':c['Low'],'Big':c['Big'],'Mega':c['Mega'],'U2':supported-c['Weak'],'U3':c['Medium']+c['Big']+c['Mega'],'below2_rate':c['Weak']/supported if supported else None,'below3_rate':(c['Weak']+c['Low'])/supported if supported else None,'realized_supported_N':len(real),'realized_missing_N':n-len(real),'realized_positive_N':pos,'realized_ge1pct_N':ge1,'realized_loser_le0_N':lose,'realized_positive_rate':pos/len(real) if real else None,'realized_ge1pct_rate':ge1/len(real) if real else None,'loser_rate':lose/len(real) if real else None,'realized_mean':mean(real) if real else None,'realized_median':median(real) if real else None,'lots':sum(lots),'mean_lots':mean(lots) if lots else None,'median_lots':median(lots) if lots else None,'buy_notional':str(buy),'notional_share':float(buy/D(total)) if total and D(total)>0 else None,'actual_PnL':str(pnl),'unit_lot_PnL':str(unit),'return_on_deployed_notional':float(pnl/buy) if buy else None,'scores':{f:{'mean':mean(r[f] for r in rr) if rr else None,'median':median(r[f] for r in rr) if rr else None} for f in ('pP','q2','q3','mP','rM')},'Entry_hour_N':{str(h):sum(r['entry_minute']//60==h for r in rr) for h in range(9,16)},'slot_N':{str(s):sum(r['slot']==s for r in rr) for s in (1,2,3)}}
def exposure(rr):
    total=group(rr)['buy_notional']
    return {'all':group(rr,total),'MRET_percentile_decile':{str(d):group([r for r in rr if decile(r['rM'])==d],total) for d in range(1,11)},'potential_bucket':{b:group([r for r in rr if fine(r['potential_return'])==b],total) for b in FINE},'coarse_bucket':{b:group([r for r in rr if coarse(r['potential_return'])==b],total) for b in COARSE},'rM_half':{'low':group([r for r in rr if r['rM']<.5],total),'high':group([r for r in rr if r['rM']>=.5],total)},'slot':{str(s):group([r for r in rr if r['slot']==s],total) for s in (1,2,3)},'band':{b:group([r for r in rr if r['band']==b],total) for b in ('P_HIGH','P_MID','P_BASE')},'Entry_hour':{str(h):group([r for r in rr if r['entry_minute']//60==h],total) for h in range(9,16)},'notional_quality':{name:group([r for r in rr if pred(r)],total) for name,pred in [('Weak',lambda r:r['potential_return']<.02),('Medium+',lambda r:r['potential_return']>=.03),('U5',lambda r:r['potential_return']>=.05),('U10',lambda r:r['potential_return']>=.10)]}}
