"""Formalize existing fit operator before certification, never loosen a tolerance."""
from control import *
import sys,platform,numpy as np,sklearn,io,contextlib
def main():
    assert (OUT/'MRET_COMPLETED_FITS_REUSE_FREEZE.json').exists()
    failure=read(PARENT/'NUMERIC_CONTRACT_FAILURE_RECEIPT.json');spec=read(PARENT/'MRET_TEACHER_FEATURE_MODEL_PRECOMMIT.json')
    save(OUT/'NUMERIC_CERTIFICATION_ROOT_CAUSE_PRECOMMIT.json',{'exact_jst':now(),'MODEL_ARTIFACT_FAILURE':False,'OOF_SCORE_FAILURE':False,'STATISTICAL_RESULT_FAILURE':False,'NUMERIC_AUDIT_OPERATOR_MISMATCH':True,'old_failure_sha256':sha(PARENT/'NUMERIC_CONTRACT_FAILURE_RECEIPT.json'),'old_failure':failure,'classification':'old independent algorithm did not instantiate the exact training numerical operator contract','old_failure_retained':True,'small_difference_ignored':False,'tolerance_relaxation':False,'newFits':0,'Safety':SAFETY})
    operator={'name':'FIT_NUMERIC_OPERATOR_V1','authority_model_sha256':sha(ROOT/'research/capital-v11-realized-monetization-signal-20261005-v1/model.py'),'train_order':'saved train_entry_ids exact, independently verified against raw completed-train projection','numeric_fields':spec['features']['numeric_fields'],'categorical_fields':spec['features']['categorical_fields'],'A':'np.asarray(raw values float(value) or NaN, dtype=np.float64, order=C), shape N x46','X0':'np.column_stack([np.nan_to_num(A,nan=0.0),np.isnan(A).astype(np.float64)]), shape N x92, C contiguous','mean':'np.mean(X0,axis=0,dtype=np.float64)','scale':'np.std(X0,axis=0,dtype=np.float64,ddof=0); exact zero scale replaced by float64 1.0','categorical':'independent train-only sorted vocabulary including explicit __UNKNOWN__; frozen field order','hard_identity':'JSON vs NPZ vs independently reconstructed canonical arrays: float64.view(uint64) exact all mean/scale elements; no tolerance','coefficients':'JSON vs NPZ coef/intercept/classes bit exact','score_tolerance':1e-12,'ordering':'OOF score identity, top20/top30/decile sorting by score DESC then entry_id ASC','independent_imports_prohibited':['v11 model.py','v11 teacher.py','v11 evaluate.py','v11 metrics.py'],'shared_primitive':'contract-defined NumPy only; independent row selection/extraction/matrix/vocab/inference/Capital implementations','alternate':'math.fsum + Decimal.from_float sensitivity diagnostic; never a hard gate','on_bit_failure':'V11R1_NUMERIC_CERT_FAIL or NUMERIC_ENVIRONMENT_BLOCKED; STOP; no fallback or repeat','on_source_failure':'V11R1_SOURCE_BLOCKED; STOP','reused_signal':'S1-S8 old PASS frozen; old S9 remains FAIL; only new S9R judged','S9R_conditions':['private/source identity exact','eight fits exact reuse','train identity/order exact','X0 construction exact','canonical mean bit exact','canonical scale bit exact','JSON/NPZ preprocessing bit exact','coef/intercept/classes exact','train reconstruction<=1e-12','OOF reconstruction<=1e-12','frozen primary hash/body valid','frozen bootstrap/results hash/body valid','new fit/refit/re-eval/tolerance relaxation0','Safety allfalse'],'capital_policy_authority_sha256':sha(PARENT/'M1_M2_CAPITAL_POLICY_PRECOMMIT.json'),'capital_implementation_sha256':sha(ROOT/'research/capital-v11-realized-monetization-signal-20261005-v1/runtime.py'),'capital_replays_if_PASS':2,'capital_replays_if_FAIL':0,'capital_rules':'exact frozen v11 gates/winner/diagnostic/relative progress; S9R FAIL numerical certification blocked','frozen_policy_change':0,'newFits':0,'Safety':SAFETY}
    save(OUT/'FIT_NUMERIC_OPERATOR_V1_PRECOMMIT.json',operator)
    buffer=io.StringIO()
    with contextlib.redirect_stdout(buffer):np.show_config()
    config=buffer.getvalue();save(WORK/'NUMPY_SHOW_CONFIG.json',{'text':config})
    save(OUT/'NUMERIC_ENVIRONMENT_FINGERPRINT.json',{'exact_jst':now(),'Python':sys.version,'NumPy':np.__version__,'sklearn':sklearn.__version__,'platform':platform.platform(),'machine':platform.machine(),'byteorder':sys.byteorder,'float_info':{k:getattr(sys.float_info,k) for k in ['max','max_exp','max_10_exp','min','min_exp','min_10_exp','dig','mant_dig','epsilon','radix','rounds']},'numpy_config_sha256':hashlib.sha256(config.encode()).hexdigest(),'numpy_config':config,'frozen_v11_versions':spec['versions'],'historical_fit_show_config_recorded':False,'environment_compatibility_hard_gate':'canonical bit equality, no widened tolerance','newFits':0})
    checkpoint('N2_NUMERIC_OPERATOR_CONTRACT_PRECOMMIT','FIT_NUMERIC_OPERATOR_V1 and bit-level/S9R contract committed before certificate; fingerprint recorded','commit -> actual GET -> independent matrix')
    print(json.dumps({'operator':'FIT_NUMERIC_OPERATOR_V1','NumPy':np.__version__,'sklearn':sklearn.__version__,'newFits':0}))
if __name__=='__main__':main()
