"""Single-execution claim; no replay within this module."""
from control import *
def main():
 assert read(OUT/'CAUSAL_CANARY_RESULTS.json')['all_PASS'] and read(OUT/'CAUSAL_CANARY_RESULTS.json')['test_N']>=43
 assert read(OUT/'PRE_MAIN_INDEPENDENT_POLICY_AUDIT.json')['mismatch_N']==0
 for z in read(OUT/'INPUT_BYTE_FREEZE.json')['files']:assert sha(PRIOR/z['path'])==z['sha256']
 old=read(OUT/'B1_B2_SEMANTIC_FREEZE.json')['frozen_policy'];assert sha(CODE/'runtime.py')==old['code_sha256']['runtime.py']
 for arm in ARMS:assert not (PRIVATE/f'{arm}_STARTED.json').exists(),'AMBIGUOUS_OR_COMPLETED_MAIN_STOP'
 code={n:sha(CODE/n) for n in ('control.py','runtime.py','replay.py','execution_bridge.py','run_main.py')};tables={n:sha(OUT/n) for n in ('B1_CAPACITY_PRESSURE_TABLE.json','B2_TENURE_LOOKUP_TABLE.json','B2_CAPACITY_PRESSURE_TABLE.json')}
 save(OUT/'MAIN_REPLAY_CLAIM.json',{'exact_jst':now(),'branch':BRANCH,'basis':read(WORK/'latest_basis.json'),'B1_replay':1,'B2_replay':1,'entrypoint':'run_main.py','single_execution_per_arm':True,'complete_or_ambiguous_or_started_replay_rerun_forbidden':True,'runtime_byte_semantic_exact':True,'code_sha256':code,'table_sha256':tables,'runtime_input_sha256':sha(PIN/'RANK_NATIVE_RUNTIME.jsonl.gz'),'market_input_sha256':sha(INPUT/'execution/MARKET_EXECUTION_BOOK_V2.jsonl.gz'),'frozen_sizing_sha256':old['immutable_sizing_sha256'],'frozen_execution_sha256':old['immutable_execution_sha256'],'shared_contract_PASS':True,'diagnostic_status_is_not_Runtime_dependency':True,'new_fits':0,'old_replay':0,'orders':0,'Safety':SAFETY})
 save(OUT/'FINAL_SELECTION_RULE_PRECOMMIT.json',{'exact_jst':now(),'source':'Current v8R1 instruction; runtime B1/B2 is old byte exact, new evaluation rules only as explicitly requested','P':{'U5':'>50','U10':'>=26','below2':'<=0.38666667','Admission_U5_recovery':'>50/116','runtime_integrity':'0','full_independent_mismatch':'0'},'Capital':{'Preservation':'PASS','rolling20_median':'>1.1991541915','rolling20_mean':'>1.1906460126','daily_geom':'>0.01032420041'},'eligible':'Preservation and Capital PASS only','winner':['2x N DESC','rolling20 median DESC','rolling20 mean DESC','daily geom DESC','U5 DESC','U10 DESC','below2 ASC','MaxDD ASC','B1 tie'],'diagnostic_arm_if_no_winner':['U5 DESC','U10 DESC','below2 ASC','rolling20 median DESC','B1 tie'],'bottleneck':'largest observed actionable exclusive U5 miss count','bottleneck_exact_tie_priority':['RANK_ADMISSION','MAX3_ONLINE_OCCUPANCY','CAPACITY_RESERVE','CASH_SIZING'],'cash_diagnostic_bottleneck_hard_dependency':False,'old_v8_monetization_override_not_applied':'Current Section21 overrides old non-policy evaluation JSON prose; no post-hoc alternative selection','Exposure':'ITERATIVE_DEVELOPMENT_EVIDENCE','fresh_OOS_claim':False})
 checkpoint('R9_MAIN_REPLAY_CLAIM','TWO_FIRST_EVALUATIONS_CLAIMED_NOT_EXECUTED',['43 canary PASS','independent policy mismatch0','hash pins','winner/bottleneck rule fixed'],{'B1_claim':1,'B2_claim':1,'Main_executed':0},'Commit actual GET required, then run_main.py exactly once. No result rescue.',{'primary_pP_diagnostic_solve':1,'uniqueness_no_good_solve':1,'independent_pP_diagnostic_solve':1})
if __name__=='__main__':main()
