"""Seal results and write final Japanese report. No portfolio replay or policy edits."""
from io_utils import *
from analyze import path,enriched
from independent_audit import csource,eod
import csv,collections,platform

def j(x,places=2,sign=False):
    if x is None or x=='':return '未測定'
    v=D(str(x));return ('+' if sign and v>0 else '')+format(v,',.'+str(places)+'f')
def table(headers,rr):
    return '| '+' | '.join(headers)+' |\n| '+' | '.join(['---']*len(headers))+' |\n'+''.join('| '+' | '.join(str(x) for x in r)+' |\n' for r in rr)+'\n'
def main():
    s=json.loads((PUB/'RESET20_SUMMARY.json').read_text());d=json.loads((PUB/'WINNER_LOSER_AND_FUNDING_DIAGNOSTICS.json').read_text());secondary=json.loads((PUB/'CHAIN38_AND_LEGACY20_RESULTS.json').read_text());audit=json.loads((PUB/'INDEPENDENT_AUDIT.json').read_text());repro=json.loads((PUB/'REPRODUCTION_RECEIPT.json').read_text());supp=json.loads((PUB/'INDEPENDENT_SUPPLEMENT.json').read_text())
    assert audit['status']==repro['status']==supp['status']=='PASS' and s['both_complete']==9
    stream=rows(ROOT/'inputs/v5/candidate_stream');books={b['entry_id']:b for b in rows(ROOT/'inputs/v5/books')};plans={x['entry_id']:x['plan'] for x in rows(PRI/'immutable/EXIT_PLANS.jsonl.gz')};cache={x['entry_id']:x for x in rows(PRI/'immutable/STATE_PREFIX_CACHE.jsonl.gz')}
    unavailable=[]
    for r in stream:
        try:
            source=csource(books[r['entry_id']]) or eod(books[r['entry_id']])
            if not source or source.get('blocked'):unavailable.append({'entry_id':r['entry_id'],'reason':'CANONICAL_REFERENCE_SOURCE_UNRESOLVED'})
        except Exception as e:unavailable.append({'entry_id':r['entry_id'],'reason':'CANONICAL_REFERENCE_SOURCE_EXCEPTION','type':type(e).__name__})
    state=[]
    for w in s['mask']+['CHAIN38']:
        for a in ['C','E']:
            ff=enriched(path(w,a));checked=usable=quality=gap=0
            for r in ff:
                prefix=cache[r['entry_id']];release=r['trade']['release_minute'] if r['trade'] else 932
                # Only pre-intent checkpoints are evaluated; an SD intent remains latched afterwards.
                cutoff=plans[r['entry_id']].get('intent_minute',prefix['control_intent_minute']) if a=='E' else prefix['control_intent_minute']
                frames=[p for p in prefix['frames'] if p['checkpoint_minute']<release and (p['checkpoint_minute']<=cutoff if a=='E' and plans[r['entry_id']]['action']=='SD_FIRST' else p['checkpoint_minute']<cutoff)]
                checked+=len(frames);usable+=sum(p['usable'] for p in frames);gap+=sum(p['evidence_gap'] for p in frames);quality+=sum(not p['usable'] and not p['evidence_gap'] for p in frames)
            state.append({'window_id':w,'arm':a,'funded_N':len(ff),'State_source_covered_N':sum(r['entry_id'] in cache for r in ff),'post_buy_pre_latch_or_control_checkpoint_N':checked,'A_usable_N':usable,'B_legitimate_quality_abstention_N':quality,'C_evidence_gap_N':gap,'funded_D_unresolved_fill_N':sum(r['trade'] is None for r in ff),'historical_receive_time':'UNKNOWN','State_new_kernel_run_N':0})
    save(PUB/'ACTUAL_HOLDING_STATE_COVERAGE.json',{'per_path':state,'C_state_use':'Overlay diagnostic only; Structural guard remains original frozen source','E_prefix_stops_at_latched_SD_or_Control_priority':True,'no_future_quality_gap_after_latch_cancels_intent':True})
    save(PRI/'V5_SOURCE_REFERENCE_UNRESOLVED_CENSUS.json',{'candidate_population_N':len(stream),'canonical_reference_unresolved_N':len(unavailable),'entries':unavailable,'evaluated_only_after_all_formal_paths':'NOT_A_PREBUY_FILTER','prior322_unknown6':'Different fixture population, retained in pinned S4 evidence','funded_unknown_in_all20paths':0})
    save(PUB/'POPULATION_AND_SOURCE_COVERAGE.json',{'original_V5_candidate_ID_N':len(stream),'original_OOF_session_N':38,'original_Development_with_context_session_N':58,'prior_fixture_population_N':322,'prior_fixture_R_unknown_N':6,'prior_fixture_completed_intervention_N':72,'all_V5_canonical_reference_unresolved_N':len(unavailable),'all_V5_precompiled_SD_reference_unresolved_N':sum(p['action']=='SD_FIRST' and p.get('source') is None for p in plans.values()),'formal20paths_funded_R_unknown_N':0,'future_source_availability_used_for_buy_gate':False,'unfunded_reference_unknown_does_not_block_measured_portfolios':True,'new_CHAIN38_SD_fill_N':secondary['CHAIN38']['E']['SHARP_DROP_fill_N'],'new_CHAIN3872_is_not_the_old_fixture_ID_set':True})
    counters={'policy_candidates':2,'formal_primary_C_paths':9,'formal_primary_E_paths':9,'formal_secondary_C_paths':1,'formal_secondary_E_paths':1,'formal_total_paths':20,'each_formal_path_runs':1,'Control_verified_full_saved_ledger_paths':10,'Control_reuse_paths':0,'independent_source_reconstructed_paths':20,'independent_each_path_runs':1,'independent_supplement_portfolio_runs':0,'reproduction_campaigns':1,'reproduction_paths':20,'reproduction_deterministic_payloads':100,'technical_repair_cycles':sum(json.loads(l).get('cycle',0)>0 for l in (PRI/'TECHNICAL_REPAIR_LEDGER.jsonl').read_text().splitlines()),'new_fit_refit_calibration':0,'new_inference':0,'new_model_teacher':0,'new_policy_score_threshold_search':0,'new_State_kernel_runs':0,'market_provider_requests':0,'protected_partition_opens':0,'orders':0,'workflow_dispatches':0,'production_code_changes':0,'previous72_history':'Pinned separate prior campaign, not current budget','auxiliary_failed_inspection_attempts':['one malformed inspection Python string in prior session','list-vs-dict archive index inspection','wrong import of native helper during post-computation census'], 'publication_GET_retry_events':'Recorded separately in PUBLICATION_TRANSPORT_EVENTS.json'}
    save(PUB/'EXECUTION_RECEIPT.json',{'status':'COMPUTATION_VERIFICATION_COMPLETE_PUBLICATION_READBACK_PENDING','counters':counters,'runtime':{'python':platform.python_version()},'native_input_and_code_pins':'SOURCE_BINDING.json / FROZEN_NATIVE_INPUT_LINEAGE.json','official_portfolio_code':pin(ROOT/'portfolio.py'),'independent_executed_code':pin(ROOT/'independent_audit.py'),'financial_tolerance':0,'offline_research_scope_only':True});save(PRI/'EXECUTION_RECEIPT.json',json.loads((PUB/'EXECUTION_RECEIPT.json').read_text()))
    selection=json.loads((PUB/'WORK_SPEC.json').read_text())['required_final_state']
    statefile=json.loads((PUB/'CURRENT_STATE.json').read_text());statefile.update(status='FINAL_SEALED_READBACK_PENDING',formal_paths_started=20,primary_C_verified_complete_N=9,primary_E_complete_N=9,secondary_complete=True,independent_audit='PASS',reproduction='PASS',completed_stages=['P0','P1','P2_W13_TO_W21','P3','P4','P5','P6'],uncompleted_obligations=['P7 final all-artifact actual GET and publication receipt'],next_action='publish sealed packages; actual GET every required file; publish readback receipt; STOP',selection=selection);save(PUB/'CURRENT_STATE.json',statefile)
    atomic(PUB/'RESUME_NEXT_ACTION.txt',b'All20formal paths, independent20paths and one reproduction campaign are complete. Only final artifact publication/readback remains. Do not rerun any completed portfolio path. Publish current payload, actual GET all required current paths, save READBACK_RECEIPT_PUBLICATION and its subsequent confirmation, then STOP.\n')
    ww=list(csv.DictReader((PUB/'RESET20_WINDOW_RESULTS.csv').open()));complete=[r for r in ww if r['paired_complete']=='True']
    lines=['# Capital V5 × SHARP_DROP EXIT — 100万円開始・20営業日の資産比較\n', '固定RESET20の9窓で、旧V5の終点資産中央値は **'+j(s['C_final_equity_stats']['median'])+'円**、新EXITは **'+j(s['E_final_equity_stats']['median'])+'円**、中央値同士の差は **'+j(s['difference_of_medians_jpy'],sign=True)+'円**。対応窓ごとの差額の中央値は **'+j(s['median_of_paired_differences_jpy'],sign=True)+'円**。改善3窓・同値0窓・悪化6窓であり、Primaryの資産改善とは判定しない。\n', '## 1. Primary RESET20：全9窓と同じpaired mask\n','各窓は100万円・保有0・pending0で開始し、20市場営業日の間は日次resetせず現金を繰り越した。両armとも終点未決済0、価格・会計不明0で、最終総資産＝ending cash。表示のみ小数2桁へ丸め、判定・集計・台帳は丸め前のDecimal/Fractionを保存した。\n']
    lines.append(table(['窓','開始→終了（2025年）','営業日／暦日幅','旧C総資産 円','新E総資産 円','E−C 円'],[[r['window_id'],r['start_session']+' → '+r['end_session'],r['business_day_N']+' / '+r['calendar_span_inclusive_days'],j(r['C_final_equity']),j(r['E_final_equity']),j(r['E_minus_C_final_equity_jpy'],sign=True)] for r in complete]))
    lines.append(table(['窓','C利益 円','E利益 円','C return%','E return%','C/E赤字','C/E200万円'],[[r['window_id'],j(r['C_profit']),j(r['E_profit']),j(r['C_return_pct']),j(r['E_return_pct']),'なし / なし','未達 / 未達'] for r in complete]))
    lines.append(table(['指標（同じ9窓）','C 円','E 円','対応差 E−C 円'],[[k,j(s['C_final_equity_stats'][k]),j(s['E_final_equity_stats'][k]),j(s['paired_delta_stats'][k],sign=True)] for k in ['min','mean','median','max']]))
    lines.append('総資産の各統計から100万円を引いた利益のmin/mean/median/maxも RESET20_SUMMARY.json に保存。赤字窓はC/Eとも0/9、200万円以上も0/9。旧予定21窓のうちW01〜12はcoverage未確定のままで、既知9・不明12を分離する。9窓は重複しており、独立9か月・月次成功率の推定ではない。\n')
    lines.append(table(['旧未測定窓','開始','終了','C/E状態'],[[r['window_id'],r['start_session'],r['end_session'],'旧coverage未確定 / 未測定'] for r in ww if r['window_id'] not in s['mask']]))
    lines.append(table(['窓','C/E funded N','新SD intent/fill N','C/E分足MTM MaxDD%','C/E EOD MaxDD%','C/E State入力取得 N'],[[r['window_id'],r['C_funded_N']+' / '+r['E_funded_N'],r['E_SHARP_DROP_intent_N']+' / '+r['E_SHARP_DROP_fill_N'],j(r['C_minute_MTM_MaxDD_pct'],4)+' / '+j(r['E_minute_MTM_MaxDD_pct'],4),j(r['C_EOD_MaxDD_pct'],4)+' / '+j(r['E_EOD_MaxDD_pct'],4),r['C_State_source_covered_N']+' / '+r['E_State_source_covered_N']] for r in complete]))
    lines+=['## 2. 実損・大Loser・負け日\n','以下の金額・件数は重複窓を含む9口座の合計。市場unique EntryはC '+str(s['C_unique_market_Entry_N'])+'、E '+str(s['E_unique_market_Entry_N'])+'で、口座取引件数 '+str(s['C_overlapping_account_trade_N'])+' / '+str(s['E_overlapping_account_trade_N'])+'と区別する。全funded取引のRは既知。\n']
    fields=[('ALL_MINUS件数','ALL_MINUS_N_overlapping_accounts',False),('ALL_MINUS / funded %','ALL_MINUS_pct_funded',True),('gross loss（実損絶対額）円','gross_loss_jpy_overlapping_accounts',True),('正PnL総和 円','gross_positive_jpy_overlapping_accounts',True),('−3%以下 件数','tail_LE_MINUS3_N',False),('−3%以下 損失円','tail_LE_MINUS3_gross_loss_jpy',True),('−4%以下 件数','tail_LE_MINUS4_N',False),('−4%以下 損失円','tail_LE_MINUS4_gross_loss_jpy',True),('−5%以下 件数','tail_LE_MINUS5_N',False),('−5%以下 損失円','tail_LE_MINUS5_gross_loss_jpy',True),('最悪1取引 損失円','worst_trade_loss_jpy',True),('最悪1取引 R%','worst_trade_R_pct',True),('マイナス日数（重複180日口座）','negative_day_N_overlapping_accounts',False),('最悪1日 PnL円','worst_daily_PnL_jpy',True),('最大分足MTM MaxDD%','max_minute_MTM_MaxDD_pct',True),('最大EOD MaxDD%','max_EOD_MaxDD_pct',True)]
    lines.append(table(['指標','旧C','新E'],[[label,j(s['C_'+key],4 if 'DD' in key else 2) if money else s['C_'+key],j(s['E_'+key],4 if 'DD' in key else 2) if money else s['E_'+key]] for label,key,money in fields]))
    lines.append('尾部の件数・損失円は軽減したが、総実損は '+j(D(s['E_gross_loss_jpy_overlapping_accounts'])-D(s['C_gross_loss_jpy_overlapping_accounts']),sign=True)+'円増加し、正PnLは '+j(D(s['E_gross_positive_jpy_overlapping_accounts'])-D(s['C_gross_positive_jpy_overlapping_accounts']),sign=True)+'円減少。負け日、最悪日、最大DDも悪化した。−5%以下は4件→4件で、大Loser消滅とはいえない。全−5..+5帯、ZERO/UNKNOWN、上下各累積閾値、円×分は RETURN_SPECTRUM_BY_WINDOW.csv / TAIL_AND_LOSS_METRICS.csv / CAPITAL_LOCK_BY_WINDOW.csv に保存した。\n')
    lines+=['## 3. 元Cに固定したWinner・Loser比較\n','元C Winner327件のうちEでも購入318件、未購入9件。共通購入の1株当たりEXIT損益は改善15・同値218・悪化85件で、赤字転落65件。数量差込みの実PnLは改善25・同値192・悪化101件。R悪化は同じbucketに残っても数え、E未購入は直接EXIT損傷と分けた。\n']
    cohort=[r for r in csv.DictReader((PUB/'ORIGINAL_C_WINNER_LOSER_TRANSITIONS.csv').open()) if r['window_id']=='ALL9_OVERLAPPING_ACCOUNTS' and r['C_fixed_band'].startswith('P')]
    lines.append(table(['元C固定Winner帯','元C N','E購入 / 未購入','EXIT改善 / 同値 / 悪化','赤字転落','R不明'],[[r['C_fixed_band'],r['C_N'],r['E_purchased_N']+' / '+r['E_not_purchased_N'],r['per_unit_EXIT_improved_N']+' / '+r['per_unit_EXIT_equal_N']+' / '+r['per_unit_EXIT_worsened_N'],r['positive_to_negative_N'],r['R_unknown_N']] for r in reversed(cohort)]))
    lines.append('元C Loser403件はE購入388・未購入15。元Cの−3%以下66件は全件Eでも購入し、45件でR損失軽減、35件で−3%tailから脱出、31件はtail内。元Cではtail外の共通購入から−3%への新流入0、E_ONLY購入から11件が新流入し、Eの−3%以下は計42件となる。−4/−5の対応、全新tail流入ID、unique ID・各窓の重複関係も非公開個別台帳に保存。U5/U10の潜在High値幅を実現Winnerには使っていない。\n')
    lines+=['## 4. EXIT単体と資金・数量の会計分解\n','各窓で同じ初期資金・追加入出金0・全決済・全PnL既知を確認した。以下は9口座合計であり、一意の因果帰属ではない。\n']
    z=d['decomposition_sum'];lines.append(table(['成分','E−Cへの寄与 円'],[['COMMON：旧C数量での直接EXIT差',j(z['COMMON_direct_EXIT_jpy'],sign=True)],['COMMON：E価格を基準とする数量差',j(z['COMMON_quantity_jpy'],sign=True)],['E_ONLY：実PnL',j(z['E_ONLY_PnL_jpy'],sign=True)],['C_ONLY：実PnLの符号反転',j(-D(z['C_ONLY_PnL_jpy']),sign=True)],['合計＝各窓Final差の合計',j(z['paired_PnL_delta_jpy'],sign=True)]]))
    fd=json.loads((PUB/'FIRST_DIVERGENCE.json').read_text());lines.append('最初の差分は '+fd['global_window']+' / '+fd['global_timestamp']+' の最初の有効SHARP_DROP観測・SELL_INTENT。intentでは枠・現金を解放せず、合法sourceのfill/release後にnative V5の後続BUYへ回した。固定event順・各332介入の資金解放trace・最初の後続funding差を非公開保存。C_ONLY利益を回収可能利益とは呼ばない。\n')
    ex=d['examples_redacted'];lines.append('固定順位の説明例：最大Loser軽減 '+ex['largest_loser_mitigation']['window_id']+' の直接EXIT差 '+j(ex['largest_loser_mitigation']['direct_EXIT_jpy'],sign=True)+'円、最大Winner損傷 '+ex['largest_winner_damage']['window_id']+' の直接EXIT差 '+j(ex['largest_winner_damage']['direct_EXIT_jpy'],sign=True)+'円、最悪新規−3%tail '+ex['worst_new_tail']['window_id']+' / '+ex['worst_new_tail']['set']+' の実PnL '+j(ex['worst_new_tail']['E_PnL_jpy'])+'円。銘柄・原R・価格・数量は非公開 DETERMINISTIC_SELECTED_EXAMPLES.json に保存し、これを使った同cycleの条件変更は0。\n')
    lines+=['## 5. Secondary：LEGACY_NORMALIZED20 / CHAIN38\n','原OOF38-session列のchainで、正規化は100万円×窓末cash÷窓開始cash。独立100万円resetでも20連続市場営業日でもない。市場未評価日7/11・7/14を含む旧列のまま。\n']
    legacy=list(csv.DictReader((PUB/'LEGACY20_PAIRED_WINDOWS.csv').open()));lines.append(table(['元array窓ID','開始→終了','旧C正規化資産 円','新E正規化資産 円','対応差 E−C 円'],[[r['window_id']+' (index '+r['original_window_array_index']+')',r['start_session']+' → '+r['end_session'],j(r['C_normalized_final_jpy']),j(r['E_normalized_final_jpy']),j(r['E_minus_C_normalized_jpy'],sign=True)] for r in legacy]))
    best=secondary['old_best_window_selected_by_old_C_only'];lines.append('旧約29万円窓は固定L02（元array index1）、'+best['start_session']+'〜'+best['end_session']+'。旧 '+j(best['C_normalized_final_jpy'])+'円→新 '+j(best['E_normalized_final_jpy'])+'円、差 '+j(best['E_minus_C_normalized_jpy'],sign=True)+'円。旧結果で選ばれた参照であり、そこだけを成功条件にはしない。\n')
    lines.append(table(['LEGACY_NORMALIZED20統計','旧C 円','新E 円'],[[k,j(secondary['C_normalized_stats'][k]),j(secondary['E_normalized_stats'][k])] for k in ['min','mean','median','max']]))
    lines.append('各armの最小/最大窓ID：C '+str(secondary['C_extreme_window_ids'])+'、E '+str(secondary['E_extreme_window_ids'])+'。中央値の元窓ID：C '+str(secondary['C_median_window_ids'])+'、E '+str(secondary['E_median_window_ids'])+'。それぞれの最大値同士の差をpaired効果にはしない。旧浮動小数の表示値は原 replay.py 式で全19件bit exact一致し、正式円比較は保存moneyからDecimal正規化した。\n')
    chain=secondary['CHAIN38'];lines.append('CHAIN38参考（'+chain['start_session']+'〜'+chain['end_session']+'、選定38session、暦日幅'+str(chain['calendar_span_inclusive_days'])+'日）：旧 **'+j(chain['C']['final_equity'])+'円**→新 **'+j(chain['E']['final_equity'])+'円**、差 **'+j(chain['E_minus_C_jpy'],sign=True)+'円**。旧funded150→新195、新SD intent/fill72/72。旧fixtureの72件とは別のCapital集合であり、38-session資産を1か月の成績にはしない。\n')
    lines+=['## 6. coverage・検算・再現・保存\n','固定9窓はC/E両方9/9完了。予定21窓としては9/21のDevelopment部分測定で、旧coverage未確定12窓は未測定・Final nullのまま。全Frozen候補1039 ID・原block・24個のH2/H3/H5実在model member・arrival/score/native codeをhash bindingし、fit・再推論・State再設計0。保有期間に必要なState証跡は全funded IDで取得済み、今回funded後のC証跡欠損・D約定未解決0。正当な品質棄権BとAのチェック数は ACTUAL_HOLDING_STATE_COVERAGE.json に分けた。旧322/6不明と全V5 source母集団の未解決'+str(len(unavailable))+'は別集計で、将来execution availabilityを購入前gateにしていない。\n','Control10経路は保存全decision・quantity・売買・cash・release・MTM・日次台帳にexact一致。人工100テストは本計算前にPASSし、修復済み旧72 fixtureのintent/fill/Rも一致。独立実装は主allocator/overlay/evaluatorをimportせず元score/book/State原traceから全20経路を再構成し、'+str(audit['scalar_check_N'])+'比較・不一致0、追加会計/cohort集計73チェックPASS。共有State kernelの保存出力を使う同一作者の別実装であり、第三者盲検監査・kernel外部認証ではない。\n','凍結同一入力で再現campaign1回、20経路・100 deterministic payloadがbyte/hash一致。作成時刻・commit/GET receipt・formal/reproductionのstageラベルは比較payloadから分離し、金額・数量・時刻・IDを許容差で合わせていない。正式20、独立20、再現20は別カウンタであり、候補policy数はC/Eの2のみ。今回の技術修復cycle '+str(counters['technical_repair_cycles'])+'/20、旧5cycle/72修復履歴は別予算で保持した。\n','新branchは research/capital-v5-sharp-drop-exit-reset20-20261007。各Primary窓のpublic/private commitとactual GETを済ませ、共有sourceを一度だけ非公開保存した。最終全成果物のcommit・path・bytes・SHA256・Git blob・実GET結果は READBACK_RECEIPT_PUBLICATION.json、receipt自身の後続確認は READBACK_CONFIRMATION.json を参照する。この本文だけを保存成功の証拠にはしない。前回S4最終publication receiptは本Workで再認証していない制限を維持し、今回28partのexact GET/full carrier一致や新branchの読戻しと分けた。\n','板depth・live実受信・将来の全量実約定は認証していない。historical receive time UNKNOWNを維持する。Fresh/Protected partition開封0、provider0、注文0、本番変更0、main merge/force push/dispatch0。\n','## 7. 判定とSTOP\n','INTEGRITY=PASS。COVERAGE=固定9/9完了・旧予定21では9/21 partial。WEALTH_EFFECT=Primary中央値差−29,291.40円・paired差中央値−14,038.50円・平均対応差−7,924.56円で資産改善PASSではない。DOWNSIDE_EFFECT=大Loser尾部金額の軽減と、総実損・負け日・最悪日・DD悪化の混在。WINNER_EFFECT=R損傷85件・赤字転落65件・未購入9件を区別。Secondaryは参考の正効果として別保存する。\n','ユーザー選択済み mainCapital=CAPITAL_MAX3_SLOT_RESERVE_V1 / mainExit=SHARP_DROP_FIRST_OBSERVED_EXIT_V0 を保持。旧成果物保持true、旧結果relabelling false、P1/追加購入前filter false、freshValidation=NOT_RUN、productionReady false、本番runtime/pointer書換えfalse、Safety9全false。offline researchの許可はSafety9と別。全成果物の保存・読戻し後STOPし、再選定・新条件・再fitへ進まない。\n','次仮説（未実行）：早期解放資金の追加購入を抑制した別Capital候補が、尾部軽減を保ちながら資産悪化を減らせるか。\n']
    atomic(PUB/'REPORT-ja.md',('\n'.join(lines)).encode());print(json.dumps({'report':pin(PUB/'REPORT-ja.md'),'counters':counters,'source_unresolved_nonfunded_N':len(unavailable)}))
if __name__=='__main__':main()
