"""Write a Japanese factual report and finite FIRST ENTRY handoff; no fits."""
import argparse,html
from common import *
def fmt(v,d=3):return 'unknown' if v is None else f'{v:.{d}f}'
def table(headers,rows):return '\n'.join(['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(map(str,r))+' |' for r in rows])
def run(basis,status,assessment):
 repeat=read(HERE/'SELECTOR_REPEAT_AUDIT.json');activity=read(HERE/'DAILY_FIRST_ENTRY_ACTIVITY.json');eh=read(HERE/'ENTRY_HIGH_EVALUATION.json');bucket=read(HERE/'SELECTOR_WATCH_BUCKET_EVALUATION.json')['policies'];wins=read(HERE/'WINNER_PRESERVATION.json')['panels'];quality=read(HERE/'QUALITY_CANDIDATE.json');balanced=read(HERE/'BALANCED_CANDIDATE.json');state=read(HERE/'STATE_INCREMENTAL_VALUE.json');audit=read(HERE/'INDEPENDENT_AUDIT.json');grid=read(HERE/'PERSISTENT_GRID_RECEIPT.json');teacher=read(HERE/'TEACHER_COMPUTATION_RECEIPT.json');model=read(HERE/'OOF_MODEL_RECEIPT.json');arms=eh['primary_watch_summaries'];q=quality['global']['candidate'];b=balanced['global']['candidate'];policy_names=[f+'_'+p for f in ['P0','P1'] for p in POLICIES]
 lines=['# Ark Terminal — Persistent Watchlist Uptrend FIRST ENTRY v2',f"Document ID: WORK_PERSISTENT_WATCHLIST_STATE_UPTREND_FIRST_ENTRY_V2_20261003\n\n保存時刻: {now()} / basis HEAD: `{basis}` / base HEAD: `{BASE_HEAD}`",f"今回のstatusは **{status}**。QUALITYは **{q}**、BALANCEDは **{b}**。"+('両candidateは同一。' if q==b else '両candidateは異なる。'),assessment,'Developmentのouter OOFだけで新しいFIRST ENTRYを生成・評価した。candidateは研究候補であり、正式採用・production promotionではない。前WorkのSAFE_UPSIDE FAILは閉じたまま保持し、threshold緩和・LR再fit・V6 R2 score/rank復活を行っていない。']
 p=repeat['primary_watch_population'];e=activity['selector_events_per_session'];w=activity['unique_watches_per_session']
 lines+=['Primaryは58 sessionsの2,155 unique(session,symbol) watch。既存canonical 2,155 Opportunity自体がfirst-selection watchへ一対一だった。対応する実際のSelector eventは2,900件。後続745件は同じwatchのrefreshとしてappendし、464 watch（21.53%）が再選出された。旧canonical event-level2155は別のreference欄に保持し、2900 eventや2155 watchを加算していない。',table(['単位','総数','1 session平均','中央値'],[['Selector events',p['selector_event_N'],fmt(e['mean'],2),fmt(e['median'],2)],['Unique watches',p['watch_N'],fmt(w['mean'],2),fmt(w['median'],2)],['Repeat events',p['repeat_event_N'],fmt(p['repeat_event_N']/58,2),'—'],['Repeated watches',p['repeated_watch_N'],fmt(p['repeated_watch_N']/58,2),'—']]),'全133 development sessionsのtraining+OOF populationは4,931 watches。first selectorから同session regular closeまでの実測closed 1mを使い、30 active-minuteでwatchを捨てない。lunchとclosing auction pauseはactive minuteへ加えない。refresh featureはそのevent timestamp以降だけ。']
 rows=[]
 for name in policy_names:
  s=arms[name];d=activity['panels'][name];rows.append([name,s['FIRST_ENTRY_N'],fmt(d['FIRST_ENTRY_per_session']['mean'],2),fmt(d['FIRST_ENTRY_per_session']['median'],1),d['zero_entry_days'],fmt(s['entry_rate_pct'],2),s['path_evaluable_N'],s['path_unknown_N']])
 lines+=[table(['Policy','FIRST ENTRY N','平均/day','中央値/day','0 Entry日','Entry rate %','Path known N','Path unknown N'],rows),'Entry数/dayは結果として測定した。10/day Gateは置いていない。各policyの0／1–5／6–10／11–15／>15の日数、Entry clock、simultaneous FIRST ENTRY demand、peak ACTIVE watchlistをDAILY_FIRST_ENTRY_ACTIVITY.jsonに保存した。']
 rows=[]
 for name in policy_names:
  d=activity['panels'][name];counts=d['day_buckets'];rows.append([name,*[counts.get(k,0) for k in ['0','1–5','6–10','11–15','>15']],max(x['max_simultaneous_FIRST_ENTRY_demand'] for x in d['daily']),max(x['peak_active_watchlist_size'] for x in d['daily'])])
 lines+=[table(['Policy','0','1–5','6–10','11–15','>15','最大同時Entry','peak watchlist'],rows),'peak watchlistはfirst selectionでactivateしFIRST ENTRYでこのWorkの監視評価を終了する未完了watch数。position releaseやCapital capacityを仮定した値ではない。']
 names=['<1%','1–<2%','2–<3%','3–<4%','4–<5%','>=5%','missing'];lines+=[table(['Selector→High exclusive bucket','watch N'],[[k,bucket[policy_names[0]][k]['watch_N']] for k in names]),'以下は各bucketにおけるFIRST ENTRY後のstrictly later observed Highまでの値幅中央値（%）。Selector future MFEは保存済みcanonical full-day evaluatorのfirst-selector値をreuseした。全bucket×policyのEntry rate／no-entry／delay／mean／p25／p75／retention／Q／D／TV／reversal／time-to-peakはSELECTOR_WATCH_BUCKET_EVALUATION.jsonに保存した。',table(['Policy','1–<2%','2–<3%','3–<4%','4–<5%','>=5%'],[[name,*[fmt(bucket[name][k]['metrics']['entry_to_high_pct']['median']) for k in names[1:6]]] for name in policy_names])]
 rows=[]
 for name in policy_names+['IMMEDIATE','R1']:
  rows.append([name,*[fmt(wins[name][str(k)]['capture_rate_pct'],2) for k in range(1,6)]])
 lines+=['Big Winner Captureは全Selector winnerを分母にし、Entry後に同じthresholdへstrictly later Highで実際に届いた割合。no-entryも分母に残し、欠測下の未到達はunknownとして別保存した。既存baselineでも比較用strictly-later条件を合わせた。旧saved Entry-bar-inclusive Captureを置換・再計算していない。',table(['Policy','>=1 Capture %','>=2','>=3','>=4','>=5'],rows),table(['Selector threshold','Winner denominator'],[[f'>={k}%',wins[policy_names[0]][str(k)]['selector_winner_denominator']] for k in range(1,6)]),table(['Candidate','>=3 Entryあり','>=3 hit','>=3 no-entry','>=3 unknown','>=5 Entryあり','>=5 hit','>=5 no-entry','>=5 unknown'],[[name,*[wins[name][str(k)][field] for k in (3,5) for field in ['FIRST_ENTRY_N','entry_after_same_threshold_hit_N','no_entry_N','unknown_N']]] for name in dict.fromkeys([q,b])])]
 rows=[]
 for name in policy_names+['IMMEDIATE','R1']:
  s=arms[name];rows.append([name,*[fmt(s['metrics'][m]['median']) for m in ['entry_to_high_pct','upside_retention_pct','path_efficiency','pre_peak_mae_abs_pct','total_variation_pct','reversal_count','time_to_peak_active_min','selector_to_entry_active_delay']]])
 lines+=[table(['Policy','Entry→High %','Retention %','Q','pre-peak MAE %','TV %','Reversal','peak active min','Entry delay min'],rows),'Q/D/TV/reversalは欠測を跨がないcomplete pre-peak pathのみ。Highはobserved値であり、一部source不足のwatchでは真の最大Highに対する下限。filled cohortの中央値同士だけで改善を断言しない。共通watchのpaired比較を下に示す。', 'IMMEDIATE/R1は同じWATCH_KEY・first-selector anchorの既存fillをreuse。既存canonical Geometryは引用と数値parityだけで、新しく定義したQ/D/TV/reversalを同じfillから測定した。旧Geometryのtime clockもreferenceとして保持し、Primary clockはfinal RC2のdated regular active minutesへ合わせた。']
 for name in dict.fromkeys([q,b]):
  rows=[]
  for baseline in ['IMMEDIATE','R1']:
   for m in ['entry_to_high_pct','path_efficiency','pre_peak_mae_abs_pct','upside_retention_pct','selector_to_entry_active_delay']:
    s=eh['paired_comparisons'][name][baseline][m];rows.append([baseline,m,s['paired_N'],fmt(s['new']['median']),fmt(s['baseline']['median']),fmt(s['new_minus_baseline']['median'])])
  lines+=[f'**{name}のpaired比較**。同一watchで両armがfilledかつ該当metric knownの場合だけ。Δはwatchごとの差の中央値で、列の中央値の単純差とは異なる。',table(['Baseline','Metric','paired N','新Entry median','baseline median','paired Δ median'],rows)]
 rows=[]
 for family in ['P0','P1']:
  for head in HEADS:
   h=state['head_metrics'][family][head];rows.append([family,head,h['N'],fmt(h['MAE']),fmt(h['Spearman'])])
 lines+=[table(['Family','Head','known OOF N','MAE','Spearman'],rows),'各headのprediction decile actual targetとsession stabilityをSTATE_INCREMENTAL_VALUE.jsonに保存した。percentile transformは各foldのtraining-side predicted distributionだけを使用し、UPTREND_SCOREはU percentile／Q percentile／1−D percentileのequal-weight平均。absolute probabilityとは呼ばない。',f"State incremental status: **{state['status']}**。P1をState9正式採用へ昇格していない。各fixed quantileでのP1−P0差を以下へ保存した。"]
 rows=[]
 for p,d in state['fixed_quantile_entry_deltas'].items():rows.append([p,fmt(d['entry_to_high_pct_median_P1_minus_P0']),fmt(d['path_efficiency_median_P1_minus_P0']),fmt(d['pre_peak_mae_abs_pct_median_P1_minus_P0']),fmt(d['capture_ge3_pp_P1_minus_P0'],2),fmt(d['capture_ge5_pp_P1_minus_P0'],2),fmt(d['entry_rate_pp_P1_minus_P0'],2)])
 lines+=[table(['Quantile','Δ High %','Δ Q','Δ MAE %','Δ >=3 Capture pp','Δ >=5 pp','Δ Entry rate pp'],rows),f"QUALITY rankingはmedian Q→lower median D→higher median High→>=5 Capture→Entry rate。BALANCEDは>=5 Capture最大値から2pp以内のpolicyを対象にQ→D→>=3 Capture→Entry rate。global 8 policiesと各family 4 policiesの両方を保存し、新threshold・profit criterion・Entry数合わせは使っていない。QUALITY={q}、BALANCED={b}。"]
 lines+=[f"Source支持はPrimary {grid['primary']['status_counts']}、observed rows {grid['primary']['observed_rows']:,}／scheduled rows {grid['primary']['expected_rows']:,}。欠測minuteを生成せず、source missingを0にせず、semantic UNKNOWNとsource missingを分離した。全training+OOFのQ/D target knownは{teacher['counts']['Q_target']:,}／{teacher['rows']:,} rows。Path unknownはEntryの品質が悪いと確定した意味ではない。",'限界は、historical actual knownAtがUNKNOWNでbar-end availabilityを仮定していること、missing sourceのPathをunknownにしていること、High touchのintrabar順序がUNKNOWNでpeak-bar Lowを保守的に含めていること、U teacherがmaximum observed Highであること。新しいprovider・Protected・Fresh Validation・OOS・Prospectiveを開いていない。',f"Independent audit: **{audit['status']}**, mismatch {audit['mismatch_N']}。grid全{audit['grid_rows_checked']:,} rows、teacher全{audit['teacher_rows_checked']:,} rows、4 policy×2 familyの全{audit['FIRST_ENTRY_records_checked']:,} recordsを照合した。Stateは事前固定indexの{audit['independent_state_sample_watch_N']} watchをfrozen independent RC2 API＋120精度で別再生し、{audit['independent_state_rows_checked']:,} State rowsを照合した。model direct predictionは{audit['model_prediction_samples_checked']:,} samples、全rowのpercentile／threshold lineage、全training rowのmedian／one-hot scopeを確認した。audit fit=0。有限sample範囲を超えた完全な独立性や実データarrival timestamp証明は主張しない。",'固定30 fitsを完了。P1 fold5の配列準備でメモリ停止したが、27 completed fitsを保存して残り3のみを実行した。float64 preprocessing exact-array parityを確認し、model／teacher／split／thresholdを変更せず、completed fitの再fitは0。hard cap36、hyperparameter／model family／weight／threshold search／bootstrapは0。']
 answers=[['1',f"Selector events平均{fmt(e['mean'],2)}/day、unique watch平均{fmt(w['mean'],2)}銘柄/day。"],['2','745 repeat events、464/2155 watch（21.53%）にrefresh。first eventと全refresh時刻を保存。'],['3','P0/P1×Q70/Q80/Q90/Q95の平均/day・中央値/dayを上表へ保存。'],['4','各policyの0 Entry日数を上表・daily JSONへ保存。'],['5–9','Selector→High 1–<2、2–<3、3–<4、4–<5、>=5%のEntry→High中央値を上の8-policy表へ保存。'],['10','>=1..5 Winner denominatorとCaptureを上表・WINNER_PRESERVATION.jsonへ保存。>=3/5のno-entry・unknownも別計数。'],['11','新EntryとIMMEDIATE/R1の共通watch、known pathのpaired Q/TV/reversalで確認。単純なfilled-cohort差を因果効果としない。'],['12','paired pre-peak MAEの中央値とwatch差中央値を上表へ保存。'],['13','bucket別remaining High／retention／delay、Winner Captureで確認待ちの値幅消費を確認。'],['14',state['status']+'。fixed-quantile差を上表に保持。'],['15',q],['16',b],['17','同じ。' if q==b else '異なる。'],['18',assessment],['19','主な制約はPath source欠測、Stateの安定したincremental value未確定、確認待ちによる残存値幅とCaptureのtradeoff。具体的な量は各表へ保存。'],['20','EXIT policy／R50 adapter／EXIT Replay／Re-entry／2回目Entry／Capital Replayを一度も実行していない。orders=0、main merge=0。']]
 lines+=[table(['必須回答','回答'],answers),'FIRST ENTRY→EXIT→watchlist再開→Re-entryという将来工程は今回の結果へ混ぜていない。次工程を行う場合はFIRST ENTRY candidateのFreeze候補化から始め、State-aware EXITは別Workで行う。North Star約+3%/sessionからteacher・threshold・candidateを逆算していない。','常に executionAllowed=false、brokerWriteAllowed=false、excelOrderWriteAllowed=false、rssOrderFunctionAllowed=false、liveTradingAllowed=false、paperTradingAllowed=false、automaticPromotionAllowed=false、productionUpdateAllowed=false、transmitted=false、productionReady=false。LONG-only／cash-equity-only、Selector変更0、EXIT設計0、Capital変更0。']
 (HERE/'REPORT-ja.md').write_text('\n\n'.join(lines)+'\n')
 handoff={'saved_at_jst':now(),'basis_head':basis,'status':status,'QUALITY_candidate':q,'BALANCED_candidate':b,'same_candidate':q==b,'assessment':assessment,'development_only':True,'next_stage_authorized_in_this_Work':False,'State_adopted':False,'FIRST_ENTRY_records':{p:{'path':f'FIRST_ENTRY_{p}.jsonl.gz','sha256':sha(HERE/f'FIRST_ENTRY_{p}.jsonl.gz'),'families':['P0','P1'],'watch_N_per_family':2155} for p in POLICIES},'audit':{'status':audit['status'],'mismatch_N':audit['mismatch_N'],'fit':0},'new_fits':30,'refits':0,'searches':model['searches'],'EXIT_calls':0,'reentry_calls':0,'capital_replay':0,'orders':0,'main_merge':0,'safety':SAFETY}
 write(HERE/'FINAL_STATUS.json',handoff)
 text=['# FINAL HANDOFF — FIRST ENTRY ONLY',f'Actual saved_at_jst: {handoff["saved_at_jst"]}\n\nActual basis_head: `{basis}`\n\nStatus: {status}',assessment,f'QUALITY: **{q}** / BALANCED: **{b}** / same: {q==b}', '全4 policyのFIRST_ENTRY filesは各2,155 watch×P0/P1を含む。no-entryも残している。row-level/private artifactsは別deliverableのPrivate Evidence packageへ保存し、GitHubにはaggregate、contract、再現code、hash receiptを保存する。', '候補選択はDevelopment outer OOFの所定のQ/D/U/Capture rankingのみ。productionReady=false。Fresh Validation unopened。前SAFE_UPSIDE WorkはFAILのまま閉じて保持。', '再現は保存sourceと固定contractから行える。完了済みFIT_LEDGERとmodelsを使えばaudit fit=0。closed 1mの実際のarrival時刻はUNKNOWNでbar-end assumption。欠測Pathはunknown。', '今回の停止点はFIRST ENTRYの生成・単体評価。EXIT・R50・Re-entry・Capital・Portfolioを実行していない。次のEXIT研究は別Workとして候補Freeze後に行う。', 'Exposure: provider0 / Protected0 / Fresh0 / Validation0 / OOS0 / Prospective0 / EXIT Replay0 / Re-entry0 / Capital0 / orders0 / main merge0 / fits30 of cap36 / searches0 / audit fits0。', 'CHECKPOINTS/FINAL.jsonのbasis_headはcommit前の実在HEAD。commit後のactual GET result HEADはLOCAL_GET_RECEIPTS/FINAL.jsonとuser-facing final receiptへ保存する。未来commit SHAは記載しない。']
 (HERE/'FINAL_HANDOFF.md').write_text('\n\n'.join(text)+'\n')
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--basis-head',required=True);ap.add_argument('--status',required=True);ap.add_argument('--assessment',required=True);a=ap.parse_args();run(a.basis_head,a.status,a.assessment)
