import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {FLAGS,emptyStatus,assemble,executionView,sourceFromCapture} from '../data.mjs';import {demoStatus} from '../demo.mjs';import {readInput,createServer} from '../server.mjs';
const safety=Object.fromEntries(FLAGS.map(k=>[k,false])),now='2026-09-14T05:16:06.000Z';
function execution(){return {version:'PHASE57_EXECUTION_V1',fixtureOnly:true,safety,transmission:'LOCKED',initialEquity:1000000,externalCashFlowJpy:0,portfolio:{equityJpy:1010000,realizedPnl:10000,unrealizedPnl:0,cashJpy:1010000,buyingPower:1010000,grossExposureJpy:0,signedNetExposureJpy:0,positions:[]},orders:{}};}
function report(){return {schemaId:'ARK_REAL_SOURCE_SEMANTICS_REPORT_V1',mode:'SOURCE_SEMANTICS_ONLY',strategyCalculated:false,readyForStrategy:false,safety,connectionState:'REAL_SOURCE_CONNECTED_OBSERVED',currentFeedObservations:[{symbol:'7203.T',captureTimestamp:now,marketTimestamp:now,currentPrice:3024,bestBid:3024,bestAsk:3025,fresh:true}],latestRawWindowMetadata:[{rawLatestSessionSourceTime:'14:15:00',normalizedLatestSourceTime:'14:15:00',normalizationParity:'PASS'}],events:[]};}
test('missing account remains unknown, transmission locked',()=>{const s=emptyStatus();assert.equal(s.portfolio,null);assert.equal(s.execution.transmission,'LOCKED');});
test('upstream source connection and parity never imply finalized or strategy ready',()=>{const s=assemble({source:report(),now});assert.equal(s.components[0].status,'CONNECTED');assert.equal(s.components[2].status,'FRESH');assert.equal(s.source.parity,'PASS');assert.equal(s.components[4].status,'UNVERIFIED');assert.equal(s.components[6].status,'UNKNOWN');assert.equal(s.portfolio,null);});
test('old report becomes stale, not a heartbeat',()=>{assert.equal(assemble({source:report(),now:'2026-09-14T05:17:06Z'}).components[0].status,'STALE');});
test('PASS label needs matching raw and normalized actual latest fields',()=>{const r=report();r.latestRawWindowMetadata[0].normalizedLatestSourceTime='13:00:00';assert.equal(assemble({source:r,now}).source.parity,'UNVERIFIED');});
test('source reader does not fabricate connection classification',()=>{const s=sourceFromCapture({mode:'SOURCE_SEMANTICS_ONLY',sourceClass:'REAL_SOURCE_DIAGNOSTIC',captureTimestamp:now,workbookHealthy:true,partialRead:false,rows:[]});assert.equal(s.connectionState,'SOURCE_CONNECTION_UNVERIFIED');});
test('partial capture cannot retain raw PASS',()=>{const s=sourceFromCapture({mode:'SOURCE_SEMANTICS_ONLY',sourceClass:'REAL_SOURCE_DIAGNOSTIC',captureTimestamp:now,workbookHealthy:true,partialRead:true,rows:[],rawWindowMetadata:report().latestRawWindowMetadata});assert.equal(s.latestRawWindowMetadata.length,0);assert.equal(s.events.length,1);});
test('non-source-only mode rejected',()=>{assert.throws(()=>sourceFromCapture({mode:'REALTIME_SHADOW'}));});
test('withdrawal separate from trading PnL and no fabricated flow-adjusted return',()=>{const e=execution();e.externalCashFlowJpy=-300000;e.portfolio.equityJpy=710000;const s=executionView(e);assert.equal(s.portfolio.pnl,10000);assert.equal(s.portfolio.flow,-300000);assert.equal(s.portfolio.returnPct,null);});
test('missing session baseline produces unknown day percent',()=>{const e=execution();e.sessionStartEquity=1000000;assert.equal(executionView(e).portfolio.todayPct,null);});
test('conservation mismatch rejects snapshot',()=>{const e=execution();e.portfolio.equityJpy+=1;assert.throws(()=>executionView(e),/CONSERVATION/);});
test('real execution input and unsafe flags rejected',()=>{assert.throws(()=>executionView({...execution(),fixtureOnly:false}));for(const f of FLAGS)assert.throws(()=>executionView({...execution(),safety:{...safety,[f]:true}}));});
test('malformed numeric cannot render zero or valid portfolio',()=>{const e=execution();e.portfolio.cashJpy='100';const s=assemble({execution:e});assert.equal(s.portfolio,null);assert.match(s.warnings[0],/MALFORMED/);});
test('demo is marked and totals match position evidence',()=>{const s=demoStatus(now);assert.equal(s.mode,'DEMO');assert.equal(s.positions.reduce((a,p)=>a+p.pnl,0),s.portfolio.unrealized);assert.equal(s.positions.reduce((a,p)=>a+p.value,0),s.portfolio.gross);assert.equal(Math.round(s.history.at(-1).equity),s.portfolio.equity);assert.equal(s.portfolio.cash+s.positions.reduce((n,p)=>n+(p.direction==='LONG'?p.value:p.details.collateral+p.details.shortProceeds-p.value),0),s.portfolio.equity);});
test('torn tail preserved, completing append recovers',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ark-ui-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'capture.jsonl');fs.writeFileSync(file,'{"id":1}\n{"id":');assert.throws(()=>readInput(file,true),/PARTIAL/);fs.appendFileSync(file,'2}\n');assert.deepEqual(readInput(file,true),{id:2});});
test('duplicate position identity fails',()=>{const e=execution();const p={symbol:'7203.T',direction:'LONG',quantity:100,averagePrice:10,markPrice:10};e.portfolio.positions=[p,p];assert.throws(()=>executionView(e),/POSITION_IDENTITY/);});
test('HTTP only GET, same origin, no file traversal or write endpoint',async t=>{const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base=`http://127.0.0.1:${server.address().port}`;assert.equal((await(await fetch(base+'/api/status')).json()).portfolio,null);assert.equal((await fetch(base+'/api/status',{method:'POST'})).status,405);assert.equal((await fetch(base+'/api/status',{headers:{Origin:'https://example.com'}})).status,403);for(const p of ['/server.mjs','/constructor','/api/arm','/api/submit'])assert.equal((await fetch(base+p)).status,404);});
test('actual #584 observer report maps to UI without changing finality',async()=>{const {SourceObserver}=await import('../../scripts/lib/phase57-source-observer.mjs');const o=new SourceObserver();o.step({mode:'SOURCE_SEMANTICS_ONLY',sourceClass:'SYNTHETIC_TRANSPORT_TEST',sourceIdentity:'synthetic',workbookIdentity:'dedicated',workbookVersion:'v1',fieldMapSha256:'a'.repeat(64),captureId:'1',captureTimestamp:now,sessionDate:'2026-09-14',connected:true,workbookHealthy:true,partialRead:false,rows:[{slot:0,generation:0,symbol:'1000.T',sourceCode:'1000',sourceDate:'2026-09-14',sourceTime:'14:15:00',open:100,high:101,low:99,close:100,volume:1,marketTimestamp:now,currentPrice:100,bestBid:99,bestAsk:101}]});const s=assemble({source:o.report(),now});assert.equal(s.components[0].status,'CONNECTED');assert.equal(s.source.feeds[0].freshness,'FRESH');assert.equal(s.source.finalizedLatest,null);assert.equal(s.portfolio,null);});
