"""Fixed paired measurements of the two new EXIT arms. No policy selection."""
from exit_common import *

METRICS=['realized_return_pct','MFE_realization_pct','Peak_Giveback_pp','opportunity_giveback_pp','held_observed_MFE_pct','holding_active_min']
def panel(rows):
    known=[r for r in rows if r['realized_return_pct'] is not None];loss=[r['realized_return_pct'] for r in known if r['realized_return_pct']<0]
    return {'Entry_N':len(rows),'sell_filled_N':len(known),'unresolved_N':len(rows)-len(known),'metrics':{k:stats(r[k] for r in known) for k in METRICS},'negative_loss_containment':{'loss_N':len(loss),'negative_return':stats(loss),'below_minus1_N':sum(r['realized_return_pct']<-1 for r in known),'below_minus2_N':sum(r['realized_return_pct']<-2 for r in known),'worst_return_pct':min([r['realized_return_pct'] for r in known],default=None)},'exit_reasons':dict(__import__('collections').Counter(r['exit_reason'] for r in rows)),'complete_execution_path_N':sum(r['execution_path_complete'] for r in known)}
def run():
    assert not (HERE/'TWO_ARM_EVALUATION.json').exists(),'NO_EVALUATION_REGENERATION'
    b=list(lines(HERE/'STATE_EXIT_RECORDS.jsonl.gz'));h=list(lines(HERE/'STATE_EXIT_HARD1_RECORDS.jsonl.gz'));pairs=list(lines(HERE/'PAIRED_EXIT_DELTAS.jsonl.gz'));assert len(b)==len(h)==len(pairs)==1600
    known=[i for i,p in enumerate(pairs) if p['paired_known']];complete=[i for i in known if pairs[i]['both_execution_path_complete']]
    paired={'paired_N':len(known),'STATE_EXIT':panel([b[i] for i in known]),'STATE_EXIT_HARD1':panel([h[i] for i in known]),'delta_HARD1_minus_STATE_EXIT':{k:stats(h[i][k]-b[i][k] for i in known if h[i][k] is not None and b[i][k] is not None) for k in METRICS},'return_improved_N':sum(pairs[i]['delta_return_pp']>1e-10 for i in known),'return_worsened_N':sum(pairs[i]['delta_return_pp']<-1e-10 for i in known),'return_equal_N':sum(abs(pairs[i]['delta_return_pp'])<=1e-10 for i in known)}
    winners={}
    for level in (3,5):
        den=[i for i,r in enumerate(b) if r['entry_observed_MFE_pct'] is not None and r['entry_observed_MFE_pct']>=level];idx=[i for i in den if i in known]
        winners[str(level)]={'basis':'strictly-later observed Entry-relative same-session High, lower bound under missing source','winner_denominator':len(den),'paired_N':len(idx),'unpaired_N':len(den)-len(idx),'complete_remaining_source_winner_N':sum(b[i]['entry_remaining_source_complete'] for i in den),'STATE_EXIT':panel([b[i] for i in idx]),'STATE_EXIT_HARD1':panel([h[i] for i in idx]),'paired_delta':{k:stats(h[i][k]-b[i][k] for i in idx if h[i][k] is not None and b[i][k] is not None) for k in ['realized_return_pct','MFE_realization_pct','Peak_Giveback_pp','opportunity_giveback_pp']},'Hard1_trigger_in_winners_N':sum(h[i]['Hard1_trigger'] for i in den)}
    triggers=[i for i,r in enumerate(h) if r['Hard1_trigger']]
    hard={'trigger_N':len(triggers),'gap_open_N':sum(h[i]['Hard1_trigger_kind']=='GAP_OPEN_AT_OR_BELOW_LINE' for i in triggers),'intrabar_line_touch_N':sum(h[i]['Hard1_trigger_kind']=='INTRABAR_LOW_TOUCH' for i in triggers),'trigger_paired_known_N':sum(i in known for i in triggers),'baseline_unresolved_but_Hard1_filled_N':sum(i not in known for i in triggers),'saved_negative_loss_N':sum(pairs[i]['saved_negative_loss'] for i in known),'trigger_return_improved_N':sum(pairs[i]['delta_return_pp']>1e-10 for i in triggers if i in known),'trigger_return_worsened_N':sum(pairs[i]['delta_return_pp']<-1e-10 for i in triggers if i in known),'trigger_delta_return_pp':stats(pairs[i]['delta_return_pp'] for i in triggers if i in known),'negative_loss_saved_pp':stats(pairs[i]['delta_return_pp'] for i in known if pairs[i]['saved_negative_loss']),'later_winners_cut':{str(level):{'confirmed_strictly_after_stop_N':sum(h[i][f'later_winner_{level}_observed'] for i in triggers),'known_no_hit_N':sum(h[i][f'later_winner_{level}_status']=='KNOWN_NO_HIT' for i in triggers),'unknown_incomplete_source_N':sum(h[i][f'later_winner_{level}_status']=='UNKNOWN_INCOMPLETE_SOURCE' for i in triggers),'stop_bar_only_order_ambiguous_N':sum(h[i][f'stop_bar_only_winner_{level}_order_ambiguous'] for i in triggers)} for level in (3,5)},'loss_bound':'raw stop line -1%; cost-adjusted touch fill about -1.0495%; gaps may lose more','no_extra_model_fit':True}
    result={'saved_at_jst':now(),'document_id':DOC,'scope':'new two-arm saved-source chronological OOF research replay; no arm adoption','single_arm':{'STATE_EXIT':panel(b),'STATE_EXIT_HARD1':panel(h)},'paired_primary':paired,'winners':winners,'Hard1':hard,'complete_paired_execution_subset':{'paired_N':len(complete),'STATE_EXIT':panel([b[i] for i in complete]),'STATE_EXIT_HARD1':panel([h[i] for i in complete]),'delta_return_pp':stats(pairs[i]['delta_return_pp'] for i in complete)},'source_limitations':{'terminal_fill_unknown_preserved':True,'intrabar_stop_order_unknown':True,'missing_minutes_no_fabrication':True,'observed_high_is_lower_bound':True,'historical_actual_known_at':'UNKNOWN; frozen RC2 assumed available at bar end'},'Entry_refit':0,'old_EXIT_read_or_comparison':0,'Reentry':0,'Capital':0,'Portfolio_Replay':0,'provider':0,'protected':0,'orders':0,'safety':SAFETY}
    write(HERE/'TWO_ARM_EVALUATION.json',result);write(HERE/'WINNER_PRESERVATION_EXIT_EVIDENCE.json',{'saved_at_jst':now(),'winners':winners,'arm_selection':0});write(HERE/'HARD1_PAIRED_DIAGNOSIS.json',{'saved_at_jst':now(),**hard,'paired_primary':paired})
    print(json.dumps({'paired_N':len(known),'Hard1_trigger_N':len(triggers),'loss_saved_N':hard['saved_negative_loss_N'],'later_3_winners_cut_N':hard['later_winners_cut']['3']['confirmed_strictly_after_stop_N'],'later_5_winners_cut_N':hard['later_winners_cut']['5']['confirmed_strictly_after_stop_N']}),flush=True)
if __name__=='__main__':run()
