"""Save the new two-arm protocol before labels/fits/outcome aggregation."""
import argparse
from exit_common import *

def run(basis):
    assert not (HERE/'TEACHER_LABELS.jsonl.gz').exists(), 'FREEZE_AFTER_LABELS_FORBIDDEN'
    e=read(ENTRY/'FIRST_ENTRY_V2_FREEZE_RECEIPT.json')
    assert e['EntryFrozen'] and e['Entry_N']==1600
    assert sha(ENTRY/'P1_Q70_FIRST_ENTRY_RECORDS.jsonl.gz')=='e7a6140b6b11d8d078a271fad76b75e68a5b2fda9e45c7db43d98ee2f282abeb'
    f=read(ENTRY/'FEATURE_FREEZE.json'); identity=f['state_identity']
    source_checks=[]
    for item in identity['source_files']:
        p=STATE/'FROZEN_RC2_SOURCE'/item['path']
        assert sha(p)==item['sha256'],p
        source_checks.append({'path':item['path'],'sha256':sha(p)})
    inputs={str(p.relative_to(SCRATCH)):{'sha256':sha(p),'bytes':p.stat().st_size}
            for p in [SOURCE,ENTRY/'P1_Q70_FIRST_ENTRY_RECORDS.jsonl.gz',ENTRY/'PERSISTENT_GRID.jsonl.gz',ENTRY/'STATE_FEATURE_METADATA.jsonl.gz',ENTRY/'SPLIT_PRECOMMIT.json',ENTRY/'FEATURE_FREEZE.json',ENTRY/'PRIVATE_INPUTS/features_numeric.npy',ENTRY/'PRIVATE_INPUTS/features_categories.npy',ENTRY/'PRIVATE_INPUTS/category_vocabulary.json',ENTRY/'PRIVATE_INPUTS/watch_row_ranges.npy']}
    write(HERE/'UPSTREAM_IDENTITY_RECEIPT.json',{'saved_at_jst':now(),'basis_head':basis,'entry_freeze_head':ENTRY_HEAD,'Entry_N':1600,'Entry_branch_read_only':True,'Legacy_State_features':0,'inputs':inputs,'exact_latest_RC2_State9':identity,'source_checks':source_checks,'Entry_refit':0,'Selector_changes':0,'old_EXIT_body_reads':0,'safety':SAFETY})
    write(HERE/'FEATURE_FREEZE.json',{'saved_at_jst':now(),'basis_head':basis,'before_teacher_computation':True,'numeric':f['P1_numeric'],'categorical':f['P1_categorical'],'numeric_N':148,'categorical_N':15,'State9_identity':identity,'Legacy_State':0,'source':'Frozen Entry P1 causal context arrays reused read-only at each post-entry closed1m; no Entry score/model predictor','preprocessing':'outer finite-label training rows only numeric median plus missing indicator; all-missing median0; train-only one-hot plus explicit missing/semantic unknown and unseen unknown','position_anchored_features_in_model':0,'entry_relative_price_used_only_by_Hard1':True,'future_fields_allowed_as_features':False,'prohibited':f['prohibited'],'safety':SAFETY})
    write(HERE/'SPLIT_PRECOMMIT.json',{'saved_at_jst':now(),'basis_head':basis,'before_teacher_computation':True,'source_sha256':sha(ENTRY/'SPLIT_PRECOMMIT.json'),'folds':read(ENTRY/'SPLIT_PRECOMMIT.json')['folds'],'train_scope':'saved selected-watch minute contexts in earlier train sessions; does not generate or alter Entry records','replay_scope':'1600 existing frozen filled P1_Q70 entries in 58 outer-test sessions only','random_split':False,'future_session_train':False,'same_session_crossing':False,'same_watch_crossing':False})
    write(HERE/'EXIT_TEACHER_CONTRACT.json',{'saved_at_jst':now(),'basis_head':basis,'before_teacher_computation':True,'head':'HOLD_CONTINUATION_VALUE','definition':'100*(mean(strictly later available executable sell opportunities)/EXIT_NOW executable sell price -1)','EXIT_NOW':'first available regular raw open start>=closed decision, excluding540/750; otherwise terminal closing-auction close','later_opportunities':'regular raw opens strictly later than EXIT_NOW fill plus same-session terminal closing-auction close, one equally weighted observed opportunity each','terminal_source_required':True,'missing_later_regular_minutes':'not fabricated, not forward filled; label is observed available opportunity mean; scheduled coverage saved separately','at_or_after_terminal': 'no later opportunities => NULL','training_target':'clip(raw_value_pct,-10,10)','future_isolation':'teacher values/raw future source suffix never passed to decision feature matrix','teacher_search':0,'peak_High_teacher':False,'Entry_conditioning':'position-independent continuation relative to selling now; evaluated only after frozen Entry in replay'})
    write(HERE/'MODEL_POLICY_FREEZE.json',{'saved_at_jst':now(),'basis_head':basis,'before_teacher_computation':True,'model':'HistGradientBoostingRegressor','parameters':PARAMS,'heads':1,'folds':5,'new_EXIT_fits':5,'fit_hard_cap':5,'Hard1_extra_fits':0,'threshold_pct':0.,'consecutive_nonpositive_observed_closed_bars':2,'counter_reset':'positive prediction, missing raw minute, AM/PM phase boundary','intent':'earliest second consecutive prediction<=0 post Entry fill; lock intent','fill':'next available eligible regular raw open at start>=intent; if none, scheduled same-session closing-auction close','forced_session_close':'preplanned closing-auction liquidation, closing source missing=>UNRESOLVED, never last-observed-close substitution','state_machine':'POSITION_OPEN -> HOLD/EXIT_INTENT -> SELL_FILL -> CLOSED; closed arms stop decisions; no reentry','hard1':{'entry_relative_line_pct':-1.,'raw_stop_line':'frozen Entry fill_price*.99','monitor':'observed eligible regular bars only, including Entry fill bar;540/750 mixed openings and AM/PM terminal auctions excluded','gap':'open<=line =>raw open; else low<=line=>raw line','sell_adjustment_bps':5,'baseline_pending_market_fill_at_same_open':'executes first, intrabar stop does not override it','threshold_touch_not_prediction_feature':True,'intrabar_high_low_order':'unknown; stop-bar High excluded from strictly-later later-winner audit','assumption':'OHLC standing stop proxy; raw line is not a guaranteed net -1% loss; unseen gaps/touches remain unobserved'},'cost':{'canonical_LONG_sell_formula':'reference*(1-halfSpreadRate-slippageRate)','adverse_rate_per_side_bps':5,'buy_cost':'already embedded in frozen fill_price, do not double count','commission_per_side':0,'spread_percent':0,'slippage_percent_per_side':.05,'reference_module':'predict/trading/backtest-cost-model.js @ Entry HEAD; research override reconciled to frozen Entry5bps, not generic default preset','no_market_impact_or_capacity':True},'arms':['STATE_EXIT','STATE_EXIT_HARD1'],'searches':0,'old_EXIT_read_or_execution':0,'new_policy_after_results':0,'formal_arm_selection':0,'safety':SAFETY})
    write(HERE/'EVALUATION_PRECOMMIT.json',{'saved_at_jst':now(),'basis_head':basis,'before_teacher_computation':True,'primary_unit':'same frozen filled Entry / WATCH_KEY; same test fold','return':'100*(sell_fill/frozen_entry_fill-1), commission0; equal-entry mean/median, not portfolio/session capital return','opportunity_MFE':'frozen strictly-later observed same-session High relative to fill; observed lower bound when source partial','MFE_realization':'100*realized_return/positive opportunity_MFE; report ratio mean/median without clipping','Peak_Giveback':'held observed MFE through bars strictly before sell minute minus realized_return (pp); fill-bar High excluded; stop-bar intrabar order unknown','opportunity_giveback':'full-session observed MFE minus realized_return, includes upside after early exit; separately named','winner_denominators':[3,5],'winner_basis':'observed Entry-relative opportunity_MFE >= threshold; partial path lower-bound diagnosis separated','paired_primary':'both arms sell-filled; each single arm filled N and unresolved N also reported','negative_loss_containment':['loss N','mean/median negative return','return<-1% N','return<-2% N','worst return'],'Hard1_saved_loss':'Hard1 trigger and both known; baseline negative and HARD1 return greater than STATE_EXIT','Hard1_later_winner_cut':'strictly later than Hard1 sell bar, later High reaches Entry+3% or+5%; stop-bar only touch excluded/ambiguous','source_completeness':'scheduled eligible bars from Entry fill through each exit; missing minutes not manufactured; paired complete subset also shown','frozen_upstream_changes':0,'old_EXIT_controls':0,'Capital_Replay':0})
    write(HERE/'FIT_LEDGER.json',{'planned':5,'hard_cap':5,'fits_reserved':0,'fits_completed':0,'runs':[],'Entry_fits':0,'Hard1_fits':0,'searches':0})
    print(json.dumps({'status':'EXIT_PROTOCOL_PREFROZEN','saved_at_jst':now(),'new_EXIT_fits_planned':5,'Hard1_extra_fits':0,'frozen_entry_read_only':True}))
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--basis',required=True);run(p.parse_args().basis)
