"""All-window comparison and minimal public/private delivery artifacts."""
from decimal import Decimal as D
from statistics import mean,median
from collections import Counter
from datetime import date
import hashlib,csv
from io_utils import *
from diagnostic import capture

def money(x):return f'{D(x):,.2f}' if x is not None else '未測定'
def main():
    a=read(OUT/'V5_RESET20_RESULT.json');b=read(OUT/'V51_RESET20_RESULT.json');am={w['window_id']:w for w in a['windows']};bm={w['window_id']:w for w in b['windows']};assert list(am)==list(bm)
    labels=rows(PRIVATE/'evaluation-only/R_LABELS.jsonl.gz');lm={r['entry_id']:r for r in labels};paired=[];changes=[];rows_compare=[];aux=[]
    for k,aw in am.items():
        bw=bm[k];ac=aw['final_cash_for_primary'];bc=bw['final_cash_for_primary'];complete=aw['status']=='COMPLETE' and bw['status']=='COMPLETE';delta=D(bc)-D(ac) if complete else None
        rows_compare.append({'window_id':k,'start_session':aw['start_session'],'end_session':aw['end_session'],'coverage_complete':aw['coverage_complete'],'V5_status':aw['status'],'V51_status':bw['status'],'V5_final_cash':ac,'V51_final_cash':bc,'delta_jpy':str(delta) if delta is not None else None})
        if complete:paired.append(delta)
        if not aw['coverage_complete']:continue
        root=PRIVATE/'runs';ad=rows(root/'V5_RESET20'/k/'DECISIONS.jsonl.gz');bd=rows(root/'V51_RESET20'/k/'DECISIONS.jsonl.gz');at=rows(root/'V5_RESET20'/k/'TRADES.jsonl.gz');bt=rows(root/'V51_RESET20'/k/'TRADES.jsonl.gz')
        amap={d['entry_id']:d for d in ad};bmap={d['entry_id']:d for d in bd}
        for key in sorted(set(amap)|set(bmap)):
            x=amap.get(key);y=bmap.get(key)
            if x is not None and y is not None and (x['quantity']!=y['quantity'] or x['reason']!=y['reason']):
                changes.append({'window_id':k,'session':x['session'],'minute':x['minute'],'entry_id':key,'entry_sha256':hashlib.sha256(key.encode()).hexdigest(),'V5_quantity':x['quantity'],'V51_quantity':y['quantity'],'V5_debit':x.get('debit'),'V51_debit':y.get('debit'),'V5_reason':x['reason'],'V51_reason':y['reason'],'V5_held_before':x['held_before_batch'],'V51_held_before':y['held_before_batch']})
        pool=[r for r in labels if r['session'] in aw['sessions']]
        aux.append({'window_id':k,'V5':capture(pool,ad,at),'V51':capture(pool,bd,bt)})
    changes.sort(key=lambda r:(r['session'],r['minute'],r['window_id'],r['entry_id']))
    save(PRIVATE/'evaluation-only/POLICY_DELTA_LEDGER.json',changes)
    first=changes[0] if changes else None
    first_public={k:v for k,v in first.items() if k not in ['entry_id','V5_held_before','V51_held_before']} if first else None
    if first_public:
        first_public['definition']='Chronologically earliest differing decision/quantity, then window_id/entry identity; no outcome-based selection'
        save(OUT/'FIRST_ACTUAL_DIFFERENCE.json',first_public)
    all_complete=len(paired)==len(am)
    pma=median(D(r['V5_final_cash']) for r in rows_compare if r['delta_jpy'] is not None);pmb=median(D(r['V51_final_cash']) for r in rows_compare if r['delta_jpy'] is not None)
    comparison={'schema':'ARK_V51_ALL_WINDOW_FINAL_COMPARISON_V1','exact_jst':now(),'planned_window_N':len(am),'paired_complete_N':len(paired),'coverage_blocked_both_N':sum(r['V5_status']=='BLOCKED_COVERAGE' and r['V51_status']=='BLOCKED_COVERAGE' for r in rows_compare),'unilateral_completion_N':sum((r['V5_status']=='COMPLETE')!=(r['V51_status']=='COMPLETE') for r in rows_compare),'V5':a['summary'],'V51':b['summary'],'median_final_cash_difference_jpy':str(pmb-pma),'paired_delta_median_jpy':str(median(paired)),'paired_delta_mean_jpy':str(mean(paired)),'paired_win_N':sum(x>0 for x in paired),'paired_tie_N':sum(x==0 for x in paired),'paired_loss_N':sum(x<0 for x in paired),'measurement_status':'MEASUREMENT_COMPLETE' if all_complete else 'MEASUREMENT_INCOMPLETE','comparison_scope':'COMPLETE_PRIMARY_SET' if all_complete else 'PARTIAL_DIAGNOSTIC_ONLY','wealth_status':'NO_POLICY_DIFFERENCE' if not changes else 'NO_WEALTH_PROGRESS' if pmb<=pma else 'DEV_WEALTH_PROGRESS' if all_complete else 'PARTIAL_DIAGNOSTIC_ONLY','wealth_status_scope':'all planned windows' if all_complete else 'paired measurable9/21-window Development subset only','north_star_status':'NORTH_STAR_MEDIAN_NOT_REACHED' if pmb<D('2000000') else 'NORTH_STAR_MEDIAN_REACHED_DEVELOPMENT','north_star_status_scope':'Measured subset; full planned-set target certification unavailable','candidate_decision':'REJECTED' if pmb<=pma else 'NO_PROMOTION_PARTIAL' if not all_complete else 'DEVELOPMENT_PROGRESS_ONLY','quantity_reason_difference_occurrences':len(changes),'quantity_reason_difference_unique_entry_N':len({r['entry_id'] for r in changes}),'first_actual_difference':first_public,'windows':rows_compare,'auxiliary_by_window':aux,'productionReady':False}
    save(OUT/'FINAL_COMPARISON.json',comparison)
    with (OUT/'FINAL_WINDOW_COMPARISON.csv').open('w') as f:
        writer=csv.DictWriter(f,fieldnames=list(rows_compare[0]));writer.writeheader();writer.writerows(rows_compare)
    counts={'V5_formal_batches':1,'V51_formal_batches':1,'planned_windows_per_policy':21,'considered_windows_per_policy':21,'executed_windows_per_policy':9,'day_attempts_per_policy':180,'formal_day_attempts_total':360,'technical_full_batch_restarts':0,'new_candidate_N':1,'candidate_threshold_rescues':0,'saved_first_day_market_compatibility_probes':1,'synthetic_evaluator_suite_invocations':2,'synthetic_evaluator_tests_final_passed':12,'synthetic_evaluator_day_invocations':178,'synthetic_candidate_suite_invocations':1,'synthetic_candidate_tests_passed':11,'synthetic_candidate_day_invocations':8,'synthetic_candidate_pure_allocation_invocations':12,'label_boundary_suite_invocations':1,'label_boundary_tests_passed':3,'R_materializations':1,'independent_window_accounting_audits':18,'new_fits':0,'refits':0,'calibration':0,'old38_full_replays':0,'original_AUC_recertifications':0,'bootstrap':0,'old_oracle_solves':0,'provider_market_prices':0,'protected_partition_openings':0,'orders':0,'main_merge':0,'force_push':0,'Claude':0,'upstream_edits':0}
    checkpoint('FINAL_RESEARCH_COMPLETE','CANDIDATE_REJECTED_MEASUREMENT_INCOMPLETE','Keep V5 baseline. Resolve missing Jul11/14 provenance using existing source/completion receipts; do not repeat the pP-lot candidate or tune it',counts,{'V5_median':str(pma),'V51_median':str(pmb),'median_delta':str(pmb-pma),'primary_set_complete':False,'accounting_mismatch_N':sum(x['mismatch_N'] for x in read(OUT/'INDEPENDENT_ACCOUNTING_AUDIT.json')['profiles'])})
    state={'exact_jst':now(),'status':'WORK_COMPLETED_WITH_COVERAGE_BLOCKERS','activeCapitalBaseline':'V5','selectedCapitalCandidate':None,'selectedResearchCandidate':None,'tested_candidate':'V5.1','candidate_decision':'REJECTED','measurement_status':comparison['measurement_status'],'wealth_status':comparison['wealth_status'],'scope':comparison['comparison_scope'],'completed':['Verified current branch/history/full Work instruction','Finite calendar coverage audit; original split unchanged','RESET20 wrapper12 tests and saved first-day exact equality','V5 reset batch21 planned9 executed180 days','R-label materialization1039 entries1016 known; exact boundaries','Score/slot/cash/quantity diagnosis','One precommitted V5.1;11 canaries;21 planned9 executed180 days','Raw-source independent accounting both policies mismatch0','All-window comparison and first actual quantity difference','No threshold rescue; candidate rejected'],'blockers':[{'kind':'coverage','sessions':['2025-07-11','2025-07-14'],'needed':'Existing source/universe coverage and Frozen Selector/Entry completed/zero/exclusion receipt','blocked_windows':12},{'kind':'evaluation_labels','known_N':1016,'unknown_N':23,'reasons':{'ineligible_after_cutoff':11,'future_fixed_EXIT_EOD_source_unavailable':12},'runtime_future_source_filter':False}],'next':'Recover existing missing-day provenance or document precise upstream regeneration scope for separate authorization; current cycle closed. No second policy, no threshold rescue, no new model claim. Small-profit allocation remains an open research question, not ruled out','counts':counts,'source_exposure':'ITERATIVE_DEVELOPMENT_EVIDENCE','fresh_validation_claim':False,'improvement_claim':False,'two_x_claim':False,'productionReady':False,'safety':{k:False for k in ['executionAllowed','brokerWriteAllowed','excelOrderWriteAllowed','rssOrderFunctionAllowed','liveTradingAllowed','paperTradingAllowed','automaticPromotionAllowed','productionUpdateAllowed','transmitted']}}
    save(OUT/'CURRENT_STATE.json',state)
    report=['# 📊 Capital V5.1 — 最終結果',f'\n実時計JST: {now()}\n', '**V5.1は不採用。測定可能な同一9窓で最終資産中央値が低下した。** 予定21窓のうち12窓はcoverage不明のまま残したため、全予定集合の月次評価は未成立。', '\n## 💴 最終資産比較\n','各窓はcash100万円・保有0から開始し、20営業日内では複利連結。以下は両policyが完了した9窓のDevelopment診断。旧LEGACY_NORMALIZED20の19窓とは初期条件・母集団が異なり、同じ改善率として比較しない。\n','|指標|V5 RESET20|V5.1 RESET20|差 V5.1−V5|','|---|---:|---:|---:|']
    for key,title in [('min_jpy','最小'),('mean_jpy','平均'),('median_jpy','**中央値**'),('max_jpy','最大')]:report.append(f'|{title}|¥{money(a["summary"][key])}|¥{money(b["summary"][key])}|¥{money(D(b["summary"][key])-D(a["summary"][key]))}|')
    report += [f'|200万円到達|0/9（0%）|0/9（0%）|0|',f'|中央値の目標不足|¥{money(a["summary"]["median_gap_to_2m_jpy"])}|¥{money(b["summary"]["median_gap_to_2m_jpy"])}|¥{money(pma-pmb)}|','|予定／完了／coverage不明|21／9／12|21／9／12|同一|',f'\npaired差の中央値は¥{money(median(paired))}。上表の中央値差¥{money(pmb-pma)}と区別する。改善／同値／悪化は{comparison["paired_win_N"]}／{comparison["paired_tie_N"]}／{comparison["paired_loss_N"]}窓。',f'\n最小・最大は上昇した一方、平均・中央値は低下し、最悪MaxDDは{100*D(a["summary"]["max_drawdown_worst"]):.4f}%→{100*D(b["summary"]["max_drawdown_worst"]):.4f}%へ悪化。', '\n![開始日別20営業日終点cash](wealth_reset20.png)', '\n## ✅ 実際に完了した作業\n', '最新HEADと既存Evidenceをactual GET。完全指示書SHA256 `2cb3fbdfb66033373a081a2c60a3a59f01e1db941eb389f5f5e5215b94abbe07`を照合し、旧model/OFF/Oracle/AUC/bootstrapをreuse。V5のコードは原本commitに一致し、Selector／Entry／EXIT・古い負結果を変更していない。', '\n営業日を公式の休日規則・2025年祝日から独立生成。元OOF38の範囲に40営業日、21窓を列挙した。7月11日・14日は休場でも候補0でもなくUNKNOWN_REASON。受領済みV4 manifestは7月14日への言及を含むが、全source完備・凍結Entry処理0の証明にならない。今後同じ探索を反復しない。', '\nreset12テスト、境界3テスト、candidate11テストが通過。人工fixture修復と空JSONL読取りの修復を行ったが、strategyや比較basisを変えず、正式batch再起動は0。保存V5最初の1日でdecision・数量・取引・MTM・日次の完全一致を確認。正式実行は各policy1batch・9窓・180日。独立会計はraw O/C・費用・数量からcash、日次carry、SELL/BUY順、MTM、保有、終点を再構成し、両policyで不一致0。', '\n## 🏷️ R5/R10・既存scoreの診断\n', 'U5/U10のEntry→Highはそのまま保持。Rは現行Capitalの固定EXIT＋EODとBUY1.0005／SELL0.9995にbindingし、100株単体referenceを1回だけmaterializeした。分類はDecimal/Fraction原本、費用は1回のみ。Structural EXITの保存returnは別列。未知はnull。\n','|母集団|N|R known|R unknown|R5|R10|','|---|---:|---:|---:|---:|---:|','|全Frozen Entry|1,039|1,016|23|55|25|','|実行適格|1,028|1,016|12|55|25|','|rank-pass・実行適格|494|492|2|34|16|','\n既存U5=170、U10=67。known U5のうちR5=54・R10=25・Loser=43。known U10のうちR5=37・R10=24・Loser=15。Uは利益化の保証にならない。', '\n旧chain台帳を再利用した捕捉はR5=19/34（55.88%）、R10=11/16（68.75%）。funded precisionは19/150（12.67%）、11/150（7.33%）。これは旧chainの購入品質であり、新しいR予測モデルのaccuracyではない。resetのN・資金・利益寄与は各窓別JSONへ保存し、重複Entryを独立機会として合算しない。\n','|固定score・元の向き|R5 AUROC|R10 AUROC|','|---|---:|---:|']
    diag=read(OUT/'CAPITAL_DIAGNOSTIC.json')
    for h,stats in diag['new_R_score_support']['eligible'].items():report.append(f'|{h}|{stats["R5"]["AUROC"]:.6f}|{stats["R10"]["AUROC"]:.6f}|')
    report += ['\nすべてknownラベルを持つ実行適格1,016件への追加順位診断。元のU5 AUC認証は再実行していない。block別・session別Nと偏りを保存。MRETの向きを反転して救済せず、absolute-loss defenseはINCONCLUSIVEのまま。scoreをR5確率と呼ばない。', '\n![net区分別の投入額・利益寄与](capital_net_bins.png)', '\n## 🔧 唯一の変更機構と最初の実差分\n', '候補V5.1はV5の同じ現在batch・購入ゲート・target・capを使う。各候補に買える最初の100株を既存raw pP順で配り、その後の追加lotを同順でcapまで配分する。従来ML比例のdesired budgetをこの整数数量配分へ置換した。新係数・新閾値・blend・Reserve救済・買い増し・過去Entry復活は0。未知scoreはnative allocationへbatch単位で戻す。', '\n同batchの具体的なcash→追加lot経路は6組（重複window44回）。初回0株を既存残余から水増しするだけの案には発火根拠がなく、その案をReplayしなかった。band capの最低lot未達には、resetで一意2件の経路しかなくR5/R10は0件だったため、単純cap緩和を採用していない。資金が残ることだけで改善とせず、今回の最終資産で判断した。']
    if first:
        report += [f'\n最初の実差分: {first["session"]} {first["minute"]//60:02d}:{first["minute"]%60:02d} JST・{first["window_id"]}。同じEntryの数量 {first["V5_quantity"]}→{first["V51_quantity"]}株、debit ¥{money(first["V5_debit"])}→¥{money(first["V51_debit"])}。時刻順の最初で固定し、好成績例を選んでいない。詳細identityはprivate、公開はSHA256。']
    report += ['\n## ⚠️ 未測定・不確実性・副作用\n', '12窓の欠測を0%で埋めず、途中資産・最後の価格・未決済を正式終点へ置換していない。両policyとも実行対象9窓では未決済・execution block0、片方だけ完了した窓0。12件の将来EXIT/EOD不足はラベルをnullにし、現在購入対象の除外条件には使用していない。11件のcutoff以降Entryは実行不適格として別mask。', '\n重複窓は口座状態が独立なだけで、独立した月次標本ではない。通常CI・有意差は出していない。全期間のR診断を見た後の設計であり、事前commitしてもFresh/OOSに変わらない。元provider到着時刻はUNKNOWNで、既存の想定可用時刻を継承した。', '\n## 💾 保存と次の1手\n', 'V5.1は中央値・平均を改善しなかったため不採用。V5をbaselineとして保持し、V5.2・新model・threshold救済を同cycleへ追加しない。次の1手は7月11日・14日の既存source/universeと凍結Selector/Entry処理完了・0件／除外receiptを回収すること。再生成が必要なら、その不足原本と上流範囲を明示した別Workが必要。', '\n詳細はFINAL_COMPARISON.json、全21窓のCSV、R_LABEL_CENSUS.json、CAPITAL_DIAGNOSTIC.json、INDEPENDENT_ACCOUNTING_AUDIT.json、CURRENT_STATE.jsonに保存。commit/tree/blob/本文のactual GET receiptを最後に追加する。privateラベル・取引台帳は公開GitHubへ載せない。research-only、productionReady=false、実注文・main merge・Claudeはすべて0。']
    (OUT/'REPORT-ja.md').write_text('\n'.join(report)+'\n')
    print({'median_delta':str(pmb-pma),'paired_delta_median':str(median(paired)),'first_difference':first_public,'counts':counts})

if __name__=='__main__':main()
