"""Official research Freeze only after the fixed integrity gates pass."""
from repair_utils import *
import argparse,numpy as np,re
STATUS='PERSISTENT_UPTREND_FIRST_ENTRY_V2_P1_Q70_OFFICIAL_FREEZE'

def run(basis):
 audit=read(HERE/'INDEPENDENT_REPAIR_AUDIT.json');ledger=read(HERE/'CORRECTED_FIT_LEDGER.json');teacher=read(HERE/'CORRECTED_TEACHER_FREEZE_RECEIPT.json');oo=read(HERE/'CORRECTED_OOF_LINEAGE_RECEIPT.json');ev=read(HERE/'P1_Q70_ENTRY_EVALUATION.json');contract=read(HERE/'P1_Q70_ENTRY_CONTRACT.json');scope=read(HERE/'REPAIR_SCOPE_PRECOMMIT.json');rs=list(rows(HERE/'P1_Q70_FIRST_ENTRY_RECORDS.jsonl.gz'))
 gates={'corrected_teacher_identity_fixed':teacher['status']=='CORRECTED_TEACHER_IDENTITY_VERIFIED','additional_fits_exactly20':ledger['fits_completed']==ledger['fits_reserved']==ledger['incremental_hard_cap']==20,'corrected_Q_D20_of20_complete':all(r['status']=='COMPLETED' for r in ledger['runs']) and len(ledger['runs'])==20,'reused_UPSIDE_lineage_unchanged':teacher['U_target_eligibility_unchanged'] and len(teacher['UPSIDE_reuse_lineage'])==10 and ledger['UPSIDE_refits']==0 and all(r['U_prediction_array_unchanged'] and r['U_percentile_array_unchanged'] and r['U_OOF_byte_hash_unchanged'] for r in oo['UPSIDE_reuse']),'corrected_OOF_complete':oo['status']=='CORRECTED_OOF_COMPLETE' and oo['rows_per_family']==223940 and oo['mixed_old_bug_Q_D_predictions']==0,'independent_audit_mismatch0':audit['status']=='PASS' and audit['mismatch_N']==0,'future_causal_leakage0':audit['future_causal_leakage']==0,'P1_Q70_FIRST_ENTRY_success':len(rs)==2155 and sum(r['entry_status']=='FIRST_ENTRY' for r in rs)==ev['Activity']['FIRST_ENTRY_N']>0,'Selector_State_fill_watch_semantics_mismatch0':audit['mismatch_N']==0 and audit['Legacy_State_features']==0,'EXIT_Reentry_Capital0':ev['EXIT_calls']==ev['Reentry_calls']==ev['Capital_replays']==audit['EXIT_calls']==audit['reentry_calls']==audit['Capital_replays']==0}
 if not all(gates.values()):
  write(HERE/'FIRST_ENTRY_V2_FREEZE_RECEIPT.json',{'saved_at_jst':now(),'basis_head':basis,'status':'FIRST_ENTRY_V2_FREEZE_BLOCKED_INTEGRITY','EntryFrozen':False,'gates':gates,'safety':SAFETY});raise SystemExit('FIRST_ENTRY_V2_FREEZE_BLOCKED_INTEGRITY')
 assert scope['Primary_Freeze_Target']==contract['Primary_Freeze_Target']=='P1_Q70' and not scope['candidate_reselection_allowed']
 required=['CORRECTED_TEACHER_FREEZE_RECEIPT.json','CORRECTED_FIT_LEDGER.json','CORRECTED_OOF_LINEAGE_RECEIPT.json','P1_Q70_ENTRY_CONTRACT.json','P1_Q70_FIRST_ENTRY_RECORDS.jsonl.gz','P1_Q70_ENTRY_EVALUATION.json','P1_Q70_SELECTOR_BUCKET_ENTRY_HIGH.json','P1_Q70_PRE_PEAK_MAE_EVIDENCE.json','P1_Q70_PATH_QUALITY_EVIDENCE.json','CORRECTED_REFERENCE_PANEL_P0_Q70_Q95.json','INDEPENDENT_REPAIR_AUDIT.json']
 freeze={'document_id':DOCUMENT_ID,'saved_at_jst':now(),'basis_head':basis,'status':STATUS,'current_status':STATUS,'Primary_Freeze_Target':'P1_Q70','EntryFrozen':True,'productionReady':False,'EXIT_PENDING':True,'REENTRY_PENDING':True,'CAPITAL_PENDING':True,'gates':gates,'teacher_definition_changes':0,'feature_State_split_fill_watch_model_score_threshold_method_changes':0,'Legacy_State_features':0,'historical_completed_fits':30,'new_repair_completed_fits':20,'incremental_fit_hard_cap':20,'cumulative_fit_ledger':50,'UPSIDE_additional_fit':0,'audit_fit':0,'independent_audit_mismatch_N':0,'future_causal_leakage':0,'Entry_N':ev['Activity']['FIRST_ENTRY_N'],'performance_selection_or_extension':0,'searches':0,'provider':0,'protected':0,'EXIT':0,'R50':0,'Reentry':0,'Capital':0,'Portfolio_Replay':0,'orders':0,'main_merge':0,'private_row_level_data_publication':0,'evidence_files':{n:{'bytes':(HERE/n).stat().st_size,'sha256':sha(HERE/n),'visibility':'PRIVATE' if n.endswith('.gz') else 'PUBLIC_SAFE'} for n in required},'stop_after_this_Work':True,'next_separately_authorized_Work':'State-aware EXIT','safety':SAFETY}
 write(HERE/'FIRST_ENTRY_V2_FREEZE_RECEIPT.json',freeze)
 write(HERE/'CURRENT_FIRST_ENTRY_V2_FREEZE.json',{'document_id':DOCUMENT_ID,'saved_at_jst':now(),'basis_head':basis,'current_status':STATUS,'EntryFrozen':True,'productionReady':False,'official_receipt':'FIRST_ENTRY_V2_FREEZE_RECEIPT.json','historical_original_FINAL_STATUS':'../FINAL_STATUS.json remains previous closed blocked Work; corrected20-fit Work supersedes its lineage block','EXIT_PENDING':True,'REENTRY_PENDING':True,'CAPITAL_PENDING':True,'safety':SAFETY})
 activity=ev['Activity'];up=ev['Upside'];buckets=read(HERE/'P1_Q70_SELECTOR_BUCKET_ENTRY_HIGH.json')['buckets'];state=contract['feature_manifest']['state_identity']
 text=[f'# FIRST ENTRY v2 — P1_Q70 Official Freeze\n',f'正式status: **{STATUS}**。`EntryFrozen=true`、`productionReady=false`。\n',f'Work: `{DOCUMENT_ID}`。actual saved_at_jst: `{freeze["saved_at_jst"]}`。actual basis_head: `{basis}`。\n',
 'Primaryは結果を見る前に固定したP1_Q70。P0はState9なしcontrol、Q80/Q90/Q95は既存selectivity referenceとして保持した。再選択・Entry/day調整・State incremental研究の再開は0。旧WorkのBLOCKと旧30 fitsは履歴として保持し、今回のcorrected-lineage Workで修復した。\n',
 'calendar bugのexact root causeは、`source_starts`がAM continuous → PM continuous → AM terminal690の順になり、unsorted arrayとのchronology比較で正常なAM→PM pathをmissingと誤判定したこと。修復は`sorted(regular_starts(day)+[690,close_minute(day)])`のみ。133 sessionでscheduled source bar集合・個数の一致を独立確認した。\n',
 '| 修復・lineage | 結果 |\n|---|---:|\n| teacher定義変更 | 0 |\n| Q NULL→known | 13,948 |\n| D NULL→known | 13,948 |\n| 元finite Q/Dの値変更 | 各0 |\n| U target / training mask変更 | 0 |\n| P0 QUALITY / ADVERSE | 各5 fits完了 |\n| P1 QUALITY / ADVERSE | 各5 fits完了 |\n| 今回追加fit | 20/20 |\n| historical / cumulative | 30 / 50 |\n| UPSIDE追加fit | 0 |\n| UPSIDE既存fit reuse | 10 |\n| audit fit | 0 |\n| 独立監査 mismatch / future leakage | 0 / 0 |\n| Legacy State feature | 0 |\n',
 '20 fitsだけでよい理由は、calendar bugがQ/Dのpath-completeness eligibilityだけに影響したため。2 families ×2 affected heads ×5 folds =20。U target・training maskは全行不変で、既存10モデル・preprocessor・training prediction referenceのSHA、2本のUPSIDE OOFファイルのbyte SHA、全OOF U prediction / percentileの一致を確認した。証明は[corrected teacher receipt](CORRECTED_TEACHER_FREEZE_RECEIPT.json)、[fit ledger](CORRECTED_FIT_LEDGER.json)、[OOF lineage receipt](CORRECTED_OOF_LINEAGE_RECEIPT.json)に保存した。\n',
 f'P1はP0 price/volume/path/Selector context + exact latest frozen RC2 State9 current +同じRC2のpast-only history。RC2 contract SHA `{state["contract_sha256"]}`、profile SHA `{state["profile_sha256"]}`、Path SHA `{state["path_contract_sha256"]}`。110 P0 numeric /148 P1 numeric /15 P1 categoricalをそのまま使用し、Legacy Stateは0。\n',
 f'独立監査は{audit["total_checks"]:,} checks、grid/teacher各{audit["grid_rows_checked"]:,}行、FIRST ENTRY records {audit["FIRST_ENTRY_records_checked"]:,}件を検査した。Stateの別kernel確認は事前固定51-watch sample /{audit["independent_state_rows_checked"]:,}行、model direct predictionは{audit["model_prediction_samples_checked"]:,} samples。percentile・threshold・train-only preprocessingは全対象行を確認。\n',
 '| P1_Q70 Activity / Entry単体品質 | 値 | evaluable N |\n|---|---:|---:|\n',
 f'| FIRST ENTRY / watch | {activity["FIRST_ENTRY_N"]:,} / {activity["watch_N"]:,} | 58 sessions |\n| 平均 / 中央値Entry per session | {activity["mean_Entry_per_session"]:.6f} / {activity["median_Entry_per_session"]:.0f} | 58 |\n| Entry rate | {activity["Entry_rate_pct"]:.6f}% | 2,155 |\n| 0 Entry sessions | {activity["zero_Entry_session_N"]} | 58 |\n| Selector→Entry delay中央値 | {activity["Selector_to_Entry_delay_active_min_median"]:.0f} active min | 1,600 |\n| Entry→strictly-later High中央値 | {up["Entry_to_strictly_later_High"]["median"]:.6f}% | {up["Entry_to_strictly_later_High"]["N"]} |\n| Upside Retention中央値 | {up["Upside_Retention_pct"]["median"]:.6f}% | {up["Upside_Retention_pct"]["N"]} |\n| Pre-peak MAE中央値 | {ev["Pre_peak_MAE_abs_pct"]["median"]:.6f}% | {ev["Pre_peak_MAE_abs_pct"]["N"]} |\n| Path Efficiency中央値 | {ev["Path_Efficiency"]["median"]:.6f} | {ev["Path_Efficiency"]["N"]} |\n',
 f'MAE / Path Efficiencyはcomplete pre-peak path {ev["path_evaluable_N"]}件だけの中央値。path unknown {ev["path_unknown_N"]}件、strictly-later High unknown {ev["remaining_high_unknown_N"]}件を分離し、補間していない。保存sourceがpartialなEntry→Highはobserved Highまでの値幅であり、完全session Highに対する下限となり得る。Retentionはpositiveなsaved first-selector future MFEを分母とする。これらの性能値はFreeze最適化Gateに使用していない。\n',
 '| Selector→High exclusive bucket | watch N | Entry N | Entry→High中央値 |\n|---|---:|---:|---:|\n']
 for b in ['1–<2%','2–<3%','3–<4%','4–<5%','>=5%']:
  z=buckets[b];text.append(f'| {b} | {z["watch_N"]} | {z["Entry_N"]} | {z["Entry_to_High_pct"]["median"]:.6f}% |\n')
 text+=['\nSelector→High bucketはfuture evaluatorの分類で、Entry decision featureではない。\n','| 累積Selector winner | denominator | Entry | no-entry | confirmed same-threshold hit | unknown | Capture参考 |\n|---|---:|---:|---:|---:|---:|---:|\n']
 for k in range(1,6):
  z=ev['Capture_reference'][str(k)];text.append(f'| >={k}% | {z["selector_winner_denominator"]} | {z["FIRST_ENTRY_N"]} | {z["no_entry_N"]} | {z["entry_after_same_threshold_hit_N"]} | {z["unknown_N"]} | {z["capture_rate_pct"]:.6f}% |\n')
 text+=['\nCaptureはconfirmed same-threshold hit / all Selector winner denominator。no-entry / unknownをdenominatorから除外していない。参考値として保存し、policyを再選択していない。\n',
 'Frozen state machine: first valid Selector → same-session persistent watch → observed closed1mごとP1 score → Q70最初のcross → BUY_INTENT → canonical next available regular raw open +5bps → FIRST ENTRY → このWorkではwatch評価終了。WATCH_KEY=session|symbol、repeat Selectorはrefresh、30分expiryなし、lunchはactive clockに加えない、FIRST ENTRY後decision停止。\n',
 '監査準備時にP1 subset gzipの不完全な保存を検出し、完全なcorrected Q70 recordsから同一2,155 recordsをatomicに保存して内容一致を確認した。また監査のhistorical ledgerとactive-model ledgerの比較条件を分離した。teacher・features・モデル・score・threshold・record値の変更は0、追加fitは0。[serialization receipt](RECORDS_SERIALIZATION_RECEIPT.json)、[audit checker receipt](AUDIT_CHECKER_LINEAGE_VIEW_RECEIPT.json)に記録した。\n',
 'OFFICIAL FREEZEの10 integrity gatesは全PASS。**PERSISTENT_UPTREND_FIRST_ENTRY_V2_P1_Q70_OFFICIAL_FREEZEに到達した。** [formal Freeze receipt](FIRST_ENTRY_V2_FREEZE_RECEIPT.json)と[independent audit](INDEPENDENT_REPAIR_AUDIT.json)が正式Evidence。\n',
 'EXIT / R50 / Re-entry / Capital / Portfolio Replay / provider / Protected-Fresh-Validation-OOS-Prospective open / orders / main mergeはすべて0。MAE p75/p90/p95、hard-stop、-1% Risk Line、bootstrap、全searchも0。executionAllowed / brokerWriteAllowed / excelOrderWriteAllowed / rssOrderFunctionAllowed / liveTradingAllowed / paperTradingAllowed / automaticPromotionAllowed / productionUpdateAllowed / transmitted / productionReadyはすべてfalse。\n',
 'Entry研究はここで閉じてSTOP。EXIT_PENDING=true、REENTRY_PENDING=true、CAPITAL_PENDING=true。次の別WorkはState-aware EXIT。Pre-peak MAE中央値はFrozen Entry Evidenceとして引き継ぐ。今回のWorkからEXIT / Re-entry / Capitalへ自動進行していない。\n']
 (HERE/'FIRST_ENTRY_V2_FREEZE_HANDOFF.md').write_text(re.sub(r'(?m)(^\|[^\n]*\|\n)\n+(?=\|)',r'\1','\n'.join(text)))
 print(json.dumps({'status':STATUS,'EntryFrozen':True,'productionReady':False,'all_gates_PASS':True,'new_fits':20,'audit_mismatch_N':0,'future_causal_leakage':0}))

if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--basis-head',required=True);run(p.parse_args().basis_head)
