import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {CONTRACT,CONTRACT_SHA256,FEATURES,SAFETY,selectionSchedule,buildDirectionFeatures,MinimalStatefulEntry,scoreLogistic,decideNow,attachPrimaryTarget,validationAdmission} from '../lib/phase57-minimal-stateful-entry.mjs';
const date='2026-09-10',iso=t=>new Date(t).toISOString(),start=Date.parse(`${date}T09:00:00+09:00`);
const bars=n=>Array.from({length:n},(_,i)=>({timestamp:iso(start+i*300000),availableAt:iso(start+(i+1)*300000),open:100+i,high:102+i,low:99+i,close:101+i,volume:100+i}));
const time=n=>iso(start+n*300000);
const candidate=n=>({symbol:'7203.T',rank:2,score:0.3,priceReference:bars(n).at(-1).close});
const snap=(n,selected=[candidate(n)],complete=true)=>({decisionTimestamp:time(n),complete,selected,selectorModelDigest:CONTRACT.selectorModelDigest,selectorFreezeSHA:CONTRACT.selectorFreezeSHA,sourceClass:'SYNTHETIC_CONTRACT_TEST'});
const params=(n=7,direction=1)=>({symbol:'7203.T',decisionTimestamp:time(n),bars:bars(n),rank:2,score:0.3,priceReference:bars(n).at(-1).close,firstSelectionTimestamp:time(7),priorSelectionCount:n-7,direction});
const model=()=>({artifactClass:'SYNTHETIC_CONTRACT_TEST',contractSha256:CONTRACT_SHA256,features:[...FEATURES],weights:FEATURES.map(k=>k==='direction'?1:0),means:FEATURES.map(()=>0),scales:FEATURES.map(()=>1),intercept:0,threshold:0.6});
const pair=()=>[1,-1].map(d=>buildDirectionFeatures(params(7,d)));
test('one architecture, ten frozen features, P21 only fallback',()=>{assert.equal(FEATURES.length,10);assert.equal(CONTRACT.model.architecture,'SHARED_L2_LOGISTIC_REGRESSION');assert.equal(CONTRACT.limits.additionalChallengersAllowed,false);assert.equal(CONTRACT.limits.fallback,'UNCHANGED_EXISTING_P21');assert.throws(()=>CONTRACT.features.push('RSI'));});
test('all nine safety flags false',()=>assert.deepEqual(Object.values(SAFETY),Array(9).fill(false)));
test('schedule is66 regular decisions, not inferred fresh calendar',()=>{const s=selectionSchedule(date);assert.equal(s.length,66);assert.equal(s[29],`${date}T02:30:00.000Z`);assert.equal(s[30],`${date}T03:35:00.000Z`);});
test('feature direction transforms shared inputs, state features same',()=>{const [a,b]=pair();assert.equal(a.features.directionalMomentum3Pct,-b.features.directionalMomentum3Pct);assert.equal(a.features.relativeVolume5,b.features.relativeVolume5);assert.equal(a.features.hybridReciprocalRank,0.5);});
test('same input deterministic feature freeze',()=>assert.deepEqual(buildDirectionFeatures(params()),buildDirectionFeatures(params())));
test('future completed bar is rejected',()=>assert.throws(()=>buildDirectionFeatures({...params(),bars:bars(8)}),/NON_PIT/));
test('future availability is rejected',()=>{const p=params();p.bars[0].availableAt=time(8);assert.throws(()=>buildDirectionFeatures(p),/NON_PIT/);});
test('missing official open blocks, does not substitute observed open',()=>{const p=params(8);p.bars.shift();assert.throws(()=>buildDirectionFeatures(p),/OPEN_MISSING/);});
test('missing recent slot blocks without padding',()=>{const p=params(9);p.bars.splice(-3,1);assert.throws(()=>buildDirectionFeatures(p),/GRID_GAP/);});
test('stale completed prefix blocks',()=>assert.throws(()=>buildDirectionFeatures({...params(8),bars:bars(7),priceReference:107}),/STALE/));
test('duplicate bar rejected',()=>{const p=params(8);p.bars[1]=p.bars[0];assert.throws(()=>buildDirectionFeatures(p),/GRID/);});
test('cross-session bar rejected',()=>{const p=params();p.bars[0].timestamp='2026-09-09T00:00:00Z';assert.throws(()=>buildDirectionFeatures(p),/GRID/);});
test('invalid OHLC rejected',()=>{const p=params();p.bars[0].low=200;assert.throws(()=>buildDirectionFeatures(p),/OHLCV/);});
test('zero volume denominator blocks, not substituted1',()=>{const p=params();p.bars.forEach(b=>b.volume=0);assert.throws(()=>buildDirectionFeatures(p),/DENOMINATOR/);});
test('outcome column rejected before feature construction',()=>{const p=params();p.bars[0].futureReturn=1;assert.throws(()=>buildDirectionFeatures(p),/OUTCOME/);});
test('future state timestamp rejected',()=>assert.throws(()=>buildDirectionFeatures({...params(),firstSelectionTimestamp:time(8)}),/FUTURE_SELECTION/));
test('price semantics preserved',()=>assert.throws(()=>buildDirectionFeatures({...params(),priceReference:1}),/PRICE_REFERENCE/));
test('model absence means WATCH',()=>assert.equal(decideNow(pair(),null).reason,'MODEL_UNAVAILABLE'));
test('real or untagged artifact blocked without training authority',()=>assert.throws(()=>scoreLogistic(pair()[0],model()),/NO_AUTHORIZED_TRAINING/));
test('state engine rejects real model before any state mutation',()=>assert.throws(()=>new MinimalStatefulEntry(date,{model:model()}),/NO_AUTHORIZED_TRAINING/));
test('constructor freezes a private model copy',()=>{const m=model(),s=new MinimalStatefulEntry(date,{model:m,syntheticContractTest:true});m.threshold=1;assert.equal(s.model.threshold,0.6);assert.throws(()=>s.model.weights.push(1));});
test('synthetic shared logistic score is exact and directional',()=>{const r=decideNow(pair(),model(),{syntheticContractTest:true});assert.equal(r.action,'ENTER');assert.equal(r.direction,1);assert.equal(r.probability,1/(1+Math.exp(-1)));});
test('exact directional ties WATCH, never arbitrary LONG',()=>{const m=model();m.weights.fill(0);assert.equal(decideNow(pair(),m,{syntheticContractTest:true}).reason,'DIRECTION_TIE');});
test('threshold equality is WATCH',()=>{const m=model();m.threshold=1/(1+Math.exp(-1));assert.equal(decideNow(pair(),m,{syntheticContractTest:true}).action,'WATCH');});
test('model feature order cannot drift',()=>{const m=model();m.features.reverse();assert.throws(()=>scoreLogistic(pair()[0],m,{syntheticContractTest:true}),/CONTRACT_MISMATCH/);});
test('zero scaler rejected',()=>{const m=model();m.scales[0]=0;assert.throws(()=>scoreLogistic(pair()[0],m,{syntheticContractTest:true}),/PARAMETERS/);});
test('changed frozen features rejected',()=>{const r=structuredClone(pair()[0]);r.features.direction=9;assert.throws(()=>scoreLogistic(r,model(),{syntheticContractTest:true}),/FREEZE_MISMATCH/);});
test('UNSEEN toWATCHING thenEXPIRED on complete absence',()=>{const s=new MinimalStatefulEntry(date);assert.equal(s.step(snap(7),{'7203.T':bars(7)}).events[0].stateAfter,'WATCHING');s.step(snap(8,[]));assert.equal(s.states.get('7203.T').state,'EXPIRED');});
test('missing snapshot never implies selection absence',()=>{const s=new MinimalStatefulEntry(date);s.step(snap(7),{'7203.T':bars(7)});s.step(snap(8,[],false));assert.equal(s.states.get('7203.T').state,'WATCHING');});
test('EXPIRED remains terminal if symbol later reappears',()=>{const s=new MinimalStatefulEntry(date);s.step(snap(7),{'7203.T':bars(7)});s.step(snap(8,[]));const r=s.step(snap(9),{'7203.T':bars(9)}).events[0];assert.equal(r.stateAfter,'EXPIRED');assert.equal(r.decision.action,'NO_ACTION');assert.equal(r.priorSelectionCount,1);});
test('ENTERED can never reenter during same session',()=>{const s=new MinimalStatefulEntry(date,{model:model(),syntheticContractTest:true});assert.equal(s.step(snap(7),{'7203.T':bars(7)}).events[0].decision.action,'ENTER');const r=s.step(snap(8),{'7203.T':bars(8)}).events[0];assert.equal(r.decision.action,'NO_ACTION');assert.equal(r.entryCount,1);});
test('WATCHING re-evaluates next selected snapshot',()=>{const s=new MinimalStatefulEntry(date);s.step(snap(7),{'7203.T':bars(7)});const r=s.step(snap(8),{'7203.T':bars(8)}).events[0];assert.equal(r.selectionIndex,2);assert.equal(r.minutesSinceFirstSelection,5);assert.ok(r.directionFeatures);});
test('feature block is diagnostic, not learned reject class',()=>{const s=new MinimalStatefulEntry(date);const r=s.step(snap(7),{}).events[0];assert.equal(r.stateAfter,'WATCHING');assert.equal(r.decision.reason,'BLOCKED_FEATURES');});
test('session close expires unentered and rejects later updates',()=>{const s=new MinimalStatefulEntry(date);s.step(snap(7),{'7203.T':bars(7)});s.close(`${date}T06:30:00Z`);assert.equal(s.states.get('7203.T').state,'EXPIRED');assert.throws(()=>s.step(snap(8)),/CLOSED/);});
test('duplicate point and membership are rejected',()=>{const s=new MinimalStatefulEntry(date);assert.throws(()=>s.step(snap(7,[candidate(7),candidate(7)])),/DUPLICATE_SELECTION/);s.step(snap(7),{'7203.T':bars(7)});assert.throws(()=>s.step(snap(7)),/DUPLICATE/);});
test('selector freeze mismatch blocked',()=>{const x=snap(7);x.selectorModelDigest='wrong';assert.throws(()=>new MinimalStatefulEntry(date).step(x),/FREEZE/);});
test('no P21 input is needed for selected-event dataset',()=>{const r=new MinimalStatefulEntry(date).step(snap(7),{'7203.T':bars(7)}).events[0];assert.equal(r.p21UsedAsGate,false);assert.equal(r.directionFeatures.length,2);});
const targetBundle=r=>({eventId:`${r.sessionDate}|${r.decisionTimestamp}|${r.symbol}`,contractSha256:CONTRACT_SHA256,featureSha256:r.featureSha256,featureFrozenBeforeLabels:true,roundTripCostBps:5,horizons:{3:{complete:true,barStarts:[time(7),time(8),time(9)],outcomeAvailableAt:time(10),LONG:{grossReturnBps:5,netReturnBps:0},SHORT:{grossReturnBps:-5,netReturnBps:-10}}}});
test('zero net is negative binary class',()=>{const r=pair()[0];assert.equal(attachPrimaryTarget(r,targetBundle(r)).target,0);});
test('missing target is null, not negative class',()=>{const r=pair()[0],b=targetBundle(r);b.horizons[3].complete=false;assert.equal(attachPrimaryTarget(r,b).target,null);});
test('cross-event or future-grid target rejected',()=>{const r=pair()[0],b=targetBundle(r);b.horizons[3].barStarts[0]=time(6);assert.throws(()=>attachPrimaryTarget(r,b),/GRID/);});
test('target cost mismatch rejected',()=>{const r=pair()[0],b=targetBundle(r);b.horizons[3].LONG.netReturnBps=1;assert.throws(()=>attachPrimaryTarget(r,b),/COST/);});
test('all flags cannot launder empty training allocation',()=>assert.equal(validationAdmission({trainingDatasetIds:['claimed'],modelFrozen:true,thresholdFrozen:true,independentReviewPassed:true,accessLedgerComplete:true,winnerRuleFrozen:true}).allowed,false));
test('fresh15 andOOS10 are disjoint reservations, never training',()=>{const a=JSON.parse(fs.readFileSync(new URL('../../predict/research/phase57-minimal-stateful-entry-fresh-allocation.json',import.meta.url)));assert.equal(a.FRESH_ENTRY_VALIDATION.length,15);assert.equal(a.RESERVED_ENTRY_OOS.length,10);assert.equal(new Set([...a.FRESH_ENTRY_VALIDATION,...a.PURGE_EMBARGO,...a.RESERVED_ENTRY_OOS]).size,26);assert.equal(a.trainingSessionIds.length,0);assert.equal(a.validationStartAllowed,false);assert.ok([...a.FRESH_ENTRY_VALIDATION,...a.RESERVED_ENTRY_OOS].every(d=>!a.calendarExclusionsInWindow.includes(d)));});
