import test from 'node:test';
import assert from 'node:assert/strict';
import {summarizeManagementReadiness as audit, combineManagementReadiness as combine, managementIntegrity as gate, isTransientDiagnosticFailure as retry} from '../lib/phase57-exit-v4-20session-runtime.mjs';
const scored = n => ({baseScore:{ready:true, stateBucket:'WINNER_PROTECTION', neighborCount:n}});
const warmup = {baseScore:{ready:false, reason:'STATE_NOT_READY'}};
const neutral = {baseScore:{ready:true, stateBucket:'NEUTRAL_HOLD', neighborCount:0}};
const insufficient = {baseScore:{ready:false, reason:'INSUFFICIENT_STATE_CONDITIONED_CAUSAL_ANALOGS', neighborCount:0}};
test('warmup is recorded, not treated as zero causal neighbors', () => { const a=audit([warmup,scored(80)]);assert.equal(a.warmup,1);assert.equal(a.minimumScoredNeighbors,80);assert.equal(gate(a,1),'SCORING_READY'); });
test('neutral HOLD needs no neighbor lookup', () => {const a=audit([neutral,scored(77)]);assert.equal(a.neutral,1);assert.equal(a.minimumScoredNeighbors,77);});
test('real insufficient analogs still block', () => assert.equal(gate(audit([insufficient,scored(80)]),1),'INTEGRITY_BLOCKED'));
test('ready with fewer than 30 neighbors blocks', () => assert.equal(gate(audit([scored(29)]),1),'INTEGRITY_BLOCKED'));
test('ready with missing neighbor count blocks', () => assert.equal(gate(audit([scored(undefined)]),1),'INTEGRITY_BLOCKED'));
test('unrecognized scorer failure blocks', () => assert.equal(gate(audit([{baseScore:{ready:false,reason:'BLOCKED_V2_EMPTY_ANALOG_POOL'}}]),1),'INTEGRITY_BLOCKED'));
test('zero trades is capacity low, not weak Entry', () => assert.equal(gate(audit([]),0),'CAPACITY_LOW'));
test('only warmup and neutral is capacity low', () => assert.equal(gate(audit([warmup,neutral]),1),'CAPACITY_LOW'));
test('aggregation preserves counts and actual minimum', () => {const a=combine([audit([warmup,scored(80)]),audit([neutral,scored(77)])]);assert.equal(a.total,4);assert.equal(a.scored,2);assert.equal(a.minimumScoredNeighbors,77);assert.equal(a.neutral,1);});
test('no scored minimum remains null', () => assert.equal(combine([audit([neutral])]).minimumScoredNeighbors,null));
for (const message of ['JQUANTS_HTTP_503','RATE_LIMITED','TypeError: fetch failed','ECONNRESET']) test(`bounded retry classifier: ${message}`, () => assert.equal(retry(message),true));
for (const message of ['AUTH_REJECTED','BLOCKED_ENTITLEMENT','AssertionError: SHA_MISMATCH\nTypeError: fetch failed','SESSION_NOT_ALLOCATED','CAUSAL_NEIGHBOR_GATE_FAILED','unexpected implementation error']) test(`no retry: ${message}`, () => assert.equal(retry(message),false));
