import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {normalizeBar,CausalBars,SymbolSlots,Bar5Manager,EvidenceLog,compareRecords,cumulative,captureHealth,verifyFreeze,SAFETY,exposedDate,reconstructEntryEvent} from '../lib/phase57-offline-parity.mjs';
import {createOfflineShadowLedger} from '../lib/phase57-offline-shadow-ledger.mjs';
import {simulatePhaseB} from '../lib/phase57-capital-allocation-v3-phase-b.mjs';
import {compareDay,STAGES} from '../lib/phase57-parity-report.mjs';
import {FREEZE} from '../lib/phase57-offline-parity.mjs';
const t=n=>new Date(Date.parse('2026-08-13T00:00:00Z')+n*300000).toISOString();
const raw=(n=0)=>({symbol:'0000.T',sourceDate:'2026-08-13',sourceTime:`09:${String(n*5).padStart(2,'0')}:00`,open:100,high:102,low:99,close:101,volume:1000,captureAt:t(n+1),availableAt:t(n+1),finalized:true});
const norm=(r=raw())=>normalizeBar(r,{label:'START',decisionTimestamp:r.captureAt});
test('freeze, safety and reserved/future dates remain locked',()=>{verifyFreeze(process.cwd());assert.ok(Object.values(SAFETY).every(x=>x===false));for(const date of ['2026-09-10','2026-10-21','2026-10-22','2026-01-07'])assert.throws(()=>exposedDate(date));assert.throws(()=>normalizeBar(raw(),{label:'START',decisionTimestamp:t(1),fixture:false}));});
test('START/END normalization retains raw labels and availability',()=>{const a=norm(),b=normalizeBar({...raw(),sourceTime:'09:05:00'},{label:'END',decisionTimestamp:t(1)});assert.equal(a.timestamp,b.timestamp);assert.equal(a.barEnd,t(1));assert.equal(a.sourceTime,'09:00:00');assert.equal(b.sourceTime,'09:05:00');});
test('forming, future, timezone-free and unavailable bars fail closed',()=>{for(const change of [{finalized:false},{captureAt:t(0)},{availableAt:t(2)},{captureAt:'2026-08-13T09:05:00'},{sourceTime:'09:03:00'}])assert.throws(()=>norm({...raw(),...change}));assert.throws(()=>normalizeBar(raw(),{label:'UNKNOWN',decisionTimestamp:t(1)}));});
test('malformed cells never become zero',()=>{for(const close of ['',null,'100','#N/A',NaN,Infinity,-1])assert.throws(()=>norm({...raw(),close}));});
test('lunch/close grid rejects synthetic bars and permits last complete bar',()=>{for(const sourceTime of ['11:30:00','12:00:00','15:30:00'])assert.throws(()=>norm({...raw(),sourceTime,captureAt:'2026-08-13T07:00:00Z',availableAt:'2026-08-13T07:00:00Z'}));assert.equal(norm({...raw(),sourceTime:'15:25:00',captureAt:'2026-08-13T06:30:00Z',availableAt:'2026-08-13T06:30:00Z'}).barEnd,'2026-08-13T06:30:00.000Z');});
test('duplicate snapshots retain earliest availability; revisions fail closed',()=>{const c=new CausalBars();assert.equal(c.add(norm()),true);assert.equal(c.add(norm({...raw(),captureAt:t(2)})),false);assert.equal(c.prefix('0000.T',t(1)).length,1);assert.throws(()=>c.add(norm({...raw(),close:100})));assert.equal(c.prefix('0000.T',t(0)).length,0);});
test('slot assignment is stable, dynamic, atomic on capacity failure, rejects stale epochs',()=>{const s=new SymbolSlots(2);s.assign(['1234','5678']);const original=structuredClone(s.slots);assert.throws(()=>s.assign(['1234','5678','9999']));assert.deepEqual(s.slots,original);s.assign(['1234','9999']);s.verify(0,'1234',1);assert.throws(()=>s.verify(1,'5678',1));assert.throws(()=>s.assign(['1234','1234']));});
function manager(direction=1){return new Bar5Manager({eventId:'x',symbol:'0000.T',direction,entryPrice:100,entryTimestamp:t(0)});}
function advance(m,values,{native=values.length}={}){return values.map((ret,i)=>{const timestamp=t(i+1);return m.step({timestamp,close:100*(1+m.direction*ret/100),v4:{timestamp,action:i+1===native?'EXIT':'HOLD',exitPrice:100*(1+m.direction*ret/100),exitReason:'V4_NATIVE'}});});}
test('bar5 directional symmetry; bar6 cannot repair adverse bar5',()=>{for(const direction of [1,-1]){const m=manager(direction),rows=advance(m,[-1,-.5,-.5,-.5,-.25],{native:9});assert.equal(rows.at(-1).decision.exitReason,'DEFENSIVE_EXIT_BAR_5');assert.throws(()=>m.step({timestamp:t(6),close:110,v4:{timestamp:t(6),action:'HOLD'}}));}});
test('reclaim exactly zero on bar5 restores v4 continuation',()=>{const m=manager();const rows=advance(m,[-1,-.5,-.5,-.5,0],{native:9});assert.equal(rows.at(-1).state,'RECOVERED_TO_V4');assert.equal(rows.at(-1).decision,null);});
test('native v4 early exit preserves fallback and no extra cost field',()=>{const r=advance(manager(),[-1,-.5,-.2]).at(-1);assert.equal(r.decision.classification,'HORIZON_FALLBACK_V4');assert.equal(r.decision.exitReason,'V4_NATIVE');assert.ok(!('netReturnPct' in r.decision));});
test('non-adverse continuation and absent/future v4 decision rejection',()=>{assert.equal(advance(manager(),[0,1]).at(-1).state,'FIRST_BAR_NON_ADVERSE_V4');assert.throws(()=>manager().step({timestamp:t(1),close:100}));assert.throws(()=>manager().step({timestamp:t(1),close:100,v4:{timestamp:t(2),action:'HOLD'}}));assert.throws(()=>manager().step({timestamp:t(2),close:100,v4:{timestamp:t(2),action:'HOLD'}}));});
test('feature prefix gaps and unavailable closes fail closed',()=>{const bars=Array.from({length:7},(_,n)=>norm(raw(n)));const e={symbol:'0000.T',sessionDate:'2026-08-13',decisionTimestamp:t(7),hybridRank:1,hybridScore:.7,firstSelectionTimestamp:t(1),priorSelectionCount:2};const ok=reconstructEntryEvent(e,bars);assert.equal(Object.keys(ok.directionFeatures[0].features).length,10);assert.throws(()=>reconstructEntryEvent(e,bars.slice(1)));assert.throws(()=>reconstructEntryEvent(e,bars.map((b,i)=>i===6?{...b,availableAt:t(8)}:b)));});
test('ledger has exact same input parity and 12 unchanged invariants',()=>{
  const opportunities=[{eventId:'a',symbol:'1000.T',sessionDate:'2026-08-13',decisionTimestamp:t(1),direction:-1,entryPrice:100,mshScore:.8,recentRealizedVolatility:.01,outcomeUsed:false,exitUsed:false},{eventId:'b',symbol:'2000.T',sessionDate:'2026-08-13',decisionTimestamp:t(2),direction:1,entryPrice:100,mshScore:.8,recentRealizedVolatility:.02,outcomeUsed:false,exitUsed:false}];
  const trades=opportunities.map((o,i)=>({eventId:o.eventId,symbol:o.symbol,direction:o.direction,causalEligible:true,v4:{exitTimestamp:t(i+2),exitPrice:i?101:99,exitReason:'V4_NATIVE',barsHeld:1}}));
  const marks=[{symbol:'1000.T',timestamp:t(1),sessionDate:'2026-08-13',close:100},{symbol:'1000.T',timestamp:t(2),sessionDate:'2026-08-13',close:99},{symbol:'2000.T',timestamp:t(2),sessionDate:'2026-08-13',close:100},{symbol:'2000.T',timestamp:t(3),sessionDate:'2026-08-13',close:101}];
  const ref=simulatePhaseB({opportunities,trades,marks,allocationId:'V3_B_RISK',exitId:'FROZEN_EXIT_V4',budgetDivisor:3});const l=createOfflineShadowLedger();for(let n=1;n<=3;n++)l.step({timestamp:t(n),sessionDate:'2026-08-13',marks:marks.filter(x=>x.timestamp===t(n)),entries:opportunities.filter(x=>x.decisionTimestamp===t(n)),exitDecisions:trades.filter(x=>x.v4.exitTimestamp===t(n)).map(x=>({eventId:x.eventId,...x.v4}))});const actual=l.snapshot();assert.deepEqual(actual.ledgerTrace,ref.ledgerTrace);assert.deepEqual(actual.closedTrades,ref.closedTrades);assert.deepEqual(actual.decisions,ref.decisions);assert.equal(Object.keys(actual.ledgerTrace[0].invariants).length,12);assert.equal(actual.ledgerTrace[1].entries[0].shortSaleProceedsCreditedJpy,0);assert.equal(actual.closedTrades[0].transactionCostsJpy,165);
});
test('ledger stops permanently on malformed input; never continues with partial state',()=>{const l=createOfflineShadowLedger();assert.throws(()=>l.step({timestamp:t(1),sessionDate:'2026-08-13',entries:[],exitDecisions:[],marks:[{symbol:'1000.T',close:NaN}]}));assert.equal(l.snapshot().halted,true);assert.throws(()=>l.step({timestamp:t(2)}),/LEDGER_HALTED/);});
test('evidence resume preserves chain, simultaneous writers and torn tails fail closed',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ark-evidence-'));const file=path.join(dir,'evidence.jsonl');try{const a=new EvidenceLog(file);a.append('FIRST',{ok:true});assert.throws(()=>new EvidenceLog(file));a.close();const b=new EvidenceLog(file);assert.equal(b.sequence,1);b.append('SECOND',{ok:false});b.close();const before=fs.readFileSync(file,'utf8');fs.appendFileSync(file,'{');assert.throws(()=>new EvidenceLog(file),/TORN_EVIDENCE_TAIL/);assert.equal(fs.readFileSync(file,'utf8'),before+'{');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('comparator reports missing coverage, one cause per difference, null empty rates',()=>{const x=compareRecords([{id:'a',x:1}],[{id:'a',x:2},{id:'b',x:3}],{stage:'LEDGER'});assert.equal(x.denominator,2);assert.deepEqual(x.mismatches.map(x=>x.primaryCause),['LEDGER_IMPLEMENTATION_DIFFERENCE','MISSING_RSS_DATA']);assert.equal(compareRecords([],[],{stage:'DATA'}).exactMatchRate,null);const y=compareRecords([{id:'a',x:1}],[{x:1,id:'a'}],{stage:'DATA'});assert.equal(y.exact,1);assert.equal(cumulative([{stages:[y]},{stages:[y]}]).DATA.denominator,2);});
test('health classifies disconnect, closed workbook, stale cells and sleep; lunch is idle',()=>{const base={now:t(2),msiiConnected:true,workbookHealthy:true,rssError:false,latestAvailableAt:t(2),lastPollAt:t(2)};assert.equal(captureHealth(base).requiredDataHealthy,true);for(const change of [{msiiConnected:false},{workbookHealthy:false},{rssError:true},{lastPollAt:t(0)},{latestAvailableAt:t(0)}])assert.equal(captureHealth({...base,...change}).requiredDataHealthy,false);assert.equal(captureHealth({...base,now:'2026-08-13T03:00:00Z'}).healthStatus,'SCHEDULED_IDLE');assert.equal(captureHealth(base).strategyDecisionAllowed,false);});
test('six-stage report measures time/price/equity differences without filling missing rates',()=>{const base={sessionDate:'2026-08-13',sourceClass:'SYNTHETIC_TRANSPORT_TEST',freezeSha256:FREEZE,...Object.fromEntries(STAGES.map(k=>[k,[]]))};base.ENTRY=[{id:'first',action:'ENTER',symbol:'0000.T',direction:1,timestamp:t(1),probability:.7,features:{a:1},referencePrice:100}];base.LEDGER=[{id:'close',timestamp:t(3),equityJpy:1000000,realizedPnlJpy:0}];const left=structuredClone(base);left.ENTRY[0].timestamp=t(2);left.ENTRY[0].referencePrice=101;left.LEDGER[0].equityJpy=1000100;left.LEDGER[0].realizedPnlJpy=100;const r=compareDay(left,base);assert.equal(r.metrics.entryTimestampDelta.max,300000);assert.equal(r.metrics.entryReferencePriceDelta.median,1);assert.equal(r.metrics.shadowEquityDeltaJpy,100);assert.equal(r.metrics.selectorSetMatchRate,null);assert.equal(r.metrics.firstEnterExactMatchRate,0);assert.equal(r.metrics.directionMatchRate,1);assert.throws(()=>compareDay({...left,sessionDate:'2026-10-22'},base));});
test('known used sparse path is disclosed and cannot imply strict-grid readiness',()=>{const identity='4dd18c66586706aebc19775c718d0fca2fb1ac569d40e8746f85aae502a44a70';const m=new Bar5Manager({eventId:'saved',symbol:'0000.T',direction:1,entryPrice:100,entryTimestamp:t(0),usedPathIdentity:identity});const row=m.step({timestamp:t(3),close:99,v4:{timestamp:t(3),action:'HOLD'}});assert.equal(row.gridGap,true);assert.equal(row.savedPathOrdinalReplay,true);assert.equal(row.barsHeld,1);assert.throws(()=>new Bar5Manager({eventId:'x',symbol:'0000.T',direction:1,entryPrice:100,entryTimestamp:t(0),usedPathIdentity:'unverified'}));});
