from common import *
import json
def pct(x):return '—' if x is None else f'{100*x:.4f}%'
def num(x):return '—' if x is None else f'{x:,.2f}'
def table(headers,body):return '\n'.join(['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(str(x) for x in row)+' |' for row in body])
def main():
 data=json.loads((OUT/'DIAGNOSTIC_ANALYSIS.json').read_text());profiles=data['profiles'];audit=json.loads((OUT/'INDEPENDENT_AUDIT.json').read_text());supp=json.loads((OUT/'INDEPENDENT_OPPORTUNITY_AUDIT.json').read_text());can=json.loads((OUT/'CANARY_RESULTS.json').read_text());ident=json.loads((OUT/'B_PLUS_IDENTITY.json').read_text());assert audit['mismatch_N']==supp['mismatch_N']==can['failed_N']==0 and ident['mismatch']==[]
 pin=json.loads((OUT/'CODE_PRECOMMIT.json').read_text());assert all(sha(CODE/k)==v for k,v in pin.items());src=json.loads((OUT/'SOURCE_HASHES.json').read_text());assert all(sha(WORK/k)==v for k,v in src.items())
 cols=('B_PLUS_MAX3','S_ONLY_MAX3','A_PLUS_MAX3');body=[]
 specs=[('funded N',lambda x:str(x['quality']['N'])),('avg funded/session',lambda x:f"{x['economic']['avg_funded_per_session']:.4f}"),('daily geometric',lambda x:pct(x['economic']['geometric_mean_daily_return'])),('rolling20 median',lambda x:f"{x['economic']['rolling20_median']:.8f}x"),('rolling20 max',lambda x:f"{x['economic']['rolling20_maximum']:.8f}x"),('Final Equity',lambda x:'¥'+num(x['economic']['final_equity'])),('2x hit',lambda x:f"{x['economic']['north_star_hit_N']}/19 (NO)"),('MaxDD',lambda x:pct(x['economic']['max_drawdown'])),('utilization mean',lambda x:pct(x['economic']['utilization_mean'])),('PF1 >=+1% rate',lambda x:pct(x['quality']['PF1_rate'])),('Loser <=0% rate',lambda x:pct(x['quality']['loss0_rate'])),('Tail <=-1% rate',lambda x:pct(x['quality']['tail1_rate']))]
 for name,fn in specs:body.append([name]+[fn(profiles[p]) for p in cols])
 for k in ('U3','Medium','U5','U10'):
  body.append([k+' capture']+[f"{x['capture_precision'][k]['funded_N']}/{x['capture_precision'][k]['total_N']} = {pct(x['capture_precision'][k]['capture'])}" for x in [profiles[p] for p in cols]])
  body.append([k+' precision']+[pct(profiles[p]['capture_precision'][k]['precision']) for p in cols])
 body += [[label]+[pct(profiles[p]['quality'][field]) for p in cols] for label,field in [('<2 contamination','below2_rate'),('<3 contamination','below3_rate')]]
 parts=['# v4 Independent Rank-Cutoff Result','38 OOF Development sessions / 19 rolling20 windows。MAX3 ONLY / new fit=0。正式Capitalの選定・promotionは行わない。',table(['Metric','v4 Main/B_PLUS','S_ONLY','A_PLUS'],body),'Captureは全Winnerを分母、Precisionは各profileのfunded Nを分母とする。B_PLUSは保存済みv4 Mainと全ledger・保存済み指標が完全一致。Final Equityの丸め前値は¥1,433,740.25。']
 parts+=['## A. Rank Quality Monotonicity',f"Candidate: `{data['rank']['candidate_monotonic']['status']}` / v4 Main funded: `{data['rank']['main_funded_monotonic']['status']}`。",'判定をprecommit: U5/U10 precision S>A>B、<2/Loser S<A<Bの4条件（隣接2組とも厳密）。全4=STRONG、一部=PARTIAL、0=NOT_MONOTONIC。空rankは条件PASSにしない。Candidate全1039件には15:20以降11件を含むがfundingは禁止。', 'Candidateのrealized品質はFrozen Entry→EXIT teacher（unresolved除外）。Fundedのrealized品質は各profileの実際のEXIT/EOD ledger。']
 fields=[('N','N'),('resolved','realized_resolved_N'),('unresolved','realized_unresolved_N'),('U2','U2_rate'),('U3','U3_rate'),('Medium','Medium_rate'),('U5','U5_rate'),('U10','U10_rate'),('<1','below1_rate'),('<2','below2_rate'),('<3','below3_rate'),('realized mean','realized_mean'),('median','realized_median'),('>=+1','PF1_rate'),('>0','positive_rate'),('=0','exact_zero_rate'),('<=0','loss0_rate'),('<=-1','tail1_rate'),('<=-3','tail3_rate')]
 for name,q in [('Candidate',data['rank']['candidate'])]+[(p+' funded',profiles[p]['funded_rank_quality']) for p in PROFILES]:
  parts += ['### '+name,table(['Metric','S','A','B'],[[label]+[(str(q[r][k]) if k in ('N','realized_resolved_N','realized_unresolved_N') else pct(q[r][k])) for r in ('S','A','B')] for label,k in fields])]
 parts+=['Candidateでは<2 contaminationのみ単調。U5/U10はA>S>B、LoserはSが最も高く、期待された全品質単調性は成立しない。Main fundedではU5と<2は単調だが、U10はA>S>B、LoserはS=A<B（厳密なS<Aではない）。Main-funded Sは18件であり、S_ONLYの41件とは選択集合が異なる。','## B. Capture vs Precision','上のPrimary Tableが全4cohortのcapture/precisionを明示。A_PLUSはU5 46/170、U10 24/67でB_PLUSの42/170、23/67を上回る一方、Mediumは24/127でB_PLUS31/127を下回る。S_ONLYはU5 12/170、U10 6/67に留まり、coverageの低下は大きい。Profileごとにheld slots・cash・ロットが変わるためfunded集合は単純包含ではない。','## C. Entry→High Buckets']
 for p in PROFILES:
  parts+=['### '+p,table(['Potential','funded N','composition','realized mean','median','>=+1','Loser <=0','Tail <=-1','actual PnL JPY'],[[b,q['N'],pct(q['composition']),pct(q['realized_mean']),pct(q['realized_median']),pct(q['PF1_rate']),pct(q['loss0_rate']),pct(q['tail1_rate']),num(q['actual_pnl_jpy'])] for b,q in profiles[p]['buckets'].items()])]
 parts+=['## D. Empty Slot / Opportunity Cost','Regular minute-samples:540<=minute<690 または750<=minute<930、各snapshotはSELL/Entry処理後。各38 sessions ×330=12,540 samples。unused sessionは「1 sample以上で保有<3」なので全profile38件。Peak<3のsession数とは異なる。',table(['Metric']+list(cols),[[k]+[profiles[p]['opportunity'][k] for p in cols] for k in ('rank_cutoff_reject_N','sessions_with_unused_MAX3_slot')]+[[f'minute positions={i}']+[profiles[p]['opportunity']['minute_samples_positions'][str(i)] for p in cols] for i in range(4)])]
 for name in ('U5','U10'):
  parts+=['### '+name,table(['Opportunity']+list(cols),[[k]+[profiles[p]['opportunity'][name][k] for p in cols] for k in ('later_arrived_slot_free_N','later_arrived_slot_occupied_N','missed_cutoff_N','missed_MAX3_N','HELD_SLOT_BLOCKED_WINNER_N')])]
 parts+=['Winner arrivalは15:20前Entryのbatch直前（due SELL後、BUY前）。初回batchも含む。occupied=既存3保有、free=0–2保有。HELD_SLOT_BLOCKEDはcapacity rejectかつbatch内先頭3 eligible以内で既存保有あり。Heldを外した仮想selection可能性のみで、約定可能性やreplacementを主張しない。未来結果をBUY/position replacementへ戻していない。']
 for p in PROFILES:parts+=['### '+p+' reject reasons',table(['Reason','N'],[[k,v] for k,v in profiles[p]['economic']['reasons'].items()]),'U5 missed: '+json.dumps(profiles[p]['opportunity']['U5']['missed_reasons'],ensure_ascii=False)+' / U10 missed: '+json.dumps(profiles[p]['opportunity']['U10']['missed_reasons'],ensure_ascii=False)]
 parts+=['## E. Economic / Capital','各profile dailyとrolling20の全データは `DAILY.csv` / `ROLLING20.csv`、minute asset curveはPrivate ZIPの各`*_CURVE.jsonl.gz`。',table(['Metric']+list(cols),[[k]+[num(profiles[p]['economic'][k]) if k in ('cash_minimum','turnover_cash_jpy','capital_recycling_used_jpy','maximum_20_session_amount') else pct(profiles[p]['economic'][k]) for p in cols] for k in ('arithmetic_mean_daily_return','median_daily_return','utilization_median','time_utilization_ge80','time_utilization_ge90','cash_minimum','turnover_cash_jpy','capital_recycling_used_jpy','maximum_20_session_amount')]+[[k]+[str(profiles[p]['economic'][k]) for p in cols] for k in ('daily_sign_counts','session_max_concurrent_counts')]+[[k]+[f"{profiles[p]['economic'][k]:.8f}x" for p in cols] for k in ('rolling20_minimum','rolling20_arithmetic_mean')]),'全profile rolling20 valid19 / 2x0 / earliest2xなし。¥1m→20日中央値: '+ '、'.join(p+' ¥'+num(1000000*profiles[p]['economic']['rolling20_median']) for p in PROFILES)+ '。']
 parts+=['### Thin Liquidity (diagnostic-only)','Hard Reject0 / position-size cap0 / eligibility・score・quantityへのLiquidity使用0。']
 for p in PROFILES:parts+=['### '+p,table(['Historical status','funded N','U5 composition','U10 composition','PF1','Loser','actual PnL'],[[s,q['N'],pct(q['U5_rate']),pct(q['U10_rate']),pct(q['PF1_rate']),pct(q['loss0_rate']),num(q['actual_pnl_jpy'])] for s,q in profiles[p]['liquidity'].items()])]
 parts+=['## F. Identity / Integrity',f"B_PLUS identity PASS / independent mismatch0 ({audit['check_N']:,} checks) / opportunity追加5 checks mismatch0 / canary{can['pass_N']} PASS、fail0。",'Primary3 replay + Independent Fraction3 replay + deterministic canary3 replay + same-Entry causal mutation2 mini replay。同じ診断profileのresult-based rerun/retuneは0。v4 Main・Control・MAX4/MAX5 replay0。新fit0。Frozen score/ML/rank/H2/H3/H5/Entry/EXIT/accounting変更0。', 'Future EXITの変更は現在Entryのdecision不変を検証。実際のfuture SELL時刻・価格を変更すると後続Entryのcash/slotsは合法的に変わるため、全session decision不変とは主張しない。MTMはfillでもcash releaseでもなく、全cash変化を実BUY/SELL ledgerで検証。', 'PrecommitされたPrimary/Independent/analysis/canary codeはhash不変。後追加のopportunity補助コードv1には構文上の空白欠落があり実行前に失敗。append-onlyでv1を保持し、audit_opportunity_v2.pyを追加して同じ独立ledgerを監査、追加replay0/mismatch0。売買・モデル・threshold・結果の変更0。', 'Frozen sources: `SOURCE_HASHES.json`。Model/score identity: `V4_IDENTITY_FREEZE.json`。Code pin/config: `CODE_PRECOMMIT.json` / `DIAGNOSTIC_CONFIG.json`。Actual GitHub receipts: `receipts/`、最終HEAD/treeは `CHECKPOINT_INDEX.json` にpostcommit GETで追記。', 'Safety全false: '+json.dumps(SAFETY,sort_keys=True)+'。orders0/main merge0/force push0/new provider0/Claude0/retune0/promotion0。', '`ITERATIVE_DEVELOPMENT_EVIDENCE`。58 supplied Development sessionsは既に複数cycleの判断に使用されており、反復によるoverfit riskがある。fresh/OOS成績ではない。Protected/Holdout/Fresh/Validation/OOS/Prospective開封0。productionReady=false。', '## Conclusions / STOP', 'S_ONLYは少数化しUpward precisionはB_PLUSより高いが、最高品質とは言えない。Loser63.4146%、日次幾何−0.2905%、Final¥895,356.10。', 'A_PLUSはBig/Megaのcaptureとprecision、低upside contaminationでB_PLUSより良い。一方Medium coverage低下、Loser56.0606%・Tail35.6061%はB_PLUSより悪く、日次幾何+0.8769%・Final¥1,393,406.80も下回る。上方向の品質改善がLoser抑制へ一貫して波及した証拠はない。', 'B_PLUSはv4 Mainを完全再現。S>A>Bの全品質単調性は不成立（PARTIAL）。3軸QUALITY/COVERAGE/CAPITALにtradeoffがあり、正式winnerや次のCapitalは選ばない。', '結果を固定しSTOP。threshold/rank/ML/model/Movement/Liquidity/MAX/Entry/EXIT変更0。次の判断はユーザーへ返す。']
 report='\n\n'.join(parts)+'\n'
 with (OUT/'REPORT_FINAL-ja.md').open('x') as f:f.write(report)
 closure={'JST':now(),'status':'CLOSED_STOP','new_fit':0,'primary_replays':3,'independent_replays':3,'deterministic_canary_replays':3,'isolated_mutation_replays':2,'B_PLUS_identity':True,'mismatch_N':0,'canary_pass_N':can['pass_N'],'frozen_changes':0,'precommitted_code_hash_unchanged':True,'score_hash':sha(FROZEN/'UPWARD_STAIRCASE_SCORE_STREAM.jsonl.gz'),'candidate_rank_status':data['rank']['candidate_monotonic'],'funded_rank_status':data['rank']['main_funded_monotonic'],'promotion':0,'retune':0,'orders':0,'new_provider':0,'Exposure':'ITERATIVE_DEVELOPMENT_EVIDENCE','Safety':SAFETY,'supplementary_code_note':'opportunity v1 syntax failure retained; v2 append-only correction, no replay/result changes.','next_direction':'STOP; user decides next independent cycle. No formal winner chosen.'}
 save(OUT/'CLOSURE.json',closure);checkpoint('R9_FINAL_DIAGNOSTIC_REPORT_AND_CLOSURE','CLOSED_STOP',closure,closure['next_direction']);print(json.dumps(closure))
if __name__=='__main__':main()
