import assert from 'node:assert/strict';
import { deriveEntryOpportunityFeatures } from '../daytrade/phase57-entry-opportunity-intelligence.js';
import { PHASE57_P23_9F_SAFETY,fitLeaveSymbolOutAnalog,evaluateLeaveSymbolOutRolling } from '../daytrade/phase57-leave-symbol-out-opportunity.js';
for(const k of ['executionAllowed','brokerWriteAllowed','excelOrderWriteAllowed','rssOrderFunctionAllowed','liveTradingAllowed','paperTradingAllowed','automaticPromotionAllowed','productionUpdateAllowed','overnightHoldingAllowed'])assert.equal(PHASE57_P23_9F_SAFETY[k],false);
function bars(date,drift){const start=Date.parse(`${date}T00:00:00Z`);return Array.from({length:12},(_,i)=>{const o=100+i*drift,c=o+drift*.6;return{timestamp:new Date(start+i*300000).toISOString(),sessionDate:date,open:o,high:Math.max(o,c)+.1,low:Math.min(o,c)-.1,close:c,volume:1000+i*20};});}
function row(date,i,symbol,good){const direction=i%2?'LONG':'SHORT',drift=(direction==='LONG'?1:-1)*(good?.24:-.12),ctx=bars(date,drift),features=deriveEntryOpportunityFeatures({contextBars:ctx,direction});return{symbol,sessionDate:date,featureCutoff:ctx.at(-1).timestamp,direction,features,targets:{mfePct:good?1:.2,adversePct:good?.2:.7,endpointNetReturnPct:good?.4:-.35,opportunityScorePct:good?.75:-.55},realizedRatchetNetReturnPct:good?.3:-.3,pointInTimeFeaturesOnly:true,futureTargetsEvaluationOnly:true};}
const train=[];for(let d=1;d<=14;d++){const date=`2026-07-${String(d).padStart(2,'0')}`;for(let i=0;i<50;i++){for(const symbol of ['A','B','C','D'])train.push(row(date,i,symbol,(i+symbol.charCodeAt(0))%3!==0));}}
const model=fitLeaveSymbolOutAnalog(train,{k:16});const p=model.predict(row('2026-07-15',999,'A',true));assert.equal(p.sameSymbolOutcomeNeighborsExcluded,true);assert.equal(p.neighborSameSymbolWeight,0);assert.equal(p.futureOutcomeUsedForPrediction,false);
const frozen=[];for(let i=0;i<20;i++)frozen.push(row('2026-07-15',2000+i,'A',i%3!==0));const ev=evaluateLeaveSymbolOutRolling({trainingExamples:train,frozenTestExamples:frozen,config:{k:16,fitLookbackSessions:8,calibrationSessionCount:3,maxCalibrationRows:120,minimumCalibrationSignals:10,minimumCalibrationNetPct:0,minimumCalibrationProfitFactor:1.01}});assert.equal(ev.integrity.sameSymbolOutcomeNeighborsForbidden,true);assert.equal(ev.integrity.testOutcomesUsedForSelection,false);assert.equal(ev.edgeClaimAllowed,false);assert.equal(ev.executionAllowed,false);for(const r of ev.predictions){assert.equal(r.sameSymbolOutcomeNeighborsExcluded,true);assert.equal(r.neighborSameSymbolWeight,0);}
console.log('P23.9F leave-symbol-out opportunity tests passed');
