import assert from 'node:assert/strict';
import { deriveEntryOpportunityFeatures } from '../daytrade/phase57-entry-opportunity-intelligence.js';
import { PHASE57_P23_9D_SAFETY,evaluateRollingRegimeOpportunity } from '../daytrade/phase57-rolling-regime-opportunity-gate.js';
for(const key of ['executionAllowed','brokerWriteAllowed','excelOrderWriteAllowed','rssOrderFunctionAllowed','liveTradingAllowed','paperTradingAllowed','automaticPromotionAllowed','productionUpdateAllowed','overnightHoldingAllowed'])assert.equal(PHASE57_P23_9D_SAFETY[key],false);
function bars(date,drift){const start=Date.parse(`${date}T00:00:00Z`);return Array.from({length:12},(_,i)=>{const o=100+i*drift,c=o+drift*0.7;return{timestamp:new Date(start+i*300000).toISOString(),sessionDate:date,open:o,high:Math.max(o,c)+0.1,low:Math.min(o,c)-0.1,close:c,volume:1000+i*20};});}
function row(date,i,good){const direction=i%2?'LONG':'SHORT',drift=(direction==='LONG'?1:-1)*(good?0.25:-0.11),ctx=bars(date,drift),features=deriveEntryOpportunityFeatures({contextBars:ctx,direction});return{symbol:`S${i%5}`,sessionDate:date,featureCutoff:ctx.at(-1).timestamp,direction,features,targets:{mfePct:good?1.1:0.2,adversePct:good?0.2:0.7,endpointNetReturnPct:good?0.4:-0.35,opportunityScorePct:good?0.85:-0.55},realizedRatchetNetReturnPct:good?0.32:-0.28,pointInTimeFeaturesOnly:true,futureTargetsEvaluationOnly:true};}
const train=[];for(let d=1;d<=18;d++){const date=`2026-07-${String(d).padStart(2,'0')}`;for(let i=0;i<70;i++)train.push(row(date,i,(i%4)!==0));}
const frozen=[];for(const date of ['2026-07-19','2026-07-20'])for(let i=0;i<20;i++)frozen.push(row(date,3000+i,(i%4)!==0));
const ev=evaluateRollingRegimeOpportunity({trainingExamples:train,frozenTestExamples:frozen,config:{fitLookbackSessions:10,calibrationSessionCount:3,maxCalibrationRows:150,minimumCalibrationSignals:10,minimumCalibrationNetPct:0,minimumCalibrationProfitFactor:1.01,analogConfig:{k:16,minTrainRows:100}}});
assert.equal(ev.integrity.rollingFitUsesOnlyPriorSessions,true);assert.equal(ev.integrity.rollingCalibrationUsesOnlyPriorSessions,true);assert.equal(ev.integrity.testOutcomesUsedForGateSelection,false);assert.equal(ev.integrity.sameSessionTrainingForbidden,true);assert.equal(ev.edgeClaimAllowed,false);assert.equal(ev.executionAllowed,false);assert.equal(ev.allFrozenRatchet.signalCount,40);for(const day of ev.dayDiagnostics){if(day.selection?.integrity){assert.equal(day.selection.integrity.fitPrecedesCalibration,true);assert.equal(day.selection.integrity.calibrationPrecedesTestDate,true);assert.equal(day.selection.integrity.testOutcomesUsedForSelection,false);}}for(const p of ev.predictions)assert.equal(p.testOutcomeUsedForSelection,false);
console.log('P23.9D rolling regime opportunity tests passed');
