import assert from 'node:assert/strict';
import { deriveEntryOpportunityFeatures } from '../daytrade/phase57-entry-opportunity-intelligence.js';
import { PHASE57_P23_10A_SAFETY,evaluateAdaptiveSignalMetaLabel } from '../daytrade/phase57-adaptive-signal-meta-label.js';
for(const k of ['executionAllowed','brokerWriteAllowed','excelOrderWriteAllowed','rssOrderFunctionAllowed','liveTradingAllowed','paperTradingAllowed','automaticPromotionAllowed','productionUpdateAllowed','overnightHoldingAllowed'])assert.equal(PHASE57_P23_10A_SAFETY[k],false);
function bars(date,drift){const start=Date.parse(`${date}T00:00:00Z`);return Array.from({length:12},(_,i)=>{const o=100+i*drift,c=o+drift*.7;return{timestamp:new Date(start+i*300000).toISOString(),sessionDate:date,open:o,high:Math.max(o,c)+.1,low:Math.min(o,c)-.1,close:c,volume:1000+i*20};});}
function row(date,i,symbol,good,meta=true){const direction=i%2?'LONG':'SHORT',drift=(direction==='LONG'?1:-1)*(good?.25:-.1),ctx=bars(date,drift),features=deriveEntryOpportunityFeatures({contextBars:ctx,direction});return{symbol,sessionDate:date,featureCutoff:ctx.at(-1).timestamp,direction,features,targets:{mfePct:good?1.1:.2,adversePct:good?.2:.7,endpointNetReturnPct:good?.4:-.3,opportunityScorePct:good?.85:-.5},realizedRatchetNetReturnPct:good?.3:-.25,pointInTimeFeaturesOnly:true,futureTargetsEvaluationOnly:true,baseSignalOosValid:meta,baseSignalSource:'P21_1_OUTER_OOS_REPLAY',sameSessionOnly:true};}
const hist=[];for(let d=1;d<=16;d++){const date=`2026-07-${String(d).padStart(2,'0')}`;for(let i=0;i<30;i++)for(const s of ['A','B','C','D'])hist.push(row(date,i,s,(i+s.charCodeAt(0))%3!==0,true));}hist.push(row('2026-07-01',999,'Z',true,false));
const frozen=[];for(let i=0;i<20;i++)frozen.push(row('2026-07-17',2000+i,'A',i%3!==0,false));
const out=evaluateAdaptiveSignalMetaLabel({historicalSignalExamples:hist,frozenTestExamples:frozen,config:{k:12,fitLookbackSessions:10,calibrationSessionCount:3,maxCalibrationRows:100,minimumCalibrationSignals:8,minimumCalibrationNetPct:0,minimumCalibrationProfitFactor:1.01}});
assert.equal(out.historicalSignalExampleCount,hist.length-1);assert.equal(out.integrity.baseSignalsOuterOosOnly,true);assert.equal(out.integrity.metaTrainingUsesOnlyPriorSessions,true);assert.equal(out.integrity.sameSymbolOutcomeNeighborsForbidden,true);assert.equal(out.edgeClaimAllowed,false);assert.equal(out.executionAllowed,false);assert.equal(out.evaluation.integrity.testOutcomesUsedForSelection,false);
console.log('P23.10A adaptive-signal meta-label tests passed');
