import assert from 'node:assert/strict';
import { deriveEntryOpportunityFeatures } from '../daytrade/phase57-entry-opportunity-intelligence.js';
import { PHASE57_P24A_SAFETY,deriveMarketContextFeatures,fitMarketContextAnalog,evaluateMarketContextRolling } from '../daytrade/phase57-market-context-opportunity.js';
for(const k of ['executionAllowed','brokerWriteAllowed','excelOrderWriteAllowed','rssOrderFunctionAllowed','liveTradingAllowed','paperTradingAllowed','automaticPromotionAllowed','productionUpdateAllowed','overnightHoldingAllowed'])assert.equal(PHASE57_P24A_SAFETY[k],false);
function bars(date,drift){const start=Date.parse(`${date}T00:00:00Z`);return Array.from({length:12},(_,i)=>{const o=100+i*drift,c=o+drift*.6;return{timestamp:new Date(start+i*300000).toISOString(),sessionDate:date,open:o,high:Math.max(o,c)+.1,low:Math.min(o,c)-.1,close:c,volume:1000+i*20};});}
function row(date,i,symbol,good){const direction=i%2?'LONG':'SHORT',ctx=bars(date,(direction==='LONG'?1:-1)*(good?.22:-.1)),base=deriveEntryOpportunityFeatures({contextBars:ctx,direction}),mctx=bars(date,.08),market=deriveMarketContextFeatures({marketContextBars:mctx,direction,stockFeatures:base,breadth:good?.65:.35,crossSectionMeanReturnPct:good?.2:-.15});return{symbol,sessionDate:date,featureCutoff:ctx.at(-1).timestamp,direction,features:{...base,...market},targets:{mfePct:good?1:.2,adversePct:good?.2:.7,endpointNetReturnPct:good?.4:-.3,opportunityScorePct:good?.75:-.5},realizedRatchetNetReturnPct:good?.3:-.25,pointInTimeFeaturesOnly:true,marketContextPointInTimeOnly:true,futureTargetsEvaluationOnly:true};}
const train=[];for(let d=1;d<=14;d++){const date=`2026-07-${String(d).padStart(2,'0')}`;for(let i=0;i<40;i++)for(const s of ['A','B','C','D'])train.push(row(date,i,s,(i+s.charCodeAt(0))%3!==0));}const model=fitMarketContextAnalog(train,{k:16});const p=model.predict(row('2026-07-15',999,'A',true));assert.equal(p.sameSymbolOutcomeNeighborsExcluded,true);assert.equal(p.marketContextUsed,true);assert.equal(p.marketContextPointInTimeOnly,true);assert.equal(p.neighborSameSymbolWeight,0);
const frozen=[];for(let i=0;i<20;i++)frozen.push(row('2026-07-15',2000+i,'A',i%3!==0));const ev=evaluateMarketContextRolling({trainingExamples:train,frozenTestExamples:frozen,config:{k:16,fitLookbackSessions:8,calibrationSessionCount:3,maxCalibrationRows:120,minimumCalibrationSignals:10,minimumCalibrationNetPct:0,minimumCalibrationProfitFactor:1.01}});assert.equal(ev.integrity.marketContextPointInTimeOnly,true);assert.equal(ev.integrity.testOutcomesUsedForSelection,false);assert.equal(ev.edgeClaimAllowed,false);assert.equal(ev.executionAllowed,false);
console.log('P24A market-context opportunity tests passed');
