"""RD02 final descriptive decision and preserved complete tabular report."""
import csv
from common import *

def table(headers,rr):return '| '+' | '.join(headers)+' |\n| '+' | '.join(['---']*len(headers))+' |\n'+'\n'.join('| '+' | '.join(str(v) for v in r)+' |' for r in rr)+'\n'
def percent(v):return 'N/A' if v is None else f'{100*v:.2f}%'
def num(v):return 'N/A' if v is None else f'{v:.6f}'
def cell(n,d):return f'{n}/{d} ({100*n/d:.2f}%)' if d else '0/0 (N/A)'

def run():
    data=rows(PRIVATE/'UNREDACTED_COLLECTION_DIAGNOSTICS.jsonl.gz');base=[r for r in data if r['scope']=='ALL'];summary=read(PUB/'EVALUATION_SUMMARY.json');audit=read(PUB/'INDEPENDENT_FEATURE_LABEL_AUDIT.json');ma=read(PUB/'INDEPENDENT_METRIC_AUDIT.json');repro=read(PUB/'REPRODUCTION_RECEIPT.json');assert audit['status']==ma['status']==repro['status']=='PASS'
    get=lambda **k:next(r for r in base if all(r[x]==v for x,v in k.items()))
    bands={'P5_PLUS':'>=+5','P4_5':'[+4,+5)','P3_4':'[+3,+4)','P2_3':'[+2,+3)','P1_2':'[+1,+2)','P0_1':'(0,+1)','L0_1':'(-1,0)','L1_2':'(-2,-1]','L2_3':'(-3,-2]','L3_4':'(-4,-3]','L4_5':'(-5,-4]','L5_PLUS':'<=-5','ZERO':'ZERO','R_UNKNOWN':'R_UNKNOWN'}
    text=['# ARK TERMINAL — RD02 / Downside V2 最終報告','文書ID: ARK_RD02_INTERRUPTED_RESUME_20261008 / 元仕様: ARK_RANK_DOWNSIDE_DIRECT_RD02_20261008','## 現行R0の全12帯（固定比較母集団）','1039一意Entry / 38 Development sessions。R_NEW既知1016、未知23。EXITはSHARP_DROP_FIRST_OBSERVED_EXIT_V0。12帯とZEROは各rankのR既知N、UNKNOWNはrank全Nを分母とする。重複加算はしない。']
    ranks={r:get(table='R0_RANK_FULL_12BAND',rank=r) for r in ['S','A','B','C']}
    text.append(table(['R_NEW %','S','A','B','C'],[[bands[b]]+[cell(ranks[r][b+'_n'],ranks[r]['all_N'] if b=='R_UNKNOWN' else ranks[r]['known_N']) for r in ranks] for b in BANDS]))
    text.append(table(['補助（12帯へ加算しない）','S','A','B','C'],[[name]+[cell(ranks[r][name],ranks[r]['known_N']) for r in ranks] for name in ['ALL_PLUS','ALL_MINUS']]+[['R-known coverage']+[cell(ranks[r]['known_N'],ranks[r]['all_N']) for r in ranks]]))
    text+=['## 各元rank内の高risk20%と残り80%：D-FULL','各block×rank内でceil(.20*N_available)。そのため合算の高risk比率は正確な20%とは限らない。同点はcanonical ID昇順。UNKNOWNを除く前に集合を決めた。各小集団は記述的診断であり、runtime gateや新S/A/B/Cではない。']
    for target_ in ['q3','q5']:
        text.append('### '+target_+'：全12帯')
        text.append(table(['R_NEW %']+[r+' '+g for r in ranks for g in ['HIGH20','REST80']],[[bands[b]]+[cell(get(table='WITHIN_R0_RANK_RISK_12BAND',method='D-FULL',target=target_,rank=r,group=g)[b+'_n'],get(table='WITHIN_R0_RANK_RISK_12BAND',method='D-FULL',target=target_,rank=r,group=g)['all_N' if b=='R_UNKNOWN' else 'known_N']) for r in ranks for g in ['HIGH_RISK_20','REST_80']] for b in BANDS]))
    text.append('A/B/Cの内部にもq3 tail濃縮があり、元rankの違いを言い直しただけではない。ただしSはq3 tail全3件、q5 tail0件。Sのq3高riskは1/11、残り2/32で、小Nから強い採用判断はできない。Aのq3高riskはR<=-3が4/32、R>=+5も9/32。残りは7/122、7/122。Winnerを選択的に保護できる追加情報とはまだ認定しない。')
    text+=['## 同数K比較：D-FULL','各blockの旧S、S+A、S+A+B件数Kを固定。全3構成でqがある共通1039 IDに対して旧native candidate_orderと低q3/低q5を比較。予測欠測によるK縮小0。K43/197/494は合算診断人数であり、1時点の資金枠や購入数量ではない。選択後のR-known Nが異なるためunknownも併記する。']
    kk=[]
    for budget in ['S','SA','SAB']:
        for order in ['R0_NATIVE','q3_LOW','q5_LOW']:
            r=get(table='EQUAL_K_SELECTION_12BAND',method='D-FULL',rank=budget,target=order)
            kk.append([budget,order,r['all_N'],cell(r['known_N'],r['all_N']),cell(r['q3_n'],r['known_N']),cell(r['q5_n'],r['known_N']),cell(r['WINNER2_n'],r['known_N']),cell(r['WINNER5_n'],r['known_N']),r['U2_n'],r['U3_n'],r['U5_n'],r['U10_n'],f"{r['positive_mass_pp_sum']:.4f}",f"{r['negative_abs_mass_pp_sum']:.4f}"])
    text.append(table(['K','order','all N','R-known','<=-3','<=-5','>=+2','>=+5','U2 n','U3 n','U5 n','U10 n','正mass pp-sum','負abs mass pp-sum'],kk))
    text.append('同数S+A=197ではq3低riskによりR<=-3が14/197→6/190へ減る一方、実現>=+5は19→4、U10は29→4。S+A+B=494でも実現>=+5は30→15、U10は47→16。件数削減だけの見かけではないが、純risk順は上方向の機会を大きく失う。UはR-knownと別maskで、U-knownを分母とする完全なcapture/densityはCSVにある。等重みpp-sumを円、回避損失、Final Equityへ換算していない。')
    text+=['## 最終判断','**NO_INCREMENT_UNDER_TESTED_DESIGN / COMPLETE_STOP**。意味は「今回仕様で、Ranking統合の採用条件を満たす追加価値は未確立」。部分的なtail順位情報とWinner tradeoffはある。市場全般のDownside予測が不可能だとは結論しない。','HARD_INTEGRITY=PASS（同一作者の別実装クロスチェック）。MEASUREMENT_SUPPORT=PASS（3構成すべて1039/1039、8/8 block ACTIVE、fallback0/UNASSESSED0）。D-FULLの事前PREDICTION_SCREENとSELECTIVITY_SCREENは未達。Championは選ばず、R0は変更しない。']
    text+=['## 固定高risk10%/20%の損失捕捉とWinner巻込み','基準母数：R<=-3は73/1016、R<=-5は23/1016、実現>=+2は137/1016、実現>=+5は48/1016。U5 total170、U10 total67。FLAGはoffline集合診断。captureの分母は同じ有効q poolの当該target全件。濃縮はblock内R-known条件付き同数無情報期待との比。']
    ff=[]
    for target_ in ['q3','q5']:
        for percent_ in [10,20]:
            r=get(table='FIXED_RISK_FLAG_TRADEOFF',method='D-FULL',target=target_,group=f'TOP_{percent_}_FLAG')
            ff.append([target_,percent_,r['all_N'],r['known_N'],cell(r[target_+'_n'],r[target_+'_pool_n']),f"{r[target_+'_enrichment']:.3f}",cell(r['WINNER2_n'],r['WINNER2_pool_n']),cell(r['WINNER5_n'],r['WINNER5_pool_n']),cell(r['U5_n'],r['U5_pool_n']),cell(r['U10_n'],r['U10_pool_n']),f"{r['positive_mass_pp_sum']:.4f}",f"{r['negative_abs_mass_pp_sum']:.4f}"])
    text.append(table(['risk','top %','FLAG allN','FLAG R-known','tail recall n/N','濃縮','>=+2 damage n/N','>=+5 damage n/N','U5 damage n/N','U10 damage n/N','FLAG正mass pp-sum','FLAG負abs mass pp-sum'],ff))
    text.append('q3上位20%はtail 27/73=36.99%を捕捉するが、U10を30/67=44.78%、実現>=+5を23/48=47.92%巻き込む。q5上位20%でも重大tail 11/23=47.83%に対し、実現>=+5は26/48=54.17%。q5事前相対条件の一部を満たしていても、最終資産に重要な大Winnerを保護できたとは言えない。偽risk側Winner混入、NOT_FLAGGED側capture/density、U2/U3も完全表に保存した。')
    metrics=list(csv.DictReader((PUB/'PROBABILITY_METRICS.csv').open()));text+=['## q5/q3/q2/qNEG・5クラス確率指標','すべて同じR-known1016 ID。qは推定riskであり、校正済み確率の保証ではない。calibration fit0。B0は同一過去trainのDirichlet0.5平滑化頻度で、新モデル有効coverageに加えていない。']
    text.append(table(['target','method','Brier','binary log loss','AUROC','AP'],[[r['target'],r['method']]+[f"{float(r[k]):.6f}" if r[k] else 'N/A' for k in ['Brier','binary_log_loss','AUROC','AP']] for r in metrics if r['mask']=='METHOD_COMMON' and r['target']!='5CLASS']))
    text.append(table(['5CLASS method','log loss'],[[r['method'],f"{float(r['multiclass_log_loss']):.6f}"] for r in metrics if r['target']=='5CLASS']))
    text.append('D-FULLは全体q3/q5のBrier・log lossでB0を改善した。ただしq3の両指標が改善したのはBlock2/6/8の3/8で、事前条件の過半数に達しない。q2/qNEGと5クラスlog lossはB0より悪い。Calibration固定binを統合せず全104 binを保存し、空binや小NをN/A/LOW_SUPPORTとして残した。AUC単独で採用していない。')
    text.append('D-FULL vs D-PRICE：q3/q5のpooled proper scoreは改善したが、q2/qNEGと5class lossは悪化。State/Path追加にはtail限定の記述的価値があるものの、包括的な追加価値は未確立。D-FULL vs D-LINEARはproper scoreで優れるが、q5 APはD-LINEARが高い。Primaryは結果後にD-PRICE/D-LINEARへ付け替えていない。')
    text+=['## RD01とのexact paired referenceと安定性','R1/R2の対応qがある既知755 IDで比較。native fillのLATER_ASOF_REFERENCEであり、厳密BUY_INTENTのRD02と同一情報集合ではない。warmup利用とtrain supportの差も混ざる。旧score再推論/refit0。旧HL0/D1/D2は順位AUROC/APのみ参考であり、新tail確率としてのBrier/log lossは付けていない。','R2 paired755では、D-FULL q3 Brier=0.069207 vs R2=0.069411、log loss=0.263297 vs0.269557。q5 Brier=0.023448 vs0.023306で悪化、log loss=0.110692 vs0.113397で改善。q5改善は一貫せず、旧研究に対する全面的incrementとは認定しない。','全38session leave-one-outの固定予測再集計で、D-FULLがB0よりq3 proper両指標良好なのは36/38、q5は37/38。一方、q2/qNEGは0/38。全583symbolも対称に除外して9328行の指標を保存。再fitなし。pooled改善の単一session依存が弱いことと、block過半数未達は別の診断であり、未来月の成功率へ換算しない。','q5陽性は23件だけ。元Sは43件、Sのq5陽性0、Aのq5陽性2。細帯・rank内・bin・sessionの小Nは件数とLOW_SUPPORTを表示し、ゼロ観測をリスクゼロの保証にしない。']
    text+=['## 検算・人工境界・1campaign再現','1600 IDの原raw/保存State/Frozen FIRST_INTENTから別経路で112000数値・6400カテゴリを照合。原価格のBUY1.0005/SELL0.9995各1回から既知1560 RをFractionで検算（評価1016＋warmup544）。未知40は保存reasonを維持。評価1039 Rの再生成0、未保存warmup materialization561試行/544既知/17未知。provider/RAW recoveryとState kernel再計算0。','別実装はprimary feature/bucket/evaluatorをimportせず、175集合、9450scope行、945000会計・capture等、22050帯/分母セル、10910確率指標行、104calibration bin、24モデルのtrain/中央値/mean/std/missingness/worker viewを照合。11人工feature fixtureと、-5〜+5の各前/同値/後33境界を検証。正式Rの分類へepsilonを導入していない。','保存モデルからの再現は1campaignだけ、予測24pass、再fit/前処理fit0。全1600 featureと3117予測行、31公開payloadおよび非公開集合・会計gzipのbytes/SHA256/Git blobが一致。4800未来only feature canaryと、実評価Rを反転したコピーの会計変更・sealed q/model不変を確認。原ラベル・表は変更していない。','この検算は同じ作者による別実装クロスチェック。独立第三者盲検監査ではない。元source/凍結State kernel/libraryを共有する限界がある。UID/mount isolationは利用不可、file-open allowlistとmanager outcome denial canaryのみ。physical blindnessを主張しない。actual arrivalはUNKNOWN、historical assumed availabilityを実受信証明へ格上げしない。','既存研究を繰り返し見たADAPTIVE/ITERATIVE DEVELOPMENT。初回時系列OOFでもFresh/OOSへ改名しない。Protected/Fresh/Prospective opens0。']
    text+=['## 再開・保存・終点','Block1〜7の完了fitを再利用し、Block7の中断したprivate carrier転送だけを封印済み同一bytesで完了。Block7 GETを閉じてからBlock8を3 fit。合計24成功fit/25試行、前処理fit24。1試行はBlock1 D-LINEARのpreprocessing/optimization前startup中断。技術repair5/20を継承し、予算resetなし。モデル再fit0。','全Block1〜8のpublic/private actual GETを確認。publicは契約・匿名集計・hash、privateはID/価格/R/feature/model/元payload。巨大集計はoverview＋全行の480000byte以下CSV partsに分割し、再結合で元の全bytes/hash一致を確認。これは研究subset選択ではない。singleton符号mass/予測平均はprivateへ保持し、件数・分母・captureを変えていない。','最終GitHub commit/path/bytes/SHA256/Git blob/actual GETとreceipt自体の後続GETはREADBACK_RECEIPT_PUBLICATION.jsonおよびREADBACK_CONFIRMATION.jsonを権威とする。EVALUATION_SUMMARY.jsonはaudit前の初回集計snapshotとしてAUDIT_PENDINGを保持し、最終integrity判断は監査receipt/FINAL_DECISION.jsonに分けてappend-only保存する。','mainCapital=CAPITAL_MAX3_SLOT_RESERVE_V1、mainExit=SHARP_DROP_FIRST_OBSERVED_EXIT_V0、mainRank=SAVED_R0、selectedNewRank=null、productionReady=false、Safety9すべてfalse。First Layer変更/P1 activation/new rank policy/Capital RESET20 Replay/orders/production write/main merge/force push/workflow dispatch0。capitalImprovement=NOT_EVALUATED。','## 次の研究仮説は1つだけ','**BUY_INTENT時点の下方向の持続性と、値動きの大きさ由来のriskを分けて表現すれば、同数のtail捕捉を維持しながらU10・実現>=+5 Winnerの巻込みを減らせるか。** 今回の主な不足はWinner tradeoff。これは次cycle用の仮説であり、このWorkで新feature/第四モデル/別seed/新threshold/rank capを追加しない。Ranking統合の自動着手はしない。','## 完全表と再現入口','R0_RANK_FULL_12BAND.csv / RISK_QUINTILE_FULL_12BAND.csv / WITHIN_R0_RANK_RISK_12BAND.csv / EQUAL_K_SELECTION_12BAND.csv / FIXED_RISK_FLAG_TRADEOFF.csv / CANONICAL_12BAND_CELLS.csv。全構成・全scopeのcapture/massはUPSIDE_AND_WINNER_PRESERVATION.csv overviewとDIAGNOSTIC_DETAILS/以下の全parts。PUBLICATION_PARTITION_MANIFEST.jsonが全9450集合scope行、全9328symbol除外指標行のlossless再結合hashを束ねる。','確率/校正/block・session/対称除外/旧paired参考はPROBABILITY_METRICS.csv / CALIBRATION_DIAGNOSTICS.csv / BLOCK_SESSION_STABILITY.csv / LEAVE_ONE_SESSION_DIAGNOSTIC.csv / LEAVE_ONE_SYMBOL_DIAGNOSTIC.csv＋同名詳細parts / OLD_MODEL_PAIRED_REFERENCE.csv / OLD_MODEL_PAIRED_FLAG_DIAGNOSTICS.csv。再現入口はprivate checkpoints/S1（固定X/label/prefix）とB01〜B08（24モデル）をmanifestどおり復元し、implementation/reproduce.py。新campaignを開始せず、REPRODUCTION_RECEIPTに保存した既実行campaignを確認する。実行済みcampaignの再実行は禁止。']
    (PUB/'REPORT-ja.md').write_text('\n\n'.join(text)+'\n')
    hypothesis=text[text.index('## 次の研究仮説は1つだけ')+1]
    (PUB/'NEXT_STAGE_DESIGN_ONLY.md').write_text('# RD02 次仮説（設計のみ）\n\n'+hypothesis+'\n\n今回status: NO_INCREMENT_UNDER_TESTED_DESIGN。主因: Winner tradeoff。上方向H2/H3/H5、R0、FIRST LAYER、EXIT、Capitalを維持する。次Workの契約凍結と別の有限検証が必要であり、本WorkはCOMPLETE_STOP。\n')
    decision={'status':'RD02_DIRECT_DOWNSIDE_COMPLETE_DEVELOPMENT','performance_status':'NO_INCREMENT_UNDER_TESTED_DESIGN','descriptive_secondary_status':['RANKING_SIGNAL_ONLY_NOT_PROBABILITY_READY','DOWNSIDE_WINNER_TRADEOFF'],'integrity':'PASS_SAME_AUTHOR_SEPARATE_IMPLEMENTATION','coverage':'PASS_1039_OF_1039_ALL3_METHODS_ALL8BLOCKS','D_FULL_prediction_screen':False,'D_FULL_selectivity_screen':False,'within_rank':'A_B_C_DESCRIPTIVE_TAIL_ENRICHMENT; S_INCONCLUSIVE_SMALL_N; Winner_preservation_insufficient','D_FULL_added_value_over_PRICE':'pooled_q3_q5_proper_score_improvement; q2_qNEG_multiclass_worse; overall_increment_not_established','added_value_over_B0_RD01':'B0_full_q3_q5_improvement_but_block_screen_failed; RD01_paired_q3_improved_q5_mixed_LATER_ASOF_REFERENCE','winner_preservation':'INSUFFICIENT','probability_ready':False,'reproduction':'PASS_ONE_CAMPAIGN_NO_REFIT_EXACT_BYTES','successful_fit_N':24,'base_attempt_N':25,'preprocessing_fit_N':24,'repair_cycles_N':5,'repair_limit':20,'completed_blocks':list(range(1,9)),'actual_GET_complete_blocks':list(range(1,9)),'selectedNewRank':None,'mainRank':'SAVED_R0','mainRankChanged':False,'mainCapital':'CAPITAL_MAX3_SLOT_RESERVE_V1','mainExit':'SHARP_DROP_FIRST_OBSERVED_EXIT_V0','CapitalReplay':0,'capitalImprovement':'NOT_EVALUATED','freshValidation':'NOT_RUN','firstLayerChanged':False,'additionalPreBuyP1GateActivated':False,'safety':SAFETY,'publication_status':'AWAITING_FINAL_ACTUAL_GET','terminal_status':'COMPLETE_STOP','next_hypothesis':'Separate BUY_INTENT downside persistence from movement-magnitude risk to preserve U10 and realized>=+5 Winners at the same tail-capture budget; design only'}
    save(PUB/'FINAL_DECISION.json',decision)
    print('FINAL_REPORT_AND_NO_INCREMENT_DECISION_WRITTEN')

if __name__=='__main__':run()
