"""Pre-outcome immutable experiment seal; no feature build and no model fit."""
import sys,os,platform,inspect,fnmatch,collections,zipfile,json,yaml
import numpy,scipy,sklearn,joblib
from sklearn.ensemble import HistGradientBoostingClassifier
from threadpoolctl import threadpool_info
from common import *
from prepare import sources

def main():
 core,split=sources();PUB.mkdir(parents=True,exist_ok=True);PRIVATE.mkdir(parents=True,exist_ok=True)
 workflow=read(INPUT/'workflow_tree.json')['tree'];raw=read(INPUT/'rd01/rd01/private/WORKFLOW_TRIGGER_RAW.json')
 matched=[];checked=[]
 for r in workflow:
  if r['type']!='blob' or not r['path'].startswith('workflows/'):continue
  path='.github/'+r['path'];body=raw[path].encode();assert blob(body)==r['sha']
  d=yaml.safe_load(body);triggers=d.get('on',d.get(True,{}));push=triggers.get('push') if isinstance(triggers,dict) else {} if 'push' in (triggers or []) else None
  if push is not None:
   push=push or {};branches=push.get('branches');ignore=push.get('branches-ignore',[])
   positive=branches is None or any(fnmatch.fnmatch(BRANCH,p) for p in branches)
   if positive and not any(fnmatch.fnmatch(BRANCH,p) for p in ignore):matched.append(path)
  checked.append({'path':path,'git_blob':r['sha'],'matched_research_push':path in matched})
 assert len(checked)==348 and not matched
 save(PRIVATE/'WORKFLOW_TRIGGER_BLOB_AUDIT.json',checked,once=True)
 save(PUB/'WORKFLOW_BRANCH_SAFETY.json',{'public_pinned_HEAD':'6375a00458936078186a1637795241fedf0236a1','definitions_checked':348,'inherited_content_vs_actual_GET_tree_git_blob_mismatches':0,'research_branch':BRANCH,'push_matches':matched,'private_workflow_tree':'NO_.github_IN_ACTUAL_GET_ROOT','workflow_dispatch':0,'orders':0,'main_merge':0,'skip_ci_used_as_safety_proof':False},once=True)
 source={'document_id':DOC,'public_repo':'Iam-2squared/ark-terminal','private_repo':'Iam-2squared/ark-capital-private-','RD01_HEAD_actual_GET':'6375a00458936078186a1637795241fedf0236a1','RD01_report_blob':'7dea60504c83463763915bf2d5b405f605ec2b85','RD01_asof_blob':'5fe72206cfb0446c77d5e29bdeba53ab50394ece','RD01_private_commit':'cfb6c9277de332a7eeee95a78d6313fc62452355','RD01_carrier':pin(INPUT/'RD01_PRIVATE.tar.xz'),'shared_source_private_commit':'8d02f4520cd52cbf92a0a04f6d0928289a2098e2','shared_source_manifest_path':'research/capital-v5-vacancy-admission-ad01-20261007/shared/SHARED_INPUTS_MANIFEST.json','shared_source_carrier':pin(INPUT/'SHARED_INPUTS.tar.xz'),'all49_shared_member_pins':'PASS','all_RD01_member_pins':'PASS','main_exit_freeze_commit':'30519cc85042a36097db54a70471de7bc679794e','main_exit_freeze_path':'research/exit-sharp-drop-overlay-counterfactual-20261007/MAIN_EXIT_FREEZE_20261007.json','main_exit_freeze':pin(INPUT/'rd01/rd01_sources/exitfreeze.json'),'corrected_exit_private_commit':'03c013cd4d9b4f94340cda8f14d1927ac68b9531','corrected_exit_carrier':pin(INPUT/'EXIT_COMPLETION.tar.xz'),'corrected_numeric_adapter':pin(INPUT/'numeric_adapter.py'),'CapitalV5_commit':'710656491be06235901b45c50a8b5cbd714ba4eb','staircase_git_blob':pin(INPUT/'shared/native/staircase.py')['git_blob'],'State_frozen_trace_archive':pin(INPUT/'STATE9_V2_FROZEN_TRACE_ARCHIVE.zip'),'State_kernel_recomputations':0,'original_first_intent_scheduler':{p.name:pin(p) for p in (INPUT/'entry_contract').glob('*') if p.is_file()},'same_RD01_branch_additional_receipt_delta':'NO_NEW_HEAD; inherited_receipt_and_confirmation_read','actual_arrival':'UNKNOWN','source_authority_differences':[]}
 save(PUB/'SOURCE_BINDING.json',source,once=True)
 save(PUB/'REUSE_AND_DELTA_ONLY.json',{'reuse':['CORE1600 IDs / 58 Development sessions / warmup20 / existing8 rolling-origin blocks','Frozen first_intent exact row ID and timestamp','saved1039 R_NEW / unknown reasons / U labels / R0 native reference / RD01 saved q','selected within-session raw slices and frozen full State9 trace','fixed native costs / repaired EXIT / canonical15:20 EOD / V5 implementation'],'new':['one fixed BUY_INTENT feature campaign<=1600 IDs','previously unsaved warmup new-exit labels<=561 once each','3 direct 5-class models / <=24 fits','first OOF / diagnostic evaluation / independent audit / one saved-model reproduction'],'not_reused_as_X':['old score bundle','HL0/D1/D2/RD01 R1/R2','R0 rank/ML/m2/m3/m5','actual fill clock/delay/open','outcomes/U/future EXIT/State/Capital availability'],'old_base_refit':0,'old_score_inference':0,'source_recovery':0,'new_periods':0,'P1_additional_prebuy_gate':False},once=True)
 save(PUB/'RD01_COMPARISON_SCOPE.json',{'scope':'ADAPTIVE_ITERATIVE_DEVELOPMENT','RD01_asof':'native fill historical contract; strict BUY_INTENT NOT_CERTIFIED','RD02_asof':'frozen first BUY_INTENT','old_predictions':'LATER_ASOF_REFERENCE','same_information_set_comparison':False,'differences_confounded':['earlier asof','warmup train support','raw/State representation','direct 5-class model'],'RD01_known_prediction_N_reference':755,'old_R1_R2_used_as_new_learning_X':False},once=True)
 save(PUB/'CUTOFF_ASOF_CONTRACT.json',{'t_x':'Frozen FIRST_ENTRY first_intent.intent_minute and row_id','raw':'same-session closed regular bar; start+1<=t_x, historical assumed available_at=start+1; lineage required','scheduler_order':'native causal_features processes closed bar and State checkpoint queue <= now before feature row and FIRST_INTENT decision; same timestamp legal under this frozen order','proof_files':{n:pin(INPUT/'entry_contract'/n) for n in ['causal_features.py','first_entry.py','price_primitives.py','P1_Q70_ENTRY_CONTRACT.json']},'State':'exact saved prefix available_at<=t_x; observed_at=as_of; current_semantics_observed and accepted current row; carried/expired state not current','calendar':'regular raw starts [540,690) / [750,925); closed times start+1. Lunch691 and terminal931 retained for causal invalidation but not regular-window occupancy','windows':'last5/20/60 scheduled active minutes already elapsed in same session; missing schedule lowers coverage, not last observed bars','actual_arrival':'UNKNOWN','label_cost_reference':'original frozen buy debit; never X price reference','X_price_reference':'last legal valid closed raw Close','prohibited':['fill clock','actual delay','fill Open/H/L/C/Volume/Value','future states/EXIT/price','R/U/Winner labels','old q/rank/score','symbol/date/fold feature','funded/E_ONLY/C_ONLY/future capital state']},once=True)
 formulas=['valid raw count / elapsed scheduled count','log(last C / first O), set statistic may include gaps','log(max H / min L)','log(last C / max H)','log(last C / min L)','sum adjacent segment log return / sum absolute adjacent segment log return; zero denominator with pairs=0, no pairs=missing','sqrt(mean adjacent segment log return squared)','min segment log(C / running segment close high), segment length>=2','negative adjacent close-return count / valid pair count','negative-return destination bar Volume sum / all valid-pair destination bar Volume sum; zero denominator=missing','log1p(mean observed raw Volume)','log1p(mean observed raw Trading Value)']
 schema={'numeric_column_order':PRICE+STATE,'PRICE_count':45,'STATE_numeric_count':25,'categorical_column_order':CAT,'vocabulary':VOCAB,'vocabulary_basis':'frozen State metadata enum (all components read for enum only, no category frequencies/outcomes); all nonempty reset enum combinations predefined','frozen_reset_enum':RESET_ENUM,'price_windows':{str(w):dict(zip(PRICE[(i*12):(i+1)*12],formulas)) for i,w in enumerate([5,20,60])},'price_extra':{'body':'(C-O)/(H-L)','upper_wick':'(H-max(O,C))/(H-L)','lower_wick':'(min(O,C)-L)/(H-L)','flat':'H=L implies valid flat OHLC and m/n/o=0','volume5_20_log':'log(mean valid V5 / mean valid V20), both positive','value5_20_log':'log(mean valid Va5 / mean valid Va20), both positive','active_minutes':'count scheduled regular raw closes<=t_x since session regular open','raw_age':'scheduled active-time difference cutoff-last legal valid raw close','raw_breaks60':'number of observed raw segment starts in last60 schedule after gap/reset/lunch; initial start excluded'},'state_windows':{'20/60':'9 valid observed state checkpoint counts / all valid State checkpoints, coverage valid / scheduled, changes across consecutive same-segment checkpoints only'},'state_extra':{'run_duration':'active(t_x)-active(first observed checkpoint of current state run); first checkpoint duration0','last_valid_age':'active(t_x)-active(last valid saved checkpoint), age is not carry authorization','breaks60':'number frozen SEGMENT_BREAK events in last60 scheduled regular checkpoint times'},'raw_validity':'finite Decimal OHLC envelope L>0, Vo>=0, Va>=0, lineage present; no rounding/epsilon','Volume_unit':'original JQuants equities bars minute Vo, shares; unchanged','TradingValue_unit':'original JQuants Va, JPY; unchanged','flat_no_pair_missing_rules':'00_READ_FIRST sections5.2/5.3','pair_continuity':'valid raw, consecutive wall-clock close minutes, same frozen segment; reset/gap/lunch breaks; no intersession carry','missing':'train median plus every numeric indicator; true missing vs evidence gap distinct','P0_reused_feature_columns':0,'P0_reason':'stored calculations/windows differ; all new columns computed under this contract','source_member_binding_private':'FEATURE_SOURCE_BINDING.jsonl.gz','availability_private':'FEATURE_AVAILABILITY.csv','all_feature_formulas_are_fixed_before_build':True}
 save(PUB/'FEATURE_FORMULAS_AND_SCHEMA.json',schema,once=True)
 save(PUB/'TARGET_5CLASS_AND_12BAND_CONTRACT.json',{'class_order':CLASSES,'target5':['R<=-5','-5<R<=-3','-3<R<=-2','-2<R<0','R>=0'],'q5':'p0','q3':'p0+p1','q2':'p0+p1+p2','qNEG':'p0+p1+p2+p3','12band_order':BANDS,'12band_boundaries':['R>=5','4<=R<5','3<=R<4','2<=R<3','1<=R<2','0<R<1','-1<R<0','-2<R<=-1','-3<R<=-2','-4<R<=-3','-5<R<=-4','R<=-5','R=0','UNKNOWN'],'formal_classification':'exact rational debit/credit before rounding; no epsilon','known_denominator':'R known within each selected collection','unknown_denominator':'all selected collection','empty':'0/0 N/A','q_is_calibrated_probability':False},once=True)
 env={'Python':sys.version,'numpy':numpy.__version__,'scipy':scipy.__version__,'sklearn':sklearn.__version__,'joblib':joblib.__version__,'platform':platform.platform(),'executable':sys.executable,'dtype_input_optimizer':'float64','sklearn_internal_bin_dtype':'uint8; internal histogram grows per sklearn1.8 implementation','threads':1,'threadpool_configuration':threadpool_info(),'model_format':'pickle protocol5; includes preprocessing and class order','HGB_signature':str(inspect.signature(HistGradientBoostingClassifier)),'official_api':'https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.HistGradientBoostingClassifier.html','official_multiclass':'one tree per class per round;100 rounds=500 trees per fit','library_selection':'one installed compatible version fixed; no version search','optimizer':'scipy L-BFGS-B float64, exact custom objective, gtol1e-7/ftol0/maxls50/maxiter1000','deterministic_payload':'sorted compact UTF8 JSON + newline; gzip mtime0; xz metadata-fixed tar; no timestamp in q payload'}
 save(PUB/'ENVIRONMENT_LOCK.json',env,once=True)
 hgb=dict(HistGradientBoostingClassifier(loss='log_loss',learning_rate=.05,max_iter=100,max_leaf_nodes=7,max_depth=3,min_samples_leaf=20,l2_regularization=1.,max_bins=64,max_features=1.,categorical_features=None,monotonic_cst=None,interaction_cst=None,warm_start=False,early_stopping=False,scoring='loss',validation_fraction=.1,n_iter_no_change=10,tol=1e-7,verbose=0,random_state=57,class_weight=None).get_params())
 pre={'document_id':DOC,'primary':'D-FULL','method_order':METHODS,'class_order':CLASSES,'inputs':{'D-LINEAR':'PRICE45 + STATE25 + fixed4 onehot','D-PRICE':'PRICE45','D-FULL':'PRICE45 + STATE25 + fixed4 onehot'},'preprocessing':'same train ID; per-model median / every numeric missing indicator; linear train mean/std including onehot; trees no scaling; train-all-missing median0 std0 scale1','linear_objective':'mean multiclass NLL + .005 sum beta^2; intercept unregularized; NONNEG reference coefficients/intercept0; all parameters initial0','linear_optimizer':{'method':'L-BFGS-B','maxiter':1000,'gtol':1e-7,'ftol':0,'maxls':50},'HGB_all_resolved_parameters':hgb,'sample_weight':None,'fit_support':{'known_R':200,'sessions':10,'each5class':3},'fit_support_missing_policy':'common train mask valid for all families; model-specific prediction mask; no combined price fallback','base_fit_limit':24,'calibration_fits':0,'fit_interruption_retry_limit':4,'technical_repair_limit':20,'warmup_label_materialization_limit':561,'feature_campaign_limit':1,'feature_ID_limit':1600,'class_weights_oversampling_SMOTE':False,'old_refits':0,'old_score_inference':0,'threshold_search':0,'new_rank_policy':0,'CapitalReplay':0,'split_pin':pin(INPUT/'shared/inputs/split'),'feature_schema_pin':pin(PUB/'FEATURE_FORMULAS_AND_SCHEMA.json'),'environment_pin':pin(PUB/'ENVIRONMENT_LOCK.json'),'precommit_implementation_pins':{p.name:pin(p) for p in (WORK/'implementation').glob('*.py')},'gates_authority':'00_READ_FIRST.txt sections12/16; unchanged','canary_and_artificial_tests':'all user section8/13; no tuning based on evaluation','privacy':'counts n/N preserved; public singleton continuous statistics suppressed; individual IDs/sources/models private','worker_separation':'manager outcomes retained privately; separate OS user65534 and open-audit allowlist of current view/runtime/code; fit input train X/train R only; predict input current X/model only; evaluator joins labels after q seal','mount_namespace':'bwrap attempted; unshare namespace Operation not permitted; OS-level file permissions used instead; not physical blind audit','fresh_validation':'NOT_RUN','safety':SAFETY}
 save(PUB/'MODEL_PRECOMMIT.json',pre,once=True)
 rowsmanifest={'source_PIN':pin(INPUT/'shared/inputs/core_runtime'),'unique_ID_N':1600,'evaluation_ID_N':1039,'warmup_ID_N':561,'sessions':58,'evaluation_sessions':38,'warmup_sessions':20,'split':split,'duplicate_entry_sample_expansion':0,'physical_row_random_split':False,'maturity':'label maturity earlier than block first eval session 00:00+09; train sessions strictly earlier','train_ID_details':'PRIVATE per-block TRAIN_ID_MANIFEST.json'}
 save(PUB/'TRAIN_AND_EVAL_ID_MANIFEST.json',rowsmanifest,once=True)
 ledger={'repair_cycle_limit':20,'repair_cycles':[{'cycle':1,'stage':'source extraction before feature/label/fit','event':'local books member became truncated after initial correct extraction; cause not established','expected_bytes':7229451,'observed_bytes':2801664,'action':'restored that exact member from already hash-verified SHARED_INPUTS carrier; source bytes and SHA then matched','semantic_change':False,'fits_or_labels_repeated':0}],'transport_attempts':[{'id':1,'action':'Git shell proxy ls-remote','status':'FAILED_NO_CREDENTIAL_USERNAME','retry':0},{'id':2,'action':'full recursive public GitHub repo tree','status':'TRANSPORT_CLOSED','alternative':'scoped tree GET'},{'id':3,'action':'URL branch endpoint with encoded slash','status':'INVALID_PATH','alternative':'git/ref/heads endpoint'},{'id':4,'action':'guessed public corrected numeric_adapter paths (two)','status':'404','alternative':'exact private completion receipt member'},{'id':5,'action':'bwrap worker mount namespace','status':'UNSHARE_OPERATION_NOT_PERMITTED','alternative':'separate unprivileged UID and data file permissions plus audit hook'}],'fit_attempts':[],'fit_interruption_reattempt_N':0,'completed_fit_repetition_N':0,'source_recovery_N':0,'spec_preimplementation_corrections':'Before build/fit: vocab from frozen enum; explicit nonregular current-State invalidation; all74 availability; warmup suffix gap kept UNKNOWN. No outcome feedback.'}
 save(PUB/'REPAIR_AND_ATTEMPT_LEDGER.json',ledger,once=True)
 save(PUB/'FIT_LEDGER.json',{'successful_fit_N':0,'base_attempt_N':0,'preprocessing_fit_N':0,'calibration_fit_N':0,'old_base_refit_N':0,'old_score_reinference_N':0,'rows':[]})
 save(PUB/'BLOCK_CHECKPOINTS.json',{'complete_blocks':[],'prediction_seals':{},'actual_GET_complete_blocks':[]})
 save(PUB/'CURRENT_STATE.json',{'stage':'S0 SOURCE_AND_SPEC_SEALED','base_fit_N':0,'feature_campaign_N':0,'selectedNewRank':None,'mainRankChanged':False,'additionalPreBuyP1GateActivated':False,'mainCapital':'CAPITAL_MAX3_SLOT_RESERVE_V1','mainExit':'SHARP_DROP_FIRST_OBSERVED_EXIT_V0','mainRank':'SAVED_R0','CapitalReplay':0,'capitalImprovement':'NOT_EVALUATED','freshValidation':'NOT_RUN','Protected_Fresh_Prospective_opens':0,'safety':SAFETY})
 print(json.dumps({'stage':'S0','source_pin':'PASS','workflows':len(checked),'research_push_matches':len(matched),'precommit':pin(PUB/'MODEL_PRECOMMIT.json')}))

if __name__=='__main__':main()
