"""One independent full reconstruction plus attribution/solver verification."""
from independent_engine import *
from independent_replay import reconstruct
from independent_evaluation import *
from control import save,checkpoint,now,SAFETY
def main():
 assert not (P/'INDEPENDENT_FULL_AUDIT_STARTED.json').exists(),'INDEPENDENT_AUDIT_ALREADY_STARTED_NO_REPEAT'
 save(P/'INDEPENDENT_FULL_AUDIT_STARTED.json',{'exact_jst':now(),'single_build':True,'primary_imports':0})
 audit=Audit();stream=rows(P/'INDEPENDENT_CURRENT_SIZING_RUNTIME.jsonl.gz');tables=read(P/'INDEPENDENT_PAST_TABLES.json');rt={r['entry_id']:r for r in stream};teacher={r['entry_id']:r for r in rows(I/'evaluation/TEACHERS_EVALUATION.jsonl.gz')};books={r['entry_id']:r for r in rows(I/'execution/MARKET_EXECUTION_BOOK_V2.jsonl.gz')};v5=Path(read(W/'v5_saved_paths.json')['private']);old=W/'authority/v9/private';rr={};dsall={}
 for p,folder,arm in [('v5',v5,'CAPITAL_MAX3_SLOT_RESERVE_V1'),('I2',old,'QUALITY_PARETO_U2_U3_TENURE_MAX3_V1')]:rr[p],dsall[p]=make_rows(folder,arm,rt,books,teacher,audit)
 identity_audit(rr,audit);matrix_audit(rr,audit);signal_audit(rr,rt,teacher,audit);algebra_audit(rr['I2'],audit);shadow_audit(rr['I2'],audit);hindsight=hindsight_audit(audit)
 quality_saved=read(O/'QUALITY_RETENTION_AND_PAIRED_DELTA.json')['profiles'];cap_saved=read(O/'CAPITAL_ROLLING20_RESULT.json')['profiles'];mask={r['entry_id'] for r in rows(PIN/'COMMON_EVAL_MASK.jsonl.gz') if r['included']};base={r['entry_id']:r for r in rr['I2']};bd=dsall['I2'];official={};metrics_all={}
 for arm in ARMS:
  dec,metrics,trades,frames,daily=reconstruct(arm,stream,tables,audit);r,dm=make_rows(P,arm,rt,books,teacher,audit);m={x['entry_id']:x for x in r};q=aggregate(r);saved=quality_saved[arm];compare(audit,arm+'/quality',q,saved['funded_quality']);metrics_all[arm]=metrics
  audit.check(arm+'/quality_support',set(m)<=mask);integ={'cash_negative':sum(c['cash']<0 for c in frames),'MAX3_excess':sum(c['concurrent']>3 for c in frames),'same_symbol_open':sum(len({p['symbol'] for p in d['held_before_batch']})!=len(d['held_before_batch']) for d in dm.values()),'cutoff_funded':sum(x['entry_minute']>=920 for x in r),'nonlot100':sum(d['quantity']%100!=0 for d in dec),'execution_unresolved':0,'causal_canary_fail':0,'leakage':0};compare(audit,arm+'/integrity',integ,saved['integrity'])
  retained=q['U5']>=53 and q['U10']>=26 and q['Medium']>=32 and q['below2_rate']<=.36024845 and q['below3_rate']<=.47204969 and not any(integ.values());floor=q['U5']>=50 and q['U10']>=26 and q['Medium']>=27 and q['below2_rate']<=.38666667 and q['below3_rate']<=.48666667;capital=metrics['rolling20_median']>1.1991541915 and metrics['rolling20_arithmetic_mean']>1.1906460126 and metrics['geometric_mean_daily_return']>.01032420041;reference=read(ROOT/'docs/evidence/capital-v9-quality-aware-max3-integration-20261005-v1/QUALITY_PARETO_U2_U3_TENURE_MAX3_V1_RESULT.json');rel=metrics['rolling20_median']>reference['rolling20_median'] and metrics['rolling20_arithmetic_mean']>reference['rolling20_arithmetic_mean'] and metrics['geometric_mean_daily_return']>reference['geometric_mean_daily_return'];official[arm]={'retained':retained,'floor':floor,'capital':capital,'three_direction':rel,'relative':rel and floor}
  for name,val in [('retention_point_PASS',retained),('v5_floor_PASS',floor)]:audit.check(arm+'/'+name,val==saved[name])
  for name,val in [('v5_economics_PASS',capital),('Capital_point_PASS',capital and retained),('I2_three_direction_PASS',rel),('RELATIVE_CAPITAL_PROGRESS',rel and floor)]:audit.check(arm+'/'+name,val==cap_saved[arm][name])
  fg={'Q1_U5_ge53':q['U5']>=53,'Q2_U10_ge26':q['U10']>=26,'Q3_Medium_ge32':q['Medium']>=32,'Q4_Weak_le36_024845pct':q['below2_rate']<=.36024845,'Q5_below3_le47_204969pct':q['below3_rate']<=.47204969,'Q6_integrity0':not any(integ.values()),'Q7_independent_mismatch0':'PENDING'};compare(audit,arm+'/Q_gates',fg,saved['quality_retention_gates']);compare(audit,arm+'/floor_gates',{'U5_ge50':q['U5']>=50,'U10_ge26':q['U10']>=26,'Medium_ge27':q['Medium']>=27,'Weak_le38_666667pct':q['below2_rate']<=.38666667,'below3_le48_666667pct':q['below3_rate']<=.48666667},saved['v5_floor_gates'])
  common=set(m)&set(base);g=aggregate([m[k] for k in set(m)-set(base)]);l=aggregate([base[k] for k in set(base)-set(m)]);dq=sum(((m[k]['quantity']-base[k]['quantity'])//100*F(m[k]['unit_100share_PnL']) for k in common),F(0));pair=saved['paired_delta'];compare(audit,arm+'/gained',g,pair['GAINED_FUNDING_vs_I2']);compare(audit,arm+'/lost',l,pair['LOST_FUNDING_vs_I2']);audit.money(arm+'/common_qty_delta',dq,pair['COMMON_FUNDED']['common_quantity_PnL_delta']);audit.check(arm+'/commonN',len(common)==pair['COMMON_FUNDED']['N']);audit.money(arm+'/actualDelta',F(q['actual_PnL'])-F(aggregate(rr['I2'])['actual_PnL']),pair['actual_PnL_delta_vs_I2']);compare(audit,arm+'/net',{f:g[f]-l[f] for f in ('U5','U10','Medium','Weak','realized_positive_N','realized_loser_le0_N')},pair['NET_counts'])
  cg=rows(P/f'{arm}_COMMON_QUANTITY_DELTA.jsonl.gz')
  for z in cg:
   k=z['entry_id'];audit.check(k+'/common_qty',z['q_I2']==base[k]['quantity'] and z['q_new']==m[k]['quantity'] and z['quantity_delta']==m[k]['quantity']-base[k]['quantity']);audit.money(k+'/unit',z['unit_100share_PnL'],m[k]['unit_100share_PnL']);audit.money(k+'/qtyPNL',z['common_quantity_PnL_delta'],F(m[k]['unit_100share_PnL'])*F(z['quantity_delta'],100))
  for name,test in [('Weak',lambda z:z['coarse_bucket']=='Weak'),('Low',lambda z:z['coarse_bucket']=='Low'),('Medium',lambda z:z['coarse_bucket']=='Medium'),('Big',lambda z:z['coarse_bucket']=='Big'),('Mega',lambda z:z['coarse_bucket']=='Mega'),('U5',lambda z:z['coarse_bucket'] in ('Big','Mega')),('U10',lambda z:z['coarse_bucket']=='Mega'),('realized_le0',lambda z:z['realized_net_return']<=0),('realized_ge1pct',lambda z:z['realized_net_return']>=.01)]:
   z=[m[k] for k in common if test(m[k])];compare(audit,arm+'/quantity_group/'+name,{'N':len(z),'quantity_delta':sum(x['quantity']-base[x['entry_id']]['quantity'] for x in z),'exact_common_quantity_PnL_delta':str(sum((F(x['unit_100share_PnL'])*F(x['quantity']-base[x['entry_id']]['quantity'],100) for x in z),F(0)))},pair['COMMON_FUNDED']['quantity_groups'][name])
  def empty(k):
   t=teacher[k];r0=rt[k];return {'entry_id':k,'session':r0['session'],'entry_minute':r0['entry_minute'],'slot':dm[k].get('funded_slot',0),'potential_return':t['potential_return'],'realized_net_return':t['realized_net_return'] or 0.,'pP':r0['pP'],'q2':r0['q2'],'q3':r0['q3'],'consensus_minrank':r0['consensus_weight'],'lots':0,'buy_debit':'0','actual_PnL':'0','unit_100share_PnL':str((F(t['sell_effective'])-F(t['buy_effective']))*100) if t['sell_effective'] and t['buy_effective'] else '0'}
  newmax=[empty(k) for k in dm if dm[k]['reason']=='MAX3_FULL' and bd[k]['reason']!='MAX3_FULL'];recover=[m[k] for k in m if bd[k]['reason']=='CASH_OR_LOT'];newcash=[empty(k) for k in dm if dm[k]['reason']=='CASH_OR_LOT' and bd[k]['reason']!='CASH_OR_LOT']
  for name,z in [('NEW_MAX3_MISS_vs_I2',newmax),('CASH_RECOVERY_vs_I2',recover),('NEW_CASH_MISS_vs_I2',newcash)]:compare(audit,arm+'/'+name,aggregate(z),pair[name])
  for label,t,total in [('U5',.05,170),('U10',.10,67)]:
   counts=Counter(d['reason'] for d in dec if d['entry_id'] in mask and teacher[d['entry_id']]['potential_return']>=t);audit.check(arm+'/'+label+'/conservation',sum(counts.values())==total);compare(audit,arm+'/'+label+'/reasons',dict(counts),saved['U5_U10_reason_conservation'][label])
  alloc=saved['allocation_diagnostics'];buy=q['buy_notional']
  for name,values,selector in [('slot',[str(s) for s in (1,2,3)],lambda r,v:str(r['slot'])==v),('band',BANDS[:3],lambda r,v:r['band']==v),('Entry_hour',[str(h) for h in range(9,16)],lambda r,v:str(r['entry_minute']//60)==v),('potential_bucket',FINE,lambda r,v:fine(r['potential_return'])==v)]:
   for value in values:compare(audit,arm+'/'+name+'/'+value,aggregate([x for x in r if selector(x,value)],buy),alloc[name][value])
  for name,pred in [('Weak',lambda x:x['potential_return']<.02),('Medium+',lambda x:x['potential_return']>=.03),('U5',lambda x:x['potential_return']>=.05),('U10',lambda x:x['potential_return']>=.10)]:compare(audit,arm+'/exposure/'+name,aggregate([x for x in r if pred(x)],buy),alloc['exposure'][name])
  compare(audit,arm+'/quantity_diag',{'mean_lots':q['mean_lots'],'median_lots':q['median_lots'],'candidate_cap_hit_N':sum(d.get('cap_hit',False) for d in dm.values() if d['reason']=='FUNDED'),'candidate_cap_hit_definition':'next one lot would exceed frozen band equity cap','waterfill_lot_N':sum(d.get('water_fill_lots',0) for d in dm.values()),'first_pass_zero_N':sum(d.get('first_pass_quantity')==0 for d in dm.values() if 'first_pass_quantity' in d)},alloc['quantity'])
 eligible=[a for a,z in official.items() if z['retained'] and z['capital']]
 def ordering(a,hit=False):
  z=metrics_all[a];v=(-z['rolling20_median'],-z['rolling20_arithmetic_mean'],-z['geometric_mean_daily_return'],-z['final_equity'],z['max_drawdown'],ARMS.index(a));return (-z['north_star_hit_N'],)+v if hit else v
 selected=sorted(eligible,key=lambda a:ordering(a,True))[0] if eligible else None;pool=[a for a,z in official.items() if z['retained']] or [a for a,z in official.items() if z['floor']];diag=selected or (sorted(pool,key=ordering)[0] if pool else 'QUALITY_PARETO_U2_U3_TENURE_MAX3_V1')
 if selected:
  hit=metrics_all[selected]['north_star_hit_N']>0;status='V10_NORTH_STAR_HIT' if hit else 'V10_CAPITAL_IMPROVED';bottleneck=None if hit else 'NORTH_STAR_CAPITAL_GAP'
 else:
  if diag in ARMS and official[diag]['retained'] and official[diag]['relative']:bottleneck='SIZING_REMAINS'
  elif all(not z['capital'] and not z['three_direction'] for z in official.values()):bottleneck='REALIZED_MONETIZATION_SIGNAL'
  else:bottleneck='SIZING_INDUCED_FUNDING_DISTORTION'
  if any(z['relative'] for z in official.values()):status='V10_PARTIAL_SIZING_PROGRESS'
  elif all(not z['capital'] and not z['three_direction'] for z in official.values()):status='V10_REALIZED_MONETIZATION_LIMIT'
  elif any(not z['retained'] for z in official.values()):status='V10_SIZING_QUALITY_REGRESSION'
  else:status='V10_NO_GO'
 short={ARMS[0]:'S1',ARMS[1]:'S2','QUALITY_PARETO_U2_U3_TENURE_MAX3_V1':'I2 saved'};decision={'status':status,'selectedCapitalCandidate':short[selected] if selected else None,'diagnosticArm':short[diag],'NEXT_BOTTLENECK':bottleneck,'eligible':eligible,'adoption':selected is not None};compare(audit,'winner_bottleneck',decision,read(O/'PROVISIONAL_WINNER_AND_BOTTLENECK.json'))
 result={'exact_jst':now(),'status':'PASS' if not audit.mismatches else 'CONTRACT_FAIL','checks':audit.checks,'mismatch_N':len(audit.mismatches),'mismatches':audit.mismatches,'max_float_delta':audit.max_float_delta,'float_tolerance':1e-12,'money_quantity':'EXACT','primary_runtime_replay_evaluator_imports':0,'implementation_independence':True,'upstream_market_source_independence_claim':False,'preparation_recomputed':False,'independent_portfolio_reconstructions':2,'saved_control_replays':0,'independent_static_hindsight':hindsight,'independent_decision':decision,'official_gates':official,'Safety':SAFETY};save(O/'INDEPENDENT_AUDIT.json',result);print(json.dumps(result),flush=True);assert not audit.mismatches,'FULL_INDEPENDENT_CONTRACT_FAIL_STOP';checkpoint('M13_FULL_INDEPENDENT_AUDIT',{'checks':audit.checks,'mismatch_N':0,'independent_integer_batch_N':hindsight['batch_N']},'Finalize Q7/gates/winner/bottleneck without new research')
if __name__=='__main__':main()
