"""Fixed gates/selection, Japanese report/private delivery and mandatory M15 STOP."""
from control import *
from evaluate import choose
import zipfile
def finalize():
    audit=read(OUT/'INDEPENDENT_AUDIT.json');assert audit['mismatch_N']==0 and audit['status']=='PASS'
    q=read(OUT/'QUALITY_RETENTION_AND_PAIRED_DELTA.json')['profiles'];c=read(OUT/'CAPITAL_ROLLING20_RESULT.json')['profiles'];decision=choose(q,c);assert decision==audit['independent_decision'];gates={}
    for a in ARMS:
        gg=dict(q[a]['quality_retention_gates'],Q7_independent_mismatch0=True);gates[a]={'quality_retention_gates':gg,'V10_QUALITY_RETENTION_PASS':all(gg.values()),'v5_quality_floor':q[a]['v5_floor_gates'],'v5_quality_floor_PASS':q[a]['v5_floor_PASS'],'v5_capital_gates':c[a]['v5_economic_gates'],'V10_CAPITAL_IMPROVED':all(gg.values()) and c[a]['v5_economics_PASS'],'I2_relative_gates':c[a]['I2_relative_gates'],'RELATIVE_CAPITAL_PROGRESS':c[a]['RELATIVE_CAPITAL_PROGRESS']}
    save(OUT/'FINAL_GATE_RESULT.json',{'exact_jst':now(),'profiles':gates,'independent_mismatch_N':0,'frozen_gate_no_relaxation':True,'Safety':SAFETY});save(OUT/'WINNER_AND_NEXT_BOTTLENECK.json',{'exact_jst':now(),**decision,'selectedBigWinnerRank':'EXISTING_MOVE_P5','selectedAuxiliaryHeads':['MOVE_U2','MOVE_U3'],'selectionPolicy':I2,'newFits':0,'SizingReplays':2,'fresh_OOS_claim':False,'productionReady':False,'Safety':SAFETY});checkpoint('M14_WINNER_AND_NEXT_BOTTLENECK',decision,'Report/deliver and mandatory M15 fixed STOP; no further research')
def pack():
    decision=read(OUT/'WINNER_AND_NEXT_BOTTLENECK.json');files={str(p.relative_to(WORK)):p.read_bytes() for p in PRIVATE.rglob('*') if p.is_file() and '__pycache__' not in p.parts};parents={'authority/Ark_Capital_v9_Quality_Aware_MAX3_Integration_20261005_PRIVATE.zip':ROOT.parent/'project_sources/22-Ark_Capital_v9_Quality_Aware_MAX3_Integration_20261005_PRIVATE-1-.zip','authority/Ark_Capital_v5_MAX3_Slot_Intelligence_20261004_PRIVATE.zip':AUTH/'downloads/Ark_Capital_v5_MAX3_Slot_Intelligence_20261004_PRIVATE.zip'}
    for name,p in parents.items():files[name]=p.read_bytes()
    manifest={'schema':'CAPITAL_V10_PRIVATE_DELIVERY_V1','exact_jst':now(),'branch':BRANCH,'v9_parent_SHA':V9_SHA,'Main_parent_SHA':MAIN_SHA,'Quality_parent_SHA':QUALITY_SHA,'GitHub_basis':read(WORK/'latest_basis.json'),**{k:decision[k] for k in ('status','selectedCapitalCandidate','diagnosticArm','NEXT_BOTTLENECK')},'newFits':0,'SizingReplays':2,'new_repository_backed_code_and_reports_included':False,'immutable_parent_archives_may_include_historical_repository_snapshots':True,'fresh_OOS_claim':False,'productionReady':False,'Safety':SAFETY,'files':[{'path':p,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()} for p,data in sorted(files.items())]};raw=(json.dumps(manifest,sort_keys=True,indent=2,ensure_ascii=False)+'\n').encode();files['MANIFEST.json']=raw
    destination=ROOT.parent/'Ark_Capital_v10_Monetization_Sizing_20261005_PRIVATE.zip'
    with zipfile.ZipFile(destination,'x',compression=zipfile.ZIP_DEFLATED,compresslevel=6) as z:
        for p,data in sorted(files.items()):z.writestr(p,data)
    with zipfile.ZipFile(destination) as z:
        assert z.testzip() is None
        for r in manifest['files']:assert hashlib.sha256(z.read(r['path'])).hexdigest()==r['sha256']
    save(OUT/'PRIVATE_PACK_MANIFEST.json',{'exact_jst':now(),'filename':destination.name,'sha256':sha(destination),'bytes':destination.stat().st_size,'manifest':manifest,'manifest_sha256':hashlib.sha256(raw).hexdigest(),'member_N':len(files),'all_member_readback_PASS':True,'new_repository_backed_code_and_reports_included':False});print(json.dumps({'private_path':str(destination),'sha256':sha(destination),'bytes':destination.stat().st_size}),flush=True)
def report():
    q=read(OUT/'QUALITY_RETENTION_AND_PAIRED_DELTA.json')['profiles'];c=read(OUT/'CAPITAL_ROLLING20_RESULT.json')['profiles'];g=read(OUT/'FINAL_GATE_RESULT.json')['profiles'];w=read(OUT/'WINNER_AND_NEXT_BOTTLENECK.json');a=read(OUT/'V5_VS_I2_IDENTITY_QUANTITY_ATTRIBUTION.json');m=read(OUT/'POTENTIAL_REALIZED_MONETIZATION_MATRIX.json')['profiles'];sig=read(OUT/'SIGNAL_FROZEN_EXIT_MONETIZATION_DIAGNOSTIC.json')['populations'];alg=read(OUT/'SIZING_ALGEBRAIC_ATTRIBUTION.json')['totals'];shadow=read(OUT/'FIXED_IDENTITY_100SHARE_SHADOW.json');hind=read(OUT/'STATIC_BATCH_HINDSIGHT_SIZING_DIAGNOSTIC.json');audit=read(OUT/'INDEPENDENT_AUDIT.json');base5=read(V5/'MAIN_REPLAY_RESULT.json');base2=read(PARENT/f'{I2}_RESULT.json');labels={ARMS[0]:'S1',ARMS[1]:'S2'}
    lines=['# Capital v10 Monetization / Sizing — Final Report',f'作成: {now()}','', '## A. Executive / v9 authority','',f"status = {w['status']}。selectedCapitalCandidate = {json.dumps(w['selectedCapitalCandidate'])}。diagnosticArm = {w['diagnosticArm']}。NEXT_BOTTLENECK = {w['NEXT_BOTTLENECK']}。",f'v9 actual terminal HEAD: `{V9_SHA}`。Main parent `{MAIN_SHA}` / Quality parent `{QUALITY_SHA}`。旧v9はV14固定STOPを保持。新branchは`{BRANCH}`。','Sizing weightのみ変更。S1=1、S2=min(rp,r2,r3)。percentile=(1+completed-past training score < currentの件数)/(N+1)。label/test cross-section0。I2 gate・tenure・cap・target・waterfill・Entry/EXIT・MAX3・cash executionはFreeze。','仕様JSONは診断前commit `53b2f58d6698828f4ab67b048570ba0a178ef294` のactual GETで固定。診断を理由にSizing候補変更0。','Exposure=ITERATIVE_DEVELOPMENT_EVIDENCE。同じ58 Development sessionsの反復利用、OOF38連結。Fresh/OOS成功ではなく将来収益保証なし。','', '## B. North Star','', '|Profile|20d min|mean|median|max|2x|','|---|---:|---:|---:|---:|---:|']
    for name,e in [('v5 saved',base5),('I2 saved',base2)]+[(labels[x],c[x]['economics']) for x in ARMS]:lines.append(f"|{name}|{e['rolling20_minimum']:.10f}|{e['rolling20_arithmetic_mean']:.10f}|{e['rolling20_median']:.10f}|{e['rolling20_maximum']:.10f}|{e['north_star_hit_N']}/19|")
    lines+=['','19 rolling20 windowsは重なりがあり独立19標本ではない。Final38を1か月成績と呼ばない。','', '## C. Quality Retention','', '|Profile|N|Medium|U5|U10|<2|<3|','|---|---:|---:|---:|---:|---:|---:|']
    for name,z in [('v5 saved',m['v5']['all']),('I2 saved',m['I2']['all'])]+[(labels[x],q[x]['funded_quality']) for x in ARMS]:lines.append(f"|{name}|{z['N']}|{z['Medium']}|{z['U5']}|{z['U10']}|{z['below2_rate']*100:.6f}%|{z['below3_rate']*100:.6f}%|")
    for arm in ARMS:
        z=g[arm];lines.append(f"{labels[arm]}: I2 retention={'PASS' if z['V10_QUALITY_RETENTION_PASS'] else 'FAIL'} / v5 floor={'PASS' if z['v5_quality_floor_PASS'] else 'FAIL'} / v5 Capital={'PASS' if z['V10_CAPITAL_IMPROVED'] else 'FAIL'} / relative progress={'PASS' if z['RELATIVE_CAPITAL_PROGRESS'] else 'FAIL'}。Gate詳細: {json.dumps(z,ensure_ascii=False)}")
    lines+=['','正式retentionはU5>=53,U10>=26,Medium>=32,<2<=36.024845%,<3<=47.204969%,integrity0,audit0。v5 floorのみPASSでもadoption対象ではない。PotentialがPrimary、realizedはdiagnostic。','', '## D. v5 vs I2 Identity Decomposition','', '|Group|N|Medium|U5|U10|Weak|loser<=0|realized>=1%|unit-lot PnL|actual PnL|mean realized|median realized|','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|']
    for name,z in [('COMMON v5',a['COMMON_FUNDED']['v5']),('COMMON I2',a['COMMON_FUNDED']['I2']),('V5_ONLY',a['V5_ONLY_FUNDED']),('I2_ONLY',a['I2_ONLY_FUNDED'])]:lines.append(f"|{name}|{z['N']}|{z['Medium']}|{z['U5']}|{z['U10']}|{z['Weak']}|{z['realized_loser_le0_N']}|{z['realized_ge1pct_N']}|¥{float(z['unit_lot_PnL']):,.2f}|¥{float(z['actual_PnL']):,.2f}|{z['realized_mean']*100:.6f}%|{z['realized_median']*100:.6f}%|")
    lines += ['',f"COMMON_QUANTITY_PNL_DELTA = ¥{float(a['COMMON_FUNDED']['COMMON_QUANTITY_PNL_DELTA']):,.2f}。identity-side actual PnL差 = ¥{float(a['identity_side_actual_PnL_delta']):,.2f}。合計差 = ¥{float(a['total_actual_PnL_delta_I2_minus_v5']):,.2f}。Decimal exact conservation PASS。",'identity/quantity diagnosticであり一意の因果分解ではない。COMMONのEntry hour・slot・score分布はJSONに保存。','', '## E. Potential → Realized Monetization Matrix','', '|Profile / potential|N|lots|buy notional|share|unit-lot PnL|actual PnL|','|---|---:|---:|---:|---:|---:|---:|']
    for p in ('v5','I2'):
        for bucket,z in m[p]['fine'].items():lines.append(f"|{p} / {bucket}|{z['N']}|{z['lots']}|¥{float(z['buy_notional']):,.2f}|{z['notional_share']*100:.4f}%|¥{float(z['unit_lot_PnL']):,.2f}|¥{float(z['actual_PnL']):,.2f}|")
    lines+=['','|Profile / potential|realized mean|median|positive|>=1%|loser<=0|potential mean|giveback mean|ratio Q25 / median / Q75|','|---|---:|---:|---:|---:|---:|---:|---:|---|']
    for p in ('v5','I2'):
        for bucket,z in m[p]['fine'].items():
            fmt=lambda v:f'{v:.6f}' if v is not None else 'n/a';lines.append(f"|{p} / {bucket}|{z['realized_mean']*100:.6f}%|{z['realized_median']*100:.6f}%|{z['realized_positive_N']}/{z['N']}|{z['realized_ge1pct_N']}/{z['N']}|{z['realized_loser_le0_N']}/{z['N']}|{z['potential_mean']*100:.6f}%|{z['giveback_mean']*100:.6f}%|{fmt(z['monetization_ratio_Q25'])} / {fmt(z['monetization_ratio_median'])} / {fmt(z['monetization_ratio_Q75'])}|")
    lines+=['','ratioはpotential>0のみ。median/Q25/Q75を主表示しratio meanを使用しない。Weak/Low/Medium/Big/Mega coarse、return on deployed notional等の全fieldは`POTENTIAL_REALIZED_MONETIZATION_MATRIX.json`。','', '## F. Signal → Frozen EXIT Monetization','', '|Population|score|AUC >0|AUC >=1%|AUC <=0|Spearman realized|','|---|---|---:|---:|---:|---:|']
    for p,z in sig.items():
        for score,v in z['scores'].items():lines.append(f"|{p} N={z['N']}|{score}|{v['AUC_realized_gt0']:.6f}|{v['AUC_realized_ge1pct']:.6f}|{v['AUC_realized_le0']:.6f}|{v['Spearman_realized_return']:.6f}|")
    lines+=['','decile別realized mean/median/loser rateは`SIGNAL_FROZEN_EXIT_MONETIZATION_DIAGNOSTIC.json`。admissionのmissing realizedは除外数を明示。fit0。scoreは真の確率と呼ばない。Quality conditional CIが0を跨ぐ親の制約を保持し、HF1/HL0再fit0。','', '## G. Sizing Algebraic Attribution','',f"I2 actual PnL ¥{alg['actual_PnL_jpy']:,.2f} = session equal-lot algebraic ¥{alg['equal_lot_algebraic_PnL_jpy']:,.2f} + sizing covariance contribution ¥{alg['sizing_covariance_contribution_jpy']:,.2f}。identity unit-lot edge ¥{alg['identity_unit_lot_edge_jpy']:,.2f}。Fraction exact conservation PASS。",'sessionごとLbar=total lots/N。equal-lot referenceはfractional lotを含み、executable policyではない。価格・cap・session構成も含むため、このcovariance全額をbatch内weightだけで回収可能と解釈しない。','', '## H. 100-share Fixed-Identity Shadow','',f"161 identities×100株、同Entry/EXIT。total PnL ¥{float(shadow['total_PnL']):,.2f} / Final38 ¥{float(shadow['Final38']):,.2f} / cash min ¥{float(shadow['cash_min']):,.2f} / violations={shadow['violations']}。",f"actual shadow-chain rolling20: {json.dumps(shadow['rolling20_summary'])}。daily PnL/1mと固定1m additive rollingも保存。",'selection-only・低utilization shadow。v5正式Capital gateとの直接policy比較に使用しない。','', '## I. Static Batch Hindsight Sizing Headroom','',f"156 saved funded batches。actual PnL ¥{float(hind['sum_actual_batch_PnL']):,.2f} / local hindsight optimum ¥{float(hind['sum_hindsight_local_optimum_PnL']):,.2f} / difference ¥{float(hind['difference']):,.2f}。",'HINDSIGHT_DIAGNOSTIC_ONLY。funded identities最低1 lot、saved budget/cap内integer。future realizedを使用。Primary recursive enumerationと独立別variable elimination solveでexact一致。将来cash feedback再最適化0、full-chain oracleでもrolling20 upper boundでもない。','151/156 batchesは単独funded identity、5件は2 identities。ただし元pickedにcash/lot失敗candidateを含むbatchでは新weightがfunding pathを変え得る。hindsightのidle/min-lot選択は固定targetのS1/S2で実行可能とは限らない。','', '## J. S1/S2 Paired Funding / Quantity Delta','', '|Arm / group|N|Medium|U5|U10|Weak|realized positive|loser<=0|actual PnL|','|---|---:|---:|---:|---:|---:|---:|---:|---:|']
    for arm in ARMS:
        p=q[arm]['paired_delta']
        for name in ['GAINED_FUNDING_vs_I2','LOST_FUNDING_vs_I2','NEW_MAX3_MISS_vs_I2','CASH_RECOVERY_vs_I2','NEW_CASH_MISS_vs_I2']:
            z=p[name];lines.append(f"|{labels[arm]} / {name}|{z['N']}|{z['Medium']}|{z['U5']}|{z['U10']}|{z['Weak']}|{z['realized_positive_N']}|{z['realized_loser_le0_N']}|¥{float(z['actual_PnL']):,.2f}|")
        lines.append(f"{labels[arm]} COMMON N={p['COMMON_FUNDED']['N']}、quantity PnL delta ¥{float(p['COMMON_FUNDED']['common_quantity_PnL_delta']):,.2f}。Net {json.dumps(p['NET_counts'])}。total PnL delta ¥{float(p['actual_PnL_delta_vs_I2']):,.2f}。")
    lines+=['','COMMON quantity deltaのWeak/Low/Medium/Big/Mega/U5/U10/realized<=0/>=1%内訳は`PAIRED_SIZING_DELTA.json`。個別replacement因果ではない。未funded miss groupのactual PnLは0で、そのpotential/realizedは評価後join。','', '## K. Slot / Band / Time / Notional Allocation','', '|Arm / group|N|buy notional|Medium|U5|U10|<2|<3|PnL|loser|','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|']
    for arm in ARMS:
        ad=q[arm]['allocation_diagnostics']
        for family in ('slot','band','Entry_hour'):
            for name,z in ad[family].items():
                fmt=lambda v:f'{v*100:.4f}%' if v is not None else 'n/a';lines.append(f"|{labels[arm]} / {family}:{name}|{z['N']}|¥{float(z['buy_notional']):,.2f}|{z['Medium']}|{z['U5']}|{z['U10']}|{fmt(z['below2_rate'])}|{fmt(z['below3_rate'])}|¥{float(z['actual_PnL']):,.2f}|{fmt(z['loser_rate'])}|")
        lines.append(f"{labels[arm]} quantity: {json.dumps(ad['quantity'],ensure_ascii=False)}")
    lines+=['','|Profile|Weak notional share|Medium+ share|U5 share|U10 share|','|---|---:|---:|---:|---:|']
    for p,e in [('v5',m['v5']['exposure']),('I2',m['I2']['exposure'])]+[(labels[a],q[a]['allocation_diagnostics']['exposure']) for a in ARMS]:lines.append('|'+p+'|'+'|'.join(f"{e[k]['notional_share']*100:.4f}%" for k in ('Weak','Medium+','U5','U10'))+'|')
    lines+=['','各bucketのbuy notional/share/PnL/return-on-deployed-notionalは同JSONに全保存。countとcapital exposureを分離。','', '## L. Capital Secondary','', '|Profile|daily geometric|arithmetic|median|Final38|maxDD|util mean|turnover|','|---|---:|---:|---:|---:|---:|---:|---:|']
    for p,e in [('v5 saved',base5),('I2 saved',base2)]+[(labels[a],c[a]['economics']) for a in ARMS]:lines.append(f"|{p}|{e['geometric_mean_daily_return']*100:.9f}%|{e['arithmetic_mean_daily_return']*100:.6f}%|{e['median_daily_return']*100:.6f}%|¥{e['final_equity']:,.2f}|{e['max_drawdown']*100:.6f}%|{e['utilization_mean']*100:.4f}%|¥{e['turnover_cash_jpy']:,.2f}|")
    for a in ARMS:
        e=c[a]['economics'];lines.append(f"{labels[a]}: utilization median={e['utilization_median']*100:.4f}%、idle cash mean=¥{e['idle_cash_mean_jpy']:,.2f}、recycled cash=¥{e['capital_recycling_used_jpy']:,.2f}、funded/session={e['avg_funded_per_session']:.6f}、total return={e['total_return']*100:.6f}%。")
    lines+=['','## M. Independent Audit','',f"61/61 causal canary PASS。pre-main141,476 checks / mismatch0。full audit {audit['checks']:,} checks / mismatch={audit['mismatch_N']}。float max delta={audit['max_float_delta']:.18g} (<=1e-12)。money/quantity exact。",'Primary sizing/runtime/replay/evaluator import0。raw frozen model scalar inference、past-only percentile、tenure、I2 action、Fraction portfolio、identity/quantity/matrix/signal/algebraic/shadow、別integer solver、quality/Capital/winner/bottleneckを照合。completed pre-main inference artifactsを再生成せずimmutable reuse。','implementation independenceでありupstream market source independenceを主張しない。親のbar-end as-of / actual arrival unknown制約を継承。','', '## N. Winner / Next Bottleneck','',f"selectedCapitalCandidate={json.dumps(w['selectedCapitalCandidate'])}。diagnosticArm={w['diagnosticArm']}。NEXT_BOTTLENECK={w['NEXT_BOTTLENECK']}。",'REALIZED_MONETIZATION_SIGNALの場合の意味は、Frozen EXIT下でpre-entry情報からpotential winnersのうち実際にmonetizeされる候補を区別する情報不足。EXIT研究への移行ではない。次の独立WorkでQuality v3 HF1/HL0 negative historyを必ず読み、同じ実験を繰り返さない。','M15で固定STOP。S3/threshold/blend/model fit/cap/target/Admission/Rank/EXIT変更、Fresh開封、orders、main mergeは行わない。','', '```', 'selectedBigWinnerRank = EXISTING_MOVE_P5','selectedAuxiliaryHeads = ["MOVE_U2","MOVE_U3"]',f'selectionPolicy = {I2}',f"selectedCapitalCandidate = {json.dumps(w['selectedCapitalCandidate'])}",f"diagnosticArm = {w['diagnosticArm']}",f"NEXT_BOTTLENECK = {w['NEXT_BOTTLENECK']}",'newFits = 0','SizingReplays = 2','fresh_OOS_claim = false','productionReady = false','CURRENT_STATE = CAPITAL_V10_M15_CLOSURE_FIXED_STOP','```']
    with (OUT/'REPORT_FINAL-ja.md').open('x',encoding='utf-8') as f:f.write('\n'.join(lines)+'\n')
def close():
    assert counts()['SizingReplays']==2 and read(OUT/'INDEPENDENT_AUDIT.json')['mismatch_N']==0
    claim=read(OUT/'MAIN_REPLAY_CLAIM.json')
    for p,h in claim['code_sha256'].items():assert sha(ROOT/p)==h
    w=read(OUT/'WINNER_AND_NEXT_BOTTLENECK.json');handoff={'exact_jst':now(),**w,'CURRENT_STATE':'CAPITAL_V10_M15_CLOSURE_FIXED_STOP','permanent_freeze':['Selector','Entry','EXIT'],'same_cycle_next_action':'STOP','next_independent_work_only':True,'HF1_HL0_negative_history_read_required_if_monetization_work':True,'no_automatic_next_work':True,'newFits':0,'SizingReplays':2,'all_prohibited_counts':ZERO,'Safety':SAFETY};save(OUT/'NEXT_WORK_HANDOFF.json',handoff)
    checkpoint('M15_CLOSURE_FIXED_STOP',{'status':w['status'],'selectedCapitalCandidate':w['selectedCapitalCandidate'],'diagnosticArm':w['diagnosticArm'],'NEXT_BOTTLENECK':w['NEXT_BOTTLENECK'],'additional_research_allowed':False},'STOP; actual GET/static receipt/private delivery only')
    save(OUT/'CLOSURE.json',{'exact_jst':now(),**w,'CURRENT_STATE':'CAPITAL_V10_M15_CLOSURE_FIXED_STOP','closed':True,'fixed_stop':True,'resume_same_cycle_allowed':False,'additional_research_allowed':False,'newFits':0,'SizingReplays':2,'independent_mismatch_N':0,'causal_canary_PASS_N':61,'counts':counts(),'v9_parent_SHA':V9_SHA,'Main_parent_SHA':MAIN_SHA,'Quality_parent_SHA':QUALITY_SHA,'report_sha256':sha(OUT/'REPORT_FINAL-ja.md'),'private_sha256':read(OUT/'PRIVATE_PACK_MANIFEST.json')['sha256'],'Exposure':'ITERATIVE_DEVELOPMENT_EVIDENCE','fresh_OOS_claim':False,'productionReady':False,'Safety':SAFETY,'post_closure_allowed':'actual GET/static scope/hash receipts/private delivery only; no research'})
if __name__=='__main__':
    import sys
    {'finalize':finalize,'pack':pack,'report':report,'close':close}[sys.argv[1]]()
