"""Japanese report and append-only receipts from fixed evidence, no inference."""
from pathlib import Path
from collections import Counter
from datetime import datetime,timezone,timedelta
import csv,json,hashlib,math,shutil
R=Path(__file__).resolve().parent;P=Path('/workspace/scratch/a1e749e0bd6c/state_predictiveness_v3_reversal_20261002_v1')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def load(n):return json.loads((R/n).read_text())
def read(n):return list(csv.DictReader((R/n).open()))
def save(n,x):(R/n).write_text(json.dumps(x,sort_keys=True,ensure_ascii=False,indent=2)+'\n')
def num(x):return None if x in [None,'','None'] else float(x)
def pct(x):return 'NA' if num(x) is None else f'{num(x)*100:.2f}%'
def val(x):return 'NA' if num(x) is None else f'{num(x):.6g}'
def pp(x):return 'NA' if num(x) is None else f'{num(x)*100:+.2f} pp'
def table(headers,rows):
 clean=lambda x:str(x).replace('&','&amp;').replace('<','&lt;').replace('>','&gt;').replace('|','\\|').replace('\n',' ')
 return '\n'.join(['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(clean(x) for x in r)+' |' for r in rows])
def main():
 stamp=datetime.now(timezone(timedelta(hours=9))).isoformat();gate=load('GATE_ASSESSMENT_V4.json');audit=load('INDEPENDENT_AUDIT_V4.json');chart=load('CHART_VALIDATION_V4.json');runner=load('NEW_DEVELOPMENT/RUNNER_FINAL_RECEIPT.json');manifest=load('DATASET_MANIFEST_V4.json');complete=load('DEVELOPMENT_COMPLETION_SUMMARY_V4.json');budget=load('BUDGET_START_V4.json');caps=budget['finite_caps'];usage=load('GITHUB_REQUEST_USAGE_AT_DELIVERY.json')
 ledger=list(map(json.loads,(R/'MODEL_EXECUTION_LEDGER.jsonl').read_text().splitlines()));fi=load('FIT_INDEX_V4.json');finals=[x for x in fi['items'] if x['status']=='FITTED'];inners=sum(len(load(x['path'])['inner_artifacts']) for x in finals)
 http=load('RUNNER_ACCOUNTING_V4.json')['actual_provider_HTTP_requests']
 actual={'provider_HTTP_requests':http,'provider_original_guard_counter':runner['provider_requests'],'new_frozen_steps':runner['new_steps'],'new_proposals':runner['fixed_pending_proposals'],'completed_pairs':len(manifest['pairs']),'isolated_Actions_runs':usage['isolated_Actions_runs'],'Actions_fanout':usage['Actions_fanout'],'fit_operations':len(ledger),'final_fitted_artifacts':len(finals),'inner_fitted_artifacts':inners,'old_saved_endpoint_reuse':29305,'new_label_endpoint_N':load('C4_LABEL_FIXATION_RECEIPT.json')['new_label_endpoint_N'],'old_label_endpoint_reuse':29305,'bootstrap_generated_vectors':1000,'independent_new_draws':0,'independent_new_fits':0,'independent_new_kernel_steps':0,'unique_figures':12,'main_merge':0,'force_push':0,'external_AI':0,'result_driven_changes':0}
 compliant=all(actual[k]<=caps[k] for k in ['provider_HTTP_requests','new_frozen_steps','new_proposals','completed_pairs','isolated_Actions_runs','Actions_fanout','fit_operations','bootstrap_generated_vectors'])
 direct=[]
 if audit['status']!='PASS' or audit['mismatch_N']:direct.append('UNRECONCILED_INDEPENDENT_MISMATCH')
 if not compliant:direct.append('COMPUTE_BUDGET_BREACH')
 if runner.get('error') and runner['error']['code'] in ['M0_80_120_MISMATCH','FROZEN_IDENTITY','STATE_FUTURE','CLOSE_MAPPING','KERNEL_CAP','PROTECTED_BOUNDARY','CROSS_DATE','CROSS_CODE','EXACT_TOKEN_MISSING','PRECOMMIT_CHANGED']:direct.append(runner['error']['code'])
 status='BLOCKED_V4_INTEGRITY' if direct else gate['status_pending_independent_audit'];integrity='FAIL_CONTROL' if not gate['integrity_control_PASS'] else 'FAIL_DIRECT' if direct else 'PASS';promoted=[] if status=='BLOCKED_V4_INTEGRITY' else gate['promoted_models']
 save('BUDGET_FINAL_V4.json',{'JST':stamp,'V4_caps_unchanged':caps,'delta':actual,'V4_finite_budget_compliant':compliant,'inherited_budget':budget['inherited_budget'],'no_reset':True,'inherited_V1_bootstrap_3000_cap1000_breach_retained':True,'inherited_V2_four_fit_ledger_gap_retained':True,'old16FAIL':16,'old88workflow_incident':88,'cumulative_known_provider_HTTP':485+runner['provider_requests'],'cumulative_known_frozen_steps':42652+runner['new_steps'],'cumulative_known_generated_bootstrap_vectors':6000,'connector_counts':'GITHUB_REQUEST_USAGE_AT_DELIVERY.json; unknown wrapper HTTP fanout not invented'})
 source=load('NEW_DEVELOPMENT/SOURCE_RECEIPTS.json');minute=[x for x in source if x.get('endpoint')=='/v2/equities/bars/minute'];acq=load('NEW_DEVELOPMENT/ACQUISITION_UNIVERSE_PRECOMMIT.json')
 save('EXPOSURE_APPEND_ONLY_DELTA.json',{'JST':stamp,'parent_exposure_SHA256':sha(P/'EXPOSURE_APPEND_ONLY_DELTA.json'),'V1_V2_V3_exposed_dates_retained':load('DATA_SCOPE_V4.json')['V1_V2_V3_exposed_dates'],'new_fixed_current_dates':[x['date'] for x in load('DATA_SCOPE_V4.json')['new_acquisition_links']],'new_minute_current_or_dependency_attempted_dates':sorted({x['scope']['date'] for x in minute}),'new_minute_rows_returned':sum(x.get('row_N',0) for x in minute),'new_acquired_dates':manifest['new_eligible_dates'],'V4_scope_now_exposed':True,'new_scope_selection_based_on_outcomes':0,'Common_Holdout':0,'Holdout':0,'Protected':0,'Fresh':0,'OOS':0,'Prospective':0,'Entry':0,'EXIT':0,'profit':0,'Capital':0,'Portfolio':0,'broker_orders':0,'future_classifier_input':0,'raw_provider_pages_exported':0,'secret_values_exported':0,'prior_outside_exposure_unknown_nonzero_retained':True})
 aggregate=read('REVERSAL_METRICS_V4.csv');pcs=read('REVERSAL_PER_CLASS_METRICS_V4.csv');risks={x['model']:x for x in read('UP_TO_DOWN_DANGEROUS_FALSE_POSITIVE_V4.csv') if x['group_kind']=='ALL'};incs=read('R0_R1_R2_R3_R4_INCREMENTAL_V4.csv');models=['R0','R1','R2','R3','R4']
 v2=P.parent/'state_predictiveness_v2_nextstate_20261002_v1';old2=list(csv.DictReader((v2/'PER_STATE_PRECISION_RECALL_F1.csv').open()));old3=list(csv.DictReader((P/'PER_STATE_PRECISION_RECALL_F1_V3.csv').open()));newstate=read('PER_STATE_PRECISION_RECALL_F1_V4.csv');states=load('REVERSAL_TARGET_SCHEMA.json')['classes']['NEXT_DISTINCT_PRIMARY'];state_support=[];accuracy_comparison=[]
 a2=list(csv.DictReader((v2/'MODEL_METRICS_AGGREGATE.csv').open()));a3=read('INHERITED_V3/REVERSAL_METRICS_AGGREGATE.csv')
 for task in ['NEXT_DISTINCT_PRIMARY','NEXT_OBSERVED_PRIMARY']:
  for state in states:
   s2=next(x for x in old2 if x['task']==task and x['control']=='REAL' and x['model']=='B0' and x['State']==state);s3=next(x for x in old3 if x['task']==task and x['control']=='REAL' and x['model']=='R0' and x['calibrated']=='True' and x['State']==state);s4=next(x for x in newstate if x['task']==task and x['control']=='REAL' and x['model']=='R0' and x['calibrated']=='True' and x['State']==state)
   state_support.append({'task':task,'State':state,'V2_actual_N':int(s2['Actual_N']),'V3_actual_N':int(s3['Actual_N']),'V4_actual_N':int(s4['Actual_N']),'V4_minus_V3_N':int(s4['Actual_N'])-int(s3['Actual_N']),'same_cohort':False})
  for model,oldmodel in [('R1','B1'),('R2','B2'),('R3','B3')]:
   z2=next(x for x in a2 if x['task']==task and x['control']=='REAL' and x['model']==oldmodel);z3=next(x for x in a3 if x['task']==task and x['control']=='REAL' and x['calibrated']=='True' and x['model']==model);z4=next(x for x in aggregate if x['task']==task and x['control']=='REAL' and x['calibrated']=='True' and x['model']==model)
   accuracy_comparison.append({'task':task,'model_V3_V4':model,'model_V2':oldmodel,'V2_accuracy':num(z2['accuracy']),'V3_accuracy':num(z3['accuracy']),'V4_accuracy':num(z4['accuracy']),'same_cohort':False})
 for name,rows in [('STATE_SUPPORT_V2_V3_V4.csv',state_support),('NINE_STATE_ACCURACY_V2_V3_V4.csv',accuracy_comparison)]:
  with (R/name).open('w') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 get=lambda task,model,cal=True:next(x for x in aggregate if x['task']==task and x['control']=='REAL' and x['model']==model and (x['calibrated']=='True')==cal)
 pc=lambda model,c:next(x for x in pcs if x['task']=='CONTEXT_REVERSAL' and x['control']=='REAL' and x['model']==model and x['calibrated']=='True' and x['class']==c)
 prior={x['model']:x for x in read('INHERITED_V3/UP_TO_DOWN_DANGEROUS_FALSE_POSITIVE.csv') if x['group_kind']=='ALL'}
 compare=[{'model':m,'V3_predicted_UP_N':int(prior[m]['predicted_N']),'V3_actual_DOWN_among_UP_N':int(prior[m]['opposite_actual_N']),'V3_rate':num(prior[m]['rate']),'V4_predicted_UP_N':int(risks[m]['predicted_N']),'V4_actual_DOWN_among_UP_N':int(risks[m]['opposite_actual_N']),'V4_rate':num(risks[m]['rate']),'V4_minus_V3_rate':num(risks[m]['rate'])-num(prior[m]['rate']) if num(risks[m]['rate']) is not None else None,'same_cohort':False} for m in models]
 with (R/'V3_V4_DANGEROUS_COMPARISON.csv').open('w') as f:w=csv.DictWriter(f,fieldnames=list(compare[0]));w.writeheader();w.writerows(compare)
 inc=lambda baseline,model:next(x for x in incs if x['task']=='CONTEXT_REVERSAL' and x['calibrated']=='True' and x['baseline']==baseline and x['model']==model)
 r12=inc('R1','R2');r23=inc('R2','R3');r24=inc('R2','R4');direction=num(r12['dangerous_rate_improvement']) is not None and num(r12['dangerous_rate_improvement'])>0
 calbetter=[m for m in ['R1','R2','R3','R4'] if num(get('CONTEXT_REVERSAL',m)['date_equal_log_loss']) is not None and num(get('CONTEXT_REVERSAL',m)['date_equal_log_loss'])<num(get('CONTEXT_REVERSAL',m,False)['date_equal_log_loss'])]
 historical_cal=lambda model:next(x for x in a3 if x['task']=='CONTEXT_REVERSAL' and x['control']=='REAL' and x['calibrated']=='True' and x['model']==model)
 nullfail=[x['model'] for x in gate['control_integrity_failures']];gates=read('PROMOTION_GATE_V4.csv');r2gate=next(x for x in gates if x['model']=='R2');pathtrend=read('PATH_TENDENCY_V3_V4.csv');supported=sum(int(x['supported_sequence_N']) for x in read('PATH_ANATOMY_SUPPORT_SUMMARY_V4.csv'))
 lead=('新規Coreの評価母数がなく、V3のR2改善の再現は検証できなかった。' if num(risks['R2']['rate']) is None else 'R2の危険UP→DOWN誤予測はR1より点推定で低下し、V3と同方向だった。' if direction else 'R2の危険UP→DOWN誤予測改善は、新しいDevelopmentの点推定では再現しなかった。')+f" R1 {pct(risks['R1']['rate'])} → R2 {pct(risks['R2']['rate'])}、改善 {pp(r12['dangerous_rate_improvement'])}。Core {gate['core_rows']:,} anchor／{gate['core_dates']} OOF日／{gate['core_folds']} fold、DOWN {gate['class_support'].get('DOWN_REVERSAL',0)}／UP {gate['class_support'].get('UP_CONTINUE',0)}。"
 reason=('新規Core評価母数がなく、TRUE_NULLとの優劣は比較不能。direct integrity監査と統計的なsignal確認は別の判定。' if gate['core_rows']==0 else '事前固定したV4 §12のTRUE_NULL integrity判定に抵触したモデル：'+','.join(nullfail)+'。これはcontrolがREALと同等以上という判定であり、未来feature leakageが直接立証されたという意味ではない。' if nullfail else 'TRUE_NULLのprimary integrity判定は通過した。')
 save('FINAL_RECEIPT.json',{'JST':stamp,'document_id':'WORK_STATE_PREDICTIVENESS_V4_CONFIRMATION_20261002_V1','status':status,'integrity':integrity,'direct_integrity_failures':direct,'control_integrity_failures':nullfail,'independent_audit':audit['status'],'independent_assertion_N':audit['assertion_N'],'mismatch_N':audit['mismatch_N'],'contract_SHA256':sha(R/'PREDICTIVENESS_V4_CONTRACT.md'),'data_scope_SHA256':sha(R/'DATA_SCOPE_V4.json'),'precommit_SHA256':sha(R/'PREDICTIVENESS_V4_PRECOMMIT.json'),'OOF_SHA256':sha(R/'OOF_ALL.jsonl'),'core_rows':gate['core_rows'],'core_OOF_dates':gate['core_dates'],'core_folds':gate['core_folds'],'class_support':gate['class_support'],'promoted_models':promoted,'State9_Path_profile_M0_changes':0,'family_mapping_target_changes':0,'Holdout_Protected_Entry_EXIT_profit_delta':[0,0,0,0,0],'result_driven_changes':0,'next_action':'HYBRID ENTRY INTELLIGENCE research only; not automatically executed' if promoted else 'No Entry handoff; preserve V4 and diagnose failure in a new precommitted Work, no current result-driven repair.'})
 summary=[]
 for m in models:
  up=pc(m,'UP_CONTINUE');down=pc(m,'DOWN_REVERSAL');z=get('CONTEXT_REVERSAL',m);rr=risks[m]
  summary.append([m,f"{rr['opposite_actual_N']}/{rr['predicted_N']} = {pct(rr['rate'])}",pct(down['Precision']),pct(down['Recall']),pct(down['F1']),pct(up['Precision']),pct(up['Recall']),pct(up['F1']),pct(z['macro_F1']),val(z['date_equal_log_loss'])])
 report=[f'# Ark Terminal — State Predictiveness V4 最終報告\n\n作成JST：{stamp}\n\n**{status}**。Integrity：{integrity}。独立再計算：{audit["status"]}、不一致{audit["mismatch_N"]}。Entryへ渡すモデル：'+(','.join(promoted) if promoted else 'なし')+'。',lead,reason,
 '## 主要結果\n\n'+table(['model','UP予測→DOWN実現','DOWN P','DOWN R','DOWN F1','UP P','UP R','UP F1','macro F1','日均等LL'],summary),
 'DOWNは価格損失ではなく、V3と同じ30 scheduled tradable slot内の最初の確認済みState/context反転。UP継続は真のRISE/SHARP_RISE遷移とcontext/local=+1でありHOLDではない。REBOUNDもcontext DOWNなら下降反転先に含む。minute anchorと窓が重複するため独立売買試行とは扱わない。',
 '## V3改善の再検証\n\n'+table(['model','V3危険率','V4危険率','V4−V3','V4 95%日cluster区間'],[[m,pct(prior[m]['rate']),pct(risks[m]['rate']),pp(compare[i]['V4_minus_V3_rate']),pct(risks[m]['CI95_low'])+'–'+pct(risks[m]['CI95_high'])] for i,m in enumerate(models)]),
 '![V3 vs V4危険誤予測](CHARTS/01_v3_vs_v4_dangerous_rate.png)',
 table(['比較','危険率改善','95%改善CI','DOWN F1差','UP F1差','macro F1差','日均等LL改善','日均等Brier改善','ECE改善'],[[b+'→'+m,pp(x['dangerous_rate_improvement']),pp(x['dangerous_improvement_CI95_low'])+'–'+pp(x['dangerous_improvement_CI95_high']),pp(x['DOWN_REVERSAL_F1_improvement']),pp(x['UP_CONTINUE_F1_improvement']),pp(x['macro_F1_improvement']),val(x['date_equal_log_loss_improvement']),val(x['date_equal_Brier_improvement']),val(x['top_label_ECE_improvement'])] for b,m,x in [('R1','R2',r12),('R2','R3',r23),('R2','R4',r24)]]),
 '差の向きは「改善が正」。V3とV4は別の日・銘柄のcohortで、V3の12.78%を同じ分母で再試験したものではない。V4内のR1/R2/R3/R4は同じtest keysで比較する。PathがR2を超えない場合は、記述/anatomyでの有用性とpredictorへのincremental promotionを分離する。',
 '![モデル・確率品質](CHARTS/02_r1_r4_reversal_metrics.png)\n\n![反転・継続P/R/F1](CHARTS/03_down_up_precision_recall_f1.png)',
 '## Development拡張とsplit\n\n'+table(['項目','結果'],[['事前承認145日／142リンク','その範囲内だけで取得'],['未exposed固定リンク','106、元の時系列順'],['新しい銘柄候補',runner['fixed_pending_proposals']],['新規取得status',json.dumps(complete['new_status_counts'],ensure_ascii=False)],['新しい取得日',len(manifest['new_eligible_dates'])],['保存済み再利用','90 pairs／29,305 endpoints'],['全入力',f"{len(manifest['pairs'])} pairs／{len(manifest['input_dates'])} dates／{manifest['endpoint_N']:,} endpoints"],['observed／null',f"{manifest['observed_N']:,}／{manifest['null_N']:,}"],['OOF Core',f"{gate['core_rows']:,}／{gate['core_dates']}日／{gate['core_folds']}fold"],['Core support',json.dumps(gate['class_support'])],['選択済み未取得・旧新合計',complete['remaining_selected_old_and_new_N']],['metadata段階の未選択capacity',complete['metadata_unselected_capacity']],['結果によるdate/security補充','0']]),
 '36のV1/V2/V3 exposure日は学習専用。新しい最初の5日はwarmup、残り101日は34/34/33の3固定fold。raw/U/label availabilityを見て日付を移動しない。meta/factorだけでfirst3を選び、分足が空でも別銘柄に交換しない。元の7件は取得不能Evidenceを再利用して保持した。UNAVAILABLE_INPUTSにはmetadata不成立と選択済みraw/U不成立を区別して保存し、実在しないsecurityを作らない。new分足取得はcurrent/previousの承認済み依存日のみ。',
 table(['fold','固定test日','入力があるtest日','train日','Core anchors','Core有効日'],[[x['fold'],len(x['test_dates']),len(set(x['test_dates'])&set(manifest['new_eligible_dates'])),len(x['train_dates']),next(z['row_N'] for z in read('REVERSAL_METRICS_BY_FOLD_V4.csv') if z['task']=='CONTEXT_REVERSAL' and z['control']=='REAL' and z['model']=='R2' and z['calibrated']=='True' and z['fold']==str(x['fold'])),next(z['date_N'] for z in read('REVERSAL_METRICS_BY_FOLD_V4.csv') if z['task']=='CONTEXT_REVERSAL' and z['control']=='REAL' and z['model']=='R2' and z['calibrated']=='True' and z['fold']==str(x['fold']))] for x in load('SPLIT_REALIZED_V4.json')['folds']]),
 '## Calibrationと安定性\n\n'+table(['model','未較正日均等LL','較正後日均等LL','較正後日均等Brier','較正後ECE'],[[m,val(get('CONTEXT_REVERSAL',m,False)['date_equal_log_loss']),val(get('CONTEXT_REVERSAL',m)['date_equal_log_loss']),val(get('CONTEXT_REVERSAL',m)['date_equal_Brier']),pct(get('CONTEXT_REVERSAL',m)['top_label_ECE'])] for m in models]),
 '較正でouter日均等LLが改善したモデル：'+(','.join(calbetter) if calbetter else 'なし')+'。同一のtrain-only温度gridを継承し、alphaとtemperatureには同じ最後のtrain日を使用する限界も保持した。outer testでmethod/temperatureを探索していない。uncal/cal両方のLL/Brier/ECEを保存し、結果を見て較正方法を追加しない。',
 table(['model','V3較正後日均等LL','V4較正後日均等LL','V3較正後Brier','V4較正後Brier','V3 ECE','V4 ECE'],[[m,val(historical_cal(m)['date_equal_log_loss']),val(get('CONTEXT_REVERSAL',m)['date_equal_log_loss']),val(historical_cal(m)['date_equal_Brier']),val(get('CONTEXT_REVERSAL',m)['date_equal_Brier']),pct(historical_cal(m)['top_label_ECE']),pct(get('CONTEXT_REVERSAL',m)['top_label_ECE'])] for m in ['R1','R2','R3','R4']]),
 'V3→V4の数値比較は異なるDevelopment cohortであり、calibration法の改善効果を分離した比較ではない。R2のV3較正後日均等LL '+val(historical_cal('R2')['date_equal_log_loss'])+' → V4 '+val(get('CONTEXT_REVERSAL','R2')['date_equal_log_loss'])+' という変化と、V4内で未較正 '+val(get('CONTEXT_REVERSAL','R2',False)['date_equal_log_loss'])+' → 較正後 '+val(get('CONTEXT_REVERSAL','R2')['date_equal_log_loss'])+' という変化を混同しない。',
 '![calibration](CHARTS/04_calibration_curve.png)\n\n![DOWN bucket](CHARTS/05_down_probability_vs_actual.png)\n\n![fold安定性](CHARTS/06_fold_stability.png)\n\n![日・銘柄](CHARTS/07_date_security_concentration.png)',
 table(['model','比較先','危険誤予測減少の最大日share','最大銘柄share','正解増加の最大日share','最大銘柄share','集中gate'],[[x['model'],x['baseline'],pct(x['dangerous_reduction_max_date_share']),pct(x['dangerous_reduction_max_security_share']),pct(x['correctness_max_date_share']),pct(x['correctness_max_security_share']),x['concentration_PASS']] for x in gates]),
 '## Path Anatomy\n\n'+table(['長さ','anchor N','sequence N','完全history N','支持基準合格'],[[x['length'],x['anchor_N'],x['sequence_N'],x['complete_history_anchor_N'],x['supported_sequence_N']] for x in read('PATH_ANATOMY_SUPPORT_SUMMARY_V4.csv')]),
 f'記述的支持基準N>=100・日>=8・銘柄>=3を満たすsequenceは合計{supported}。長さ1=current、長さ2=current＋直前1 completed run、長さ3/4はその延長。R4 predictorの前run1–4はV3と同じ。RISE開始、SHARP_RISE開始、PULLBACK含有、RISE_STOP含有は各長さの別CSVを保存。V3と共通するsequenceについて、cohort全体に対するUP/DOWN rate差の同方向再現をPATH_TENDENCY_V3_V4.csvに保存した。小Nの100%はpromotion根拠にしない。',
 table(['sequence','V3 N','V4 N','V3 DOWN','V4 DOWN','V3 UP','V4 UP','UP傾向同方向','DOWN傾向同方向'],[[x['sequence'],x['V3_N'],x['V4_N'],pct(x['V3_DOWN_rate']),pct(x['V4_DOWN_rate']),pct(x['V3_UP_rate']),pct(x['V4_UP_rate']),x['UP_direction_relative_to_cohort_reproduced'],x['DOWN_direction_relative_to_cohort_reproduced']] for x in sorted(pathtrend,key=lambda z:-int(z['V4_N']))[:12]]),
 '![Path長さ](CHARTS/08_path_length_reversal_support.png)\n\n![反転Paths](CHARTS/09_top_down_reversal_paths.png)\n\n![継続Paths](CHARTS/10_top_up_continue_paths.png)',
 '## Negative controlsとintegrity\n\n'+table(['control','model','matched N','日','REAL日均等LL','control日均等LL','判定'],[[x['control'],x['model'],x['matched_row_N'],x['date_N'],val(x['REAL_date_equal_log_loss']),val(x['control_date_equal_log_loss']),x['warning']] for x in read('NEGATIVE_CONTROL_V4.csv') if x['task']=='CONTEXT_REVERSAL' and x['calibrated']=='True' and x['model'] in ['R2','R3','R4']]),
 reason+' V3ではwarning／promotion vetoだったが、ユーザーV4 §12の明示条件に従い、primary calibrated TRUE_NULLの日均等LLがREAL以下、またはR1へのpositive gainがREALの90%以上という判定を新label前に固定した。低accuracyや悪calibrationだけでBLOCKにはしない。SHIFT60は同じ連続bridgeでのregime/dependence stressで、単独ではfuture leakageの証明にしない。timestamp、target順序、fold、train/end purge、whole-label donor移動は独立logicで直接監査した。',
 '## 9State secondary\n\n'+table(['task','R1 accuracy','R2 accuracy','R3 accuracy','R4 accuracy','V4 support','有効日'],[[t,*[pct(get(t,m)['accuracy']) for m in ['R1','R2','R3','R4']],get(t,'R2')['row_N'],get(t,'R2')['date_N']] for t in ['NEXT_DISTINCT_PRIMARY','NEXT_OBSERVED_PRIMARY']]),
 '![V2/V3/V4 precision](CHARTS/11_nine_state_precision_v2_v3_v4.png)\n\n![9x9混同行列](CHARTS/12_nine_by_nine_confusion.png)',
 '全9classは支持0でも残す。分母0はNAであり0%への置換ではない。9State精度とrare Stateの母数はsecondaryで、reversal gateの代わりにしない。V2/V3との比較は別cohortでありcontrolled incremental gainではない。略号RS/R/SR/PB/RG/RB/SD/D/DSはRISE_STOP/RISE/SHARP_RISE/PULLBACK/RANGE/REBOUND/SHARP_DROP/DROP/DROP_STOP。',
 '## 独立監査・予算・禁止境界\n\n'+table(['項目','結果'],[['独立監査',f"{audit['status']}／{audit['assertion_N']:,} assertions／mismatch {audit['mismatch_N']}"],['provider HTTP',f"{runner['provider_requests']}/{caps['provider_HTTP_requests']}"],['Frozen step',f"{runner['new_steps']}/{caps['new_frozen_steps']}"],['fits',f"{len(ledger)}/{caps['fit_operations']}（final {len(finals)}＋inner {inners}）"],['bootstrap','1000 vectors exactly once；全metric共用；独立new draw0'],['Actions',f"{usage['isolated_Actions_runs']}run／fanout{usage['Actions_fanout']}"],['12図',chart['status']],['State9/Path/profile/M0/target/family変更','各0'],['Holdout/Protected/Fresh/OOS/Prospective','各0'],['Entry/EXIT/profit/Capital/Portfolio/orders','各0'],['main merge/force push/external AI','各0']]),
 '監査は同じassistantによる別コードで、外部人間の独立査読ではない。保存features/labels/split/OOF/fit係数、inner選択、target、risk、metric、calibration、Path、9State、controls、bootstrapを再計算した。normal equationは検算するがrefitしない。State9/Path kernel全semantic suiteは再実行していない。purge済みfull API responseの再取得監査でもない。historical known_at UNKNOWNとbar_end availability仮定を区別する。V1 3000/cap1000超過、V2の4fit ledger gap、旧16FAIL／88workflow incident、過去outside exposure unknown/nonzeroを保存しリセットしない。',
 '独立checker初回はgrouped containerへのappendが一時listへ書かれる実装不具合でPath検算時に例外停止した。格納行を修正し、全OOF recordのgroup収容assertionを追加してread-only監査を再実行した。未完了の初回をPASSとは扱わない。AUDIT_IMPLEMENTATION_REPAIR_RECEIPT_V4.jsonに失敗source hash・原因・修正境界を保存し、candidate OOF・ラベル・features・model・calibration・gateには変更0、追加fit/draw0。figure03のlegend位置と空foldの表示も提示上だけ修正した。',
 '## Promotion・次段階\n\n'+table(['model','baseline','support','danger改善','主要反転metric','calibration','DOWN recall','集中','TRUE NULL不合格','総合'],[[x['model'],x['baseline'],x['core_support_PASS'],x['dangerous_improvement_PASS'],x['major_metric_PASS'],x['calibration_not_fatally_worse_PASS'],x['DOWN_recall_guard_PASS'],x['concentration_PASS'],x['TRUE_NULL_equivalent_or_better'],x['comparison_PASS']] for x in gates]),
 'Entryへ渡す候補：'+(','.join(promoted) if promoted else 'なし')+'。'+('次はHYBRID ENTRY INTELLIGENCE研究だが自動実行しない。' if promoted else 'V4を結果に合わせてtarget/model/calibrationで修復してpromotionしない。必要な次研究は新しいContractで、V4をexposedとして固定する。')+' 将来EXIT研究へ再利用できるのは、観測済みのPath/context/stop/gap証拠とrisk指標・prefix/provenanceであり、EXIT/HOLD ruleやprofit Evidenceではない。']
 # All21 requested answers, grounded in the exact tables above.
 answers=[['1','R2の12.78%改善再現',('点推定でR1に対して同方向。' if direction else 'R1に対する危険率改善は点推定で再現せず。')+'V4 R2 '+pct(risks['R2']['rate'])+'。最終認証：'+status],['2','R1→R2改善量',pp(r12['dangerous_rate_improvement'])+'、95%CI '+pp(r12['dangerous_improvement_CI95_low'])+'–'+pp(r12['dangerous_improvement_CI95_high'])],['3','R2→R3/R4', 'danger改善 R3 '+pp(r23['dangerous_rate_improvement'])+'／R4 '+pp(r24['dangerous_rate_improvement'])+'。総合gateは上表。'],['4','DOWN P/R/F1','R2 '+ '/'.join(pct(pc('R2','DOWN_REVERSAL')[k]) for k in ['Precision','Recall','F1'])],['5','UP P/R/F1','R2 '+ '/'.join(pct(pc('R2','UP_CONTINUE')[k]) for k in ['Precision','Recall','F1'])],['6','calibration','outer日均等LL改善：'+(','.join(calbetter) if calbetter else 'なし')+'。較正悪化も保存。'],['7','OOF日数',gate['core_dates']],['8','fold数',gate['core_folds']],['9','DOWN support',gate['class_support'].get('DOWN_REVERSAL',0)],['10','UP support',gate['class_support'].get('UP_CONTINUE',0)],['11','1日／1銘柄集中','R2集中gate '+r2gate['concentration_PASS']+'。risk減少・correctness gainを各shareで保存。'],['12','TRUE NULLに勝ったか','primary不合格モデル '+(','.join(nullfail) if nullfail else 'なし')+'。固定matched日均等LL/gain規約。'],['13','Path Anatomy傾向','共通sequence '+str(len(pathtrend))+'、V4支持基準合格 '+str(supported)+'。同方向／逆方向は別CSV、Entry/EXIT rule化0。'],['14','9State精度','next-distinct R2 '+pct(get('NEXT_DISTINCT_PRIMARY','R2')['accuracy'])+'／next-observed '+pct(get('NEXT_OBSERVED_PRIMARY','R2')['accuracy'])+'。別cohort V2/V3比較は図11。'],['15','rare State support','全9State Actual_NとV2/V3/V4を保存。SHARP_RISE等は支持0/小Nも除外しない。'],['16','Development未取得','選択済み旧新 '+str(complete['remaining_selected_old_and_new_N'])+'件。metadata未選択capacity '+str(complete['metadata_unselected_capacity'])+'枠は別計上。'],['17','Entryへ渡せるか','可・研究handoffのみ' if promoted else '不可'],['18','渡すモデル',','.join(promoted) if promoted else 'R2/R3/R4いずれもなし'],['19','EXIT再利用Evidence','causal Path/context/stop/gap anatomy、riskとsupport、provenance。EXIT/HOLD/利益は未研究。'],['20','禁止exposure','Holdout/Protected/Entry/EXIT/profit今回delta各0。過去unknown/nonzero保持。'],['21','identity変更','State9/Path/profile/M0各0、family/targetも0。']]
 if gate['core_rows']:
  answers[0][2]='危険FP改善はV3と同方向、95%差CIは正。ただし絶対率12.78%は未再現：V4 R2 '+pct(risks['R2']['rate'])+'。別cohort比較で、最終認証は '+status+'。'
  answers[2][2]='危険率は点推定でR3 '+pp(r23['dangerous_rate_improvement'])+'／R4 '+pp(r24['dangerous_rate_improvement'])+' 改善したが、両差CIは0を含む。DOWN F1は各低下、R2超えのincremental promotionなし。'
  answers[5][2]='V4内ではtrain-only較正で日均等LL改善モデルなし。R2 '+val(get('CONTEXT_REVERSAL','R2',False)['date_equal_log_loss'])+'→'+val(get('CONTEXT_REVERSAL','R2')['date_equal_log_loss'])+'、R1比calibration gate未達。V3比較は別cohort。'
  answers[11][2]='R2/R4はmatched日均等LLでTRUE NULLより良い。R3はTRUE NULLの方が良く、固定§12で全WorkをBLOCK。未来leakageの直接立証ではない。'
  sameup=sum(x['UP_direction_relative_to_cohort_reproduced']=='True' for x in pathtrend);samedown=sum(x['DOWN_direction_relative_to_cohort_reproduced']=='True' for x in pathtrend)
  answers[12][2]='共通 '+str(len(pathtrend))+' sequenceのcohort相対傾向はUP '+str(sameup)+'／DOWN '+str(samedown)+' が同方向。下降傾向は一様な再現ではない。V4支持基準合格は全長さで '+str(supported)+'、rule化なし。'
  oldmetric=lambda task:next(x for x in a3 if x['task']==task and x['control']=='REAL' and x['calibrated']=='True' and x['model']=='R2')
  answers[13][2]='R2 V3→V4：next-distinct '+pct(oldmetric('NEXT_DISTINCT_PRIMARY')['accuracy'])+'→'+pct(get('NEXT_DISTINCT_PRIMARY','R2')['accuracy'])+'、next-observed '+pct(oldmetric('NEXT_OBSERVED_PRIMARY')['accuracy'])+'→'+pct(get('NEXT_OBSERVED_PRIMARY','R2')['accuracy'])+'。別cohort、secondaryのみ。'
  sr=[x for x in state_support if x['State']=='SHARP_RISE'];answers[14][2]='全9Stateのactual supportは両taskでV3より増加。SHARP_RISEは '+ '／'.join(x['task']+' '+str(x['V3_actual_N'])+'→'+str(x['V4_actual_N']) for x in sr)+'。小Nをpromotion根拠にしない。'
 if gate['core_rows']==0:
  answers[0][2]='新規Core評価母数0のため検証不可。V3結果は変更せず保持。';answers[11][2]='比較不能。no control warningは勝利やsignalの認証ではない。'
 report.append('日／銘柄などのsubsetが1日clusterしか持たない場合、保存global bootstrapによるCIは点推定へ退化し、有効な不確実性認証ではない。risk CSVのcluster_CI_informativeを確認する。新しいwithin-date drawで救済しない。主要metricのadjusted-tail CIは固定gateであり、全追加macro比較を含む厳密なfamily-wise error保証は主張しない。provider cap guardの事前I/O counterと実HTTPはRUNNER_ACCOUNTING_V4で区別し、原本receiptを保持する。')
 report.append('## V2/V3/V4 secondaryの母数比較\n\n'+table(['task','State','V2 support','V3 support','V4 support','V4−V3'],[[x['task'],x['State'],x['V2_actual_N'],x['V3_actual_N'],x['V4_actual_N'],x['V4_minus_V3_N']] for x in state_support])+'\n\n'+table(['task','model','V2 accuracy','V3 accuracy','V4 accuracy'],[[x['task'],x['model_V3_V4'],pct(x['V2_accuracy']),pct(x['V3_accuracy']),pct(x['V4_accuracy'])] for x in accuracy_comparison]))
 report.append('## 必須21問への回答\n\n'+table(['番号','問い','回答'],answers));(R/'REPORT-ja.md').write_text('\n\n'.join(report)+'\n')
 (R/'00_README.txt').write_text('Ark Terminal State Predictiveness V4 — COMPLETE one ZIP\nStatus: '+status+'\nIntegrity: '+integrity+'; independent audit '+audit['status']+'; mismatches '+str(audit['mismatch_N'])+'\n'+lead+'\nRead REPORT-ja.html (12 embedded charts), REPORT-ja.md, FINAL_RECEIPT, NEXT_STAGE_HANDOFF first.\nAll machine-readable CSVs, OOF, fits, labels, features, trace evidence, acquisition receipts and original V3 COMPLETE ZIP included.\nPublic code/contracts/aggregates are on the dedicated GitHub branch; SOURCE_CODE_LOCATION_INDEX.json pins their exact hashes/commit.\nDATASET_MANIFEST_PORTABLE_V4.json and INPUT_LOCATION_INDEX_V4.csv resolve archive-relative input paths without altering original manifest.\nNo rerun of acquisition/labels/fits/bootstrap under completed V4. No Entry/EXIT/orders/Holdout. One complete ZIP, no splitting regardless size.\n')
 (R/'NEXT_STAGE_HANDOFF.md').write_text('# V4 handoff\n\nStatus: '+status+'; integrity '+integrity+'; independent '+audit['status']+'.\n\n'+lead+'\n\n'+reason+'\n\nPromoted models: '+(','.join(promoted) if promoted else 'none')+'. No automatic Entry/EXIT or Hybrid research.\n\nRead README/report/receipt/contract/precommit/scope/identity/split/gates/controls/calibration/independent audit/budget/exposure and all checkpoint receipts. Preserve original V3 COMPLETE unchanged, V1 BLOCK/bootstrap breach, V2 ledger gap and all prior exposure.\n\nAll V4 acquired/label/prediction dates are now exposed Development. Do not result-refill securities, switch calibrated variant, retune targets/State/Path/thresholds or regenerate the1000 vectors. A future authorized research needs a new precommit and explicitly acknowledges this exposure.\n\nReusable causal evidence is descriptive Path anatomy, family mappings, stop/gap/prefix rules, saved targets/risk definitions and provenance. This is not an EXIT/Entry/profit rule. Holdout/Protected/Fresh/OOS/Prospective remain unopened.\n')
 print(json.dumps({'status':status,'integrity':integrity,'core_rows':gate['core_rows'],'core_dates':gate['core_dates'],'core_folds':gate['core_folds'],'R2_dangerous_rate':num(risks['R2']['rate']),'independent':audit['status'],'promoted':promoted,'report_bytes':(R/'REPORT-ja.md').stat().st_size}))
if __name__=='__main__':main()
