"""Result-blind finite design; percentile and tie conventions fixed before solves."""
from control import *
def main():
 rank=ROOT/'docs/evidence/capital-rank-bigwinner-vnext-20261005-v1'
 delivery=read(rank/'PRIVATE_DELIVERY_RECEIPT.json')
 pack=ROOT.parent/'deliverables'/delivery['filename'];assert sha(pack)==delivery['sha256']
 mask=rows(PRIVATE/'COMMON_EVAL_MASK.jsonl.gz');ids={r['entry_id'] for r in mask if r['included']}
 tt={r['entry_id']:r for r in rows(INPUT/'evaluation/TEACHERS_EVALUATION.jsonl.gz')}
 assert len(ids)==1028 and sum(tt[k]['label_bigwinner5'] for k in ids)==170 and sum(tt[k]['label_bigwinner10'] for k in ids)==67
 save(OUT/'PACK_AUTHORITY_MATCH.json',{'exact_jst':now(),'archive_sha256':sha(pack),'GitHub_receipt_sha256':delivery['sha256'],'archive_exact':True,'manifest_original_bytes_sha256':read(OUT/'INPUT_BYTE_AND_SOURCE_FREEZE.json')['original_manifest_byte_sha256'],'manifest_transitively_pinned_by_exact_archive':True,'mask_N':1028,'U5':170,'U10':67})
 band={'training_rows':'Exact identical completed pre-cutoff train_entry_ids of frozen H2/H3/H5 and MOVE_P block; no test rows','old_band':'ML=sum(PAVA(p2,p3,p5))/sum(frozen head base_rates); S>=2 A>=1.5 B>=1 C otherwise','ordering':['pP DESC','Entry timestamp ASC','symbol ASC'],'training_percentile':'Let keys=(-pP,timestamp,symbol) ascending, N training rows; r=(N-number of training keys strictly less than current key)/N. Includes own training key. Test r uses training insertion index only. This is a full-order empirical CDF (score ties resolved by frozen order).','boundaries':'P_HIGH if r>(N-S)/N; else P_MID if r>(N-S-A)/N; else P_BASE if r>(N-S-A-B)/N; else P_BELOW. Integer numerator comparisons avoid float boundary ambiguity. Exact boundary belongs to lower band.','train_volume_preservation':'Exact S/A/B/C counts on same training rows; test counts deliberately NOT forced','training_score_apply':'Saved models predict only; model fitting/calibration/score-stream regeneration=0','training_cutoff':'training entry_minute<920; models exact saved train IDs already embody this scope'}
 policy={'arms':['RANK_NATIVE_GREEDY_MAX3','RANK_NATIVE_LAST_SLOT_OPTION_MAX3'],'same_batch_order':['pP DESC','entry_timestamp ASC','symbol ASC'],'admission':['P_HIGH','P_MID','P_BASE'],'A1':'Reserve never; free slot admit rank order; full MAX3 reject','A2':'Reserve only if pre-pick occupancy=2. Strictly later training admitted max r by exact minute. P_future_better=count(M_j(t)>r)/training_session_N; ACCEPT iff count*2<session_N; equality RESERVE. Occupancy0/1 never reserve; full3 reject. Higher batch last-slot reserve implies all remaining lower batch reserve.','tables':'Completed training sessions, no U5/U10 outcomes or test-session future candidates. Empty future max encoded null (-infinity).','sizing':{'base':{'P_HIGH':'0.68','P_MID':'0.56','P_BASE':'0.44'},'candidate_equity_cap':{'P_HIGH':'0.45','P_MID':'0.35','P_BASE':'0.25'},'breadth_increment':'0.055','max_target':'0.92','weight':'pP proportional (not true-probability claim)','lot':100,'waterfill':'Frozen v5 first pass floor; only initially funded rows receive descending one-lot rounds. No candidate backfill after initial cash/lot failure; no later topup.','liquidity':'Frozen v5 diagnostic-only; no added gate'},'runtime_input_allowlist':['entry_id','session','symbol','entry_minute','entry_timestamp','raw_reference','pP','block','rank_units','train_N','band','liquidity (diagnostic only)'],'execution_contract':'Frozen v5 valid_market/frozen_execution/EOD 15:20/MTM/cash release; LONG cash MAX3 no replacement','BUY':'1.0005','SELL':'0.9995','commission':'0','money':'Decimal precision28 frozen v5 contract; exact currency/quantity audit after money representation normalization','same_minute':'Confirmed exits and mark updates processed before Entry batch. Picked-but-unfunded row occupies same-batch pick capacity only; do not backfill.'}
 oracle={'solves':['ALL_U5','ALL_U10','ADMISSION_U5','ADMISSION_U10'],'primary_population':1028,'U5':170,'U10':67,'all':'Every supported pre-cutoff OOF candidate; admission subset fixed by band mapping','scope':'Physical MAX3 cash LONG 100-share-minimum no sizing caps; continuous 38 sessions starting1M; frozen source/Entry/EXIT release, same-symbol, no replacement','objective_U5':['max U5','max U10 conditional on max U5','min sum stable candidate ordinal; deterministic graph tie ordering'],'objective_U10':['max U10','min sum stable candidate ordinal; deterministic graph tie ordering'],'certificate':'Cash-relaxed interval min-cost flow gives global count upper bound; exact Decimal feasible 100-share witness must attain bound. If not attained, LABEL/PHYSICAL_CERTIFICATE_BLOCKED STOP, not silently one-lot-limited ceiling. Unrestricted sizing need not be solved when minimum-lot witness attains global upper bound.','runtime_reads_Oracle':False,'nonwinner_arcs':'Zero-outcome arcs not needed to establish relaxed count bound; exact witness can omit them. Dropping them only from solver objective proof, never Selector/runtime population.','schedule_dependency':'Band/last-slot/gates already precommitted here before Oracle outcomes. Compute outcome-blind mapping to supply admission Oracle; D5 acknowledges this precommit, not a new result-dependent design.'}
 gates={'P1':'funded U5>50','P2':'funded U10>=26','P3':'below2 funded rate<=0.38666667','P4':'cash<0/MAX3/same-symbol/execution unresolved/future leakage=0','P5':'independent decision/quantity mismatch=0','Capital':{'rolling20_median_gt':1.199154192,'rolling20_mean_gt':1.190646013,'daily_geometric_gt':0.01032420041,'North_Star':'2x window N>0'},'winner_order':['2x hit N DESC','rolling20 median DESC','rolling20 mean DESC','daily geometric DESC','U5 funded DESC','U10 funded DESC','below2 contamination ASC','minute MaxDD ASC','A1 simplicity tie'],'eligible':'Preservation PASS only','promotion':'Only Preservation PASS and all Capital gates or North Star; mixed slot diagnostic only, selectedCapitalCandidate null otherwise','diagnostic_arm_if_no_preservation_pass':'Apply same ordering among A1/A2 for diagnosis only; v5 remains Capital benchmark. This does not adopt failed arm.','bottleneck':'Largest mutually exclusive observed U5 nonfunding count among rank admission/reserve/MAX3/cash. Unique largest => corresponding enum; tied largest or only other/execution/same-symbol => NO_CLEAR_SINGLE_BOTTLENECK. Physical unavoidable is an overlapping ceiling decomposition, never added to reasons.','float_tolerance':1e-12,'money_quantity_tolerance':0,'independent_method':'Standalone Fraction accounting and scalar model inference; no primary runtime/replay/evaluator imports','data_exposure':'ITERATIVE_DEVELOPMENT_EVIDENCE; protected/fresh unopened; 19 rolling windows overlap'}
 for name,obj in [('BAND_MAPPING_PRECOMMIT.json',band),('LAST_SLOT_POLICY_PRECOMMIT.json',policy),('ORACLE_PRECOMMIT.json',oracle),('EVALUATION_WINNER_PRECOMMIT.json',gates)]:save(OUT/name,{'exact_jst':now(),'Safety':SAFETY,'specification':obj})
 checkpoint('D3_ORACLE_PRECOMMIT','ALL_DESIGN_PRECOMMITTED',['mapping and ties','A1/A2','4 Oracle objectives/certificate','preservation/Capital/winner/bottleneck order'],{'fits':0,'policy_N':2,'replay_N':0,'design_before_Oracle_outcomes':True},'Apply saved models on training rows; freeze distributions; four evaluator-only Oracle solves once')
if __name__=='__main__':main()
