import type {Status,Position,Activity,Component} from './contracts.js';
const pages=['Dashboard','Portfolio','Positions','Activity','Market','Execution','System','Research','Logs'];
const icons=['◈','◷','▥','↗','▤','⌁','▦','◇','≡'];
const el=(id:string)=>document.getElementById(id)!;
const esc=(v:unknown)=>String(v??'UNKNOWN').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?'¥'+v.toLocaleString('ja-JP',{maximumFractionDigits:0}):'—';
const pct=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?(v>0?'+':'')+v.toFixed(2)+'%':'—';
const positive=(v:unknown)=>typeof v==='number'?(v>=0?'positive':'negative'):'';
const badge=(s:string)=>`<span class="badge ${/^(PASS|READY|CONNECTED|FRESH|MATCH)$/.test(s)?'good':/FAIL|BLOCKED|STALE|ERROR/.test(s)?'bad':'neutral'}">${esc(s)}</span>`;
const time=(s:string|null)=>s&&Number.isFinite(Date.parse(s))?new Date(s).toLocaleTimeString('ja-JP',{timeZone:'Asia/Tokyo',hour12:false}):'—';
let state:Status|null=null,period='1D',category='ALL',search='',selected:string|null=null;
function route(){let name='';try{name=decodeURIComponent(location.hash.slice(1));}catch{}return pages.find(p=>p.toLowerCase()===name.toLowerCase())??'Dashboard';}
const card=(label:string,value:string,sub='',cls='')=>`<article class="metric"><span>${label}</span><strong class="${cls}">${value}</strong><small>${sub}</small></article>`;
const panel=(title:string,body:string,sub='')=>`<section class="panel"><div class="panel-head"><h2>${title}</h2><span>${sub}</span></div>${body}</section>`;
const empty=(msg:string)=>`<div class="empty"><span>◌</span><p>${msg}</p></div>`;
function components(rows:Component[]){return `<div class="health">${rows.map(c=>`<div><span>${esc(c.name)}<small>${esc(c.detail??'')}</small></span>${badge(c.status)}</div>`).join('')}</div>`;}
function chart(s:Status){
 const cutoff=period==='ALL'?0:Date.parse(s.observedAt)-({'1D':1,'1W':7,'1M':30,'3M':90}[period]??1)*86400000;
 const points=s.history.filter(p=>Date.parse(p.at)>=cutoff),buttons=`<div class="periods">${['1D','1W','1M','3M','ALL'].map(p=>`<button data-period="${p}" aria-pressed="${p===period}">${p}</button>`).join('')}</div>`;
 if(points.length<2)return buttons+empty('履歴未接続 — 2点以上の観測から描画します');
 const low=Math.min(...points.map(p=>p.equity)),high=Math.max(...points.map(p=>p.equity)),span=Math.max(1,high-low);
 const line=points.map((p,i)=>`${35+i/(points.length-1)*680},${210-(p.equity-low)/span*165}`).join(' ');
 return buttons+`<svg viewBox="0 0 760 260" role="img" aria-label="Equity history"><path d="M35 45H715 M35 100H715 M35 155H715 M35 210H715" class="grid"/><polyline points="${line}" class="equity-line"/><text x="35" y="25">${money(high)}</text><text x="35" y="245">${time(points[0].at)} JST</text><text x="620" y="245">${time(points.at(-1)!.at)}</text></svg><div class="chart-caption">観測 ${points.length} 点 · Equityは外部cash flowを含む · PnLは別集計</div>`;
}
function positionTable(rows:Position[]){return rows.length?`<div class="table-wrap"><table><thead><tr>${['Symbol','Side','Qty','Avg price','Mark','Value','Unrealized','%','Entry JST','Bars','MFE / MAE','EXIT'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(p=>`<tr><td><button class="symbol" data-symbol="${esc(p.symbol)}">${esc(p.symbol)}</button><small>${esc(p.name)}</small></td><td>${badge(p.direction)}</td><td>${p.quantity}</td><td>${money(p.averagePrice)}</td><td>${money(p.price)}</td><td>${money(p.value)}</td><td class="${positive(p.pnl)}">${money(p.pnl)}</td><td class="${positive(p.pnl)}">${pct(p.pnlPct)}</td><td>${time(p.entryAt)}</td><td>${p.barsHeld??'—'}</td><td>${pct(p.mfe)} / ${pct(p.mae)}</td><td>${badge(p.exitState)}</td></tr>`).join('')}</tbody></table></div>`:empty('ポジション情報が未接続、または保有なし');}
function activityTable(rows:Activity[]){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Time JST</th><th>Symbol</th><th>Event</th><th>State</th><th>Reason / Evidence</th></tr></thead><tbody>${rows.slice(0,200).map(a=>`<tr><td>${time(a.at)}</td><td>${esc(a.symbol)}</td><td>${esc(a.type)}</td><td>${badge(a.state)}</td><td>${esc(a.reason)}<details><summary>Evidence</summary><pre>${esc(JSON.stringify(a.raw,null,2))}</pre></details></td></tr>`).join('')}</tbody></table></div>`:empty('表示できるイベントはありません');}
function stats(s:Status){const p=s.portfolio;return `<div class="metrics">${card('TOTAL EQUITY',money(p?.equity),'Shadow / fixture equity')}${card('TODAY’S P&L',money(p?.today),pct(p?.todayPct),positive(p?.today))}${card('TOTAL TRADING P&L',money(p?.pnl),pct(p?.returnPct),positive(p?.pnl))}${card('AVAILABLE CASH',money(p?.cash),'External flows excluded from P&L')}</div>`;}
function content(s:Status,page:string):string{
 const p=s.portfolio;
 if(page==='Dashboard')return stats(s)+`<div class="columns">${panel('Portfolio overview',chart(s),'EQUITY · JPY')}${panel('System health',components(s.components),'READ ONLY')}</div>`+panel('Open positions',positionTable(s.positions),`${s.positions.length} observed`)+panel('Recent activity',activityTable(s.activity.slice(0,5)));
 if(page==='Portfolio')return stats(s)+panel('Equity history',chart(s))+`<div class="metrics">${card('REALIZED',money(p?.realized))}${card('UNREALIZED',money(p?.unrealized))}${card('EXTERNAL NET FLOW',money(p?.flow),'Deposits − withdrawals + adjustments')}${card('MAX DRAWDOWN',pct(p?.maxDD))}${card('GROSS EXPOSURE',money(p?.gross))}${card('NET EXPOSURE',money(p?.net))}${card('BUYING POWER',money(p?.buyingPower))}${card('INITIAL CAPITAL',money(p?.initial))}</div>`+panel('Accounting boundary','<p class="note">Trading PnLと外部入出金は別集計。入出金ありの場合、時系列から収益率を算出できるまでReturnは未表示です。</p>');
 if(page==='Positions')return panel('Open positions',positionTable(s.positions),'Symbolを選ぶと詳細');
 if(page==='Activity')return panel('Activity stream',activityTable(s.activity),'Latest 200 events');
 if(page==='Market')return `<div class="metrics">${card('RAW LATEST',esc(s.source.rawLatest))}${card('NORMALIZED LATEST',esc(s.source.normalizedLatest))}${card('NORMALIZATION',esc(s.source.parity))}${card('FINALIZED LATEST',esc(s.source.finalizedLatest),'Finalization is not yet verified')}</div>`+panel('Source feed',s.source.feeds.length?`<div class="table-wrap"><table><thead><tr><th>Symbol</th><th>Price</th><th>Bid</th><th>Ask</th><th>Source JST</th><th>Age ms</th><th>Freshness</th></tr></thead><tbody>${s.source.feeds.map(f=>`<tr><td>${esc(f.symbol)}</td><td>${money(f.price)}</td><td>${money(f.bid)}</td><td>${money(f.ask)}</td><td>${time(f.marketTimestamp)}</td><td>${f.feedAgeMs??'—'}</td><td>${badge(f.freshness)}</td></tr>`).join('')}</tbody></table></div>`:empty('Source feed未接続'))+panel('Semantics boundary','<p class="note">RAW normalization PASSはbar finalization PASSではありません。通常5mと15:30 closeのcontractは別です。過去barの年齢でfeedをSTALE判定しません。</p>');
 if(page==='Execution')return `<div class="metrics">${card('EXECUTION MODE',esc(s.execution.mode))}${card('TRANSMISSION',esc(s.execution.transmission))}${card('RECONCILIATION',esc(s.execution.reconciliation))}${card('ORDER INTENTS',String(s.execution.orders.length))}</div>`+panel('Control boundary','<p class="note">操作はread-only。外部注文・ARM変更・Emergency Stop操作はこの画面から実行できません。</p><div class="controls"><button disabled>ARM · disabled</button><button disabled>Emergency Stop · disabled</button></div>')+`<div class="columns">${panel('Preflight',components(s.execution.preflight))}${panel('Configured constraints',`<div class="health">${Object.entries(s.execution.limits).map(([k,v])=>`<div><span>${esc(k)}</span><b>${v.toLocaleString()}</b></div>`).join('')||empty('Constraints unknown')}</div>`)}</div>`+panel('Order intent history',activityTable(s.activity.filter(a=>a.category==='EXECUTION')));
 if(page==='System')return `<div class="columns">${panel('Connections & readiness',components(s.components))}${panel('Runtime identity',`<dl>${Object.entries(s.system).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`)}</div>`+panel('Legacy UI','<p class="note">旧UIは保存されています。<a href="/legacy" target="_blank" rel="noopener">旧UIの利用について</a></p>');
 if(page==='Research')return panel('Frozen Full Main','<div class="freeze"><span class="eyebrow">STRATEGY IDENTITY · UNCHANGED</span><h2>Frozen Minimal Hybrid v1</h2><p>MSH-Entry v1 × V3_B_RISK × MAX_3</p><strong>EXIT_V5_DYNAMIC_RECLAIM_BAR_5</strong></div>')+panel('Research boundaries',`<div class="health"><div><span>Primary</span><b>MAX_3 × v5</b></div><div><span>Conservative Sub</span><b>MAX_5 × v5</b></div><div><span>Baseline</span><b>MAX_10 × v5</b></div><div><span>EXIT comparator</span><b>MAX_3 × v4</b></div><div><span>Future OOS · planned 2026-10-22 · first 20 eligible sessions</span>${badge('LOCKED')}</div></div><p class="note">表示は固定contractの概要です。モデルhash照合・OOS開封・予約期間の戦略結果取得は行いません。</p>`);
 return panel('Operational logs',`<div class="filters"><label>Category <select id="category">${['ALL','SOURCE','EXECUTION'].map(c=>`<option ${c===category?'selected':''}>${c}</option>`).join('')}</select></label><label>Search <input id="search" value="${esc(search)}" placeholder="symbol / event / reason"></label></div>`+activityTable(s.activity.filter(a=>(category==='ALL'||a.category===category)&&[a.symbol,a.type,a.reason].join(' ').toLowerCase().includes(search.toLowerCase()))));
}
function detail(){const p=state?.positions.find(p=>p.symbol===selected);el('detail').hidden=!p;if(p)el('detail').innerHTML=`<button id="close-detail" aria-label="Close position details">×</button><span class="eyebrow">POSITION DETAIL</span><h2>${esc(p.symbol)}</h2><p>${esc(p.name)}</p>${badge(p.direction)}<dl>${Object.entries(p.details).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`;}
function render(){if(!state)return;const page=route();el('page-name').textContent=page;el('nav').innerHTML=pages.map((p,i)=>`<a href="#${p.toLowerCase()}" ${p===page?'aria-current="page"':''}><span>${icons[i]}</span>${p}</a>`).join('');el('top-status').innerHTML=badge(state.mode)+`<span>${time(state.observedAt)} JST</span>`;el('warnings').innerHTML=state.warnings.map(w=>`<div class="warning">${esc(w)}</div>`).join('');const focus=document.activeElement?.id,caret=focus==='search'?(el('search') as HTMLInputElement).selectionStart:null;el('content').innerHTML=content(state,page);if(focus==='search'){const input=document.getElementById('search') as HTMLInputElement|null;input?.focus();if(caret!==null)input?.setSelectionRange(caret,caret);}detail();}
window.addEventListener('hashchange',()=>{selected=null;render();});
document.addEventListener('click',e=>{const target=(e.target as Element).closest('button');if(!target)return;if(target.dataset.period){period=target.dataset.period;render();}if(target.dataset.symbol){selected=target.dataset.symbol;detail();}if(target.id==='close-detail'){selected=null;detail();}});
document.addEventListener('input',e=>{if((e.target as HTMLElement).id==='search'){search=(e.target as HTMLInputElement).value;render();}});
document.addEventListener('change',e=>{if((e.target as HTMLElement).id==='category'){category=(e.target as HTMLSelectElement).value;render();}});
let busy=false;async function poll(){if(busy||document.hidden)return;busy=true;try{const response=await fetch('/api/status',{signal:AbortSignal.timeout(4000)});if(!response.ok)throw Error('HTTP '+response.status);const s=await response.json() as Status;if(s.schemaId!=='ARK_APP_V2_STATUS_V1'||!Array.isArray(s.components)||!Array.isArray(s.positions))throw Error('STATUS_SCHEMA');state=s;render();el('transport-error').hidden=true;}catch{el('transport-error').hidden=false;el('transport-error').textContent='STATUS DISCONNECTED — 表示値は最終取得時の値です。現在の状態として扱わないでください。';}finally{busy=false;}}
void poll();setInterval(()=>void poll(),1000);
