"""Metadata/receipt serialization only; no new metric, resampling or outcome selection."""
import json,pathlib,hashlib,collections
from adapter import ROOT,BASE,OUT,PRIVATE,read,rows,save,sha,digest,now,HEADS
def main():
 source=read(OUT/'SOURCE_MANIFEST.json');m=read(BASE/'sources/R1_PACKAGE_MANIFEST.json')['members'];checked=0
 for r in source['members']:
  if r.get('archive')=='A':assert m[r['member']]['sha256']==r['sha256'] and m[r['member']]['bytes']==r['bytes'];checked+=1
 refs=read(ROOT/'r1_work/score_certification/TRAINING_REFERENCE_POPULATIONS.json');current=rows(ROOT/'r1_work/score_certification/CURRENT_FOUR_HEAD_INTELLIGENCE.jsonl.gz');record=[]
 for t in refs:
  hs=hashlib.sha256(json.dumps(t['scores'],separators=(',',':')).encode()).hexdigest();hi=hashlib.sha256(json.dumps(t['train_identity_order'],separators=(',',':')).encode()).hexdigest();assert hi==t['train_identity_sha256']
  assert all(r[t['head']]['reference_sha256']==hs for r in current if r['block']==t['block'])
  record.append({'head':t['head'],'block':t['block'],'N':t['reference_N'],'ordered_score_reference_sha256':hs,'ordered_training_identity_sha256':hi,'hashes_have_distinct_meanings':True})
 # apply_patch materialization added one transport LF; remove it for exact original GET-body hashing only.
 cert=read(BASE/'sources/REMOTE_mret_certificate.json');b=(BASE/'sources/REMOTE_MRET.json').read_bytes();assert hashlib.sha256(b[:-1]).hexdigest()==cert['primary_sha256']
 scorecert=read(ROOT/'r1_work/score_certification/SCORE_REFERENCE_CERTIFICATION.json');assert scorecert['current_intelligence_sha256']==sha(ROOT/'r1_work/score_certification/CURRENT_FOUR_HEAD_INTELLIGENCE.jsonl.gz') and scorecert['training_reference_sha256']==sha(ROOT/'r1_work/score_certification/TRAINING_REFERENCE_POPULATIONS.json')
 save('REFERENCE_HASH_AND_CERTIFICATE_REUSE.json',{'exact_jst':now(),'ordered_reference_checks':record,'A_selected_member_manifest_matches':checked,'same_hash_R1_score_certificate_reused':True,'R1_score_certificate_sha256':sha(ROOT/'r1_work/score_certification/SCORE_REFERENCE_CERTIFICATION.json'),'same_hash_MRET_original_primary_certificate_reused':True,'exact_GET_original_MRET_body_sha256':cert['primary_sha256'],'local_transport_sha256':sha(BASE/'sources/REMOTE_MRET.json'),'transport_encoding_note':'one appended LF from materialization, JSON unchanged; exact original GET bytes verified after removal of precisely one transport LF, not score data repair','source_certificate_hashes':{p.name:sha(p) for p in (BASE/'sources').glob('REMOTE_*AUDIT.json')}|{'MRET_behavior':sha(BASE/'sources/REMOTE_MRET_BEHAVIOR.json'),'MRET_original_certificate':sha(BASE/'sources/REMOTE_mret_certificate.json')},'original_raw_metric_definition_reused':True,'new_inference':0})
 masks=read(PRIVATE/'COHORT_MASKS.json');data={r['entry_id']:r for r in rows(PRIVATE/'V5_SCORE_OUTCOME_ROWS.jsonl.gz')};index={}
 for name,ids in {'C2':masks['C2'],'C3':masks['C3'],**{f'C2_slot{i}':[k for k in masks['C2'] if data[k]['native_funded_slot']==i] for i in [1,2,3]},**{'C4_'+r:ids for r,ids in masks['C4'].items()}}.items():index[name]=ids
 metadata=[]
 top=read(OUT/'FIXED_BUDGET_CAPTURE_DENSITY.json')
 flags=read(OUT/'FLAG_ID_SETS.json') if (OUT/'FLAG_ID_SETS.json').exists() else read(PRIVATE/'FLAG_ID_SETS.json')
 topsets={(c,h,f):[r['entry_id'] for r in sorted([data[k] for k in ids],key=lambda r:(-r['scores'][h],r['entry_time'],r['symbol'],r['entry_id']))[:top[c][h][f]['N']]] for c,ids in index.items() for h in HEADS for f in ['0.2','0.3']}
 def target_meta(ids,t):
  known=[k for k in ids if data[k][t] is not None];positive=sum(data[k][t]==1 for k in known)
  return {'total_N':len(ids),'known_N':len(known),'unknown_N':len(ids)-len(known),'positive_N':positive,'negative_N':len(known)-positive,'distinct_sessions':len({data[k]['session'] for k in known}),'mask_hash':digest(known)}
 for (c,h,f),ss in topsets.items():
  for t in ['Weak','Medium','U2','U3','U5','U10','positive','Loser']:metadata.append({'artifact':'FIXED_BUDGET_CAPTURE_DENSITY.json','path':[c,h,f,t],'density_population':target_meta(ss,t),'capture_population':target_meta(index[c],t),'conditioning':'original fixed TopK set'})
 for h,ff in flags.items():
  for f,ss in ff.items():
   for t in ['Weak','Medium','U5','U10','positive','Loser']:metadata.append({'artifact':'FLAGGED_LOSER_WINNER_TRADEOFF.json','risk_direction':'-'+h,'fraction':f,'target':t,'density_population':target_meta(ss,t),'capture_population':target_meta(masks['C2'],t),'conditioning':'original fixed FLAG set'})
 save('METRIC_COHORT_METADATA_INDEX.json',{'supplements_compact_point_tables':True,'records':metadata,'binary_class_fields_for_concordance_Spearman':None,'concordance_and_Spearman_metadata':'continuous target; positive/negative_N null, not invented binary class; known_N and sessions/mask in target matrix','pair_N_never_independent_N':True})
 matrix=read(OUT/'corrections/EXPERT_TARGET_MATRIX.json')['cohorts'];roles=read(OUT/'corrections/ROLE_DECISIONS.json');signed=read(OUT/'corrections/MRET_SIGNED_CONTROLS.json')['cohorts'];flag=read(OUT/'FLAGGED_LOSER_WINNER_TRADEOFF.json');census=read(OUT/'CHANNEL_CENSUS.json')
 compact={'exact_jst':now(),'completed_stages':['F0','F1','F2','F3','F4','F5','F6','F7'],'roles':{k:v['status'] for k,v in roles.items()},'L1':'PASS','L2':'PASS','L3':'NOT_EVALUATED','conditional_metrics':{c:[{k:v for k,v in r.items() if k not in ['AUC_bootstrap','AP_bootstrap','bootstrap']}|{'AUC_CI95':r.get('AUC_bootstrap',{}).get('CI95'),'valid_N':r.get('AUC_bootstrap',{}).get('valid_N')} for r in z['metrics']] for c,z in matrix.items()},'FLAG_rows':[{k:v for k,v in r.items() if k not in ['Weak','Medium','U2','U3','U5','U10','positive','Loser']}|{t:{k:v for k,v in r[t].items() if not k.endswith('bootstrap')} for t in ['Weak','Medium','U5','U10','positive','Loser']} for r in flag['rows']],'MRET_signed':{c:{'target':z['target'],'scores':{h:{'AUC':r['AUC'],'CI95':r['AUC_bootstrap']['CI95'],'known_N':r['known_N'],'unknown_N':r['unknown_N'],'native_concordance':r['native_bucket_concordance']['concordance']} for h,r in z['scores'].items()},'deltas':{h:{'delta':r['mP_minus_control'],'CI95':r['paired_bootstrap']['CI95'],'valid_N':r['paired_bootstrap']['valid_N']} for h,r in z['all_control_deltas'].items()}} for c,z in signed.items()},'channels':census,'independent_audit':read(OUT/'INDEPENDENT_DIAGNOSTIC_AUDIT.json'),'synthetic':{'required':18,'pass':18,'fail':0},'budgets':{'newFits':0,'currentInference':0,'CapitalReplays':0,'ControlReplays':0,'runtimePolicies':0,'primaryDiagnosticBatch':1,'independentDiagnosticVerification':1},'Capital':'NOT_EVALUATED','champion':'V5','selectedCapitalCandidate':None,'corrected_bootstrap_resolution':'evidence/corrections/* are canonical; original preliminary failure outputs retained in private pack'}
 save('F3_F7_PUBLIC_DIAGNOSTICS.json',compact)
 save('F7_CHECKPOINT.json',{'exact_jst':now(),'complete':True,'stage':'F7','synthetic_PASS':18,'final_mismatch_N':0,'old_failed_bootstrap_mismatch_N':194,'new_fit_inference_replay':0,'primaryDiagnosticBatch':1,'independentDiagnosticVerification':1,'code_hashes':{p.name:sha(p) for p in (BASE/'code').glob('*.py')},'input_manifest_hash':sha(OUT/'SOURCE_MANIFEST.json'),'packet_hash':sha(PRIVATE/'FROZEN_EXPERT_PACKET.jsonl.gz'),'completed':['F0','F1','F2','F3','F4','F5','F6','F7'],'unfinished':['F8 cards','F9 report/closure'],'next':'finish two unexecuted cards, not replay'})
 print(json.dumps({'F7':'COMPLETE','public_bytes':(OUT/'F3_F7_PUBLIC_DIAGNOSTICS.json').stat().st_size,'metadata_N':len(metadata)}))
if __name__=='__main__':main()
