import fs from 'node:fs';import path from 'node:path';
const arg=(n,f=null)=>{const i=process.argv.indexOf(n);return i>=0&&i+1<process.argv.length?process.argv[i+1]:f};
const universePath=arg('--universe','data/screener-universe.json');const output=arg('--output','tmp/p25-marketwide-5m-input.json');const limit=Math.max(0,Number(arg('--limit','0'))||0);const chunkSize=Math.max(10,Math.min(100,Number(arg('--chunk','50'))||50));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function getJson(url,attempt=1){const res=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 ArkTerminal/3.0','accept':'application/json'}});if(!res.ok){if(attempt<3){await sleep(500*attempt);return getJson(url,attempt+1)}throw new Error(`Yahoo spark HTTP ${res.status}`)}return res.json()}
function latestFinite(values=[]){for(let i=values.length-1;i>=0;i--){const n=Number(values[i]);if(Number.isFinite(n)&&n>0)return n}return null}
function parseOne(item,metaBySymbol,observedAt){const symbol=String(item?.symbol??'').toUpperCase();const response=item?.response?.[0]??{};const meta=response?.meta??{};const quote=response?.indicators?.quote?.[0]??{};const price=latestFinite(quote?.close)||Number(meta?.regularMarketPrice);const volumes=Array.isArray(quote?.volume)?quote.volume:[];const volume=volumes.reduce((s,v)=>s+(Number.isFinite(Number(v))?Math.max(0,Number(v)):0),0);const prev=Number(meta?.chartPreviousClose??meta?.previousClose);const md=metaBySymbol.get(symbol)??{};if(!Number.isFinite(price)||price<=0||!Number.isFinite(volume)||volume<=0)return null;return {symbol,sector:md.sector??'未分類',market:md.market??null,status:'analyzed',currentPrice:price,volume,dailyChangePercent:Number.isFinite(prev)&&prev>0?((price/prev)-1)*100:0,scannedAt:observedAt};}
const u=JSON.parse(fs.readFileSync(universePath,'utf8'));let entries=Array.isArray(u)?u:(u.entries??[]);if(limit>0)entries=entries.slice(0,limit);if(!entries.length)throw new Error('empty universe');const metaBySymbol=new Map(entries.map(x=>[String(x.symbol).toUpperCase(),x]));const symbols=[...metaBySymbol.keys()];const observedAt=new Date().toISOString();const out=[];for(let i=0;i<symbols.length;i+=chunkSize){const chunk=symbols.slice(i,i+chunkSize);const url='https://query1.finance.yahoo.com/v8/finance/spark?symbols='+encodeURIComponent(chunk.join(','))+'&range=1d&interval=5m';const json=await getJson(url);for(const item of json?.spark?.result??[]){const row=parseOne(item,metaBySymbol,observedAt);if(row)out.push(row)}if((i/chunkSize)%5===0)console.log(`marketwide spark ${Math.min(i+chunkSize,symbols.length)}/${symbols.length} valid=${out.length}`);await sleep(80)}
fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify({meta:{provider:'yahoo-finance-spark',observedAt,inputSymbols:symbols.length,validSymbols:out.length,pointInTime:true},entries:out},null,2)+'\n');console.log(JSON.stringify({status:'MARKETWIDE_5M_SOURCE_READY',inputSymbols:symbols.length,validSymbols:out.length,coverage:out.length/symbols.length,output},null,2));if(out.length<Math.min(100,Math.floor(symbols.length*0.8)))process.exit(1);
