import fs from 'node:fs';
import path from 'node:path';
import {simulateLaneCPortfolio,PHASE57_P25_LANE_C_ALLOCATION_PROFILES,PHASE57_P25_LANE_C_SAFETY} from '../predict/portfolio/phase57-p25-lane-c-portfolio-simulator.js';
import {P25_EXIT_V3_SAFETY} from '../predict/daytrade/phase57-p25-exit-v3-independent-protocol.js';
const arg=(n,f=null)=>{const i=process.argv.indexOf(n);return i>=0&&i+1<process.argv.length?process.argv[i+1]:f;};
const shardDir=arg('--shard-dir');const partialDir=arg('--partial-dir');const barsPath=arg('--bars');const output=arg('--output');if(!shardDir||!partialDir||!barsPath||!output)throw new Error('usage: --shard-dir <dir> --partial-dir <dir> --bars <json> --output <json>');
const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));const mean=xs=>xs.length?xs.reduce((s,x)=>s+x,0)/xs.length:null;const profitFactor=xs=>{const gp=xs.filter(x=>x>0).reduce((s,x)=>s+x,0),gl=-xs.filter(x=>x<0).reduce((s,x)=>s+x,0);return gl>0?gp/gl:(gp>0?Infinity:null);};const maxDD=xs=>{let e=1,p=1,m=0;for(const r of xs){e*=1+r/100;p=Math.max(p,e);m=Math.max(m,(p-e)/p*100);}return m;};const summary=xs=>{const r=xs.filter(finite).map(Number);let e=1;for(const x of r)e*=1+x/100;return {n:r.length,netReturnPct:(e-1)*100,meanNetReturnPct:mean(r),winRate:r.length?r.filter(x=>x>0).length/r.length:null,profitFactor:profitFactor(r),maxDrawdownPct:maxDD(r)};};
const freeze=JSON.parse(fs.readFileSync(path.join(partialDir,'freeze.json'),'utf8'));const measurements=fs.readFileSync(path.join(partialDir,'partial-measurements.ndjson'),'utf8').split(/\r?\n/).filter(Boolean).map(line=>JSON.parse(line));const bars=JSON.parse(fs.readFileSync(barsPath,'utf8'));if(bars.status!=='P25_INCOMPLETE_ABCD_BARS_COMBINED'||bars.sessionDate!==freeze.sessionDate)throw new Error('bars input invalid');
const files=fs.readdirSync(shardDir).filter(f=>f.endsWith('.json')).sort();if(!files.length)throw new Error('no dynamic shard files');const shards=files.map(f=>JSON.parse(fs.readFileSync(path.join(shardDir,f),'utf8'))).sort((a,b)=>a.shard.index-b.shard.index);const shardCount=shards[0]?.shard?.count;if(!Number.isInteger(shardCount)||shards.length!==shardCount)throw new Error(`dynamic shard cardinality mismatch ${shards.length}/${shardCount}`);for(let i=0;i<shards.length;i++){const s=shards[i];if(s.status!=='P25_INCOMPLETE_ABCD_DYNAMIC_SHARD_READY'||s.sessionDate!==freeze.sessionDate||s.shard.index!==i||s.shard.count!==shardCount)throw new Error(`invalid dynamic shard ${i}`);for(const k of ['executionAllowed','brokerWriteAllowed','excelOrderWriteAllowed','rssOrderFunctionAllowed','liveTradingAllowed','paperTradingAllowed','automaticPromotionAllowed','productionUpdateAllowed','transmitted','freshHoldoutConsumed'])if(s.safety?.[k]!==false)throw new Error(`unsafe ${k} shard ${i}`);}
const pairs=shards.flatMap(s=>s.B?.pairs??[]);const blocked=shards.flatMap(s=>s.B?.blocked??[]);const pointAudit=shards.flatMap(s=>s.pointAudit??[]).sort((a,b)=>String(a.observedAt??'').localeCompare(String(b.observedAt??'')));const seen=new Set();for(const p of pairs){if(seen.has(p.key))throw new Error(`duplicate dynamic pair ${p.key}`);seen.add(p.key);}pairs.sort((a,b)=>String(a.entry?.entryTimestamp??'').localeCompare(String(b.entry?.entryTimestamp??''))||String(a.symbol??'').localeCompare(String(b.symbol??'')));
const portfolioBars={};for(const [symbol,rows] of Object.entries(bars.sessionBarsBySymbol??{})){const map=new Map((rows??[]).map(bar=>[String(bar.timestamp),{timestamp:String(bar.timestamp),close:Number(bar.close)}]));for(const p of pairs.filter(x=>x.symbol===symbol))map.set(String(p.entry.entryTimestamp),{timestamp:String(p.entry.entryTimestamp),close:Number(p.entry.entryPrice)});portfolioBars[symbol]=[...map.values()].sort((a,b)=>a.timestamp.localeCompare(b.timestamp));}
const portfolioTrades=pairs.map(p=>({entryAccepted:true,frozenBeforeOutcome:true,currentOutcomeUsed:false,symbol:p.symbol,sector:p.entry.sector,signalDirection:p.entry.signalDirection,sessionDate:freeze.sessionDate,entryTimestamp:p.entry.entryTimestamp,entryPrice:Number(p.entry.entryPrice),exitTimestamp:p.v3.exitTimestamp,exitPrice:Number(p.v3.exitPrice),exitReason:p.v3.exitReason,netReturnPct:Number(p.v3.netReturnPct)}));const portfolioSessions=[{sessionDate:freeze.sessionDate,sessionBarsBySymbol:portfolioBars,trades:portfolioTrades}];const dProfiles={};for(const profile of PHASE57_P25_LANE_C_ALLOCATION_PROFILES)dProfiles[profile.id]=simulateLaneCPortfolio({sessions:portfolioSessions,profile,managementMode:'EXIT_V3',universeVariant:'DYNAMIC_5M'});
const originalSelected=new Set(measurements.flatMap(x=>(x.selected??[]).map(r=>String(r.symbol??'').trim().toUpperCase())).filter(Boolean));const usable=new Set(Object.keys(bars.sessionBarsBySymbol??{}));const safety={...P25_EXIT_V3_SAFETY,...PHASE57_P25_LANE_C_SAFETY,phase:'57.p25.incomplete-abcd-dynamic',mode:'READ_ONLY_DYNAMIC5M_POINT_SHARDED_RECOMBINE',executionAllowed:false,brokerWriteAllowed:false,excelOrderWriteAllowed:false,rssOrderFunctionAllowed:false,liveTradingAllowed:false,paperTradingAllowed:false,automaticPromotionAllowed:false,productionUpdateAllowed:false,transmitted:false,freshHoldoutConsumed:false};for(const k of ['executionAllowed','brokerWriteAllowed','excelOrderWriteAllowed','rssOrderFunctionAllowed','liveTradingAllowed','paperTradingAllowed','automaticPromotionAllowed','productionUpdateAllowed','transmitted','freshHoldoutConsumed'])if(safety[k]!==false)throw new Error(`unsafe ${k}`);
const frozenEntryCount=shards.reduce((s,x)=>s+Number(x.B?.frozenEntryCount??0),0);const payload={schemaVersion:1,phase:'57.p25.incomplete-abcd-dynamic',status:'P25_INCOMPLETE_ABCD_DYNAMIC_READY',sessionDate:freeze.sessionDate,createdAt:new Date().toISOString(),B:{route:'Dynamic 5m Selection -> Frozen Entry -> EXIT v3',pointCount:measurements.length,expectedPointCount:measurements.length,missingExpectedBucketCount:0,frozenEntryCount,resolvedCount:pairs.length,blockedCount:blocked.length,summary:summary(pairs.map(x=>x.v3?.netReturnPct)),pairs,blocked},D:{route:'Dynamic 5m Selection -> Frozen Entry -> EXIT v3 -> Capital Allocation',initialEquityJpy:1_000_000,profileWinnerSelected:false,profiles:dProfiles},pointAudit,dynamicBundleAudit:{originalSelectedSymbolUnionCount:originalSelected.size,evaluableSelectedSymbolUnionCount:[...originalSelected].filter(s=>usable.has(s)).length,excludedSymbols:[...originalSelected].filter(s=>!usable.has(s)).sort()},methodology:{sameFrozenDynamicSelectionEvidence:true,sameExistingDynamic5mExitV3PortfolioEvaluator:true,capitalAllocationPolicyUnchanged:true,allocationProfileWinnerSelection:false,resultBasedRetuning:false,executionTopologyOnlyPointSharding:true,deterministicRecombine:true,noBackfillOrFabrication:true},safety};fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(payload,null,2)+'\n');console.log(JSON.stringify({status:payload.status,sessionDate:payload.sessionDate,B:payload.B.summary,D:Object.fromEntries(Object.entries(dProfiles).map(([k,v])=>[k,{totalReturnPct:v.return?.totalReturnPct,maxDrawdownPct:v.risk?.maxDrawdownPct,finalEquityJpy:v.return?.finalEquityJpy}]))},null,2));
