"""Render saved diagnostic aggregates; no research evaluation or provider call."""
import hashlib
import json
from pathlib import Path

B=Path('docs/evidence/phase57-long-exit-v345-paired')
s=json.loads((B/'summary.json').read_text())
l=json.loads((B/'lineage-audit.json').read_text())
c=json.loads((B/'contract.json').read_text())
lines=[]
def para(x):lines.extend([x,''])
def table(headers,rows):
    lines.append('| '+' | '.join(headers)+' |')
    lines.append('| '+' | '.join('---' for _ in headers)+' |')
    lines.extend('| '+' | '.join(map(str,r))+' |' for r in rows);lines.append('')
def f(x):return 'N/A' if x is None else f'{x:.4f}'
def r(x):return f"{x['count']}/{x['denominator']} ({f(x['ratePct'])}%)"

para('# Phase57 LONG-only EXIT v3 / v4 / v5: Historical diagnostic and paired-replay feasibility')
para('2026-09-16 JST. Verdict: **EXIT_ARCHITECTURE_INCONCLUSIVE**. No LONG EXIT foundation selected. This is direct Entry Development / IN-SAMPLE historical reuse, not Fresh Validation, OOS, Prospective, final PASS or production readiness.')
para('Repo Iam-2squared/ark-terminal; branch research/phase57-long-only-cash-equity; PR #587 remains open, no main merge. Start upstream head e2a2f8752d859365187a2798bd840689146dcf2e. Preregistered computation head 13e5aa84ac7e4b39200662b9c71435ba4c62ac24. Main branch API at start/end evidence preparation: b7801ce2c13772cbc3f5b51506819c119fe868ea. The PR response separately returned base SHA f43abbbb41718e513d46c69c81b2efcf6653ab07; it is not substituted for the main branch reference. Final result commit and final-head CI are reported in the task handoff/GitHub history.')
para('## Completion and blockers')
table(['Task','Result'],[['v3/v4/v5 lineage','Recovered source, candidate contract, commit and SHA'],['Fixed 277 identity','277 retained; no regeneration or trade replacement'],['Post-entry diagnostic','Completed on available horizons with missingness disclosed'],['Fixed / Session-End','41 common path-complete pairs only; not 277-pair success'],['v3 / v4 / v5 paired replay','NOT EXECUTED: causal analog input unavailable; metrics null'],['Foundation selection','INCONCLUSIVE; neither reuse nor new EXIT justified by unmeasured arms']])
para('The recovered v3/v4 continuation uses a pinned 56-day analog snapshot ending 2026-08-12. Every such analog is later than the latest target Entry on 2025-01-09. The unchanged scorer requires earlier session AND fully realized analog before query time, with at least 30 neighbors. This frozen pool therefore provides zero causal neighbors for every target Entry. The snapshot itself was not opened. No alternative frozen pre-Entry pool was identified in the recovered lineage. A synthetic test of the unchanged scorer confirms rejection of later analogs. This is a causal input-artifact mismatch, not evidence that v3/v4/v5 performance failed.')
para('Additional blockers: incomplete session-end paths, and v5 final bar5 versus old bar6 runtime / truncated-v4-trace fallback semantics. Future analogs, newly fitted pools, missing-data HOLD, bar6 substitution and fabricated performance are not used. No additional market acquisition was attempted because filling price paths would not fix the frozen analog chronology.')
para('## Frozen upstream and identity')
para('Selector freeze commit 565d74b3dea823581fdb32380113aac5913a248d; payload 3dc6d222d4039737c0dcfdcfa4a83372202152e29b582225419ab97c00610d59; Ridge 994f1dbaba1d32e97458d5dd9d4c646ef443fbb37128650e8166001d8deabefb. Candidate Threshold 2.0, score P1+2P2+3P3+4P4, features frozenSelectorRidgeScore and frozenSelectorRidgeRank, no optional feature, no WAIT/expiry; no repeated ENTER for a symbol-session. Upstream status remains MSH_ENTRY_LONG_V1_FROZEN_FOR_EXIT_RESEARCH; Historical BORDERLINE; Fresh Validation PENDING.')
table(['Artifact','Verified SHA-256'],[[p,h] for p,h in c['sourcePins'].items() if any(k in p for k in ['candidate-v1','final-model','final-scaler','upstream-freeze/manifest','historical-enter-identities','global-data-budget'])])
para('Dataset 2024-09-17–2025-01-09, 76 Development sessions, saved 277 ENTER. Entry timestamp/reference is copied exactly from the existing ledger: causally available closed Decision Price; no prediction, re-ranking or Entry timestamp regeneration. All source pin checks passed. The Global Budget remains 195; Fresh consumption = 0.')
para('## Existing EXIT lineage / LONG compatibility')
table(['Arm','Identity / semantics','Compatibility'],[['Fixed','Inherited future.slice(0,12), completed close, regular-session end cap, cost 0.05%','Reference only'],['Session-End','Last regular-session completed close; same cost','Reference only'],['v3','Dual gate state-conditioned; prior analog 1/3/6-bar forecasts, min30 neighbors; loser1bar, winner2 confirmations','LONG branch exists; causal input mismatch'],['v4','Structural risk trajectory; v3/v2 analog dependency; loser trajectory/emergency, winner giveback, neutral loss persistence','LONG branch exists; causal input mismatch'],['v5','EXIT_V5_DYNAMIC_RECLAIM_BAR_5; DEVELOPMENT_FINAL_SELECTED_NOT_VALIDATED; frozen v4 continuation','Causal input mismatch and adapter parity unresolved']])
para('v5 authoritative branch research/phase57-exit-v4-hybrid-msh-large-scale at ea15a594103bd6c9146f19a4aebafb83067d869b. Final candidate commit 417ad9d6dc92c3110e680cdc4a6c8dcf94b4ee5e; final sweep implementation commit aaa99030295ffb447de273881b16aad1eab1a7e9. First completed bar non-adverse continues v4; adverse enters DEFENSIVE; completed-close reclaim >=0 by bar5 continues v4; no reclaim exits at bar5. Older dynamic-state module asserts horizon6 and is NOT the selected bar5 implementation. The selected sweep simulator consumes truncated v4 management decisions and falls back to v4 if horizon is absent. Early v4 exit and missing-horizon behavior must be explicitly mapped before claiming a faithful online mechanical adapter. No sweep was executed. The other v5 research-baseline branch contains different continuation/GBM experiments, not the requested final candidate. Mixed-direction old development does not establish LONG-only suitability.')
table(['Source','SHA-256','Last change'],[[p,x['sha256'],x['lastChangeCommit']] for p,x in l['sourceIdentities'].items()])
para('## Provenance and measurement semantics')
para('New authorized workflow run 35091141862 succeeded at preregistered head13e5aa84. Artifact10443914414 ZIP SHA72df35b601c94a6931791a924846b1449492dd2361572570937d9f4b7750b647. Original encrypted Development checkpoint runs34926225832 / 34936002178 / 34964031692 were recovered and checked; prior EXIT diagnostic run35087975004 remained unopened/unused. Raw page SHA, normalized SHA and source audits are in paths.json.gz. Transient decrypted raw cache was deleted by the workflow; original encrypted checkpoints remain.')
para('Five-minute bars reuse the frozen normalizer, without forward-fill/interpolation/substitution. Same-day raw OHLC/reference basis, LONG only, no overnight and no corporate-action adjustment added. Completed-bar timestamps determine observability. Strict 30m excludes lunch/session-end crossing. Session-End excludes auction-only bars; regular close15:00 before2024-11-05,15:30 thereafter. Sparse observed-minute bars are disclosed, not imputed. PROVIDER_GAP means an absent expected 5m slot: it does NOT prove an outage rather than no trade. No absent interval is silently assumed flat. Returns are reference-price diagnostics, not broker-realized fills; liquidity/slippage and auction execution remain unproven.')
para('MFE=max(0,future HIGH/reference−1); MAE=min(0,future LOW/reference−1). Extremum times use completed-bar ends, not known intrabar times. Same-bar extrema order is UNKNOWN_INTRABAR_ORDER. All percent returns use percentage units; net=gross−0.05 percentage point. Future paths are evaluation only. Missing entries remain in the 277 identity inventory; each metric states its availability denominator.')
table(['Horizon','Available /277','Missing reasons','MAE median /p05 /worst %','MFE mean /median /P25 /P75 /P90 %','Close return mean /median %','Sparse paths'],[[k,r(h['availability']),json.dumps(h['unavailableReasons']),'/'.join(f(h['maePct'][q]) for q in ['median','p05','min']),'/'.join(f(h['mfePct'][q]) for q in ['mean','median','p25','p75','p90']),'/'.join(f(h['returnPct'][q]) for q in ['mean','median']),h['sparsePathCount']] for k,h in s['horizons'].items()])
para('The 181 strict30m results reproduce the already frozen Entry reference (MAE median−1.533742%, p05−10.256410%, worst−35.294118%). This is identity/measurement parity, not independent validation. Only41/277 have every expected remaining regular 5m slot; all41 are in2024-09-18–2024-11-01. This coverage-selected subset cannot stand for all277 or all76 sessions.')
para('Important session-boundary limitation: all187 entries dated2024-11-05 or later lack the expected15:25-start final slot in the recovered normalized paths. This systematic absence may reflect closing-auction/no-trade representation rather than random provider loss; the current expected-slot checker does not establish which. Therefore41 is completeness under this preregistered conservative slot policy, not proof that only41 original market paths can ever be reconstructed. No final close is imputed, no auction is silently substituted, and the pre-result slot rule is not retroactively changed. Auction/session-end semantics must be resolved explicitly before full-session replay. This is an additional DATA_REQUIREMENT_MISMATCH, not a reason to buy missing bars blindly. The strict30m reference parity is unaffected.')
para('## Adverse, recovery, opportunity, timing and path types')
para('Immediate first5m completed-close adverse: '+r(s['immediateAdverse']['first5mCompletedCloseNegative'])+'; first5m LOW adverse: '+r(s['immediateAdverse']['first5mLowBelowEntry'])+'. These are different definitions.')
for k in ['30','SESSION_END']:
    h=s['horizons'][k]
    para('### '+k)
    table(['MAE bucket','Count/rate','Later completed-close reclaim','Recovery median clock min','Later +1/+2/+3/+5 counts','Horizon-close median %'],[[level,r(v['adverse']),r(v['laterCompletedCloseReclaim']),f(v['recoveryClockMinutesAfterAdverse']['median']),'/'.join(str(v['laterOpportunityCounts'][str(n)]) for n in [1,2,3,5]),f(v['horizonCloseReturnPct']['median'])] for level,v in h['adverseRecovery'].items()])
    table(['MFE at least','Count/rate'],[[level,r(v)] for level,v in h['mfeAtLeast'].items()])
    table(['Ordering','Count','Rate %'],[[name,n,f(100*n/h['availability']['count'])] for name,n in h['ordering'].items()])
    table(['Time to','<=5m','5–10m','10–15m','15–30m','>30m','Median min'],[[name,*v['exclusiveBuckets'].values(),f(v['distribution']['median'])] for name,v in [('MFE',h['timeToMfe']),('MAE',h['timeToMae'])]])
para('Recovery excludes the first adverse bar because its intrabar ordering is unknown. Later completed CLOSE>=Entry defines reclaim, not a profitable final outcome. Later opportunity counts exclude entries with no later observation. Adverse cohorts and their complete available denominators are not statistically independent. Detailed first-adverse depth/time and later path are retained per entry in paths.json.gz.')
table(['Exclusive descriptive class','Count /277'],[[k,s['pathTypes'].get(k,0)] for k in ['A_EARLY_ADVERSE_THEN_RECOVERY','B_EARLY_FAILURE','C_FAST_WINNER','D_WINNER_THEN_GIVEBACK','E_SLOW_WINNER','F_CHOP_NO_EDGE','G_UNKNOWN']])
para('Classes were fixed before path results: first ±1% touch, early<=15m, fast<=30m, final close sign; same-bar first touch is UNKNOWN. These labels are descriptive, not live rules, causal structural labels or an EXIT threshold search. 243 UNKNOWN =236 incomplete session paths +7 ambiguous same-bar first ±1% touches. Slow winner0 is not evidence of absence in the full277.')
para('## Paired reference results — NOT a five-arm comparison')
arms=s['pairedReferenceOnly']['arms'];names=list(arms)
rows=[]
for label,get in [('N',lambda a:a['n']),('Gross sum (percentage points)',lambda a:f(a['grossSumPctPoints'])),('Net sum (percentage points)',lambda a:f(a['netSumPctPoints'])),('Average / median net %',lambda a:f(a['netTradePct']['mean'])+' / '+f(a['netTradePct']['median'])),('Win rate',lambda a:r(a['winRate'])),('Profit factor',lambda a:f(a['profitFactor'])),('DD trade-order proxy (pp)',lambda a:f(a['maxDrawdownRealizedTradeOrderProxyPctPoints'])),('Mean / median loss %',lambda a:f(a['lossTradePct']['mean'])+' / '+f(a['lossTradePct']['median'])),('Worst / p05 net %',lambda a:f(a['netTradePct']['min'])+' / '+f(a['netTradePct']['p05'])),('Mean / median holding bars',lambda a:f(a['holdingBars']['mean'])+' / '+f(a['holdingBars']['median'])),('Holding clock buckets',lambda a:json.dumps(a['holdingClockMinutes']['exclusiveBuckets'])),('Pre-exit MAE mean / median %',lambda a:f(a['preExitMaePct']['mean'])+' / '+f(a['preExitMaePct']['median'])),('Gross MFE capture mean / median',lambda a:f(a['grossAvailableMfeCapture']['mean'])+' / '+f(a['grossAvailableMfeCapture']['median'])),('Giveback mean / median pp',lambda a:f(a['givebackFromAvailableMfePctPoints']['mean'])+' / '+f(a['givebackFromAvailableMfePctPoints']['median'])),('Session-end exposure',lambda a:r(a['sessionEndExposure'])),('Recovered-cohort net winner preserved',lambda a:r(a['adverseHandling']['recoveredWinnerPreserved'])),('False early exit before later close reclaim',lambda a:a['adverseHandling']['falseEarlyExitBeforeLaterCloseRecovery']),('Mean loss reduction vs end on end-losers (pp)',lambda a:f(a['adverseHandling']['lossReductionVsSessionEndPctPoints']['mean'])),('End-losers held to end',lambda a:a['adverseHandling']['loserHeldToSessionEnd']),('Positive profit Top1/3/5 shares',lambda a:'/'.join(f(100*v)+'%' for v in a['concentration']['positiveProfitTop1Top3Top5'].values()))]:rows.append([label,*[get(arms[n]) for n in names]])
table(['Metric',*names],rows)
table(['Realized net loss bucket',*names],[[str(k),*[r(arms[n]['realizedLossBuckets'][str(k)]) for n in names]] for k in [-1,-2,-3,-5,-10]])
for k in [1,2,3,5]:
    table(['Available MFE >= '+str(k)+'%','Net realization count/rate','Exit before later first touch','Winner net mean /median %'],[[n,r(arms[n]['opportunityRealization'][str(k)]['netRealizedAtLeast']),r(arms[n]['opportunityRealization'][str(k)]['prematureExitBeforeLaterFirstTouch']),f(arms[n]['opportunityRealization'][str(k)]['winnerFinalNetPct']['mean'])+' / '+f(arms[n]['opportunityRealization'][str(k)]['winnerFinalNetPct']['median'])] for n in names])
para('Gross/net sums are sums of unweighted per-trade percentage returns, not portfolio ROI. DD is an Entry-time/symbol/ID-ordered additive closed-trade proxy, not execution-time equity, mark-to-market or capital-allocation drawdown. MFE capture uses same full-session available MFE, is unbounded below, and excludes2 MFE<=0 denominators; net capture is separately stored. Giveback here includes opportunity AFTER exit, not only already-earned upside. Premature means exit before first later level touch, not all possible winner impairment. End-loss cohorts are hindsight diagnostic labels. Both references share the same41 identities, cost and path; Fixed standalone availability173 is not mixed into this table.')
for n in names:
    para('### '+n+' concentration (absolute return share; top5 groups)')
    for field,groups in arms[n]['concentration']['grouped'].items():table([field,'Trades','Net sum pp','Absolute share %'],[[g['identity'],g['trades'],f(g['netSumPctPoints']),f(100*g['absoluteReturnShare'])] for g in groups[:5]])
table(['Requested arm','Replayed trades','Return/risk/capture/holding metrics','Selection'],[[n,0,'NULL — not measured, not zero performance','No ranking'] for n in ['v3','v4','v5']])
para('## Interpretation and exact next action')
para('Tail and recovery coexist: at30m,10/181 paths reach MAE<=−10%, and2/10 later reclaim Entry at a completed close;63/105 of the <=−1% cohort reclaim. Thus an immediate adverse print alone does not establish structural failure. Conversely,41 complete session paths show substantial giveback and concentration; simply holding longer is not uniformly better. In the shared reference subset Fixed realizes +3/+5 on6/24 and3/15, versus Session-End8/24 and5/15, but Session-End has worse average net and lower-tail realized return. These are diagnostics, not sufficient evidence for choosing v3/v4/v5 or designing optimal stops.')
para('Biggest remaining risk: causal EXIT forecasting inputs and full-path coverage are not reproducible for the fixed277. Next action requires a genuinely pre-Entry frozen analog pool with artifact SHA and adequate neighbors, or explicit authorization for a separately versioned causal LONG Development pool (which changes the old frozen evidence context). Also specify final bar5 early-v4-exit/missing-horizon parity and resolve missing-path/no-trade coverage without filling or replacing the277. Do not call a new pool an unchanged frozen replay. Do not silently acquire another period. No new LONG EXIT design/training/tuning is performed until that responsibility is resolved.')
para('## Tests, safety and stop')
para('Offline regression2886 PASS (Predict2702, Discovery26, Foundation39, Python30, RSS89). Additional focused tests20 PASS: path/causal6, aggregation4, artifact/summary integrity3, upstream7. One initial unittest module-import error was fixed; all final focused tests pass. New path workflow35091141862 SUCCESS. Final-head CI is checked after publication; a green CI does not unblock scientific replay. Integrity rerenders aggregates from saved derived paths only, never predicts Entry or replays v3/v4/v5.')
table(['Counter','Value'],[[k,v] for k,v in s['counts'].items()]+[['Selector logic changes',0],['Entry logic changes',0],['Existing EXIT strategy changes',0],['Fresh budget consumed',0]])
table(['Safety flag','Value'],[[k,str(v).lower()] for k,v in s['safety'].items()])
para('STOP: EXIT_ARCHITECTURE_INCONCLUSIVE. Frozen upstream remains unchanged. No official LONG EXIT validation, OOS PASS or production readiness claim.')
para('## Evidence checksums')
table(['Artifact','SHA-256'],[[p.name,hashlib.sha256(p.read_bytes()).hexdigest()] for p in sorted(B.iterdir()) if p.is_file() and p.name!='report.md'])
(B/'report.md').write_text('\n'.join(lines)+'\n')
