"""Render P0 findings and a NON-FROZEN next-step comparator proposal."""
import json
from scripts.phase57_msh_entry_v2_architecture import OUT, CONTRACT, read, sha, MAE_NAMES, MFE_NAMES

def make():
 d=read(OUT/'diagnostic.json.gz');c=read(CONTRACT);lines=[]
 def p(s=''):lines.append(s)
 def fmt(x,n=3):return 'UNKNOWN' if x is None else f'{x:,.{n}f}' if isinstance(x,(int,float)) else str(x)
 def table(h,rs):
  p();p('| '+' | '.join(h)+' |');p('| '+' | '.join(['---']*len(h))+' |')
  for r in rs:p('| '+' | '.join(str(v) for v in r)+' |')
  p()
 def summary_table(groups):
  table(['Group','277-side N','strict30m N','Net30 mean %','Net30 median %','Net30 PF','MFE median %','MAE median %','Tail<=−10 N','LONG EXIT N/mean %','Portfolio accepted N/PnL JPY'],[(k,v['N'],v['strictN'],fmt(v['net30ReferencePct']['mean']),fmt(v['net30ReferencePct']['median']),fmt(v['net30ReferencePct']['PF']),fmt(v['mfe']['median']),fmt(v['mae']['median']),v['tail']['-10']['n'],f"{v['selectedExitNetPct']['n']}/{fmt(v['selectedExitNetPct']['mean'])}",f"{v['acceptedPortfolioPnlJpy']['n']}/{fmt(v['acceptedPortfolioPnlJpy']['sum'],2)}") for k,v in groups.items()])
 failure=[
 {'id':'A','failure':'TAIL_FAILURE_NOT_DETECTED','verdict':'TRUE','evidence':'10/181 enter paths have MAE<=−10%;5 are57590. v1 score has no explicit adverse-risk meaning. Detectability before entry remains unproven.'},
 {'id':'B','failure':'OPPORTUNITY_TRADABILITY_CONFUSED','verdict':'PARTIAL','evidence':'2/10 extreme paths also reach+5%;89180 has21/21 +5 HIGH opportunities but only7/22 profitable chosen exits. Target mismatch is established; actual executable fill quality is unmeasured.'},
 {'id':'C','failure':'SCORE_NOT_CALIBRATED_FOR_REALIZED_OUTCOME','verdict':'TRUE','evidence':'Strict181 score-quartile return/MFE/MAE/tail directions all nonmonotonic; Q4 tail5/45 vsQ1 1/46. No claim that the ordinal probabilities themselves fail formal probability calibration.'},
 {'id':'D','failure':'CROSS_SYMBOL_GENERALIZATION_WEAK','verdict':'PARTIAL','evidence':'Top1/Top3 symbol removal cash replay−7.86%/−19.71%; profit concentration and tail influence material. No held-symbol out-of-sample model evaluation performed.'},
 {'id':'E','failure':'COVERAGE_EXECUTION_SEMANTICS_LIMITATION','verdict':'TRUE','evidence':'96/277 lack strict30m;104 excluded from common173;full277 equity unknown. Upstream L1 membership filters on future-label availability. Same-close reference is not guaranteed execution.'},
 {'id':'F','failure':'OTHER_PRICE_GRANULARITY_AND_DEPENDENCE','verdict':'PARTIAL','evidence':'89180 seven profitable exits are7→8 or8→9 JPY,15 exits gross-flat; loss10 observations cover6 symbols, half one symbol. Tick size/spread and causal fill harm not measured.'}]
 architecture={
  'verdict':'MSH_ENTRY_LONG_V2_ARCHITECTURE_DIAGNOSTIC_COMPLETE',
  'meaning':'Architecture requirements complete; risk predictability / v2 performance INCONCLUSIVE. STOP before model/target/features/state/numeric gates freeze or fit.',
  'primaryProblem':'MULTIPLE', 'failureAttribution':failure,
  'rootCausePriority':['Preserve PIT field/missing semantics and denominator identity','Separate upside opportunity from adverse-path risk meaning','Assess severe/moderate/extreme + winners jointly with symbol influence control','Define calibration target and group/chronological evaluation','Same-downstream throughput/preservation/portfolio robustness trade-off'],
  'mustPreserve':['Frozen Selector','cash-equity LONG only','same Decision Price reference and PIT timestamps','reasonable throughput with denominator disclosure','+3/+5 opportunity preservation','simple execution state','same-session scope','Frozen EXIT/Equal/cash ledger comparator'],
  'mustImprove':['deep adverse tails and frequency','cross-symbol quality and top1/top3 sensitivity','score interpretation/calibration','portfolio PF/MaxDD/median direction','winner-risk trade-off transparency'],
  'mustNot':['symbol ID predictor/blacklist/symbol model/threshold','89180 or57590 special rules','post-hoc time/segment/liquidity filter','future MAE/MFE/reclaim/EXIT/PnL feature','feature zoo','Validation/OOS tuning','score-based sizing','silent outcome-selected coverage expansion'],
  'families':[{'family':'C Opportunity Gate + Risk Veto','disposition':'FIRST_PREDEVELOPMENT_FAMILY_TO_SPECIFY_NOT_SELECTED','reason':'Keep Frozen Selector opportunity; test a small independently interpretable adverse-risk gate. No veto threshold chosen.'},
   {'family':'A Single Quality Model','disposition':'MINIMAL_ALTERNATIVE_FOR_NEXT_CONTRACT','reason':'May suffice if a clearly defined net-quality target can balance tail and preservation; no composite weight chosen.'},
   {'family':'B Two-Head','disposition':'RESERVE_NOT_DEFAULT','reason':'Separate risk/quality meanings useful, but only10 extreme events and existing opportunity Selector do not justify duplicating opportunity training or a complex shared model.'},
   {'family':'D Minimal Stateful / WAIT','disposition':'DEFER_NO_TIMING_COUNTERFACTUAL_EVIDENCE','reason':'Waiting changes timestamps/prices and label windows; this diagnostic does not test causal delayed entry.'},
   {'family':'Symbol models / broad feature ensembles / targetless score blending','disposition':'REJECT_FOR_THIS_DESIGN','reason':'Violates symbol-generalization, small-sample simplicity or explicit score meaning.'}],
  'questions':{
   'Q1':'Prefer a small new risk/quality responsibility alongside frozen opportunity, rather than only changing v1 threshold; architecture not frozen.',
   'Q2':'MULTIPLE: opportunity/tradability separation, realized-outcome calibration, tail failure and cross-symbol dependency.',
   'Q3':'Non-score market state is justified for investigation; incremental predictive value not yet demonstrated. Six-field fixed descriptive panel only.',
   'Q4':'ENTER/SKIP is the initial comparator proposal; no evidence requires WAIT. Final state not frozen.',
   'Q5':'Keep risk and opportunity meanings separate; separate outputs do not mandate two independently complex models.',
   'Q6':'Retain ordinal opportunity as a preservation benchmark/possible auxiliary; do not let HIGH-touch ordinal alone define tradability.',
   'Q7':'Tail auxiliary may be useful, but10 extreme events across6 symbols cannot support a complex tail-only classifier; include severity continuum and censored labels.',
   'Q8':'Do not use score for sizing; Equal remains frozen.',
   'Q9':'Predeclare symbol-disjoint grouped evaluation plus chronological evaluation with overlapping label-window purge; show symbol-macro and event-micro statistics, top-contributor and dominant-tail influence. All remain Development; Frozen Selector was already outcome-exposed.',
   'Q10':'Existing3800 candidates/1828 strict labels and existing feature snapshots support a later Development contract and small experiment; complete whole-universe executable portfolio is not currently established.'},
  'modelFamilyFreeze':None,'targetFreeze':None,'featureFreeze':None,'stateFreeze':None,'numericCompletionGates':None,
  'predictabilityVerdict':'INCONCLUSIVE_NOT_TESTED_WITH_HELD_SYMBOL_MODEL', 'counters':c['counters'],'safety':c['safety']}
 comparator={
  'status':'DRAFT_FOR_NEXT_PRE_DEVELOPMENT_CONTRACT_NOT_A_V2_CANDIDATE','baseline':'MSH_ENTRY_LONG_V1_FROZEN_FOR_EXIT_RESEARCH','challenger':'NOT_IMPLEMENTED',
  'inputUniverse':'Same frozen3800 Top5 selection events /760 timestamps /76 sessions; NOT only277 old ENTERs. v1 identity277 immutable; challenger decisions may differ. No acceptance intersection as primary comparison.',
  'entryState':'ENTER/SKIP proposal, first accepted Entry per symbol-session; timing/WAIT change would require separately versioned comparator',
  'fixed':{'selector':d['identities']['selectorFreezeCommit'],'decisionPrice':'identical frozen event reference','exit':'LONG_EXIT_BAR5_TWO_LOWER_CLOSES_V1','allocation':'EQUAL_MAX3 / V3_0_EQUAL arithmetic','cashLedger':'scripts/phase57_long_capital_integration.py','capitalContract':'predict/research/phase57-long-capital-integration-v1.json','initialCashJpy':1000000,'lotShares':100,'maxConcurrent':10,'costRoundTripPctEntryNotional':.05,'sizingBudgetDivisor':3},
  'eventOrder':['observed completed bar','frozen exit decision','reference exit and cash release','entry symbol ASC then eventId; common snapshot equity/slots','observed MTM'],
  'coverage':'Primary all candidate events, causal Entry eligibility only. Keep censored/unresolved positions, no fictional marks/cash release. Null fullPortfolio equity when unpriced. Predeclared common observable subset is secondary only; no v1/v2 acceptance intersection or future completion in Entry features.',
  'inheritedUniverseLimitation':'L1 matchedFeatures requires future label availability. Frozen3800 may be used only as the shared historical conditional universe; no future-conditioned eligibility may enter the eventual decision runtime. Need separately versioned audit before claims on full live universe; do not modify Selector in this task.',
  'coverageMinimum':'277 existing entry identities have full post-entry diagnostic paths; retained3800 fields have1828 strict HIGH/LOW labels. Chosen-exit/cash paths for alternative3800 entries require projection from existing76 checkpoints, not new provider/Fresh. Do not represent173/277 as challenger universe.',
  'reference':'latest accepted minute close; missing=no observation not zero volume. Before2024-11-05 regular end15:00, later15:30; 15:25-start auction interval not silently replaced. Lunch not elapsed trading bars for30 wall-clock label. Sparse-minute5m bars disclosed. Same-bar HIGH/LOW ordering UNKNOWN_INTRABAR_ORDER. Reference-close fills unproven.',
  'splitting':'Next contract must freeze chronology and symbol grouping before fit; fit scaler/calibration within training folds only; purge overlapping label windows and keep same symbol-session together. Existing v1 fitted full Development makes this a developmental comparison, not new OOS proof. Hold-symbol tests evaluate added Entry component conditional on exposed Frozen Selector.',
  'metrics':{
   'entry':['ENTER count/rate/per-session','unique symbols/trades-per-symbol','time/segment/liquidity distribution','feature missingness and censoring by arm'],
   'opportunity':['+1/+2/+3/+5 Precision and Preservation against SAME frozen available candidate label denominator','MFE','remaining opportunity at decision'],
   'risk':['MAE median/p05/worst','MAE<=−2/−5/−10','first-bar adverse','later observed reclaim with missing flag'],
   'calibration':['score quantiles vs net return/PF/MFE/MAE/tail','score definition-specific calibration, not arbitrary score monotonicity only'],
   'portfolio':['Final Equity/Return/PF/MaxDD','Median trade/Win rate','cash utilization/accepted/rejected count'],
   'robustness':['Top1 trade/symbol andTop3 trades/symbols removed descriptive cash replays','Top5 symbols if support','positive/negative contribution HHI','profitable/losing symbols/median symbol contribution/dispersion','leave-major-symbol-out','dominant-tail-symbol influence']},
  'gatePhilosophy':'Multi-axis trade-offs explicit; no requirement every metric improves. No post-hoc numeric hurdle here; next contract freezes numerical gates before v2 outcomes.',
  'freshBudgetSHA':d['identities']['globalBudgetSHA'],'freshBudget195Preserved':True,'trainNow':False,'predictionNow':False}
 (OUT/'architecture-decision.json').write_text(json.dumps(architecture,indent=2)+'\n')
 (OUT/'fair-comparator-draft.json').write_text(json.dumps(comparator,indent=2)+'\n')
 p('# MSH-Entry LONG v2 — P0 Architecture Diagnostic')
 p('**MSH_ENTRY_LONG_V2_ARCHITECTURE_DIAGNOSTIC_COMPLETE — STOP before learning.**')
 p('Historical / Development / IN-SAMPLE / Outcome-exposed。設計要件の診断完了。Entry v2性能やtail予測可能性の証明ではない。新model fit/prediction/feature selection/threshold searchは0。')
 p('結論：v1は上昇HIGHのOpportunityを選ぶが、深い逆行や実現利益の質を直接評価していない。89180の利益は7件の1円上昇に集中し、tail10件の半分は1銘柄。既存pullbackに記述的差はあるが分布は重なり、銘柄横断の予測力は未証明。次は最小Risk Veto/Quality案のPre-Development Contractを作る段階。今回は学習せずSTOP。')
 p('## Identity / scope')
 table(['Item','Value'],[['Branch','research/phase57-long-only-cash-equity'],['PR','#587 Draft / unmerged'],['Source head',c['sourceHead']],['Final head','This report commit; exact final hash in completion message'],['Latest main at start',c['mainAtStart']],*list(d['identities'].items()),['LONG EXIT','LONG_EXIT_BAR5_TWO_LOWER_CLOSES_V1'],['Allocation','EQUAL_MAX3; V3_0_EQUAL arithmetic'],['Cash ledger','scripts/phase57_long_capital_integration.py (SHA in contract)'],['Period','2024-09-17–2025-01-09'],['Sessions / candidate events','76 / 3800'],['ENTER / strict30m / paired / actual Equal accepted','277 /181 /173 /166'],['strict30m ∩ paired','158; strict181 is NOT the portfolio173 subset'],['Reference PDF','Named Entry v2 handoff PDF not present; user full specification + repo evidence used']])
 p('Entry v1 threshold2.0, features score/rank, model/scaler unchanged. Saved predictions only; no inference rerun. Feature timestamps can be causal while models were fitted on exposed Development: no retrospective real-time performance claim.')
 p('## P0 — Tail / winner / joint path')
 table(['Metric','strict181 result'],[['MAE median %',fmt(d['strict181']['mae']['median'])],['MAE p05 %',fmt(d['strict181']['mae']['p05'])],['MAE worst %',fmt(d['strict181']['mae']['min'])],['MAE<=−10', '10/181 (6 symbols;5 events one symbol)'],['MFE median %',fmt(d['strict181']['mfe']['median'])],['Later CLOSE reclaim after −10 touch','2/10 within strict30m; hit-bar order not inferred'],['Intrabar order unknown','7/181 extrema fall in same bar']])
 table(['MAE bucket']+MFE_NAMES+['Total'],[[a,*[d['jointMatrix'][a][b] for b in MFE_NAMES],sum(d['jointMatrix'][a].values())] for a in MAE_NAMES])
 p('MAE buckets exactly user boundaries: >−1; (−2,−1]; (−5,−2]; (−10,−5]; <=−10. MFE buckets <1;[1,2);[2,3);[3,5);>=5. No retuning. Extreme10 includes2 +5 and3 +3 opportunities: bad-path removal must quantify winner sacrifice. Max HIGH is not sellable PnL.')
 summary_table(d['tailCohorts']);summary_table(d['winnerCohorts'])
 table(['Extreme event','MAE%','MFE%','E[L]','Selector score','Price','Net30%','LONG exit net%'],[(r['eventId'],fmt(r['mae']),fmt(r['mfe']),fmt(r['mshScore']),fmt(r['ridgeScore']),r['x']['decisionPrice'],fmt(r['net30']),fmt(r['longNet'])) for r in d['extremeRows']])
 p('## P1/P7/P8 — Feature inventory / PIT / descriptive separation')
 p('27 fields inventoried:17 conditionally causal-formula fields (includes time, constants and redundant fields; NOT17 selected predictors),8 unavailable numeric snapshots,1 dated Master exact release-clock unknown,1 saved in-sample MSH score. Raw per-feature timestamp vectors are not retained; safety audit combines frozen builder source guards, source pins,3800 decision provenance and prior-selection ordering. This does not prove real-time latency or availability after provider arrival. Frozen L1 cross-section filters feature rows by future label availability; daily eligibility/adjustment metadata release clocks are not serialized. Therefore17 is conditional formula-time causality, not full-pipeline PIT certification. Original minute normalizer also maps missing volume/turnover to0; verify original missing counts before promoting any volume-derived feature.')
 table(['Field','Available /277','Available /181','PIT status','Preliminary class'],[(r['name'],r['available277'],r['strictAvailable181'],r['pitStatus'],r['preliminaryClassification']) for r in d['featureInventory']])
 p('Full definitions/source/timestamp/availableAt/lookback/missing/session/previous-session/fill/overlap/leakage/complexity/direction are in feature-inventory.json. No missing fill. VWAP is cumulative HLC3-volume PROXY, not traded-turnover VWAP. Segment is diagnostic-only until Master release semantics verified. Absolute liquidity, spread, gap, volatility and breadth snapshots were not silently reconstructed from outcome paths.')
 table(['Fixed descriptive panel','Tail / non-tail available','Median tail / non-tail','Cliff delta','Tail in non-tail range','+3 /+5 winner medians','Delta excluding dominant-tail symbol'],[(k,f"{v['tail']['n']}/{v['nonTail']['n']}",f"{fmt(v['tail']['median'])}/{fmt(v['nonTail']['median'])}",fmt(v['cliffDelta']),fmt(v['tailInsideNonTailRangeRate']),f"{fmt(v['winners']['3']['median'])}/{fmt(v['winners']['5']['median'])}",fmt(v['leaveDominantTailSymbolOutInfluenceDiagnostic']['cliffDelta'])) for k,v in d['signals'].items()])
 p('Six fields were fixed by semantics before new distribution analysis. Delta=P(tail value>non-tail)−P(<), ties0; descriptive only, no cutoff/AUC search. After cohort inspection, dominant-tail-symbol removal was added as an influence diagnostic, not a filter or candidate selection.')
 p('Pullback6 has the largest absolute difference among retained market-state panel fields: median−19.73% vs−11.11%, delta−0.493. However all8 observed extreme values lie within non-tail range,5 are57590; removing that symbol leaves only3 extreme observations and delta−0.251. Same-symbol direction agrees for57590 and81070, but only2 symbols support both groups. This is an OPTIONAL hypothesis, not established cross-symbol prediction.')
 p('VWAP proxy delta−0.425 falls to−0.095 after dominant-tail removal (only2 tail observations); available only108/277. Relative-volume tail median0.384 is close to +5-winner median0.349: low-volume rejection could remove winners. Momentum delta≈0; freshness nearlyconstant. Price direction flips on removing57590 and89180 has7–8JPY entries: no price threshold or spread conclusion justified. Classifications remain semantic candidates, not performance-selected features.')
 table(['Signal','Within-symbol tail/non-tail delta'],[(k,'; '.join(f"{a['symbol']}({a['tailN']}/{a['nonTailN']}):{fmt(a['cliffDelta'])}" for a in v['withinSymbol'])) for k,v in d['signals'].items()])
 p('## P2/P3/P9/P10 — Opportunity, symbol generalization and concentration')
 co=d['concentration'];m=co['top1Mechanism']
 p('89180:61 ENTER in277;21 strict30m;22 portfolio accepted. All21 strict paths have MFE>=5 andMAE0. Of22 selected-exit trades,7 profit and15 gross-flat (cost-only loss). Every profitable exit is7→8JPY or8→9JPY: a1JPY move equals14.29% or12.5%, amplified by many shares under equal-notional sizing. This observed price-scale mechanism explains the large HIGH label/PnL concentration; it does NOT establish tick size, spread, available depth or executable fill.')
 p('The remaining39/61 entries for89180 lack selected-exit outcome. Observed successful paths cannot establish quality on all61. Comparisons are descriptive; no symbol rule.')
 table(['Net contribution group','Symbols','JPY','Share total net','Share corresponding positive/negative symbol contribution'],[(f'Profit top{k}',','.join(v['symbols']),fmt(v['pnlJpy'],2),fmt(v['shareOfNetPnl']),fmt(v['shareOfPositiveSymbolPnl'])) for k,v in co['profits'].items()]+[(f'Loss top{k}',','.join(v['symbols']),fmt(v['pnlJpy'],2),'—',fmt(v['shareOfNegativeSymbolPnl'])) for k,v in co['losses'].items()])
 p(f"156 symbols in277;106 accepted symbols, profitable{co['profitableSymbols']}, losing{co['losingSymbols']}. Positive-net-symbol HHI={co['positiveSymbolHHI']:.4f}; negative-net-symbol HHI={co['negativeSymbolHHI']:.4f}. HHI squares normalized positive/negative NET SYMBOL contributions separately; it is not trade-level gross profit/loss HHI. Profit concentration is stronger, losses also repeated. 57590 contributes5/10 extreme paths and−120,721JPY net.")
 table(['Existing SAME Equal cash replay','Final equity JPY','Return%','DD%'],[(k,fmt(v['finalEquityJpy'],2),fmt(v['totalReturnPct']),fmt(v['maxDrawdownPct'])) for k,v in co['priorCashStress'].items() if not k.startswith('WINSORIZED')])
 p('For all major top5 symbols, per-symbol PnL/PF/Precision/MAE/MFE/score distribution and fixed-quantity leave-one-out attribution are saved in diagnostic.json.gz. Top1/top3 removal results above are actual existing cash replays; other single-symbol deletions are explicitly additive, NOT self-financing portfolio return.')
 table(['PIT field','Top1 median','Top3 median','Other median'],[(f,*[fmt(d['featureDistributionByContributorGroup'][g][f]['median']) for g in ['TOP1','TOP3','OTHER']]) for f in c['descriptiveSignalPanel']])
 p('## P4 — Score calibration')
 p('These quartiles use strict181 (46/45/45/45), NOT prior portfolio accepted166 quartiles. Return here is exact+30m CLOSE reference minus0.05pp; frozen LONG EXIT returns and denominators are separate. This diagnostic does not change EXIT.')
 table(['Quartile','N','Mean net30%','Median%','PF','Positive%','Mean MFE%','Mean MAE%','MAE<=−10','+1/+2/+3/+5 hits'],[(k,v['N'],fmt(v['net30ReferencePct']['mean']),fmt(v['net30ReferencePct']['median']),fmt(v['net30ReferencePct']['PF']),fmt(100*v['net30ReferencePct']['positiveRate']),fmt(v['mfe']['mean']),fmt(v['mae']['mean']),v['tail']['-10']['n'],'/'.join(str(v['precision'][str(t)]['hits']) for t in [1,2,3,5])) for k,v in d['scoreQuantiles'].items()])
 p('Return, MFE, MAE and tail safety monotonicity all FALSE. Q4 captures more+5 but also5/45 deep adverse paths. E[L] is expected ordinal HIGH opportunity, NOT expected return/tail probability/size utility. Formal probability-calibration error was not tested; no claim of fitted score being prospectively calibrated.')
 p('## P5/P6 — Time / segment / liquidity')
 summary_table(d['byTime']);summary_table(d['bySegment']);summary_table(d['byLiquidity'])
 p('Open has6/64 observed tails; Growth8/89 (5 from57590), Standard2/81. Mid liquidity4/9 versusHigh6/172; Low has0 evaluable out of4 and cannot be called safe. Groups overlap and condition on Selector/Entry/coverage; no independent sector/regime causality, no segment/liquidity/time filter. Within-group score tables retained in compressed diagnostic.')
 p('## Coverage minimum and fair comparison')
 p('Strict30m missing96:51 absent expected slots,20 session end,25 lunch. PROVIDER_GAP is inherited reason name, not proof whether a missing slot is no-trade or provider loss. Portfolio excluded104:65 missing before LONG EXIT,20 no remaining normal bar,19 another comparison candidate censored. Selected LONG alone resolves192/277, but this is NOT a new portfolio subset or result. Existing173 paired and181 strict overlap158 only. All28 15:00 entries excluded from portfolio; no execution inference from label absence.')
 p('15:25-start auction interval after2024-11-05 remains unresolved as regular-bar versus auction representation. No NEW forward fill, future substitution or fabricated liquidation. Inherited future-label-availability membership and raw missing-volume-to-zero handling are disclosed, not certified safe or silently corrected. Exact source clock, calendar/lunch and price reference definitions retained. Full277 portfolio unknown. This does not prevent this descriptive architecture diagnostic, but complete challenger portfolio needs existing-cache path projection for all possible3800 candidate entries.')
 p('## P12–P15 — Failure attribution, requirements, architecture questions')
 table(['Failure','Verdict','Evidence'],[(a['failure'],a['verdict'],a['evidence']) for a in failure])
 table(['Priority','Architecture dependency'],enumerate(architecture['rootCausePriority'],1))
 for k in ['mustPreserve','mustImprove','mustNot']:p(f"**{k}:** "+'; '.join(architecture[k]))
 table(['Question','Recommendation, NOT freeze'],architecture['questions'].items())
 table(['Family','Disposition','Reason'],[(r['family'],r['disposition'],r['reason']) for r in architecture['families']])
 p('C is the first family to specify in the next contract, not a selected architecture. A is a minimal alternative. B is reserve; D WAIT deferred; symbol models/feature zoo rejected. Model family, targets, features, state and numeric gates remain UNFROZEN.')
 p('Fair comparator draft: same3800 events/76 sessions/Frozen Selector/reference/0.05% cost/LONG EXIT/Equal/1mJPY/100share/10positions/ledger/event order/missing semantics. Entry alone varies. Each arm has its own causal accepted set; comparing only intersected ENTERs would hide throughput and preservation. Same symbol-session grouped, chronological and held-symbol evaluation plus overlap purge; all still Development, because upstream was outcome-exposed.')
 for k,v in comparator['metrics'].items():p(f"**Required {k} metrics:** "+'; '.join(v))
 p('Trade-offs explicit; do not demand every metric improve or invent PF/MAE/DD numerical gates after outcomes. Next Pre-Development Contract must fix score meaning, minimal features/model, missing-state policy, split and quantitative trade-off gates BEFORE Entry v2 fit.')
 p('## STOP / counters / artifacts')
 p('Frozen components changed0. Entry v2 fit0/prediction0; v1 fit0/prediction0. Fresh0/OOS0/Prospective0; J-Quants0/Yahoo0/other provider0. Global195 sessions untouched, exact budget SHA checked. All9 safety false; no main merge. Historical statement reuse and diagnostic outputs only.')
 p('Artifacts: diagnostic.json.gz (all277, per-symbol, calibration, panel distributions, coverage); feature-inventory.json; architecture-decision.json; fair-comparator-draft.json; diagnostic contract/source pins; offline integrity tests and CI. Final head and final-head CI reported in completion message.')
 (OUT/'report.md').write_text('\n'.join(lines)+'\n')
 print(architecture['verdict'])
if __name__=='__main__':make()
