import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
const arg=(n,f=null)=>{const i=process.argv.indexOf(n);return i>=0&&i+1<process.argv.length?process.argv[i+1]:f;};
const partialDir=arg('--partial-dir');const historyPath=arg('--history-pack');const barsPath=arg('--bars');const output=arg('--output');if(!partialDir||!historyPath||!barsPath||!output)throw new Error('usage: --partial-dir <dir> --history-pack <json> --bars <json> --output <json>');
const sym=v=>String(v??'').trim().toUpperCase();const uniq=xs=>[...new Set(xs.map(sym).filter(Boolean))].sort();
const freeze=JSON.parse(fs.readFileSync(path.join(partialDir,'freeze.json'),'utf8'));const measurements=fs.readFileSync(path.join(partialDir,'partial-measurements.ndjson'),'utf8').split(/\r?\n/).filter(Boolean).map(line=>JSON.parse(line));const barsCombined=JSON.parse(fs.readFileSync(barsPath,'utf8'));if(barsCombined.status!=='P25_INCOMPLETE_ABCD_BARS_COMBINED'||barsCombined.sessionDate!==freeze.sessionDate)throw new Error('combined bars invalid');const usableSymbolSet=new Set(Object.keys(barsCombined.sessionBarsBySymbol??{}));const dynamicUnion=uniq(measurements.flatMap(x=>(x.selected??[]).map(r=>r.symbol)));const evaluableDynamicUnion=dynamicUnion.filter(s=>usableSymbolSet.has(s));
const dynamicBundle={schemaVersion:1,phase:'57.p25.partial-dynamic5m-postclose-bundle',status:'P25_PARTIAL_DYNAMIC5M_POSTCLOSE_BUNDLE_READY',sessionDate:freeze.sessionDate,createdAt:new Date().toISOString(),pointCount:measurements.length,expectedPointCount:measurements.length,missingExpectedBucketCount:0,missingExpectedBuckets:[],completeFiveMinuteCoverage:false,selectedSymbolUnionCount:evaluableDynamicUnion.length,selectedSymbolUnion:evaluableDynamicUnion,originalSelectedSymbolUnionCount:dynamicUnion.length,originalSelectedSymbolUnion:dynamicUnion,evaluationExcludedSymbolsDueToMissingPostCloseBars:dynamicUnion.filter(s=>!usableSymbolSet.has(s)),points:measurements.map(x=>({bucket:new Date(Math.floor(Date.parse(x.observedAt)/(5*60_000))*5*60_000).toISOString(),observedAt:x.observedAt,inputSymbols:Number(x.inputSymbols),selected:(x.selected??[]).filter(r=>usableSymbolSet.has(sym(r.symbol))).map(r=>({symbol:sym(r.symbol),sector:String(r.sector??'UNKNOWN'),currentPrice:Number(r.currentPrice),sourceScannedAt:r.sourceScannedAt??x.observedAt,opportunityScore:Number(r.opportunityScore),turnoverYen:Number(r.turnoverYen)})),methodology:x.methodology,policy:x.policy,safety:x.safety})),barsReady:true,barFailureCount:0,barFailures:[],sessionBarsBySymbol:Object.fromEntries(evaluableDynamicUnion.map(s=>[s,barsCombined.sessionBarsBySymbol[s]])),methodology:{selectionMembershipCapturedPointInTime:true,postCloseBarsUsedOnlyAsPrefixAtRecordedSelectionCutoff:true,sparseValidBarsRetainedWithoutFabrication:true,partialLateStart:true,formalFullSession:false,missingEarlierBucketsNeverBackfilledOrFabricated:true,resultBasedRetuning:false,freshHoldoutConsumed:false,missingPostCloseBarsNeverBackfilledInterpolatedOrReplaced:true},safety:freeze.safety};
const tmpBundle=path.join(path.dirname(output),'p25-incomplete-dynamic-bundle.json'),tmpBD=path.join(path.dirname(output),'p25-incomplete-bd.json');fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(tmpBundle,JSON.stringify(dynamicBundle,null,2)+'\n');const child=spawnSync(process.execPath,['scripts/run_p25_dynamic5m_exitv3_portfolio_daily.mjs','--bundle',tmpBundle,'--history-pack',historyPath,'--output',tmpBD],{encoding:'utf8',stdio:['ignore','pipe','pipe'],timeout:12*60*1000,killSignal:'SIGKILL'});process.stdout.write(child.stdout??'');process.stderr.write(child.stderr??'');if(child.error)throw child.error;if(child.status!==0)throw new Error(`B/D evaluator failed: ${child.stderr||child.stdout}`);const bd=JSON.parse(fs.readFileSync(tmpBD,'utf8'));const payload={schemaVersion:1,phase:'57.p25.incomplete-abcd-dynamic',status:'P25_INCOMPLETE_ABCD_DYNAMIC_READY',sessionDate:freeze.sessionDate,B:bd.B,D:bd.D,dynamicBundleAudit:{originalSelectedSymbolUnionCount:dynamicUnion.length,evaluableSelectedSymbolUnionCount:evaluableDynamicUnion.length,excludedSymbols:dynamicUnion.filter(s=>!usableSymbolSet.has(s))},methodology:{sameFrozenDynamicSelectionEvidence:true,sameExistingDynamic5mExitV3PortfolioEvaluator:true,capitalAllocationPolicyUnchanged:true,allocationProfileWinnerSelection:false,resultBasedRetuning:false},safety:{executionAllowed:false,brokerWriteAllowed:false,excelOrderWriteAllowed:false,rssOrderFunctionAllowed:false,liveTradingAllowed:false,paperTradingAllowed:false,automaticPromotionAllowed:false,productionUpdateAllowed:false,transmitted:false,freshHoldoutConsumed:false}};fs.writeFileSync(output,JSON.stringify(payload,null,2)+'\n');console.log(JSON.stringify({status:payload.status,B:payload.B?.summary,D:Object.fromEntries(Object.entries(payload.D?.profiles??{}).map(([k,v])=>[k,{totalReturnPct:v.return?.totalReturnPct,maxDrawdownPct:v.risk?.maxDrawdownPct}]))},null,2));
