import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';

const arg=(n,f=null)=>{const i=process.argv.indexOf(n);return i>=0&&i+1<process.argv.length?process.argv[i+1]:f;};
const partialDir=arg('--partial-dir'),historyPath=arg('--history-pack'),barsPath=arg('--bars'),output=arg('--output');
const shardIndex=Number(arg('--shard-index')),shardCount=Number(arg('--shard-count'));
if(!partialDir||!historyPath||!barsPath||!output||!Number.isInteger(shardIndex)||!Number.isInteger(shardCount)||shardIndex<0||shardIndex>=shardCount||shardCount<1)throw new Error('usage: --partial-dir <dir> --history-pack <json> --bars <json> --output <json> --shard-index <n> --shard-count <n>');
const sym=v=>String(v??'').trim().toUpperCase();
const uniq=xs=>[...new Set(xs.map(sym).filter(Boolean))].sort();
const freeze=JSON.parse(fs.readFileSync(path.join(partialDir,'freeze.json'),'utf8'));
const measurements=fs.readFileSync(path.join(partialDir,'partial-measurements.ndjson'),'utf8').split(/\r?\n/).filter(Boolean).map(line=>JSON.parse(line));
const barsCombined=JSON.parse(fs.readFileSync(barsPath,'utf8'));
if(barsCombined.status!=='P25_INCOMPLETE_ABCD_BARS_COMBINED'||barsCombined.sessionDate!==freeze.sessionDate)throw new Error('combined bars invalid');
const usableSymbolSet=new Set(Object.keys(barsCombined.sessionBarsBySymbol??{}));
const selectedPoints=measurements.map((point,index)=>({point,index})).filter(x=>x.index%shardCount===shardIndex);
if(!selectedPoints.length)throw new Error(`dynamic point shard ${shardIndex}/${shardCount} empty`);
const shardMeasurements=selectedPoints.map(x=>x.point);
const dynamicUnion=uniq(shardMeasurements.flatMap(x=>(x.selected??[]).map(r=>r.symbol)));
const evaluableDynamicUnion=dynamicUnion.filter(s=>usableSymbolSet.has(s));
const dynamicBundle={schemaVersion:1,phase:'57.p25.partial-dynamic5m-postclose-bundle-shard',status:'P25_PARTIAL_DYNAMIC5M_POSTCLOSE_BUNDLE_READY',sessionDate:freeze.sessionDate,createdAt:new Date().toISOString(),pointCount:shardMeasurements.length,expectedPointCount:shardMeasurements.length,missingExpectedBucketCount:0,missingExpectedBuckets:[],completeFiveMinuteCoverage:false,selectedSymbolUnionCount:evaluableDynamicUnion.length,selectedSymbolUnion:evaluableDynamicUnion,originalSelectedSymbolUnionCount:dynamicUnion.length,originalSelectedSymbolUnion:dynamicUnion,evaluationExcludedSymbolsDueToMissingPostCloseBars:dynamicUnion.filter(s=>!usableSymbolSet.has(s)),points:shardMeasurements.map(x=>({bucket:new Date(Math.floor(Date.parse(x.observedAt)/(5*60_000))*5*60_000).toISOString(),observedAt:x.observedAt,inputSymbols:Number(x.inputSymbols),selected:(x.selected??[]).filter(r=>usableSymbolSet.has(sym(r.symbol))).map(r=>({symbol:sym(r.symbol),sector:String(r.sector??'UNKNOWN'),currentPrice:Number(r.currentPrice),sourceScannedAt:r.sourceScannedAt??x.observedAt,opportunityScore:Number(r.opportunityScore),turnoverYen:Number(r.turnoverYen)})),methodology:x.methodology,policy:x.policy,safety:x.safety})),barsReady:true,barFailureCount:0,barFailures:[],sessionBarsBySymbol:Object.fromEntries(evaluableDynamicUnion.map(s=>[s,barsCombined.sessionBarsBySymbol[s]])),methodology:{selectionMembershipCapturedPointInTime:true,postCloseBarsUsedOnlyAsPrefixAtRecordedSelectionCutoff:true,sparseValidBarsRetainedWithoutFabrication:true,partialLateStart:true,formalFullSession:false,missingEarlierBucketsNeverBackfilledOrFabricated:true,resultBasedRetuning:false,freshHoldoutConsumed:false,missingPostCloseBarsNeverBackfilledInterpolatedOrReplaced:true,executionTopologyOnlyPointSharding:true},safety:freeze.safety};
const outDir=path.dirname(output),tmpBundle=path.join(outDir,`dynamic-bundle-${shardIndex}.json`),tmpBD=path.join(outDir,`dynamic-bd-${shardIndex}.json`);
fs.mkdirSync(outDir,{recursive:true});
fs.writeFileSync(tmpBundle,JSON.stringify(dynamicBundle,null,2)+'\n');
const child=spawnSync(process.execPath,['scripts/run_p25_dynamic5m_exitv3_portfolio_daily.mjs','--bundle',tmpBundle,'--history-pack',historyPath,'--output',tmpBD],{encoding:'utf8',stdio:['ignore','pipe','pipe'],timeout:10*60*1000,killSignal:'SIGKILL'});
process.stdout.write(child.stdout??'');process.stderr.write(child.stderr??'');
if(child.error)throw child.error;
if(child.status!==0)throw new Error(`dynamic point shard evaluator failed: ${child.stderr||child.stdout}`);
const bd=JSON.parse(fs.readFileSync(tmpBD,'utf8'));
const safety={executionAllowed:false,brokerWriteAllowed:false,excelOrderWriteAllowed:false,rssOrderFunctionAllowed:false,liveTradingAllowed:false,paperTradingAllowed:false,automaticPromotionAllowed:false,productionUpdateAllowed:false,transmitted:false,freshHoldoutConsumed:false};
const payload={schemaVersion:1,phase:'57.p25.incomplete-abcd-dynamic-point-shard',status:'P25_INCOMPLETE_ABCD_DYNAMIC_POINT_SHARD_READY',sessionDate:freeze.sessionDate,shardIndex,shardCount,sourcePointIndexes:selectedPoints.map(x=>x.index),sourceObservedAts:shardMeasurements.map(x=>x.observedAt),B:bd.B,pointAudit:bd.pointAudit??[],dynamicBundleAudit:{originalSelectedSymbolUnionCount:dynamicUnion.length,evaluableSelectedSymbolUnionCount:evaluableDynamicUnion.length,excludedSymbols:dynamicUnion.filter(s=>!usableSymbolSet.has(s))},methodology:{sameFrozenDynamicSelectionEvidence:true,sameExistingDynamic5mExitV3PortfolioEvaluator:true,pointPartitionByOriginalStableIndex:true,noPointReorderingWithinShard:true,capitalAllocationIgnoredUntilGlobalRecombine:true,resultBasedRetuning:false},safety};
fs.writeFileSync(output,JSON.stringify(payload,null,2)+'\n');
console.log(JSON.stringify({status:payload.status,shardIndex,pointCount:shardMeasurements.length,resolvedCount:payload.B?.resolvedCount,summary:payload.B?.summary},null,2));
