"""Evidence-contract and synthetic counterexample tests; no historical raw opened."""
import copy,json,unittest
import numpy as np
from scripts import phase57_dictionary_anatomy as a
from scripts import phase57_research_dictionary_v0 as v
from scripts import phase57_chart_reader_research as reader
from scripts import test_phase57_expansion_research as fixtures

class AnatomyTests(unittest.TestCase):
 def row(self,**kw):
  r={'id':'x','tier':'daily','status':'WATCH','reasons':['calibration'],'checks':{'raw':True,'incremental':True,'tail':True}};r.update(kw);return r
 def test_calibration_is_not_absence(self):
  x=a.classify(self.row(),'daily');self.assertEqual(x['RELIABLE_PARTIAL_GATE_FAILURE']['status'],'CONFIRMED');self.assertNotEqual(x['NO_RELIABILITY_DEMONSTRATED']['status'],'CONFIRMED')
 def test_redundancy_preserves_signal(self):
  x=a.classify(self.row(reasons=['REDUNDANT_WITH:value_AM']),'intraday');self.assertEqual(x['REDUNDANT_RELIABLE_TRAIT']['status'],'CONFIRMED')
 def test_joint_adjustment_not_causal_attribution(self):
  r=self.row(checks={'raw':True,'incremental':False,'tail':False});x=a.classify(r,'intraday');self.assertEqual(x['PEER_ADJUSTMENT_LOSS']['status'],'CONFIRMED');self.assertIn('cannot attribute',x['PEER_ADJUSTMENT_LOSS']['basis'])
 def test_failed_base_not_tail_causation(self):
  x=a.classify(self.row(checks={'raw':False,'incremental':False,'tail':False}),'daily');self.assertEqual(x['TAIL_SESSION_SENSITIVITY']['status'],'INDICATION')
 def test_recent_peer_never_promoted(self):
  for state in ['USABLE','WATCH','INSUFFICIENT']:
   x=a.classify(self.row(status=state),'intraday')
   for k in ['RECENT_ONLY_RELIABILITY','PEER_CLUSTER_RELIABILITY']:self.assertEqual(x[k]['status'],'UNKNOWN')
 def test_daily_missing_intraday_is_structural(self):
  x=a.classify(self.row(status='INSUFFICIENT',tier='intraday',checks={},reasons=['PAIRED_SAMPLE_BELOW100']),'daily');self.assertIn('absent by lane design',x['SAMPLE_INSUFFICIENT']['basis'])
 def test_liquidity_subset_not_confirmed(self):
  x=a.classify(self.row(liquidityStrata=[{'pass':True},{'pass':False},{'pass':False}]),'intraday');self.assertEqual(x['STRATUM_LOCAL_SIGNAL']['status'],'INDICATION')
 def test_reader_actual_history_schema_blocker(self):
  day,rows,previous,history=fixtures.ResearchTests().data()
  actual=[{'daily':{'Date':h['session']},'tr':h['tr'],'barValue':{int(k):v for k,v in h['barValues'].items()}} for h in history]
  with self.assertRaises(KeyError):reader.context(day,580,rows,previous,actual)
 def test_reader_value_key_mismatch(self):
  day,rows,previous,history=fixtures.ResearchTests().data();correct=reader.context(day,580,rows,previous,history)
  for h in history:h['barValue']={int(k):v for k,v in h.pop('barValues').items()}
  broken=reader.context(day,580,rows,previous,history)
  self.assertIsNotNone(correct['features']['rvol_value']);self.assertIsNone(broken['features']['rvol_value'])
 def test_reader_stale_current_context_counterexample(self):
  day,rows,previous,history=fixtures.ResearchTests().data();x=reader.context(day,755,rows,previous,history)
  self.assertEqual(x['lastCompletedBar'],610);self.assertEqual(x['status'],'RESEARCH_CONTEXT_AVAILABLE')
 def test_pullback_ratio_crosses_phase_and_direction(self):
  bars=[{'t':t,'C':c} for t,c in [(545,100),(550,102),(555,101),(755,100),(760,96),(765,97)]]
  swings=v.swings(bars,1.)
  self.assertEqual(len(swings),2);self.assertEqual([x['direction'] for x in swings],[1,-1])
  self.assertFalse(v.same_phase(swings[0]['confirmedAt'],swings[1]['confirmedAt']))
  self.assertEqual(swings[1]['amplitude']/swings[0]['amplitude'],2.)
  from unittest.mock import patch
  day='2024-10-01'
  for b in bars:b.update(O=b['C'],H=b['C']+.1,L=b['C']-.1,Va=100.,Vo=1.,VWAP=100.)
  rows=[{'Time':f"{b['t']//60:02}:{b['t']%60:02}",'H':b['H'],'L':b['L'],'Va':100.,'Vo':1.} for b in bars]
  with patch.object(v,'bars5',return_value=bars):
   result,_,_=v.intraday_traits(day,{'Va':600.,'Vo':6.,'O':100.},{'C':100.,'H':105.,'L':95.},rows,.01,[])
  self.assertEqual(result['pullback_depth'],2.)
 def test_gate_is_population_not_per_symbol(self):
  from scripts import phase57_expansion_assess as assessor
  import inspect
  code=inspect.getsource(assessor.assess)
  self.assertIn('complete=len(usable)>=8 and len(families)>=4 and daily>=2 and intra>=2',code)
 def test_fixed_rows_and_no_promotion(self):
  p=a.BASE/'diagnostic'
  if not p.exists():self.skipTest('diagnostic generated by CI before test')
  rows=a.read(p/'02_all_traits.json');self.assertEqual(len(rows),146);self.assertEqual(sum(r['status']=='WATCH' for r in rows),92)
  for lane in ['daily','intraday']:
   old={x['id']:x for x in a.read(a.SOURCE/(lane+'-reliability.json'))}
   for row in (x for x in rows if x['lane']==lane):
    for k,value in old[row['id']].items():self.assertEqual(row[k],value)
  self.assertFalse(a.read(p/'09_decision.json')['dictionaryReaderReadyForEntryExit'])
if __name__=='__main__':unittest.main()
