"""Render immutable v3 results. No fit, replay, selection or retune."""
from checkpoint import *
import csv
A=json.loads((OUT/'SELECTION_ANALYSIS.json').read_text());profiles=A['profiles'];m=profiles['QUALITY_V3_MAX3'];c=A['control_read_only'];q=m['quality'];cq=c['quality'];e=m['economic'];ce=c['economic']
def p(v):return '—' if v is None else f'{v*100:+.4f}%'
def rate(v):return '—' if v is None else f'{v*100:.4f}%'
def mult(v):return '—' if v is None else f'{v:.6f}x'
def yen(v):return '—' if v is None else f'¥{v:,.0f}'
def num(v):return '—' if v is None else str(v)
def delta(a,b,kind):
 if a is None or b is None:return '—'
 if kind in ('pct','rate'):return f'{(a-b)*100:+.4f}pp'
 if kind=='multiple':return f'{a-b:+.6f}x'
 if kind=='yen':return f'¥{a-b:+,.0f}'
 return f'{a-b:+.4f}'
fmt={'pct':p,'rate':rate,'multiple':mult,'yen':yen,'N':num}
lines=['# Capital v3 MAX3 Top-3 Quality Result','','## A. Main vs Control','','| Metric | Control Liquidity OFF | QUALITY_V3 | Delta |','|---|---:|---:|---:|']
metric_rows=[]
for title,key,kind in [('daily geom','geometric_mean_daily_return','pct'),('rolling20 median','rolling20_median','multiple'),('rolling20 maximum','rolling20_maximum','multiple'),('Final Equity','final_equity','yen'),('MaxDD','max_drawdown','rate'),('utilization mean','utilization_mean','rate')]:
 a,b=ce[key],e[key];metric_rows.append({'metric':title,'Control':a,'QUALITY_V3':b,'delta':b-a});lines.append(f'| {title} | {fmt[kind](a)} | {fmt[kind](b)} | {delta(b,a,kind)} |')
lines.insert(10,f"| 2x hit | {ce['north_star_hit_N']}/{ce['valid_rolling20_window_N']} ({rate(ce['north_star_hit_rate'])}) | {e['north_star_hit_N']}/{e['valid_rolling20_window_N']} ({rate(e['north_star_hit_rate'])}) | {delta(e['north_star_hit_rate'],ce['north_star_hit_rate'],'rate')} |")
for title,key in [('PF1 >=+1% rate','PF1_rate'),('loser <=0% rate','loss0_rate'),('tail <=-1% rate','tail1_rate')]:
 a,b=cq[key],q[key];lines.append(f'| {title} | {rate(a)} | {rate(b)} | {delta(b,a,"rate")} |');metric_rows.append({'metric':title,'Control':a,'QUALITY_V3':b,'delta':b-a})
for k,title in [('U3','U3 capture'),('Medium','Medium3–<5 capture'),('U5','U5 capture'),('U10','U10 capture')]:
 a,b=c['capture'][k],m['capture'][k];lines.append(f'| {title} | {a["funded_N"]}/{a["total_N"]} ({rate(a["capture_rate"])}) | {b["funded_N"]}/{b["total_N"]} ({rate(b["capture_rate"])}) | {delta(b["capture_rate"],a["capture_rate"],"rate")} |');metric_rows.append({'metric':title,'Control':a['capture_rate'],'QUALITY_V3':b['capture_rate'],'delta':b['capture_rate']-a['capture_rate']})
for title,key in [('<2% contamination','below2_rate'),('<3% contamination','below3_rate')]:lines.append(f'| {title} | {rate(cq[key])} | {rate(q[key])} | {delta(q[key],cq[key],"rate")} |')
lines+=['',f'200万円到達: **{"YES" if e["north_star_hit_any"] else "NO"}**',f'Selection Status: **{A["selection_status"]}**',f'Economic Status: **{A["economic_status"]}**','',f'1日幾何平均: **{p(e["geometric_mean_daily_return"])}**。100万円 → 20日中央値: **{yen(1000000*e["rolling20_median"])}**、20日最大: **{yen(e["maximum_20_session_amount"])}**。38 sessions、valid rolling20=19、blocked=0、最初の2x区間なし。','',f'Q1–Q8: {", ".join(k+"="+v for k,v in A["scoreboard"].items())}。PF1 gap_to_100pct: **{rate(q["PF1_gap_to_100pct"])}**。','', '### Realized selection quality','', '| Metric | Control | MAIN |','|---|---:|---:|']
for title,key,kind in [('funded N','funded_N','N'),('realized mean','realized_mean','pct'),('realized median','realized_median','pct'),('>0 rate','positive_rate','rate'),('<=-3% rate','tail3_rate','rate'),('worst return','worst_realized_return','pct'),('p05 return','p05_realized_return','pct')]:lines.append(f'| {title} | {fmt[kind](cq[key])} | {fmt[kind](q[key])} |')
lines+=['',f'MAIN realized resolved {q["realized_resolved_N"]}/{q["funded_N"]}; >=+1% {q["PF1_N"]}, >0 {q["positive_N"]}, <=0 {q["loss0_N"]}, <=-1% {q["tail1_N"]}, <=-3% {q["tail3_N"]}。候補teacherの実現欠損23件は0%補完しない。','', '## B. Entry→High bucket → realized result','', '| Entry→High | funded N / bucket N | funded rate | realized mean | median | PF1 rate | loser rate |','|---|---:|---:|---:|---:|---:|---:|']
for k in ('<1','1-<2','2-<3','3-<4','4-<5','5-<10','>=10'):
 b=m['potential_buckets'][k];lines.append(f'| {k}% | {b["funded_N"]}/{b["candidate_N"]} | {rate(b["funded_rate"])} | {p(b["realized_mean"])} | {p(b["realized_median"])} | {rate(b["PF1_rate"])} | {rate(b["loss0_rate"])} |')
lines+=['','Bucketはstrictly-later/pre15:20 actual High。評価専用であり、runtimeへの入力0。','', '## C. Rank Cutoff independent diagnostics','', '| Metric | MAIN | S_ONLY | A_PLUS | B_PLUS |','|---|---:|---:|---:|---:|']
cols=[profiles[x] for x in ('QUALITY_V3_MAX3','S_ONLY_MAX3','A_PLUS_MAX3','B_PLUS_MAX3')]
for title,section,key,kind in [('funded N','quality','funded_N','N'),('avg funded/session','economic','avg_funded_per_session','N'),('daily geom','economic','geometric_mean_daily_return','pct'),('rolling20 median','economic','rolling20_median','multiple'),('rolling20 max','economic','rolling20_maximum','multiple'),('Final Equity','economic','final_equity','yen'),('MaxDD','economic','max_drawdown','rate'),('utilization','economic','utilization_mean','rate'),('EXIT>=+1% rate','quality','PF1_rate','rate'),('EXIT<=0% rate','quality','loss0_rate','rate'),('EXIT<=-1% rate','quality','tail1_rate','rate')]:
 vals=[fmt[kind](x[section][key]) if title!='avg funded/session' else f'{x[section][key]:.4f}' for x in cols];lines.append('| '+title+' | '+' | '.join(vals)+' |')
lines.append('| 2x hit | '+' | '.join(f'{x["economic"]["north_star_hit_N"]}/19 (0%)' for x in cols)+' |')
for key,title in [('U3','U3 capture'),('Medium','Medium3–<5 capture'),('U5','U5 capture'),('U10','U10 capture')]:lines.append('| '+title+' | '+' | '.join(rate(x['capture'][key]['capture_rate']) for x in cols)+' |')
for key,title in [('below2_rate','<2% funded rate'),('below3_rate','<3% funded rate')]:lines.append('| '+title+' | '+' | '.join(rate(x['quality'][key]) for x in cols)+' |')
lines+=['','各診断のrank identity violation=0、backfill violation=0、MAX3 violation=0。3診断は独立Evidenceのみ。同cycleで正式採用するprofileの変更0。','', '## D. Missed Winner / Selected Loser','']
sr=m['slot_regret'];lines+=['| Same-entry batch diagnostic | N |','|---|---:|',f'| MAX3 binding entry batch | {sr["MAX3_binding_entry_batch_N"]} |',f'| selected loser while missed PF1 (batches/pairs) | {sr["selected_loser_missed_PF1_batch_N"]}/{sr["selected_loser_missed_PF1_pair_N"]} |',f'| selected <3 while missed U5 (batches/pairs) | {sr["selected_below3_missed_U5_batch_N"]}/{sr["selected_below3_missed_U5_pair_N"]} |',f'| selected lower realized while better missed (batches/pairs) | {sr["selected_lower_realized_better_missed_batch_N"]}/{sr["selected_lower_realized_better_missed_pair_N"]} |',f'| missed U5 due MAX3 | {sr["missed_U5_due_MAX3_N"]} |',f'| missed U10 due MAX3 | {sr["missed_U10_due_MAX3_N"]} |','', 'Regretは事前固定した同時刻Entry batch内FUNDED対MAX rejectの比較。既存held positionも枠を占めるが、将来結果による差替え/EXIT上書きは行わない。未来teacherは診断専用。','', '| Missed cohort | quality gate | MAX3 | cash/lot |','|---|---:|---:|---:|']
for key in ('U3','Medium','U5','U10'):
 v=m['missed_reasons'][key];lines.append(f'| {key} | {v.get("QUALITY_GATE_REJECT",0)} | {v.get("MAX_POSITION_CAP",0)} | {v.get("CASH_OR_LOT_CONSTRAINED",0)} |')
lines+=['',f'全候補reasons: {json.dumps(e["reasons"],ensure_ascii=False)}。U5 gate拒否112件の失敗条件: L3=63 / LF1=71 / LSAFE=80 (重複あり)。Liquidity理由の拒否0。','', '## E. Thin Liquidity','', '| Historical liquidity status | MAIN funded N | PF1 | loser | tail<=-1 | U3/U5/U10 | mean | median |','|---|---:|---:|---:|---:|---:|---:|---:|']
for status in ('LIQUIDITY_ELIGIBLE','EXTREME_ILLIQUIDITY_REJECT','LIQUIDITY_UNKNOWN'):
 v=m['liquidity_cohorts'][status];lines.append(f'| {status} | {v["N"]} | {v["PF1_N"]} ({rate(v["PF1_rate"])}) | {v["loss0_N"]} ({rate(v["loss0_rate"])}) | {v["tail1_N"]} ({rate(v["tail1_rate"])}) | {v["U3_N"]}/{v["U5_N"]}/{v["U10_N"]} | {p(v["realized_mean"])} | {p(v["realized_median"])} |')
th=m['liquidity_cohorts']['EXTREME_ILLIQUIDITY_REJECT'];ct=c['liquidity_cohorts']['EXTREME_ILLIQUIDITY_REJECT'];o=m['old_reject52'];of=o['funded']
lines+=['', '| Thin subset | Control | MAIN |','|---|---:|---:|']
for title,key,kind in [('funded N','N','N'),('PF1 rate','PF1_rate','rate'),('loser rate','loss0_rate','rate'),('tail<=-1 rate','tail1_rate','rate'),('U5 N','U5_N','N'),('U10 N','U10_N','N'),('mean realized','realized_mean','pct'),('median realized','realized_median','pct'),('worst','worst','pct'),('p05','p05','pct'),('no-trade MTM5m events','no_trade_MTM_N','N'),('EOD regular','EOD_regular_N','N'),('EOD auction','EOD_auction_N','N'),('EOD unexecuted','EOD_unexecuted_N','N'),('actual PnL','actual_pnl_jpy','yen')]:lines.append(f'| {title} | {fmt[kind](ct[key])} | {fmt[kind](th[key])} |')
lines+=['',f'旧Liquidity reject52 Winner: admission eligible **{o["admission_pre1520_eligible_N"]}/52**、funded U5 **{of["U5_N"]}**、U10 **{of["U10_N"]}**、実現mean **{p(of["realized_mean"])}** / median **{p(of["realized_median"])}**、actual PnL **{yen(of["actual_pnl_jpy"])}**。Controlは11 U5 / 8 U10。','', '薄いWinnerのcaptureは増えたが、thin全体のPF1率とtail率は改善していない。数量・他候補・cash recycling・compoundingが同時に変わるため、cohort PnLをPortfolio deltaの独立因果分解と呼ばない。Liquidity Hard Gate/capはOFFのまま。','', '## F. Integrity','']
ind=json.loads((OUT/'INDEPENDENT_AUDIT.json').read_text());can=json.loads((OUT/'FOCUSED_TEST_RESULTS.json').read_text());hd=json.loads((OUT/'HEAD_QUALITY_DIAGNOSTICS.json').read_text())['heads']
lines+=['| Head | OOF N | ROC AUC | Brier | top20% enrichment |','|---|---:|---:|---:|---:|']
for name in ('H5','H3','HF1','HL0'):
 v=hd[name];lines.append(f'| {name} | {v["N"]} | {v["ROC_AUC"]:.6f} | {v["Brier"]:.6f} | {v["top20_enrichment"]:.6f}x |')
lines+=['','Head別positive base、decile observed rate、block AUC/base rateはHEAD_QUALITY_DIAGNOSTICS.jsonへ保存。HF1/HL0の識別力はこのOOFでは弱く、今回のgate/Qは選択品質改善に結び付かなかった。Head削除・重み変更0。','',f'- New fits **24** (H3/HF1/HL0各8)、H5 new fits **0**。H5 byte reuse hash `{sha(V2/"CORE_P5_SCORE_STREAM.jsonl.gz")}`。',f'- CORE manifest exact identity、Movement追加0。Primary Main1 + diagnostic3、Control replay0、MAX4/5 replay0、result retune0。',f'- Canary **{can["canary_N"]}/{can["canary_N"]} PASS**。Independent **{ind["checks_N"]:,} checks / mismatch0**。Primary logic imports0。', '- Protected/Holdout/Fresh/Validation/OOS/Prospective開封0、新provider0、Frozen Entry/EXIT変更0。', '- orders0、main merge0、force push0。Safety10 flagsは全false、productionReady=false。','', 'Historical actual tradeはexecution reference。provider到着時刻はUNKNOWNで、Controlと同じcompleted-minute availability仮定を維持。Liquidity cap OFFのquantityに対するhistorical executable depthは保証していない。Development feasibility/negative Evidenceで終了。','', '### Daily / rolling20 / capital secondary','', '| Metric | MAIN |','|---|---:|']
for title,key,kind in [('daily arithmetic mean','arithmetic_mean_daily_return','pct'),('daily median','median_daily_return','pct'),('rolling20 min','rolling20_minimum','multiple'),('rolling20 mean','rolling20_arithmetic_mean','multiple'),('median utilization','utilization_median','rate'),('time >=80% utilization','time_utilization_ge80','rate'),('minimum cash','cash_minimum','yen'),('turnover cash','turnover_cash_jpy','yen'),('recycled cash used','capital_recycling_used_jpy','yen'),('avg funded trades/session','avg_funded_per_session','N')]:lines.append(f'| {title} | {fmt[kind](e[key])} |')
lines+=['',f'Sessions with max concurrent0/1/2/3: {json.dumps(e["session_max_concurrent_counts"])}。MAX3は最大同時保有数であり資金3等分ではない。','',f'Paired daily delta: positive {A["paired_daily_delta"]["positive_day_N"]}、negative {A["paired_daily_delta"]["negative_day_N"]}、equal {A["paired_daily_delta"]["equal_day_N"]}。mean {p(A["paired_daily_delta"]["mean"])}、median {p(A["paired_daily_delta"]["median"])}、max gain {p(A["paired_daily_delta"]["max_gain"])}、max deterioration {p(A["paired_daily_delta"]["max_deterioration"])}。','', 'Limit-up causal authority confirmed0、funded142はUNKNOWN。UNKNOWNを理由に停止せず、通常EOD routeを維持。全4profile EOD unexecuted0。','',f'Repo Iam-2squared/ark-terminal / branch capital-state9-vnext-20261004 / instruction basis {CONTROL_HEAD}。','', '**STOP: Main・3診断・監査・Report完了後に設定変更/診断採用を行わず、次cycleの判断をユーザーへ返す。**','']
with (OUT/'REPORT-ja.md').open('x') as f:f.write('\n'.join(lines))
save(OUT/'NORTH_STAR_REPORT.json',{'jst':now(),'Main':{k:e[k] for k in ('geometric_mean_daily_return','arithmetic_mean_daily_return','median_daily_return','valid_primary_day_N','blocked_execution_day_N','valid_rolling20_window_N','rolling20_minimum','rolling20_median','rolling20_arithmetic_mean','rolling20_maximum','north_star_hit_any','north_star_hit_N','north_star_hit_rate','earliest_2x_hit','maximum_20_session_amount')},'amount_from_1m_median':1000000*e['rolling20_median'],'selection_status':A['selection_status'],'economic_status':A['economic_status'],'NORTH_STAR_HIT':False,'diagnostics_not_adopted':True,'safety':SAFETY})
with (OUT/'ROLLING20_ALL_PROFILES.csv').open('x',newline='') as f:
 writer=csv.DictWriter(f,fieldnames=['profile','start_session','end_session','growth_multiple','amount_from_1m','hit']);writer.writeheader()
 for k,v in profiles.items():writer.writerows({'profile':k,**w} for w in v['economic']['rolling20_windows'])
print(json.dumps({'report':str(OUT/'REPORT-ja.md'),'selection_status':A['selection_status'],'economic_status':A['economic_status'],'NORTH_STAR_HIT':False}))
