"""Append-only closure: preserve negative evidence and stop this cycle."""
from checkpoint import *
archive=json.loads((PRIVATE/'ARCHIVE_BUILD_RECEIPT.json').read_text())
assert (ROOT.parent/'private_delivery/quality_v3_saved_archive_identity.json').exists()
a=json.loads((OUT/'SELECTION_ANALYSIS.json').read_text());ind=json.loads((OUT/'INDEPENDENT_AUDIT.json').read_text());can=json.loads((OUT/'FOCUSED_TEST_RESULTS.json').read_text())
assert ind['mismatch_N']==0 and can['failed_N']==0
save(OUT/'EVIDENCE_DELIVERY_RECEIPT.json',{'jst':now(),'filename':Path(archive['path']).name,'sha256':archive['sha256'],'bytes':archive['bytes'],'members':archive['member_N'],'saved':True,'local_identity_persisted':True,'private_source_data_publication':False,'public_report':'REPORT-ja.md','orders':0,'safety':SAFETY})
closure={'jst':now(),'repo':'Iam-2squared/ark-terminal','branch':git('branch','--show-current'),'instruction_basis':CONTROL_HEAD,'basis_HEAD':git('rev-parse','HEAD'),'result_HEAD_receipt':'receipts/Q10_NORTH_STAR_AND_CLOSURE.json','status':a['economic_status'],'selection_status':a['selection_status'],'NORTH_STAR_HIT':a['NORTH_STAR_HIT'],'evidence_type':'Development-only formal negative Evidence; fixed design tested once','Main':'QUALITY_V3_MAX3','Main_result':{k:v for k,v in a['profiles']['QUALITY_V3_MAX3']['economic'].items() if k not in ('daily_series','rolling20_windows')},'scoreboard':a['scoreboard'],'quality':a['profiles']['QUALITY_V3_MAX3']['quality'],'capture':a['profiles']['QUALITY_V3_MAX3']['capture'],'independent_checks_N':ind['checks_N'],'independent_mismatch_N':0,'canary_N':can['canary_N'],'canary_fail_N':0,'new_fits':24,'H5_new_fits':0,'Main_measurement_replays':1,'diagnostic_measurement_replays':3,'independent_audit_replays':4,'deterministic_verification_replays':4,'control_replays':0,'MAX4_MAX5_replays':0,'threshold_feature_weight_search':0,'result_based_retune':0,'diagnostic_adoption':0,'old_evidence_changes':0,'Frozen_entry_exit_changes':0,'source_hashes':json.loads((PRIVATE/'SOURCE_MANIFEST.json').read_text()),'config_hash':sha(OUT/'DESIGN_PRECOMMIT.json'),'feature_manifest_hash':sha(OUT/'CORE_FEATURE_MANIFEST.json'),'score_hashes':{'H5':sha(V2/'CORE_P5_SCORE_STREAM.jsonl.gz'),'Q':sha(PRIVATE/'QUALITY_V3_SCORE_STREAM.jsonl.gz')},'model_hashes':json.loads((PRIVATE/'MODEL_HASHES.json').read_text()),'report_hash':sha(OUT/'REPORT-ja.md'),'exposure':EXPOSURE,'safety':SAFETY,'orders':0,'main_merge':0,'force_push':0,'new_provider_requests':0,'blockers':[],'next_direction':'STOP. No same-cycle gate/Q/Head/Movement/rank/cap/MAX/Entry/EXIT/liquidity rescue or diagnostic adoption. Next-cycle decision returns to user; existing Control and MAX3 research policy remain fixed.'}
save(OUT/'CAPITAL_QUALITY_V3_CLOSURE.json',closure)
checkpoint('Q10_NORTH_STAR_AND_CLOSURE','CAPITAL_QUALITY_V3_WORSE_CLOSED',{'Selection_Status':a['selection_status'],'Economic_Status':a['economic_status'],'NORTH_STAR_HIT':False,'North_Star_hit':'0/19','archive_saved':True,'archive_sha256':archive['sha256'],'report_sha256':sha(OUT/'REPORT-ja.md'),'independent_mismatch_N':0,'canaries_passed':can['canary_N']},next_direction=closure['next_direction'])
