import assert from 'node:assert/strict';
import test from 'node:test';
import {PHASE57_MSII_ORDER_STYLE,createShadowOrderIntent,normalizeMarketSpeedReadOnlyEvent} from '../predict/realtime/phase57-msii-shadow-execution.js';
import {cashUpstreamActionFromShadowIntent} from './phase57_cash_upstream_action.mjs';
import {buildLockedRequestFromAction,freezeOwnershipBaseline,validateOwnershipBaseline} from './phase57_cash_upstream_request.mjs';
const AT='2026-09-03T00:35:00.000Z';
const SAFE={executionAllowed:false,brokerWriteAllowed:false,excelOrderWriteAllowed:false,rssOrderFunctionAllowed:false,liveTradingAllowed:false,paperTradingAllowed:false,automaticPromotionAllowed:false,productionUpdateAllowed:false,transmitted:false};
function shadow(){const e=normalizeMarketSpeedReadOnlyEvent({schemaVersion:2,phase:'58.p9.sync-capture',sourceMode:'MARKETSPEED_II_RSS_READ_ONLY',capturedAt:AT,symbol:'7203',sourceFunctions:['RssMarket'],market:{bestBid:100,bestAsk:100.2,bestBidSize:500,bestAskSize:500},ticks:[],phase57Snapshot:{direction:1,asOf:AT,modelId:'fixture',artifactSha256:'a'.repeat(64),frozen:true,futureOutcomeUsed:false,thresholdSearchAfterCapture:false,entryRetunedAfterCapture:false},methodology:{phase57DirectionIsFrozenBase:true,phase58MayConfirmDeferOrAbstainOnly:true,phase58MayReverseDirection:false,pointInTimeOnly:true,sameCaptureBoundary:true,futureOutcomeUsed:false,historicalDecisionReconstructionAllowed:false},safety:SAFE},{marketSizeUnit:'SHARES',tickSizeUnit:'SHARES'});return createShadowOrderIntent({strategyId:'V1_V3__MAX_3',symbol:'7203',side:'BUY',intentKind:'ENTRY',decisionAt:AT,decisionSequence:0,requestedQuantity:100,referencePrice:100.1,referenceEvent:e,orderStyleResearchLabel:PHASE57_MSII_ORDER_STYLE.MARKETABLE_QUOTE,ttlMs:5000,decisionLatencyMs:100,selectorVersion:'SEL',entryVersion:'ENT',exitVersion:'EXIT',allocationVersion:'ALLOC',futureOutcomeUsed:false});}
test('validated upstream action becomes a lineage- and ownership-bound locked request',()=>{const action=cashUpstreamActionFromShadowIntent(shadow());const ownership=freezeOwnershipBaseline({capturedAt:AT,externalPositions:[{symbol:'123A',quantity:40}],arkManagedPositions:[]});const r=buildLockedRequestFromAction(action,{snapshotPath:'C:/Ark/account.json',ownershipBaseline:ownership});assert.equal(r.intent.symbol,'7203.T');assert.equal(r.intent.side,'BUY');assert.equal(r.externalPositions[0].symbol,'123A.T');assert.equal(r.upstreamLineage.sourceActionSha256,action.actionSha256);assert.equal(r.upstreamLineage.sourceIntentSha256,action.lineage.sourceIntentSha256);assert.equal(r.ownershipBaselineSha256,ownership.baselineSha256);assert.equal(r.inspectionOnly,true);});
test('tampering action or ownership hash fails closed',()=>{const action=cashUpstreamActionFromShadowIntent(shadow());const ownership=freezeOwnershipBaseline({capturedAt:AT,externalPositions:[],arkManagedPositions:[]});assert.throws(()=>buildLockedRequestFromAction({...action,quantity:200},{snapshotPath:'x',ownershipBaseline:ownership}),/HASH_MISMATCH/);assert.throws(()=>validateOwnershipBaseline({...ownership,frozen:false}),/HASH_MISMATCH|MUST_BE_FROZEN/);});
test('ownership overlap and non-lot Ark inventory are rejected',()=>{assert.throws(()=>freezeOwnershipBaseline({capturedAt:AT,externalPositions:[{symbol:'7203',quantity:100}],arkManagedPositions:[{symbol:'7203.T',quantity:100}]}),/POSITION_OWNERSHIP_OVERLAP/);assert.throws(()=>freezeOwnershipBaseline({capturedAt:AT,arkManagedPositions:[{symbol:'7203',quantity:50}]}),/LOT_INVALID/);});
