import assert from 'node:assert/strict';
import test from 'node:test';
import {createInitialExternalOwnershipBaseline} from './phase57_cash_ownership_baseline.mjs';
const NOW=new Date('2026-09-15T06:00:30.000Z');
const SAFE={executionAllowed:false,brokerWriteAllowed:false,excelOrderWriteAllowed:false,rssOrderFunctionAllowed:false,liveTradingAllowed:false,paperTradingAllowed:false,automaticPromotionAllowed:false,productionUpdateAllowed:false,transmitted:false};
function snapshot(overrides={}){return {schemaId:'ARK_ACCOUNT_READONLY_SNAPSHOT_V2',capturedAt:'2026-09-15T15:00:00+09:00',source:'MARKETSPEED_II_RSS',mode:'READ_ONLY',positions:[{symbol:'123A',quantity:40}],orders:[],executions:[],buyingPower:1000000,safety:{...SAFE},...overrides};}
test('explicit fresh read-only snapshot freezes current positions as external only',()=>{const b=createInitialExternalOwnershipBaseline(snapshot(),{confirmAllCurrentPositionsExternal:true,now:NOW,maxAgeSeconds:60});assert.equal(b.schemaId,'ARK_CASH_OWNERSHIP_BASELINE_V1');assert.equal(b.externalPositions[0].symbol,'123A.T');assert.equal(b.externalPositions[0].quantity,40);assert.deepEqual(b.arkManagedPositions,[]);assert.equal(b.frozen,true);assert.match(b.baselineSha256,/^[a-f0-9]{64}$/);});
test('confirmation is mandatory',()=>{assert.throws(()=>createInitialExternalOwnershipBaseline(snapshot(),{now:NOW}),/EXPLICIT_EXTERNAL/);});
test('stale or future snapshot fails closed',()=>{assert.throws(()=>createInitialExternalOwnershipBaseline(snapshot({capturedAt:'2026-09-15T14:00:00+09:00'}),{confirmAllCurrentPositionsExternal:true,now:NOW,maxAgeSeconds:60}),/TOO_OLD/);assert.throws(()=>createInitialExternalOwnershipBaseline(snapshot({capturedAt:'2026-09-15T15:01:00+09:00'}),{confirmAllCurrentPositionsExternal:true,now:NOW,maxAgeSeconds:60}),/FROM_FUTURE/);});
test('open orders or executions prevent baseline capture',()=>{assert.throws(()=>createInitialExternalOwnershipBaseline(snapshot({orders:[{orderNumber:'x'}]}),{confirmAllCurrentPositionsExternal:true,now:NOW}),/OPEN_BROKER_ORDERS/);assert.throws(()=>createInitialExternalOwnershipBaseline(snapshot({executions:[{executionDate:'x'}]}),{confirmAllCurrentPositionsExternal:true,now:NOW}),/EXECUTIONS_PRESENT/);});
test('unsafe snapshot and unresolved position identity fail closed',()=>{assert.throws(()=>createInitialExternalOwnershipBaseline(snapshot({safety:{...SAFE,brokerWriteAllowed:true}}),{confirmAllCurrentPositionsExternal:true,now:NOW}),/UNSAFE_SNAPSHOT/);assert.throws(()=>createInitialExternalOwnershipBaseline(snapshot({positions:[{symbol:'',quantity:100}]}),{confirmAllCurrentPositionsExternal:true,now:NOW}),/IDENTITY_UNRESOLVED/);});
