from pathlib import Path
import csv,json,hashlib,datetime,shutil
R=Path(__file__).resolve().parent;W=R.parent;V=W/'state_predictiveness_20261002_v1';A=W/'state9_rc2_market_audit/continuity_20261001_200641'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(n,x):
 p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,ensure_ascii=False,sort_keys=True,indent=2)+'\n')
def main():
 assert not (R/'PREDICTIVENESS_V2_PRECOMMIT.json').exists()
 cfg=json.loads((V/'runner/config.json').read_text());old=json.loads((V/'DATASET_MANIFEST.json').read_text());exposed=sorted({x['date'] for x in cfg['acquisition_session_scope']})
 links=list(csv.DictReader((A/'DERIVED_G1/DEVELOPMENT_PREVIOUS_DEPENDENCY_ASSESSMENT.csv').open(encoding='utf-8-sig')))
 usable=[{'date':x['session_id'].removeprefix('JPX:'),'previous':x['previous_trading_session_id'].removeprefix('JPX:')} for x in links if x['previous_existing_development_allowed_under_new_grant']=='True']
 assert len(usable)==142
 full=sorted({d for x in usable for d in [x['date'],x['previous']]});assert full==cfg['authorized_days']
 new=sorted([x for x in usable if x['date'] not in exposed and x['date']>max(p['date'] for p in old['pairs'])],key=lambda x:x['date'])[:24]
 assert len(new)==24
 scope={'authorized_Development_days':full,'authorized_current_links':usable,'blocked_days':cfg['blocked_days'],'current_scope':'All142authorized Development current links inventoried; chronological acquisition cap24new dates after latest V1 usable date,3metadata-selected codes/date; all25existing valid pairs reused.','new_acquisition_links':new,'new_proposal_cap':72,'metadata_selection':'paired dated master Code/Mkt/CoName/ProdCat continuity, exclusion IDs, SHA256(sorted master metadata), per-day first3action-compatible codes; no global unique security constraint, no price/outcome refill','V1_exposed_dates':exposed,'existing_input_pairs':old['pairs'],'input_cap_fixed_without_V2_target_results':True,'authorization':'Current V2 Work sections4/5 + inherited Development ledger and previous-dependency authorization; existing J-Quants route only, inherited temporary raw/decrypt semantics.','source_refs':[{'path':str(A/'DERIVED_G1/DEVELOPMENT_PREVIOUS_DEPENDENCY_ASSESSMENT.csv'),'SHA256':sha(A/'DERIVED_G1/DEVELOPMENT_PREVIOUS_DEPENDENCY_ASSESSMENT.csv')},{'path':str(V/'runner/config.json'),'SHA256':sha(V/'runner/config.json')}],'provider_contract_basis':'Pinned plan a10a5523... data plan SHA3ba4ec47... and inherited completed168request acquisition; historical reattested entitlement until2026-10-06. No claim of newly verified current subscription; auth/terms refusal stops external requests and leaves local corpus evaluable.','no_protected_payload':True}
 dump('DATA_SCOPE_V2.json',scope);dump('V1_EXPOSED_DEV.json',{'dates':exposed,'conservative_acquisition_exposure':True,'status':'V1_EXPOSED_DEV','not_fresh':True});dump('V2_NEW_DEV_EVAL.json',{'requested_dates':[x['date'] for x in new],'status':'V2_NEW_DEV_EVAL_RELATIVE_TO_V1_ONLY','not_market_fresh_or_OOS':True,'actual_input_eligibility_pending':True})
 dump('FEATURE_SCHEMA_V2.json',json.loads((V/'FEATURE_SCHEMA.json').read_text()))
 classes=['RISE_STOP','RISE','SHARP_RISE','PULLBACK','RANGE','REBOUND','SHARP_DROP','DROP','DROP_STOP']
 dump('TARGET_SCHEMA_V2.json',{'class_order':classes,'primary':['NEXT_DISTINCT_PRIMARY','TRANSITION_WITHIN30'],'secondary':['NEXT_OBSERVED_PRIMARY','PRICE_H5','PRICE_H15','PRICE_H30'],'motion':{'UP_MOVE':['RISE','SHARP_RISE','REBOUND'],'DOWN_MOVE':['DROP','SHARP_DROP','PULLBACK'],'NON_DIRECTIONAL_OR_STOP':['RANGE','RISE_STOP','DROP_STOP']},'context':{'UP_CONTEXT':['RISE','SHARP_RISE','PULLBACK','RISE_STOP'],'DOWN_CONTEXT':['DROP','SHARP_DROP','REBOUND','DROP_STOP'],'RANGE_CONTEXT':['RANGE']},'null_not_class':True})
 dump('SPLIT_PLAN_V2.json',{'new_eval_dates':[x['date'] for x in new],'fixed_three_blocks':[new[i:i+8] for i in (0,8,16)],'training':'All input-eligible dates strictly before block start. V1_EXPOSED_DEV is training only in primary new-date experiment.','local_fallback':'If0new usable dates, chronological input-eligible local dates; first5initialtrain and remaining contiguous3balanced test blocks. Exposed evaluation diagnostic only.','initial_train_date_min':5,'no_data_outcome_selection':True,'test_window_within_session':True,'purge':'exact donor/target label_end strictly earlier test_start','support_dates':{'GOOD':12,'LIMITED_BUT_EVALUABLE':6,'INSUFFICIENT_DEV_EVAL':0},'bootstrap_seed':2026100203,'permutation_seed':2026100202})
 dump('BUDGET_START_V2.json',{'inherit_no_reset':True,'V1_budget_SHA256':sha(V/'BUDGET_FINAL.json'),'V1_consumption':json.loads((V/'BUDGET_FINAL.json').read_text()),'V1_GitHub_usage':json.loads((V/'GITHUB_REQUEST_USAGE_AT_DELIVERY.json').read_text()),'V2_caps':{'new_dates':24,'new_proposals':72,'current_pairs_including_reuse':97,'new_frozen_steps':36864,'provider_HTTP_requests':900,'Actions_runs':2,'Actions_fanout':1,'outer_folds':3,'model_families':4,'strengths':3,'datasets':3,'classification_tasks':3,'price_tasks':3,'fit_operations':648,'bootstrap_generated_draw_vectors_total':1000,'independent_new_draws':0},'routine_repair_count_not_stop':True})
 now=datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=9))).isoformat()
 contract='''# State Predictiveness V2 Contract — Next-State

## Inheritance and scope
V1 BLOCK and3000draw budget breach remain permanently unchanged. Frozen State9/Path/profile/M0 identities in FROZEN_IDENTITY_RECEIPT are mandatory. Current scope DATA_SCOPE_V2 is fixed before V2 target generation. All145authorized dates/142current links inventoried;24chronological V1-unused new dates after latest reused date,3metadata-selected securities per date; exact25old pairs reused. No price-based substitution or after-target scope expansion. New provider only existing J-Quants route/secret binding in isolated Actions, temporary raw purged. Historical entitlement is not a current provider certification. Provider refusal/unknown conditions stops external requests, not local work; local fallback split already fixed. State-exposure667andold44identity exclusions apply current/previous. V1_EXPOSED_DEV and V2_NEW_DEV_EVAL are relative research exposure categories, not OOS/freshness certificates.

## Targets (all scheduled tradable slots, not compressed observed index)
Current must be genuinely observed, continuous-auction, non-null, admitted. NEXT_DISTINCT_PRIMARY: scan next1..30scheduled tradable slots in the same causal segment and contiguous endpoint order. Every visited endpoint must remain observed/admitted/continuous, without null/reset/gap. First genuine frozen Path TRANSITION determines destination and exact label_end. Transition before a later gap remains available for this conditional9class target; do not require post-event survival. If no event, all30slots must be fully observed to record NO_TRANSITION_WITHIN30, which is not a10thState. Any interruption before event gives unavailable. TRANSITION_WITHIN30 requires the entire30slot observed window, even after a transition; label_end is window end, TRANSITION versus NO_TRANSITION. NEXT_OBSERVED_PRIMARY is next scheduled tradable endpoint only, adjacent scheduled endpoint in same segment and observed/continuous; no skipping null. No lookahead into features. Price5/15/30secondary preserves exact V1 price formula, availability guards and JPY/U units, reuses existing labels for old corpus; missing new labels generated from fixed features only.

Class order: RISE_STOP,RISE,SHARP_RISE,PULLBACK,RANGE,REBOUND,SHARP_DROP,DROP,DROP_STOP. Ties argmax choose earlier class. Binary order NO_TRANSITION,TRANSITION. Family mappings TARGET_SCHEMA_V2 literal. No result-driven grouping. Full current V1allowlist63fields and K4/recent15 causal Path unchanged; S/A/B/C,Membership,velocity excluded. Null carried display never becomes target State. No kernel semantic suite rerun, missing new traces generated in current-slot isolated worker only.

## Split/model
SPLIT_PLAN_V2 fixes three8-date new-evaluation blocks; train all valid earlier dates, min5initialdates. No random rows; exact labels/donor ends before test_start. New-date admission from raw/input quality only; empty dates/folds retained. If no new data, local first5dates initialtrain, remaining dates balanced across3blocks, strictlydiagnostic V1exposed OOF. >=12distinct evaluableOOFdates GOOD;6..11limited;below6insufficient. No field identifiessecurity/date in fittedfeatures. Equaltrain date then security-session mass. Numeric impute/scale and categorical vocabulary train-only. B0weighted prior, B1currentPrimary shrunklookup pseudo-count10(V1). B2/B3weighted onehotridge, unpenalizedintercept,alpha[.01,.1,1]; last usable training date inner validation using earlierusabletrainingdates, select date-equal logloss (price MSE),ties largeralpha. If only1usabletraindate, fixedalpha.1, explicitly inner unavailable. Clipscore>=1e-12normalize; no logisticchallenger. Only existing frozenoutput-derivedfeatures. Models/target/splits cannot changeafterresults.

## Controls
TRUE_NULL: one deterministic permutation for each task/date/security-session group(seed2026100202), entire label/provenance tuple moves jointly, rowkey/fold/featurefixed. Singleton group remains and is counted. No donor crosses date/session/fold. SHIFT60: shift target anchor+60slots; require intact same-segment/observedcontinuous t..shiftanchor before target scan, target window rules apply. Stress control, not theoreticalnull. Train eachcontrol/model samegrid, real/control evaluation exact matchedrowset. Statisticalnull retaining groupmarginal classpriors is not mathematically independent globalnull. B0equality is expected and not integrityfailure. Positive B2/B3 gain vs matchedB1 with null gain>=90%real gain is a controlwarning/veto promotion; null absolute logloss<=real is also warning. This follows userwarning/block option, with finalD reserved for demonstrated leak/partition/mismatch/precommit/budgetbreach (§24). Weak/no predictiveness alone neverD. SHIFT60 strong => REGIME_PERSISTENCE_OR_SHIFT_CONTROL_WARNING, neveractualleakageproof withoutdirecttimestampfailure.

## Metrics / bootstrap
Save all9states for both9class tasks including zero supports,0correct/predicted/actual; precision/recall mathematicallyundefined when denominators0=>NA, never fabricated0%. Zero divisionF1=>NA whenprecisionorrecallundefined, otherwise0whenboth0. Overallaccuracy, balancedaccuracy over true-supportedclasses, macro precision/recall/F1 over full9classes with undefined treated0onlyfor macro convention, Brier(sum9squares), logloss, confusionmatrix; save date-equal metrics as primary inferentialmeasure. Predicted/actual classsupport and FP/FN breakdown, familyconfusion/precision/recall; family prediction is map9classargmax, not reargmax summedfamilyprobabilities. Binary prevalence/balanced/F1/precision/recall; fullaccuracyaloneinsufficient. New- versus exposed-date results separately identified.
Generate exactly1000globaldate-clustervectors once(seed2026100203)over fixedoutertestdateuniverse, includingemptydates. Everymodel/task/metric/horizon reuses samevectors; selecteddrawdate contributes its full rows eachappearance. When task has no labels in draw, markunavailable, no redraw. Percentile95% CIs descriptive;18candidateclaims adjustedCI tail1/720 forB2/B3×9states. Independentchecker uses savedvectors,0newdraws. Vectorcount1000 even if two vectors happen equal; distinctvalues reported separately, cannot guarantee1000distinctvalues in tinydateuniverse. Count cap is generatedvectors, notmetricoperations.

## Promotion and final status
Per-statecandidate requires predicted>=50,true>=50,OOFdate>=6,>=2folds eachwithclasspredictionandtrueexamples; bothfolds higherprecisionvsB1, adjustedbootstraplowerprecisiondifference>0; globaldateequalBrier/logloss<=B1; grosspositivecorrectnessimprovement share<=.5perday/security; nullcomparison notwarned. Pathincremental additionallyB3vsB2samecriteria. No per-featureablationclaim orEntrythreshold. Insufficientclassesstillmeasured. A onlyintegrityPASS,adequateevalandpromotableB2/B3; B integrityPASS adequateeval no promotions; C integrityPASS insufficienteval/classsupport; D actualfuturefeatureleak,partitioncontamination,unreconciledchecker,mustchangefixedcontract,orbudgetbreach. Incompleteprovideracquisition cannot manufacturefreshdata; preservefailureandrunlocalscope. NoHoldout/Protected/Fresh/OOS/Prospective/Entry/EXIT/profit/Capital/Portfolio/externalAI/mainmerge/forcepush/orders.

## Finite compute
Literal caps in BUDGET_START_V2:24newdates,72proposals,97maxpairs,36864newkernelsteps,900providerHTTP,2isolatedActionsruns(maxfanout1),648fitoperations,1000totalgeneratedbootstrapvectors; independentdraws0. NeverresetV1. Reuse exactsavedfits on routine resume, countfailedfits/requests. Evidence-onlycommits trigger0Actions. Allcode/evidencecheckpoint timestamps JST. Publicrepo code/contracts/aggregate-only; row-levelresearch/artifactbytes privateuserdelivery.
'''
 (R/'PREDICTIVENESS_V2_CONTRACT.md').write_text(contract)
 (R/'V1_FORENSIC_REPORT.md').write_text('# V1 Failure Forensics\n\nV1 original BLOCK remains. Direct SHIFT60 timestamp/segment audit1170targets,0violations; matchedH5=81,H15=51,H30=20,2dates/1fold. No actualleakageproven. Shift retains serial/regimepersistence and is nottruenull.\n\nBootstrap3000vs1000totalcap,excess2000: horizon-loop generation. V2once1000globalindices shared.\n\nFold2dates2025-04-30/2025-06-02 contain5eligiblepairs and1635scheduledrows; allhorizons0targets due sparse raw/exacthorizon/intervening gaps, opening/auction, sessionend. Exactdate/security/horizonreasoncounts inCSV/JSON, noafterresultreplacement.\n')
 files=['PREDICTIVENESS_V2_CONTRACT.md','DATA_SCOPE_V2.json','FEATURE_SCHEMA_V2.json','TARGET_SCHEMA_V2.json','SPLIT_PLAN_V2.json','BUDGET_START_V2.json','V1_EXPOSED_DEV.json','V2_NEW_DEV_EVAL.json']
 dump('PREDICTIVENESS_V2_PRECOMMIT.json',{'JST':now,'hashes':{n:sha(R/n) for n in files},'V1_known_results_inherited_not_blinded':True,'V2_targets_or_fits_generated_before_fix':0,'status':'V2_PRECOMMITTED','provider_acquisition_pending':True,'no_post_result_change':True})
 dump('runner_config.json',{**cfg,'acquisition_session_scope':new,'maxproposals':72,'maxrequests':900,'newscope_sha':sha(R/'DATA_SCOPE_V2.json')})
 print(json.dumps({'newdates':[x['date'] for x in new],'scopeSHA':sha(R/'DATA_SCOPE_V2.json'),'contractSHA':sha(R/'PREDICTIVENESS_V2_CONTRACT.md')}))
if __name__=='__main__':main()
